### ISSUE TITLE
"Welcome" Quest Mistake

### ISSUE THREAD

**Issue by TheBedrockMaster** [AllTheMods/ATM-10#1]
I'm sorry, I had to... "you want to" should be changed to "you may want to" or something similar.

"Welcome to All the Mods on 1.21 now on Neoforge. This version of Minecraft is very new and will take some time to grow. With each update you will notice more and more mods being added and then eventually quests will start coming out. This pack is for those of us that love to test new things and want to see how the pack grows over time. If you want a more complete experience you want to play ATM9 for now."

**Comment by Griefed** [comment]
As per https://github.com/AllTheMods/ATM-10/issues/2682#issuecomment-2840220301

Suggestion:
Stargate Journey (https://www.curseforge.com/minecraft/mc-mods/sgjourney) 
It recently got a version for NeoForge MC 1.21.1. As it's also present in ATM9, it would be awesome to see it here, too.
