### ISSUE TITLE
Replacement of mod in "all the mods 10"

### ISSUE THREAD

**Issue by MrPiggione** [AllTheMods/ATM-10#100]
On behalf of many players, I ask you to replace MI with GT, for several reasons:
1. _Inconsistency with the vanilla style of play_
2. _Small amount of content_
3. _Fewer features added by MI_

**It will also be a huge thank you if there are 2 versions, one with GT and the other with MI,**

Thank you in advance for making amazing builds

**Comment by Kevin-Marsh** [comment]
No
