### ISSUE TITLE
ForceCraft

### ISSUE THREAD

**Issue by BossDarkCreeper** [AllTheMods/ATM-10#1001]
### Feature Details

Would be a great addition as time torches are a great way to increase farms. https://www.curseforge.com/minecraft/mc-mods/forcecraft/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6

**Comment by SpinHarmony** [comment]
Definitely a good suggestion, but please use #2 for suggestions instead of creating a new issue.
