### ISSUE TITLE
[Bug]: Observer texture bug

### ISSUE THREAD

**Issue by YocyCraft** [AllTheMods/ATM-10#1004]
### Possible Fixes

Yes

### Modpack Version

1.14

### What happened?

![2024-11-01_15 23 01](https://github.com/user-attachments/assets/47faf6df-0a24-4d89-a04d-05d12d970324)

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/812
