### ISSUE TITLE
[Bug]: Occultism's Book does not recognize white chalk for achievement.

### ISSUE THREAD

**Issue by arthurtmd** [AllTheMods/ATM-10#1005]
### Possible Fixes

Yes

### Modpack Version

1.15

### What happened?

After modifying the recipes and rituals of the Occultism mod, the book needs to unlock achievements to follow the rituals. Even though the chalk is white, the book does not recognize it as completed and does not release the drawing of the 1st ritual.
![2024-11-01_09 52 59](https://github.com/user-attachments/assets/538c985f-dae3-431f-ac5f-c13edbd84a5b)
![Sem título](https://github.com/user-attachments/assets/8271e750-8a5b-4e1d-a0ea-951dd91ec7e6)

### latest.log

https://gist.github.com/arthurtmd/669f0f5c6f01ecd14b5727012ad59d3f

### Developer reports

https://github.com/klikli-dev/occultism

**Comment by Eqis-Edu** [comment]
Check #972
