### ISSUE TITLE
[Crash]: Just dire things fluid placer

### ISSUE THREAD

**Issue by OmegaAlpha83** [AllTheMods/ATM-10#101]
### Possible Fixes

Yes

### Modpack Version

0.12

### What happened?

Whenever i open the simple fluid placers menu while it's actively placing fluids my game crashes, I can assume this happens for other blocks from the mod but, i don't know if this is an issue with some mods in ATM 10 or a just dire things issue i should report to that github. It only crashes the client, not the server. I have attached the crash log.

### Crash Log

https://gist.github.com/OmegaAlpha83/c8b0fa0571bc630a0caeb369173a3ed3

**Comment by alekthefirst** [comment]
Fixed in JDT 0.11.13, released with ATM10 0.15
