### ISSUE TITLE
[Bug]: ATM Star Shards have no recipe back to their counterpart

### ISSUE THREAD

**Issue by AriaElidove** [AllTheMods/ATM-10#1010]
### Possible Fixes

Yes

### Modpack Version

v1.15

### What happened?

Check for the usages for the ATM Star Shard and see there is no recipe to use them with.

Starry Bees are the main reason that this is problematic, as they provide the shards without a means to obtain the full star :P
![image](https://github.com/user-attachments/assets/ba0ab5b2-ccf8-467e-b2b4-d1e7d2c37a8c)

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/661
