### ISSUE TITLE
[Quests issues]: AE2 Meteorite hunting. How to complete?

### ISSUE THREAD

**Issue by Hegroze** [AllTheMods/ATM-10#1011]
### Modpack Version

1.14

### Describe the issue

I created a meteorite compass and found a meteorite in order to complete this quest. I found a meteorite, dug it up, and... nothing.
After that, I found about 3-4 more meteorites and nothing happened either, how do I move forward, how do I complete the quest?
![изображение_2024-11-02_050651222](https://github.com/user-attachments/assets/60ca72fc-8462-47ea-b91b-e32d027c959d)

**Comment by TheBedrockMaster** [comment]
That quest is supposed to be completed when you get the advancement for finding a meteorite.

**"My quest is stuck/grey"**
If you have a quest that isn't completing, you need to check if you completed all of it's requirements, you can check this by clicking on the quest, and clicking the small triangle/arrow on the top left of the quest popup. That will show all requirements.

If all the requirements are met, then the quest is probably actually stuck, which sometimes happens with FTB Quests:
To complete it, you need to be an OP (/op "username" from console) or have cheats enabled (if you didn't enable cheats in the world creation, open to LAN with cheats enabled).
With that, open the quests window.
Click the pencil icon on the bottom right, which enables editing mode.
Right click the quest in question.
Click Complete Instantly.

That will complete the quest, then disable the pencil button afterwards.

**"I want the reward from the quest though"**
In that case, in the quest popup, right click the reward, and click Reset Progress, that will let you claim the reward.
