### ISSUE TITLE
[Bug]: Armadillos not dropping scutes

### ISSUE THREAD

**Issue by VioletPhoena** [AllTheMods/ATM-10#1012]
### Possible Fixes

Yes

### Modpack Version

1.15

### What happened?

Armadillos always show "Next scute: 4s" in Jade. Right-clicking a brush on them does nothing. Attempting to use a brush with a dispenser just results in a black particle effect, with or without an armadillo in front of it.

**Comment by ffups** [comment]
any update on this? Still unable to brush the armadillos

**Comment by MadDogTen** [comment]
I have the same issue, Hoping someone has an idea for a fix.

**Comment by ffups** [comment]
> I have the same issue, Hoping someone has an idea for a fix. Seems impossible to get Armadillo scutes.

I saw on the atm discord that the wannabee will farm scutes from the armadillo, havent tested it myself but thats one workaround. The other being the armadillo seeds.

**Comment by MadDogTen** [comment]
> > I have the same issue, Hoping someone has an idea for a fix. Seems impossible to get Armadillo scutes.
> 
> I saw on the atm discord that the wannabee will farm scutes from the armadillo, havent tested it myself but thats one workaround. The other being the armadillo seeds.

Will try, thanks.

> Armadillos not dropping scutes via brushing is intentional. Scutes drop on death as a part of the [Hardened Armadillos](https://www.curseforge.com/minecraft/mc-mods/hardened-armadillos) mod.

Ah, Understood. Didn't even think to try killing them. Thanks for the help.

**Comment by xtended2l** [comment]
> Armadillos not dropping scutes via brushing is intentional. Scutes drop on death as a part of the [Hardened Armadillos](https://www.curseforge.com/minecraft/mc-mods/hardened-armadillos) mod.

Just to let you know, this made "Isn't is scute?" advancement impossible to fulfill.
