### ISSUE TITLE
[Bug]: Each Upgrade resets Quests and some other things

### ISSUE THREAD

**Issue by tekook** [AllTheMods/ATM-10#1017]
### Possible Fixes

Yes

### Modpack Version

1.15

### What happened?

On each update something does happen to the player identifier.
Everytime we upgrade the server all quests of the questbook are reset and doable again.
Some other stuff like mekanism frequencies also get reset (e.G. the owner is not visible anymore and just displays the uuid of the mc player.)

**Comment by 19Arice** [comment]
This has to do with forge client loading. when you change you forge client to a new update of a mod its a new folder. make sure you update the client version your using and not download a new version on forge. (multiple versions show up as separate modpacks on the forge launcher). copy and past your ftb quest data from the client folder you had everything done on and past it into the ftbquest folder of the new version. can do the same thing on the server's save to have the quests completed for everyone/enable quest sharing for ftb teams and team up.

Hope this helps, had the same issue.

**Comment by tekook** [comment]
> can do the same thing on the server's save to have the quests completed for everyone/enable quest sharing for ftb teams and team up.
@19Arice I'm playing only on a server.
My Client was never recreated, I always just upgrade the modpack via curseforge.

Can you point to the folder of file which needs to be preserved on the server? I always preserve the complete "world" folder between upgrades, and still Mekanisn and Quests are buggy after each upgrade.
