### ISSUE TITLE
[Bug]: I died to a shulker with "keepinventory true" and now my boots I wore turned into copper horse armor.

### ISSUE THREAD

**Issue by Tim-Odermatt** [AllTheMods/ATM-10#1021]
### Possible Fixes

Yes

### Modpack Version

1.15

### What happened?

I died to a shulker with "keepinventory true" and now my boots I wore turned into copper horse armor.
My boots were nowhere to be found. The horse armor protecting my feet did not solve that issue.
My Silent Gear Crimson Steel Boots > turned into > Copper Horse Armor from "Everything is Copper"

This is my first death where something weird happend to my Inventory.

Maybe I should remove the Grave mod. While plaing on keepinventory true?

**Comment by Corail31** [comment]
@Tim-Odermatt Sorry for this, by testing, i realised that having an HorseArmor in your inventory is making a problem in my code with the "auto-equip".
You can disable the "auto-equip" in client config (command /tbgui config) by setting "auto_equip_rule" to "NEVER".
You can use the command /tbrecovery to restore your boots and i'll make a fix soon.

**Comment by Tim-Odermatt** [comment]
@Corail31
Thank you. <3

**Comment by TheBedrockMaster** [comment]
Please let me know if/when this gets fixed.

**Comment by Corail31** [comment]
@TheBedrockMaster I linked the updated version (9.1.6).

**Comment by TheBedrockMaster** [comment]
Thanks, I was wondering if that update was apart of the recent ATM10 update. Should be good though.
