### ISSUE TITLE
[Quests issues]: 

### ISSUE THREAD

**Issue by Arthurabekat** [AllTheMods/ATM-10#1025]
![2024-11-03_18 39 08](https://github.com/user-attachments/assets/32267e87-8c2a-4a85-a9a2-da35481df1a5)
### Modpack Version

ATM10 1.15

### Describe the issue

Dunno if it should be in here, but the natures aura quest book is not letting me look through it, as i dont have the required advancements. But i cant get them. Its really annoying but i dont even know if it is a bug..

**Comment by TheBedrockMaster** [comment]
That's the mod's guide book, not the quest book, this should be fixed now anyway
