### ISSUE TITLE
[Bug]: silent gear properties

### ISSUE THREAD

**Issue by Jotunheim12** [AllTheMods/ATM-10#1028]
### Possible Fixes

Yes

### Modpack Version

1.15

### What happened?

making a brass pickaxe with silent gear doesn't have the silk touch property anymore. it says its there but it doesn't actually function.

**Comment by DaddyLongspoon** [comment]
This is already reported on Mr Chaos' github https://github.com/SilentChaos512/Silent-Gear/issues/697

**Comment by Jotunheim12** [comment]
> This is already reported on Mr Chaos' github [SilentChaos512/Silent-Gear#697](https://github.com/SilentChaos512/Silent-Gear/issues/697)

My bad. I’m still not used to GitHub so I find it difficult to navigate through so I missed that.

**Comment by DaddyLongspoon** [comment]
> > This is already reported on Mr Chaos' github [SilentChaos512/Silent-Gear#697](https://github.com/SilentChaos512/Silent-Gear/issues/697)
> 
> My bad. I’m still not used to GitHub so I find it difficult to navigate through so I missed that.

It's not a bad thing at all, not an attack at you but more just sharing the info, save the atm team from wasting time looking into it.  I don't think you should close the issue until it's fixed, somebody else will only make a duplicate.  have a great day

**Comment by Jotunheim12** [comment]
guess ill reopen in case i find other things that shouldnt be as they are. like the mekanism logistical pipe not connecting to any side of the recycler

**Comment by DaddyLongspoon** [comment]
> guess ill reopen in case i find other things that shouldnt be as they are. like the mekanism logistical pipe not connecting to any side of the recycler

That one is also already on the silent gear issues page.. and its not just the recycler, its all of his machines, grader, starlight charger, alloy machine etc..  and its not just meka plumbing, its all of them, pipes, MI item pipes, laserIO, modular routers...   but vanilla hoppers do work so there's your temporary fix, your mega pipe will happily pull from/ insert into a hopper ;)
it appears to be the same item handling difference between forge and neo forge which got mystical Agriculture last month, hopefully wont long.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/767
