### ISSUE TITLE
[Feature]: Alternate soul lava generation instead of bees 

### ISSUE THREAD

**Issue by shade1822226911** [AllTheMods/ATM-10#1029]
### Feature Details

it would be nice for soul lava to have another way of generating it instead of bees, or at the very least make soul lava bees also flower from soul lava buckets [maybe by adding a tag that soul lava and its bucketed form share] so omega upgrades actually work on them

**Comment by DaddyLongspoon** [comment]
The omega cards (and any other simulator cards) do already work on soul lava bee (and any other which pollinates from licking a fluid, water bee, lithium bee etc). just dig a one block hole where you would put a feed slab and pour it in there.  The only downside is you can't fit anything else like you might with the feed slab.  I have two soul bees in a hive generating several hundred buckets an hour.
![IMG_1396](https://github.com/user-attachments/assets/d51b7aa0-3e6e-43bc-bda3-66412c935f45)

**Comment by shade1822226911** [comment]
> The omega cards (and any other simulator cards) do already work on soul lava bee (and any other which pollinates from licking a fluid, water bee, lithium bee etc). just dig a one block hole where you would put a feed slab and pour it in there. The only downside is you can't fit anything else like you might with the feed slab. I have two soul bees in a hive generating several hundred buckets an hour. ![IMG_1396](https://private-user-images.githubusercontent.com/155957521/383290925-d51b7aa0-3e6e-43bc-bda3-66412c935f45.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTQ2NjMsIm5iZiI6MTczMDk5NDM2MywicGF0aCI6Ii8xNTU5NTc1MjEvMzgzMjkwOTI1LWQ1MWI3YWEwLTNlNmUtNDNiYy1iZGEzLTY2NDEyYzkzNWY0NS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNTQ2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWU2NmEzNjkwMWRiNGFkNmM0YTk4YTY1MjNmYWQ4NmY4NTYxYjc3YTMzNWJkNDEzNDUyMDAxNDdkYzVkZDUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o0U5mefIaSSGZ6WoesBW8gxJ7TQ4Lvz4OpgRgYl6plo)

I never knew that, Thank you for the info!
Although I will keep this issue open for a little longer because it wouldn't hurt to look over more methods
