### ISSUE TITLE
[Crash]: Help pls. Game crashes when entering the world

### ISSUE THREAD

**Issue by Hegroze** [AllTheMods/ATM-10#1033]
### Possible Fixes

Yes

### Modpack Version

1.14

### What happened?

The game crashed after the mob threw a potion. All subsequent attempts to enter the world are unsuccessful.
The game freezes at the moment of entering the world (Screenshots attached)
Tried to turn off shaders, did not help.
Tried to turn off particles, did not help.
The game is allocated 14 GB of RAM. Increased to 20 GB, unsuccessfully.
Crash logs attached.

### Crash Log

https://gist.github.com/Hegroze/20b398468ed0ef718d9b5380a7b91e43

**Comment by Tim-Odermatt** [comment]
You could temporarily add Neruina, which maybe will stop the PoisonCloud from Ticking and resulting in a crash, when successfull the mod will tell you what entity it stopped from ticking and where it is. Then you can just kill that effect.

remember to backup bevor testing.
irons_spellbooks:poison_cloud
at: x=3662.56, y=65.50, z=-3097.68

https://www.curseforge.com/minecraft/mc-mods/neruina/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6

**Comment by Hegroze** [comment]
> You could temporarily add Neruina, which maybe will stop the PoisonCloud from Ticking and resulting in a crash, when successfull the mod will tell you what entity it stopped from ticking and where it is. Then you can just kill that effect.
> 
> remember to backup bevor testing. irons_spellbooks:poison_cloud at: x=3662.56, y=65.50, z=-3097.68
> 
> https://www.curseforge.com/minecraft/mc-mods/neruina/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6

Thank you very much, it helped❤️.
I installed the mod, after several attempts I finally managed to load into the world.
Apparently the game broke because of this cloud (I'm attaching a screenshot).
Should I keep this mod to avoid further conflicts.

**Screenshot**
https://imgur.com/a/4TMc2WJ

**Comment by alekthefirst** [comment]
Fixed in i believe Irons 3.8.6, though change logs are unclear and it could very well be 3.8.5
