### ISSUE TITLE
[Bug]: Advance AE - Stock Export Bus cannot configure item amount using mouse middle click.

### ISSUE THREAD

**Issue by Spulcr** [AllTheMods/ATM-10#1038]
### Possible Fixes

Yes

### Modpack Version

ATM 10 - 1.16

### What happened?

In Advanced AE, the Stock Export Bus can't configure item amounts using the middle mouse click. Middle-clicking doesn’t do anything. When I use the ME Threshold Export Bus from Extended AE, the middle-click works fine, but the ME Threshold Export Bus doesn’t have a slot for a crafting card.

**Comment by FireBall1725** [comment]
+1 also having this issue, ATM 10 1.2

I was able to figure out a workaround for items, but unfortunately i wasn't able to find one for liquids

**Comment by Nlcko** [comment]
Your issue has been already reported for several weeks >> https://github.com/AllTheMods/ATM-10/issues/808
Look for « Applied Energistics » in the search bar, it helps before open a new report.

**Comment by alekthefirst** [comment]
Issue has presumably since been resolved and i am able to configure amounts in stock export buses just fine
https://github.com/user-attachments/assets/d5d7858b-48e9-4f6e-b01f-fbe3addd7746

**Comment by Spulcr** [comment]
> Issue has presumably since been resolved and i am able to configure amounts in stock export buses just fine https://github.com/user-attachments/assets/d5d7858b-48e9-4f6e-b01f-fbe3addd7746

Finally

**Comment by SkorFury** [comment]
Im having the same exact bug in ATM9 2/15/25 version 1.0.3

**Comment by Simon2009sch** [comment]
Me to
