### ISSUE TITLE
Functional storage single drawr and cupboard from Hancrafted have a recpie conflict[Bug]: 

### ISSUE THREAD

**Issue by 1matto** [AllTheMods/ATM-10#104]
### Possible Fixes

Yes

### Modpack Version

0.12

### What happened?

ther's a recipe conflict wit the single drawer and the cupboard in version 0.12 of ATM10

**Comment by aAndrew3030** [comment]
Duplicate of 
https://github.com/AllTheMods/ATM-10/issues/98

**Comment by Kevin-Marsh** [comment]
This will be patched in the next version.

**Comment by TheBedrockMaster** [comment]
Duplicate of
 https://github.com/AllTheMods/ATM-10/issues/98
