### ISSUE TITLE
[Bug]: Cobwebs Keep Spawning in and Other Debuff Keep Applying On Me When Killing Mobs

### ISSUE THREAD

**Issue by CodeXenois** [AllTheMods/ATM-10#1046]
### Possible Fixes

Yes

### Modpack Version

1.16

### What happened?

Every time I kill anything i get debuff with like 10 different negative debuff and cobweb spawns in under me

**Comment by Spulcr** [comment]
I believe it’s from the 'Infernal Mobs' mod. You only get debuffs and cobwebs from killing an 'Infernal Mobs' mob. You can disable it in the config.

**Comment by CodeXenois** [comment]
thanks
