### ISSUE TITLE
[Bug]: Update 1.16 Corrupts World

### ISSUE THREAD

**Issue by TronWoWGamer** [AllTheMods/ATM-10#1048]
### Possible Fixes

Yes

### Modpack Version

1.16

### What happened?

World gets corrupted after some time.  I thought it was due to JustDireThings SimpleBlockPlacer, but I removed this item and it still happened.  Thought it was due to Industrial Foregoing Fluid Extractor, so I broke and replaced them and then it happened again.  The last time it happened, I had just added an AE2 import bus to the top of a FunctionalStorage drawer and connected the smart cable to the AE2 system and within seconds it happened again.

Modded blocks can no longer be accessed after this.  Storage cannot be accessed whether chests, drawers, AE2 system, backpacks, nothing.  If I break a block, it just disappears, as if you were in creative and broke a block.  I can see the tooltip for vanilla blocks (glass, planks) but not modded blocks, though I can still walk through my Ethereal Glass.  My animals stop moving completely, and chunks start disappearing.  I can't exit the game through normal "save and exit".  It just sits there and hands for like 5-10 minutes until I kill the Java process in task manager.

I can restore a previous backup but eventually it does it again.

### latest.log

https://gist.github.com/TronWoWGamer/ef6108a1a73f6d7fc4c62f1e1492dd13

**Comment by NJM1564** [comment]
I had the same problem but it did that instantly on world load. I couldn't even assess the quest book. 
Downgrading to the last version fixed it for me.

**Comment by Fangzwusky** [comment]
same issue as comment, but world gets corrupted on first login. then just never works again. had too roll back too 1.15

**Comment by elbim** [comment]
Same here in 1.16.
Updated to 1.17 and the issue did not pop up again after 5 hours playing.
