### ISSUE TITLE
[Bug]: Mystical Enlightenment enchantment cannot be applied to mystical agriculture sword.

### ISSUE THREAD

**Issue by DaddyLongspoon** [AllTheMods/ATM-10#1049]
### Possible Fixes

Yes

### Modpack Version

1.0.16

### What happened?

tried to add mystical enlightenment to supremium sword, anvil says no, just a big red x.  Made a tertium sword, same.  This is a new problem, it was working back on beta...   (I'm on a second play through). it appears that if you start a world now you won't be able to get the awakening dust..
I put another basic pack together with MA and it worked fine, so I suspect the problem is with the (atm10) pack and not with MA.

**Comment by zeziba** [comment]
Ran into this as well, the enchantment conflicts with smite and similar enchantments now.

Enchant with the mystical enlightenment first then use books to add the other enchants to ensure to works properly.
