### ISSUE TITLE
[Bug]: Factory Blocks didn't have a recipe anymore 

### ISSUE THREAD

**Issue by LaughElephant** [AllTheMods/ATM-10#1055]
### Possible Fixes

Yes

### Modpack Version

1.16

### What happened?

I can't craft Factory Blocks anymore. I also placed some in my base and if I leave my base its crashing the server because of server Ticks.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/1031
