### ISSUE TITLE
[Crash]: Tick crash

### ISSUE THREAD

**Issue by Demonknight1434** [AllTheMods/ATM-10#106]
### Possible Fixes

Yes

### Modpack Version

10-0.12.zip

### What happened?

Description: Ticking player
[crash-2024-07-15_21.02.35-server.txt](https://github.com/user-attachments/files/16242287/crash-2024-07-15_21.02.35-server.txt)

### Crash Log

https://gist.github.com/Demonknight1434/23ddeedb333dff0479820611e6f199b9

### Latest.Log

https://gist.github.com/Demonknight1434/23ddeedb333dff0479820611e6f199b9

**Comment by Kevin-Marsh** [comment]
This should be prevented in the next version of the pack with an update to the Relics mod
