### ISSUE TITLE
[Bug]: Mystical Agriculture config about watering can may not work

### ISSUE THREAD

**Issue by Plokim1437** [AllTheMods/ATM-10#1060]
### Possible Fixes

Yes

### Modpack Version

1.7

### What happened?

I wanted to enable fake player to use watering can and I went to config file. But when I restarted the game I found it still banned. I tried to find why but there were no code and command adout it. Today I ask my friends for help and they suggest me to send an issue. May something is wrong,  I need help.

**Comment by TheBedrockMaster** [comment]
It should be as easy as changing the config, for further help I recommend joining the ATM Discord and asking there.

**Comment by Plokim1437** [comment]
Yep it should be easy. I changed the config and the watering can, However, can't be enabled for fake player. For some reason, I can't get access to Discord so I raise an isuue here. 
I go to saves file and other relative mods' config to cover the reason too. It shows that the bool in config file is ture but still act like false in singleplayer. I dont know why. 
![Screenshot 2024-11-07 144010](https://github.com/user-attachments/assets/8ff815b0-7e7b-474d-b5a0-f213d20b8749)
![Screenshot 2024-11-07 143448](https://github.com/user-attachments/assets/30bbd133-3585-4885-b512-c306ce3d0d04)

**Comment by TheBedrockMaster** [comment]
The Discord is linked here https://github.com/AllTheMods/ATM-10, I would try to help here but this isn't something that is intended to be done to the game. Go for it though of course.
