### ISSUE TITLE
[Bug]: Leather Recipe From Mystical Agriculture

### ISSUE THREAD

**Issue by ItaloBrunoM** [AllTheMods/ATM-10#1061]
### Possible Fixes

Yes

### Modpack Version

1.16

### What happened?

Mystical's leather recipe is making meat, I tried several possibilities, but only the meat recipe is enabled
![2024-11-07_01 12 32](https://github.com/user-attachments/assets/2b9efce6-419a-4665-992f-448eab0f4ec3)
![2024-11-07_01 12 39](https://github.com/user-attachments/assets/b75667be-04ae-4439-8651-64dada11259a)

**Comment by TheBedrockMaster** [comment]
Have you clicked the polymorph arrow button? That should swap the recipes.
