### ISSUE TITLE
[Bug]: Entangled Block not connecting to Mekanism Tube

### ISSUE THREAD

**Issue by tomokari07** [AllTheMods/ATM-10#1062]
### Possible Fixes

Yes

### Modpack Version

1.16

### What happened?

I was trying to connect the entangled block to transfer sodium but it wouldn’t connect

**Comment by AwakenedRose** [comment]
like the quantum entagloporter block ?? if so have you configured the sides for item input or output??

**Comment by alekthefirst** [comment]
Mekanism pressurized tubes can't connect to entangled blocks, i believe you are able to workaround this by an ME system and/or Mekanism gas tanks, but as far as i am aware this is as intended
