### ISSUE TITLE
[Crash]: Please help me

### ISSUE THREAD

**Issue by gebaojian** [AllTheMods/ATM-10#1063]
### Possible Fixes

Yes

### Modpack Version

1.16

### What happened?

I was playing normally and the game crashed suddenly, and looking at the crash report showed that there was a problem with three mods： - NaturesAura-41.3.jar
 - ftb-chunks-neoforge-2101.1.2.jar
 - relics-1.21-0.9.2.0.jar
 Please help me

### Crash Log

https://gist.github.com/gebaojian

**Comment by alekthefirst** [comment]
No crash log provided in link, closing as stale until further information or issues surface
