### ISSUE TITLE
[Bug]: piglich and other allthemods spawn eggs crafting recipes bugged

### ISSUE THREAD

**Issue by about21midgets** [AllTheMods/ATM-10#1069]
### Possible Fixes

Yes

### Modpack Version

1.15

### What happened?

for both methods to craft a piglich spawn egg in survival, that being  mob grinding utils with the mob swab and  reliquary with the charms, they either dont drop an egg or are replaced with a chicken egg.
i also found some vindicator varients in the atm mod that craft chicken eggs instead of their actual variants
is this intended or a bug?

**Comment by DaddyLongspoon** [comment]
Check in JEI if these mobs actually have a spawn egg.  Mob Swabs usually always produce a chicken spawn egg if none is available (chicken egg may be the default egg or the first in the table or something)

**Comment by TheBedrockMaster** [comment]
This isn't really a bug, you're not supposed to be able to get piglich spawn eggs.
