### ISSUE TITLE
[Feature]: Ars Addon StarbuncleMania

### ISSUE THREAD

**Issue by Revv1e** [AllTheMods/ATM-10#1073]
### Feature Details

I was wondering if it would be possible to add StarbuncleMania into the mod to sort of make Ars another possible way to go through in the materials processing for magic things, being able to get Fortune on the ores, and then crushing with Occultism would be fun to go through, and makes it a fun way to use magic to do things rather than having to go with machines all the time.

Also c'mon Starbuncles are cute!

**Comment by TheBedrockMaster** [comment]
Use #2 for mod suggestions

**Comment by Revv1e** [comment]
Sorry, thank you!
