### ISSUE TITLE
[Bug]: Nature's Aura book doesn't unlock with progression

### ISSUE THREAD

**Issue by thisKid619** [AllTheMods/ATM-10#1074]
### Possible Fixes

Yes

### Modpack Version

10-1.16

### What happened?

Nature's Aura guide book doesn't unlock anything after gathering brilliant fiber and golden leaves. None of the multi-blocks can be viewed either

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/1014
