### ISSUE TITLE
[Bug]: Occultism stable warmhole makes the game crash when linked

### ISSUE THREAD

**Issue by paulo1525** [AllTheMods/ATM-10#108]
### Possible Fixes

Yes

### Modpack Version

0.11 today's release

### What happened?

When a stable warmhole (not previously linked) is linked to the dimensional storage actuator and the game tries to save the changes, it crashes.
`The game crashed whilst saving entity nbt
Error: java.lang.IllegalStateException: Missing id for entity in: {linkedStorageControllerPosition:{dimension:"minecraft:overworld",pos:[I;1707,69,189]}}`

### latest.log

https://gist.githubusercontent.com/paulo1525/ca4cef66f260b61bf40115fbb18bb297/raw/00d5b0476bc941a92e1b6af902fec06160305359/gistfile1.txt

### Developer reports

https://github.com/klikli-dev/occultism

**Comment by Seegras** [comment]
Yes.. But only in the inventory. If you manage to place it before it saves, it works.

**Comment by alekthefirst** [comment]
Fixed in Occultism 1.21.1-1.153.3, released with ATM10 0.41
