### ISSUE TITLE
[Bug]: Resapie conflict (Or something else?)

### ISSUE THREAD

**Issue by NJM1564** [AllTheMods/ATM-10#1081]
### Possible Fixes

Yes

### Modpack Version

All the mods 10

### What happened?

Mystical Agriculture uses the same resapie for raw beef and leather. This is a problem for trying to autocraft.
Edit: Trying to make leather with rabbit hide also seems to be jamming up.
Edit 2: Problem seems to be with  AE2 Crafting Tree. Pulled (removed) it and it seems to work. Why do we even have that mod?

**Comment by alekthefirst** [comment]
Issue has since been resolved
![image](https://github.com/user-attachments/assets/ed284ac0-4139-48c4-b14a-014894e7b525)
