### ISSUE TITLE
[Bug]: Uncraftable Syntetic rubber

### ISSUE THREAD

**Issue by Fangzwusky** [AllTheMods/ATM-10#1082]
### Possible Fixes

Yes

### Modpack Version

1.15

### What happened?

Attempting too craft synthetic rubber in any mixer does not work. Recipe produces yellow dye instead. Alltheores sulfur does not work in this recipe. and no other sulfurs are craftable in the pack. Other sulfurs cheated in does work. 1b Synthetic oil + 1 sulfur dust of any kind works but not with the only available sulfur from alltheores. So it's uncreatable without cheating.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/1041
