### ISSUE TITLE
[Bug]: Disconnect Unknown Cause Likley Nature's Aura Book With In Game Projection

### ISSUE THREAD

**Issue by zeziba** [AllTheMods/ATM-10#1085]
### Possible Fixes

Yes

### Modpack Version

1.17

### What happened?

Just updated the game to 1.17 and was going to get into nature's aura.

Crafted the tree stump and golden dust to make the ritual site. Then crafted the book and used the projection button.
After right clicking to anchor it in world the game disconnected.

I redid the above and it repeated the same.

The final time I placed the ritual and it did it again even after completing the ritual space and the projection finalizing. 

[disconnect-2024-11-08_22.19.20-client.txt](https://github.com/user-attachments/files/17685966/disconnect-2024-11-08_22.19.20-client.txt)
[disconnect-2024-11-08_22.24.18-client.txt](https://github.com/user-attachments/files/17685967/disconnect-2024-11-08_22.24.18-client.txt)
[disconnect-2024-11-08_22.16.33-client.txt](https://github.com/user-attachments/files/17685968/disconnect-2024-11-08_22.16.33-client.txt)

**Comment by zeziba** [comment]
Reloaded the game world today and it did the same less than 30 secs into the world.

[disconnect-2024-11-09_10.29.13-client.txt](https://github.com/user-attachments/files/17688636/disconnect-2024-11-09_10.29.13-client.txt)

**Comment by lukyky414** [comment]
I have the same error log,
```
[Render thread/ERROR] [net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl/]: Failed to handle packet net.minecraft.network.protocol.game.ClientboundSetPlayerTeamPacket@109865e3
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'c_overworld_1'.
```

Only on client side, my server is running fine (and the other player are not disconnected). There is no log on the server.
Seems random, not related to a particular mod or interaction with the world.

I would really like to find what mod is causing this.

**Comment by lukyky414** [comment]
I have found in scoreboard.dat in the world folder.
This team contains all of my minecolonies villagers + some tag (like UUID) for visitors.

This bug is related to minecolonies:
https://github.com/ldtteam/minecolonies/issues/10425

**Comment by zeziba** [comment]
Got back to playing, deleted the minecolonies data folder in the save game folder and now I am not having any issues with the score board.  Been playing around 2 hours near and around the mine colony and have used nature's aura without repeat of the previous issues.

Read through the various patch notes for mine colonies and nature's aura and cannot see if there was a change that would have affected this particular issue as the issues is still live on the mine colonies github.

Have also updated to 1.19.
