### ISSUE TITLE
Composite table error

### ISSUE THREAD

**Issue by YCJ-GuLi** [AllTheMods/ATM-10#1088]
edition:1.17
![1](https://github.com/user-attachments/assets/3935eb70-ebe5-4c0d-950a-87f91f01cff9)
![2](https://github.com/user-attachments/assets/1dc5ca47-d8c4-4af6-8194-ef592db8c19d)
![3](https://github.com/user-attachments/assets/1729c71e-7eb8-4812-9a8d-e4ec413615af)
A large number of item formulas have been incorrectly modified

**Comment by Droxtor** [comment]
Same here with latest 1.17 patch
![image](https://github.com/user-attachments/assets/dfe86045-b0f2-41ed-bfd6-6cb1713772bf)
