### ISSUE TITLE
[Bug]: AE2 Condenser Gives No Items.

### ISSUE THREAD

**Issue by FallenPumpking** [AllTheMods/ATM-10#109]
### Possible Fixes

Yes

### Modpack Version

.14

### What happened?

The Matter Condenser from AE2, shows it will give 0 items per "item". Upon filling the storage component up, no matter balls or singularities are given.

**Comment by Kevin-Marsh** [comment]
This has been fixed by Applied Energistics. You can either manually update the mod or wait for the next pack update.
