### ISSUE TITLE
[Bug]: Recipe Bug

### ISSUE THREAD

**Issue by KenZync** [AllTheMods/ATM-10#1090]
### Possible Fixes

Yes

### Modpack Version

1.17

### What happened?

right placement but why there is number
![image](https://github.com/user-attachments/assets/f6c95cf7-8afa-4d1d-b330-c8705e125c39)

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/1088
