### ISSUE TITLE
[Bug]: Quest not working

### ISSUE THREAD

**Issue by RxIaY** [AllTheMods/ATM-10#1092]
### Possible Fixes

Yes

### Modpack Version

1.16

### What happened?

I cant complete the Quests in Ocultism and Ethernal Starlight

**Comment by TheBedrockMaster** [comment]
Please give more information, what specific quests won't complete?

**Comment by TheBedrockMaster** [comment]
"My quest is stuck/grey"
If you have a quest that isn't completing, you need to check if you completed all of it's requirements, you can check this by clicking on the quest, and clicking the small triangle/arrow on the top left of the quest popup. That will show all requirements.

If all the requirements are met, then the quest is probably actually stuck, which sometimes happens with FTB Quests:
To complete it, you need to be an OP (/op "username" from console) or have cheats enabled (if you didn't enable cheats in the world creation, open to LAN with cheats enabled).
With that, open the quests window.
Click the pencil icon on the bottom right, which enables editing mode.
Right click the quest in question.
Click Complete Instantly.

That will complete the quest, then disable the pencil button afterwards.

"I want the reward from the quest though"
In that case, in the quest popup, right click the reward, and click Reset Progress, that will let you claim the reward.

I can reopen this if it's unrelated.

**Comment by Sarlesa** [comment]
Anything we can do to fix it if we arent admin? We play on a server but the owner doesnt use cheats or anything like that....
