### ISSUE TITLE
[Bug]: Conflicting bronze dust recipes

### ISSUE THREAD

**Issue by Maxi3773** [AllTheMods/ATM-10#1098]
### Possible Fixes

Yes

### Modpack Version

1.17a

### What happened?

There are two conflicting recipes for creating bronze using dust:
![Screenshot 2024-11-09 200145](https://github.com/user-attachments/assets/86e2012f-69e3-40e5-b832-f72dadde4049)
The first recipe (yielding 4 bronze dust) is consistent with other ways of creating bronze and other alloys and should therefore be kept. **The second recipe (yielding 3 bronze dust) is inconsistent** with other ways of creating bronze and should be removed.

**Comment by TheBedrockMaster** [comment]
Thanks, if you see other recipes like this please let us know :)
