### ISSUE TITLE
[Bug]: All ProductiveBees Recipes from EMI are gone when playing the last update on a server

### ISSUE THREAD

**Issue by 5pHiNxX** [AllTheMods/ATM-10#110]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-0.14

### What happened?

When playing in singleplayer the recipes are shown. But on server no recipe from ProductiveBees is shown in EMI.

### latest.log

https://gist.github.com/5pHiNxX/edf7baf31e547efc64e099e201a484aa

**Comment by 5pHiNxX** [comment]
Found a workaround. Executed the `/reload` command serverside and the recipes are shown again.

**Comment by kollinkoko** [comment]
/reload does not fix the issue for me.

**Comment by 5pHiNxX** [comment]
> /reload does not fix the issue for me.

Oh you're right. Tried to reproduce my workaround and found out, that it was not the reload command. But if you switch to single player, open EMI and a Productive Bees recipe and then switch back to multi-player without closing the game, the recipes seem to work.

**Comment by MarianNapi** [comment]
Seems fixed in Version 0.16+?

**Comment by 5pHiNxX** [comment]
Yes. Definitifely fixed
