### ISSUE TITLE
[Bug]: AE2 Being Very Erratic

### ISSUE THREAD

**Issue by ImTehCookie** [AllTheMods/ATM-10#1108]
### Possible Fixes

Yes

### Modpack Version

1.17

### What happened?

For some reason I cannot fathom, AE2 seems to hate this setup no matter what I do. If I get it working temporary, it breaks again the moment the server restarts. It is a ME Wireless Connector with 3 export bus's exporting lava into a dimensional chest. Also connected to it is a ME Active Formation Pane placing down redwood logs for a Fluid Extractor setup for latex. I cannot fathom why this setup breaks. I get it working but randomly breaking parts of it and replacing them. Sometimes adding a ME Interface solves the problem but then it breaks again once the server restarts. 
No matter what I do, once the server restarts I get told the export bus's, formation pane, and if I have a ME Interface placed, all have missing device channels. Using the Network tool, it shows that only 15 channels are being used in total for this setup so I cannot see why this constantly breaks. At one point I thought it might be an issue with energy so I placed down a dense energy cell just for testing, which fixed it for a day or so but then started again after the 3rd or 4th server restart. I'm at my wits end.

![image](https://github.com/user-attachments/assets/586d9df7-e65b-4882-a111-21095d37f1a9)

![image](https://github.com/user-attachments/assets/190df77b-47a5-4c7b-93d8-b6e1ffd1da8d)

![image](https://github.com/user-attachments/assets/1629be24-d109-4d29-b583-a04b80164804)

![image](https://github.com/user-attachments/assets/53bc509a-5a82-45af-87ae-fc2702eff9c9)

### latest.log

https://gist.github.com/ImTehCookie/a60bfcfd484073956bfbdd866336f662

### Developer reports

https://github.com/AppliedEnergistics/Applied-Energistics-2

**Comment by AwakenedRose** [comment]
have you tried using smart dense cables they allow up to 32 channels ?? i seen none in your setup thats why im asking

**Comment by ImTehCookie** [comment]
I've tried swapping out cables of every kind, they all show less than 6 or 7 channels being used, I've given up on the setup and swapped to a different version. I'm just confused because I can't pin down why it would work up until the server restarted.
