### ISSUE TITLE
[Crash]: Keybinding issue and crash

### ISSUE THREAD

**Issue by NeuFangerss** [AllTheMods/ATM-10#111]
### Possible Fixes

Yes

### Modpack Version

0.14

### What happened?

I was trying to swap my key bindings for sprint and sneak. Every time I pressed left ctrl for sneak, it says it is already bound to other things and forces to the next key press instead of staying left ctrl. Does the same for and key. Tried to click away, all that does is set sneak to left click. I went to the search bar and clicked 'Key' to search for ctrl, so that I can clear other binds and only have sneak set to that key so there is no conflict. As I typed C and then T it said Saving World and crash. Mind that I just loaded the pack and have not entered any world yet. I have only been to the settings menu from the home screen. 

### Crash Log

https://gist.github.com/NeuFangerss/620b2359a8d2cd18e11ec3eeef56c971.js"

### Latest.Log

https://gist.github.com/NeuFangerss/a85f0c093e0a59745292fd5e62469210.js

**Comment by NeuFangerss** [comment]
I find in order to get my key binds to stick and not to be set to the next input, I have to close the client after the bind has been set to. Clicking done just binds the action to left click.

**Comment by NeuFangerss** [comment]
Crashing is happening any time I type. I was tying to enter a world and it crashed again

**Comment by Kevin-Marsh** [comment]
Please try removing easy villagers and see if the issue persists.

**Comment by tubaplayer112** [comment]
had the same issue/bug i had to change the keybind for easyvillagers cycle trade. it was c for me and i changed it to a random key. which crashed the game but it remembered the change and now pressing c no longer crashes my game.

**Comment by Kevin-Marsh** [comment]
This is caused by Easy Villagers and can be solved by updating the mod. This will also be updated in the next version of the pack.
