### ISSUE TITLE
[Bug]: Raw Uranium and Raw Yellorium OreDictionary missing

### ISSUE THREAD

**Issue by Macromious** [AllTheMods/ATM-10#1115]
### Possible Fixes

Yes

### Modpack Version

1.17a

### What happened?

I am unable to substitute yellorium ore for uranium ore in mekanism machines such as the purification chamber and enrichment chamber. JEI shows no recipes for the use of yellorium in these machines, and it can only be smelted to uranium ore.

**Comment by alekthefirst** [comment]
Yellorium ore is no longer obtainable by any normal means, and will thusly not receive such compatibility
