### ISSUE TITLE
[Bug]: allthemodium silent gear armor set bonus disparity

### ISSUE THREAD

**Issue by Supergod99** [AllTheMods/ATM-10#1122]
### Possible Fixes

Yes

### Modpack Version

1.18

### What happened?

The new version gave allthemodium armor set their former abilites back, but this does not apply to the silent gear versions (still take fall damage), which are much, much more expensive to craft (assuming its all allthemodium plates). Not sure if this is intended or not.

**Comment by alekthefirst** [comment]
This is intended, the silent gear armor receives a different set of bonuses instead, as well as higher armor and armor toughness values
