### ISSUE TITLE
[Bug]:  Network Error Report?

### ISSUE THREAD

**Issue by Silverrye** [AllTheMods/ATM-10#1129]
### Possible Fixes

Yes

### Modpack Version

1.17a

### What happened?

[disconnect-2024-11-12_07.55.56-client.txt](https://github.com/user-attachments/files/17719197/disconnect-2024-11-12_07.55.56-client.txt)

Unsure what I have done to get this message, but every once in a while this happens.  Kicks me out of my world I created with my husband. Network + Computer were restarted prior to this message. No added mods.  Can join back in but will send an error again. Repeatable but unsure why, unsure what is causing said issue.

**Comment by lukyky414** [comment]
Someone else has the same issue:
https://github.com/AllTheMods/ATM-10/issues/1085

They did not mention Network + Computer.
I personnally did not use that mod, but still have the exact same bug.

**Comment by lukyky414** [comment]
I have found in scoreboard.dat in the world folder.
This team contains all of my minecolonies villagers + some tag (like UUID) for visitors.

This bug is related to minecolonies:
https://github.com/ldtteam/minecolonies/issues/10425

**Comment by Silverrye** [comment]
> I have found in scoreboard.dat in the world folder. This team contains all of my minecolonies villagers + some tag (like UUID) for visitors.
> 
> This bug is related to minecolonies: [ldtteam/minecolonies#10425](https://github.com/ldtteam/minecolonies/issues/10425)

Did you ever find a fix or no? Just curious about what we should do or if we should try to restart and remove mine colonies.

**Comment by CloWnicide** [comment]
Newest pack version has an updated version of Minecolonies that fixes this issue it seems.

**Comment by TheBedrockMaster** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1085
