### ISSUE TITLE
[Crash]: Client crashes when close to a potion melder

### ISSUE THREAD

**Issue by Liliune** [AllTheMods/ATM-10#1131]
### Possible Fixes

Yes

### Modpack Version

1.17a

### What happened?

Getting close to a chunk with a potion melder is causing me to crash on The CDU servers and i was told to inform the ATM team of this happening on the server with Neruina

### Crash Log

https://mclo.gs/0LdeGrs

### Latest.Log

https://mclo.gs/5Q44TGb

**Comment by alekthefirst** [comment]
Fixed in Ars Noveau 5.3.2, released with ATM10 1.26
