### ISSUE TITLE
[Bug]: Daylight cycle in the mining dim

### ISSUE THREAD

**Issue by ColinDuch** [AllTheMods/ATM-10#1132]
### Possible Fixes

Yes

### Modpack Version

1.18

### What happened?

Hi in the quest book it say that the mining dim as no daylight cycle but it's not the case for me so i don't really know if it's something that can be fix or if it an error in the quest book.
Thank you

### latest.log

https://gist.github.com/ColinDuch/efd2c4d97b6838d44aea4120506f1da6

**Comment by thevortex** [comment]
apologies, there is a lot of outdated info in the guide, we changed it to a normal daylight cycle because mek didnt understand permanent daylight and some of its machines suffered as a result

**Comment by alekthefirst** [comment]
Fixed in https://github.com/AllTheMods/ATM-10/commit/30ca2f3748b5e2c7b99dbaa7021b318e89e7bec8
Released with ATM10 2.0 (possibly 1.27 if timezones mess with timestamps)
