### ISSUE TITLE
[Feature]: Make ATM stars 

### ISSUE THREAD

**Issue by YCJ-GuLi** [AllTheMods/ATM-10#1144]
### Feature Details

I can make ATM stars and also produce ATM stars Shard.
Why can't we use ATM stars Shard to create ATM stars
![1](https://github.com/user-attachments/assets/98846f75-b281-4498-8bb0-c6f07925ba31)
![2](https://github.com/user-attachments/assets/fa7f1c74-222c-462d-bb5a-994673a8c6e0)

**Comment by YCJ-GuLi** [comment]
This makes my ATM stars bee useless

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/661

**Comment by YCJ-GuLi** [comment]
> 重复：#661

When is this problem expected to be resolved?
