### ISSUE TITLE
[Bug]: Iridium CANNOT be found.

### ISSUE THREAD

**Issue by Medelaldersmannen** [AllTheMods/ATM-10#1145]
### Possible Fixes

Yes

### Modpack Version

1.19

### What happened?

Been looking everywhere for iridium ore, both overworld, nether end and miningworld.

Seen a couple of threads on reddit aswell that people have problem findning it, 

been using digitalminer and spells aswell as just raw pickaxemining.

much appreciated if anyone can either deny or confirm my suspicions.

**Comment by DaddyLongspoon** [comment]
the mining drill from modern industrial will find it, or you'll find it quite quickly with boon of the earth enchantment.
There are a few ores from modern industrial (titanium is another) which don't spawn in the world, you're supposed to get them with the mining drill.  but boon enchantment breaks that, then you can make a seed or bee.

**Comment by Seanypat** [comment]
I hold a pickaxe with Boon of the Earth on it in my main hand and cast Spectral Hammer at max level to get a lot of drops at once. This is the only way I've found Iridium, and Titanium as @DaddyLongspoon mentioned above.

**Comment by Zombiebear99** [comment]
You could use occultism elderith miner that work and fast
