### ISSUE TITLE
[Bug]: Crafting Grid keeps spinning items

### ISSUE THREAD

**Issue by Skripted42** [AllTheMods/ATM-10#1146]
### Possible Fixes

Yes

### Modpack Version

Newest atm

### What happened?

If i put anything into any crafting grid it keeps spinning in a circle (Teleporting grids in a circle motion), which makes it impossible to craft. Anyone encountered this problem before and is there a fix for it?

**Comment by alekthefirst** [comment]
https://old.reddit.com/r/allthemods/comments/1ey49xs/anyone_know_how_to_fix_this/ljaxnsi/
