### ISSUE TITLE
[Bug]: Simulator Upgrade not producing Combs

### ISSUE THREAD

**Issue by CrZ25** [AllTheMods/ATM-10#115]
### Possible Fixes

Yes

### Modpack Version

10-0.14

### What happened?

When adding the Simulator Upgrade onto Advanced Hive the combs will stop producing for any type of bees (draconic, sulfur, iron, etc.).

**Comment by MarianNapi** [comment]
It's a little bit buggy.
As a workaround do it like that:

![image](https://github.com/user-attachments/assets/3f7f2274-82c4-4b8c-83d0-49891abb6a2a)

The feeding slab has to be on the upper side of the block BELOW the hive. The Feeding item has to be in the RIGHTMOST Slot of the feeding slab

**Comment by JaisDK** [comment]
I just tested having something in each slot and there's no such bug/limitation

**Comment by Roksidian** [comment]
I have this exact problem with the energizing bees and also silicon bees but diamond,allthemodium,draconic, etc works perfectly im wondering how i could find a solution
Also the only way energizing bees produces combs is using the hive without a simulator

**Comment by JaisDK** [comment]
open a new issue instead of resurrecting a year old closed issue
