### ISSUE TITLE
[Feature]: Add "sparce structures" mod to fine tune the frequency off all structures in the pack.

### ISSUE THREAD

**Issue by Shrimpgodd** [AllTheMods/ATM-10#1152]
### Feature Details

Sparse Structures by: [Maxence]

(https://www.curseforge.com/members/maxence)

The mod adds the command /dumpstructuresets that makes a list of all in-game structures inside of a txt file. That structure data can then be copied into the same mods config file and each structures generation frequency can be tuned. I use it to turn down the frequency of villages, pirate ships, floating islands, ae2 meteors, and those little cave camps. this would also be a good solution for players looking for a single config file to adjust a specific structures spawn rates. the config will have to be updated whenever new structures are added either through more mods or mod updates. This could also help with structure overlap, i have every structure set to be twice as rare and world generation seems to be way less janky.

**Comment by Mitchell5200** [comment]
Use #2 for mod suggestions.
