### ISSUE TITLE
[Bug]: Typing capital "C" when naming a server crashes the game

### ISSUE THREAD

**Issue by Baxterbixby** [AllTheMods/ATM-10#116]
### Possible Fixes

Yes

### Modpack Version

0.14

### What happened?

When connecting to a new server typing a capital "C" into the server name at any point causes the whole game to crash.
EDIT: Typing "C" anywhere at all during the main menu does this. All other capital letters are okay to type. Just "C" crashes the game

**Comment by Kevin-Marsh** [comment]
This is caused by the Easy villagers mod. Updating the mod should resolve it or you can wait for the next update.
