### ISSUE TITLE
[Bug]: Connection Lost on Lan - Failed to Encode Packet

### ISSUE THREAD

**Issue by YukinariSaio** [AllTheMods/ATM-10#1160]
Updated to most recent pack version, S.O. was trying to join [ We've been playing fine for a while. ] And they get this error.

![image](https://github.com/user-attachments/assets/aa3a5d10-daee-4233-824c-ebfb46404346)

We've tried another world, changing versions of Neo Forge as well as using same config files.

**Comment by YukinariSaio** [comment]
As a note, I'm hosting and am able to play normally

**Comment by NavigatorNoodles** [comment]
Adding to this, I was having the same issue; removing Supplementaries fixed it.

**Comment by oatmealmanFG** [comment]
same issue for me and my son. unable to disable supplimentaries on my sons pc as FTB wont load mod list. disabled on mine and will test.

**Comment by cferreras** [comment]
> Adding to this, I was having the same issue; removing Supplementaries fixed it.

That works!
