### ISSUE TITLE
[Bug]: Unable to play multiplayer might be an issue caused by the update of the mod Actually Additions.

### ISSUE THREAD

**Issue by hhhhhhhhhhhhhh204** [AllTheMods/ATM-10#1168]
### Possible Fixes

Yes

### Modpack Version

1.20

### What happened?

Unable to play multiplayer might be an issue caused by the update of the mod Actually Additions.

Internal Exception:io.netty.handler.codec.EncoderException: Failed to encode packet
clientbound/minecraft:custon_payload

**Comment by Silverrye** [comment]
Would like to say I'm experiencing the same issue when trying to open to a LAN!

**Comment by Balibaloo** [comment]
Same here

**Comment by hhhhhhhhhhhhhh204** [comment]
> 此处相同你最后的工作版本是什么？
> 
> 编辑：19个作品很好

**Comment by hhhhhhhhhhhhhh204** [comment]
1.19

**Comment by hhhhhhhhhhhhhh204** [comment]
1.19

**Comment by hhhhhhhhhhhhhh204** [comment]
> Same here What was the last working version for you?
> 
> Edit: 19 works fine

1.19

**Comment by Alucard1313** [comment]
It's not Actually Additions that is causing the problem, it's Supplementaries. Remove it for now until an update fixing the issue is released.
