### ISSUE TITLE
[Bug]: Public server - Levitation Potion Recipe per EMI doesnt craft

### ISSUE THREAD

**Issue by daleamann** [AllTheMods/ATM-10#117]
### Possible Fixes

Yes

### Modpack Version

10-0.14

### What happened?

Following the recipe in EMI for a potion of flight, the second to last potion is the Levitation potion. However, it is not working to be crafted on the public server.

**Comment by daleamann** [comment]
Nor can you make Potion of Ancient Knowledge. Bottles of Enchantin will not go into the brewer stand.

**Comment by daleamann** [comment]
10-0.16 update does not fix the brewing issues.

**Comment by MarianNapi** [comment]
I was playing on a server on 0.12 and also ran into the problems with the Potion of Ancient Knowledge.
When I went into single player I could brew it. Back on the server didn't work.

Also updated to 0.16 yesterday and can confirm it's still not working

**Comment by daleamann** [comment]
10-0.18 still not working for these recipes.

**Comment by daleamann** [comment]
10-0.19 not working

**Comment by WednesdayMWS** [comment]
10-0.48 still doesn't craft

**Comment by ryocryte** [comment]
0.51, still does not craft.

**Comment by danif86** [comment]
same for haste + more
