### ISSUE TITLE
[SERVER]:How to update server from (All The Mods 10-0.13) to All The Mods 10-0.14 .

### ISSUE THREAD

**Issue by 1SuPaul** [AllTheMods/ATM-10#118]
I plan on hosting a server for my own use my loptop,but All The Mods 10 is a constantly-changing modpack. So if I wanna start play now with my friends. How do I do to update the server for newer version and more fantastic mods that your team plug in?

**Comment by Mitchell5200** [comment]
https://allthemods.github.io/alltheguides/help/server/#updating

**Comment by 1SuPaul** [comment]
I'll try it,appreciated for the help.
