### ISSUE TITLE
[Bug]: Deepslate Yellorite Ore doesn't have the same processing possibilities as normal yellorite ore

### ISSUE THREAD

**Issue by localzuk** [AllTheMods/ATM-10#1181]
### Possible Fixes

Yes

### Modpack Version

1.20

### What happened?

Normal Yellorite ore can be processed into Uranium to be used wherever uranium is used. However, the deepslate variant cannot be processed in the same way. For example, it cannot be fed into a SAG Mill or any furnace.

**Comment by alekthefirst** [comment]
Yellorite has been unified into normal uranium, which should have those processing possibilities
