### ISSUE TITLE
[Bug]: Can't break Stone with Pickaxe

### ISSUE THREAD

**Issue by dave36464736** [AllTheMods/ATM-10#1182]
### Possible Fixes

Yes

### Modpack Version

1.21

### What happened?

I updated to 1.21. I logged on and tried to break stone with my vibranium pickaxe. I was told my unbreaking was issue. I removed. Same issue. Tried another pickaxe, same issue. I cannot break any stone. cobble, Diorite, Anything.

**Comment by loootz1** [comment]
seems most pickaxes are broken including my eclipse alloy paxel which has power and no enchants thatll cause it to not work

**Comment by c0mmoncents** [comment]
Also can confirm regular diamond and supremium  pickaxes are not working properly.

**Comment by Jbod23** [comment]
Ran into this as well, can be fixed by adding the mod: "Load my F'ing tags" by author Blodhgarm.
