### ISSUE TITLE
[Bug]: Tangled Hatred Kill quest not tracking

### ISSUE THREAD

**Issue by tombomb** [AllTheMods/ATM-10#1188]
### Possible Fixes

Yes

### Modpack Version

1.20

### What happened?

Killing the tangled Hatred is not triggering the quest completed

### latest.log

https://gist.github.com/tombomb/0904d4620d50e4e7da970ffad715f25f

**Comment by ToshibaEC0Microwave** [comment]
I found the problem I had the wrong tangled hatred in. This will be fixed!

**Comment by alekthefirst** [comment]
Fixed in https://github.com/AllTheMods/ATM-10/pull/1308
Released with ATM10 1.27
