### ISSUE TITLE
[Bug]: Fluorite Bee cannot flower on "alltheores:Fluorite_Block" 

### ISSUE THREAD

**Issue by Tim-Odermatt** [AllTheMods/ATM-10#1195]
### Possible Fixes

Yes

### Modpack Version

1.22

### What happened?

Fluorite Bee cannot flower on "alltheores:Fluorite_Block", but it can on the "Mekanism:Fluorite_Block" which is not a "real" Block

![image](https://github.com/user-attachments/assets/d5e88d1a-2df5-4042-a5f3-0bbb120854fd)

**Comment by alekthefirst** [comment]
Resolved by letting fluorite bee flower on more variants of fluorite
![image](https://github.com/user-attachments/assets/a143ab96-ed17-455b-9718-29cd09c5b707)
