### ISSUE TITLE
[Crash]: unable to create native thread: possibly out of memory or process/resource limits reached

### ISSUE THREAD

**Issue by thomasreichmann** [AllTheMods/ATM-10#1198]
### Possible Fixes

Yes

### Modpack Version

1.22

### What happened?

I've set up an ATM10 server running on my homelab. To manage the server, I’m using Pterodactyl on the machine. Currently, this is the only server running. The machine has 16GB of total RAM, with the server allocated 10GB, leaving sufficient overhead to avoid OOM (Out of Memory) issues if the system requires additional resources.

Even though this is a OOM related crash, the ram usage of the machine never maxed out, so I believe it is a thread limit issue.

I first encountered this exact same crash on an older world I was playing on, but since I had the world created since before the 1.0 launch of atm10, I decided that it was better to just attribute it to some weird bugged world gen, so I tried to create a new world to play on, after about 2-4h of playing on it, the crash happened again.

The crash mentions `fastasyncworldsave`, but I doubt that it is the actual culprit here, I found [this issue](https://github.com/someaddons/FastAsyncWorldSave/issues/10) which seems to be the same crash, but apparently it had nothing to do with the mod.

(I was the only one playing on the server for the entire duration)

### Crash Log

https://gist.github.com/thomasreichmann/83837145ec9864ae061f3850e6ddfdb3

### Latest.Log

https://gist.github.com/thomasreichmann/2cf5bd73eb78f1814d8a01756cd4cb9c

**Comment by alekthefirst** [comment]
most linux distros imposes a limit for how many threads a process can create, fast async world save creates a lot of threads and for some this issue has indeed been fixed by disabling fast asinc world save

**Comment by thomasreichmann** [comment]
Thanks @JacubRSTNC that was exactly what was causing it, it is crazy to me that this config didn't appear in any of my searches. ty
