### ISSUE TITLE
[Crash]: Typing 'c' while in the main menu crashes the game

### ISSUE THREAD

**Issue by logicallysound** [AllTheMods/ATM-10#120]
### Possible Fixes

Yes

### Modpack Version

0.14

### What happened?

I intended to name my ATM10 world "LogicallyATM10" but just after typing the 'c', the game crashed.

This also happens in other parts of the main menu (e.g. typing 'c' while searching for key binds), regardless of whether or not there is a text input box to type into. The crash log seems to point to a key handler from the Easy Villagers mod. Unbinding the "Cycle Trades" key (default is 'C') causes the crash to no longer occur.

### Crash Log

https://gist.github.com/logicallysound/147509b88b7fd95a8e1f62931bd766af

### Latest.Log

https://gist.github.com/logicallysound/097118a4d344fa1d45dfad0a3b585552

**Comment by logicallysound** [comment]
Additional info: the crash also does not occur with the Easy Villagers key still bound if there's already a saved world, which suggests it only happens when there are no saved worlds.

**Comment by logicallysound** [comment]
Seems like this was fixed by the mod developer very recently: https://github.com/henkelmax/easy-villagers/commit/dc18bb76086c9f819607acfb6dc57bc08a36f662

**Comment by logicallysound** [comment]
This is a duplicate of #116, closing.

**Comment by TheBedrockMaster** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/116
