### ISSUE TITLE
[Bug]: 'clientbound/minecraft:custom_payload’

### ISSUE THREAD

**Issue by Herograme** [AllTheMods/ATM-10#1200]
### Possible Fixes

No

### Modpack Version

1.22

### What happened?

i'm opening the door to my world for my friend to enter via radmin we're both playing the original version.

whenever he tries to connect he gets in but is immediately disconnected with the following warning:
 “`Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet ‘clientbound/minecraft:custom_payload’` ”

### latest.log

https://gist.github.com/Herograme/37b6ac77e34c5eba6b28498220ebe089

**Comment by rhullah** [comment]
I had this issue to and the only fix I found was the install [Packet Fixer](https://www.curseforge.com/minecraft/mc-mods/packet-fixer) on the server and on all clients.

**Comment by Herograme** [comment]
> I had this issue too and the only fix I found was the install [Packet Fixer](https://www.curseforge.com/minecraft/mc-mods/packet-fixer) on the server and on all clients.

I tested it recently but I didn't get any success, it keeps showing the same error

**Comment by PeaceDuckX** [comment]
same problem

**Comment by TheBedrockMaster** [comment]
Let me know if anyone has this issue in 1.22.

**Comment by PeaceDuckX** [comment]
> Let me know if anyone has this issue in 1.22.

I have on 1.22

**Comment by Herograme** [comment]
I'll try the test in 1.22 on Supplementaries and let you know

**Comment by TheMasterTM69** [comment]
> I deleted Supplementaries on ATM10 v1.22 and its works. So, seems the problem really with this mod
> 
> > I'll try the test in 1.22 on Supplementaries and let you know
> 
> > Let me know if anyone else has this issue in 1.22.

Can confirm, deleteing supplementaries helped and the other person can join.

**Comment by joaoavilars** [comment]
It worked for me by installing Packet Fixer on 1.22

**Comment by Herograme** [comment]
i've just tested with version 1.23 and everything works, this bug has been resolved

**Comment by Herograme** [comment]
i've just tested with version 1.23 and everything works, this bug has been resolved

**Comment by Geberation** [comment]
Having same issue today, playing locally with a friend 

On neoforge 
game version 1.21.1 

All the Mods 10-4.10


Happened 3 time in a row , i had to disable supplementaries :(
