### ISSUE TITLE
[Bug]: LAN Crashing on versions past 1.19

### ISSUE THREAD

**Issue by jsandrey** [AllTheMods/ATM-10#1203]
### Possible Fixes

Yes

### Modpack Version

1.22

### What happened?

Using both versions 1.20 and 1.22 after opening to Lan, player 2 will join and leave instantly and be given this error "internal exception io.netty.handler.codec.EncoderException failed to encode packet 'clientbound/minecraft:custom_payload". After returning to 1.19 we were able to join no issue so seems to be a bug introduced in 1.20 

### latest.log

https://gist.github.com/jsandrey/b84e318fcdbca6844843d6e58949d45c

**Comment by Alucard1313** [comment]
In 1.20, it was the Supplementaries mod that caused this problem. I don't know if it was fixed. Try removing it and then try opening LAN again.

**Comment by sakurazaki** [comment]
+1 my friend and I are having the same issue.
