### ISSUE TITLE
[Bug]: netheriteSight recipe is broken

### ISSUE THREAD

**Issue by KuzyXD** [AllTheMods/ATM-10#1204]
### Possible Fixes

Yes

### Modpack Version

1.22

### What happened?

https://imgur.com/a/fiv5McX

**Comment by thevortex** [comment]
you can fix this one yourself locally @KuzyXD by editing the config/potionsmaster/netherite.json to have the name 'netherite_scrap' instead of 'netherite' but fix will be in for next update

**Comment by KuzyXD** [comment]
> you can fix this one yourself locally @KuzyXD by editing the config/potionsmaster/netherite.json to have the name 'netherite_scrap' instead of 'netherite' but fix will be in for next update

Thanks. I got it work. By the way the product title seems corrupted 
![image](https://github.com/user-attachments/assets/9a40f84f-b2da-4317-b9f9-71fdbe301081)
