### ISSUE TITLE
[Bug]: When I open a world, the game doesn’t go above 4 FPS.

### ISSUE THREAD

**Issue by Solarynmoon** [AllTheMods/ATM-10#1206]
### Possible Fixes

Yes

### Modpack Version

10-1.22

### What happened?

The problem started yesterday when I installed and tried to play in my world. At first, I thought it was an issue with my PC, so I changed the settings, but nothing happened. Since the problem wasn’t with my PC, I assumed it could be related to the world. I tried generating a new one, but the same issue occurred. Then, I reinstalled the modpack, but again, nothing changed. Finally, I switched to a different version, and the game worked fine. What can I do to fix this problem permanently?

**Comment by TiccerMC** [comment]
This happened to my son.  I changed the profile memory settings to 12GB.  Problem solved.  How much RAM have you allocated?
![image](https://github.com/user-attachments/assets/e15b9cdb-bf28-4e03-b125-5d28038abd83)

**Comment by Solarynmoon** [comment]
I had around 5GB, but once you mentioned it, I tried to change, and voilà, the problem’s fixed. Thanks!
