### ISSUE TITLE
[Bug]: Pump/Advanced Pump/Experience Pump upgrade not showing recipe?

### ISSUE THREAD

**Issue by GarrysPixel** [AllTheMods/ATM-10#1213]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-1.19(Release)

### What happened?

Even though the Pump/Advanced Pump/Experience Pump upgrade is visible in the JEI, it doesn't show the recipe. Nor does any mod showcase/download website, they don't even show the upgrade at all. Did the remove it? The rest of the recipes works fine. Unless I'm missing something here

I'm asking this, because I have tons of jumbo XP tanks filled to the brim and the XP tap takes half a hour to empty....
So I was wondering if I can upgrade it by storing it in the backpack and then inject it to myself

![image](https://github.com/user-attachments/assets/56491836-e3cf-4ccd-9605-38a0725ed542)

**Comment by TheBedrockMaster** [comment]
The recipes are working fine for me in version 1.22

**Comment by ViRb3** [comment]
This is happening again on a fresh ATM 4.10 world.

**Comment by ViRb3** [comment]
Oh, it seems that the pump isn't implemented yet in Sophisticated Storage (not to be confused with Sophisticated Backpacks), so the item is just a placeholer: https://github.com/P3pp3rF1y/SophisticatedStorage/issues/514#issuecomment-2439429231
