### ISSUE TITLE
[Bug]: Vanilla Raw Ore Blocks missing AllTheCompressed counterparts

### ISSUE THREAD

**Issue by somedude-git** [AllTheMods/ATM-10#1215]
### Possible Fixes

Yes

### Modpack Version

1.22

### What happened?

Raw iron, gold, and copper ores lack [AllTheCompressed](https://github.com/Pdiddy973/AllTheCompressed/) (Version [4.0.1](https://www.curseforge.com/minecraft/mc-mods/allthecompressed/files/5771226)) recipes. Initially, I realized the issue while running the game with with [EMI ](https://github.com/emilyploszaj/emi)(Version [1.1.18](https://www.curseforge.com/minecraft/mc-mods/emi/files/5872513))- and the problem persisted with the mod removed. No other additional mod was present.

### latest.log

https://gist.github.com/somedude-git/fd80bd61fc0ee1cb929a022573ecc6b3

**Comment by TheBedrockMaster** [comment]
I think they just don't exist.

**Comment by TheBedrockMaster** [comment]
Thanks, these have been added to AllTheCompressed. The mod will be updated in the next pack version.
