### ISSUE TITLE
[Bug]: Cannot bind Right CTRL to jump

### ISSUE THREAD

**Issue by betgear** [AllTheMods/ATM-10#122]
### Possible Fixes

Yes

### Modpack Version

10-0.16

### What happened?

Attempting to bind Right CTRL to jump causes the focus to not move from the jump selection, so when attempting to leave the key bind menu the mouse click to exit the screen becomes the new key bind.

**Comment by jasonmorvan** [comment]
Its not just 'Jump' I cannot bind anything without it constantly capturing any mouse input as a bind. And the reset buttons need to be clicked on the very left of the button, and the master key reset needs to be clicked multiples times to get past the input capture.

**Comment by Xirall** [comment]
i found a solution. go into the modpack folder, open options.txt and change the keybind manually. oh and do while minecraft isnt open otherwise mc will overwrite it

**Comment by kaladinsb0** [comment]
Can confirm. I am unable to rebind anything to Shift or CTRL buttons. They immediately go to "Not bound". Has been happening for multiple versions now.
