### ISSUE TITLE
[Bug]: Infernal Mobs spawn in hyperboxes

### ISSUE THREAD

**Issue by FeenieTheFeenus** [AllTheMods/ATM-10#1221]
### Possible Fixes

Yes

### Modpack Version

1.22

### What happened?

Setting up a mobfarm inside a hyperbox causes some of the mobs to be from the infernal mob mod. This can be really annoying since some of them leave webs everywhere, fling you around etc. setting up a mob farm in the overworld does not have infernal mobs spawn.

Side note: Summoning a wither in a hyperbox can also cause them to be an infernal mob

**Comment by alekthefirst** [comment]
Due to how the hyperboxes make new dimensions per box, we can't blacklist them from infernal mobs
The solution to your problems is to make the mob farms in one of the blacklisted dimensions
