### ISSUE TITLE
[Bug]: Cobblestone not dropping

### ISSUE THREAD

**Issue by johnnybravo1502** [AllTheMods/ATM-10#1223]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-1.22 - (Release)

### What happened?

When I try to mine stone it takes insanely long like mining empty handed - even though I am using a pickaxe and cobble is not dropping. Tried 4-5 different new worlds, survival, creative and couldn't find a solution.

**Comment by TheBedrockMaster** [comment]
I can't reproduce this issue, could you add a latest.log please?

**Comment by alekthefirst** [comment]
Closed as stale due to no response
