### ISSUE TITLE
[Feature]: Backpack

### ISSUE THREAD

**Issue by Minecrafterthebuilder** [AllTheMods/ATM-10#1224]
### Feature Details

i open backpack it kicks me from server 
![2C5869EC-DD5D-4453-9210-2E5717E8DBBE](https://github.com/user-attachments/assets/ff4684b5-b7ce-4664-b573-6e504863cb39)

**Comment by TheBedrockMaster** [comment]
Please open a crash/bug report with your latest log please, this isn't a feature request, nor do we have the information required to help you.
