### ISSUE TITLE
[Bug]: Modern Industrialization Digital Circuit Board not Assembling

### ISSUE THREAD

**Issue by RajBaj1** [AllTheMods/ATM-10#1227]
### Possible Fixes

Yes

### Modpack Version

1.22

### What happened?

Digital circuit board is not crafting in Modern Industrialization assembler even though all required components and liquid is in assembler.

![image](https://github.com/user-attachments/assets/c0948795-80c9-4211-8dbd-a5e171e25098)

**Comment by alekthefirst** [comment]
I am unable to reproduce this issue
https://github.com/user-attachments/assets/7aa9b94a-307b-40be-9fd5-0223af14369e

**Comment by Zombiebear99** [comment]
Remove the overdrive module

**Comment by Zombiebear99** [comment]
That makes the assembler use other recipes
