### ISSUE TITLE
[Bug]: ars specific mob causing lag

### ISSUE THREAD

**Issue by WilliamsJ99** [AllTheMods/ATM-10#1235]
### Possible Fixes

Yes

### Modpack Version

1.22

### What happened?

We have observed that Whirlisprigs are contributing to substantial lag on servers. This has been confirmed through performance analysis tools such as Spark and observable monitoring systems, which consistently highlight these entities as a primary source of performance degradation. The server's performance improves noticeably, and the lag is eliminated once the Whirlisprigs are removed or killed. This indicates that their behaviour or resource demands disproportionately impact server resources, leading to these performance issues. Further investigation into their mechanics and optimization could help mitigate these effects.

**Comment by Jarva** [comment]
Can you provide a spark report or anything to show this?

Whirlisprigs contain very little logic as the whole processing is done by the flower block itself.

**Comment by alekthefirst** [comment]
Closed as stale due to lack of response to inquiry about further information
