### ISSUE TITLE
[Bug]:  USING A BUCKET on a framed trapdoor crashes the game and wont let me back into my world.

### ISSUE THREAD

**Issue by Sage027** [AllTheMods/ATM-10#125]
### Possible Fixes

Yes

### Modpack Version

ATM10    0.16

### What happened?

I accidently clicked with a bucket on a framed trapdoor witch crashes the game and wont let me back into my world.

hope you can fix this so other people don't have this happen to them

The game crashed whilst encountered exception while building chunk meshes
Error: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pk" is null

**Comment by alekthefirst** [comment]
While its unclear which version this was fixed in, it has been fixed

https://github.com/user-attachments/assets/45bc6b1a-a3f1-4af3-83c9-5d92cc46ccca
