### ISSUE TITLE
[Bug]: Unobtainium-Allthemodium Alloy Block recipe is not accurate

### ISSUE THREAD

**Issue by dickynasje** [AllTheMods/ATM-10#1255]
### Possible Fixes

Yes

### Modpack Version

1.24

### What happened?

In the recipe JEI making a single ingot costs 10k source which i tested by making 9 ingots with 9 full source jars nearby and it successfully used 9 full source jars which means a single source jar is 10k source(?). Meanwhile the recipe for the block is 90k source. Ive tried putting 9 full source jars to craft a block and it prompts `Not enough source nearby` ive also tried using the ME source jar to expose it to all of my accumulated source inside the ME system (50Mil+) and it still prompts the same `Not enough source nearby`

**Comment by CletisWalmsley** [comment]
From what I have seen on the ATM10 discord, it seems that the enchanting apparatus cannot take source from more than one source jar for a single craft. This would mean that any recipe requiring more than 10k source is simply impossible to craft (I have the same problem)

**Comment by DaddyLongspoon** [comment]
> From what I have seen on the ATM10 discord, it seems that the enchanting apparatus cannot take source from more than one source jar for a single craft. This would mean that any recipe requiring more than 10k source is simply impossible to craft (I have the same problem)

 maybe not impossible with creative source jar?
I haven't tried it and can't right now, I used all my stars, have a block in front of bees, might break that down when I have a few thousand more star shards
