### ISSUE TITLE
[Bug]: Pipe Upgrade Distribution 

### ISSUE THREAD

**Issue by LittleMonkeyJump** [AllTheMods/ATM-10#127]
### Possible Fixes

Yes

### Modpack Version

0.16

### What happened?

When I go to a pipe upgrade I have installed inside of a pipe. I attempt to change the Distribution setting, immediately once I click to change the setting I get kicked from the game. Will not let me back into the game for at least an hour.

**Comment by alekthefirst** [comment]
Fixed in Pipez 1.21-1.2.17, released with ATM10 0.21
