### ISSUE TITLE
[Crash]: Crash when opening AE2's Guide

### ISSUE THREAD

**Issue by BambooVert** [AllTheMods/ATM-10#1271]
### Possible Fixes

Yes

### Modpack Version

1.25

### What happened?

Crash when opening AE2's Guide。I tested it seven times, and it crashes as soon as I open this guide

### Crash Log

https://gist.github.com/BambooVert/ca09dd08c7735ab69abea3944793956d

### Latest.Log

https://gist.github.com/BambooVert/c27d9dcb3d9cfe2f996ee488b1abb492

**Comment by Nile737** [comment]
Out of curiosity, not to rush anyone because the guide is also online but is there a temporary solution I can use while I try and learn how to use it?

**Comment by BambooVert** [comment]
> Out of curiosity, not to rush anyone because the guide is also online but is there a temporary solution I can use while I try and learn how to use it?出于好奇，不要催促任何人，因为该指南也在线，但是在我尝试学习如何使用它时，是否有可以使用的临时解决方案？

Use an external web page to view
https://guide.appliedenergistics.org/1.21/ae2-mechanics/autocrafting

**Comment by alekthefirst** [comment]
Unable to reproduce in ATM10 2.8, 
https://github.com/user-attachments/assets/a18186f9-3d40-4ea4-9ebe-035015d05b71
