### ISSUE TITLE
[Bug]: Lost Tablet never awakens.

### ISSUE THREAD

**Issue by xtended2l** [AllTheMods/ATM-10#1273]
### Possible Fixes

Yes

### Modpack Version

1.24

### What happened?

Lost Tablet from Corail Tombstone mod, captured using enchanted fishing rod of misadventure, never awakens: 
![image](https://github.com/user-attachments/assets/f49e12c3-de95-4b5e-aa8c-041f18251a42)

I captured two of these, and they just keep shaking when you hold them in hand. In previous versions of modpack it should awaken in a couple of minutes. I was waiting for hours, carrying them around, etc.

**Comment by Corail31** [comment]
@xtended2l Hi, i confirm you that you're right about the issue. Can you open the issue on my repository ? Thanks you.

**Comment by xtended2l** [comment]
> @xtended2l Hi, i confirm you that you're right about the issue. Can you open the issue on my repository ? Thanks you.

Hi, Done.
https://github.com/Corail31/tombstone_lite/issues/265
