### ISSUE TITLE
[Bug]: FarmingForBlockhead's market MerchantEntity ClassCastException AgeableMob

### ISSUE THREAD

**Issue by leagris** [AllTheMods/ATM-10#1280]
### Possible Fixes

Yes

### Modpack Version

1.25

### What happened?

Attempt at picking up the merchant with <kbd>Shift</kbd>+<kbd>RMB</kbd> might have caused the unfortunate class cast exception and crashed the client.

Extrct of [`crash-2024-11-28_15.42.34-client.txt`](https://gist.github.com/leagris/4dff20f134d4df2fbeda063adbe7ef32#file-crash-2024-11-28_15-42-34-client-txt):
```none
java.lang.ClassCastException: class net.blay09.mods.farmingforblockheads.entity.MerchantEntity cannot be cast to class net.minecraft.world.entity.AgeableMob (net.blay09.mods.farmingforblockheads.entity.MerchantEntity is in module farmingforblockheads@21.1.2 of loader 'TRANSFORMER' @2291b211; net.minecraft.world.entity.AgeableMob is in module minecraft@1.21.1 of loader 'TRANSFORMER' @2291b211)
```

### latest.log

https://gist.github.com/leagris/4dff20f134d4df2fbeda063adbe7ef32#file-latest-log

**Comment by alekthefirst** [comment]
I am unable to reproduce this on ATM10 2.8 and trying to pick up the merchant as one would a villager simply results in no interaction at all
