### ISSUE TITLE
[Feature]: Spice of Life don't reset on death

### ISSUE THREAD

**Issue by DJ-Laser** [AllTheMods/ATM-10#1287]
### Feature Details

It is annoying to lose all food progress each time you die. Would the modpack devs consider changing the SOL config option `resetOnDeath` to `false`?

**Comment by alekthefirst** [comment]
It was considered before adding the mod and the decision was made to have it reset on each death.

**Comment by TheBedrockMaster** [comment]
For now this is not planned.
