### ISSUE TITLE
[Bug]: internal exception: io.netty.handler.codec.EncoderException: Failed to encode pacjet 'clientbound/minecraft:custom_payload'

### ISSUE THREAD

**Issue by HDCrazyHD** [AllTheMods/ATM-10#1289]
### Possible Fixes

Yes

### Modpack Version

10-1.25

### What happened?

I try to open a lan server with my friend but dont work...
![imagem_2024-11-29_220158608](https://github.com/user-attachments/assets/9ba62a62-723a-49d4-b940-05cb493fd7a4)

**Comment by alekthefirst** [comment]
Will need logs
latest.log works, use https://mclo.gs and put the link to it here

**Comment by HDCrazyHD** [comment]
I try again and workk!!
Thx for help and sorry
