### ISSUE TITLE
[Bug]: when searching for @intergrated dynamic or just scrolling through the EMI recipe list, game instant closes with no error or crash report

### ISSUE THREAD

**Issue by Roners258** [AllTheMods/ATM-10#129]
### Possible Fixes

Yes

### Modpack Version

latest 0.17

### What happened?

I have just updated the pack when Intergrated Dyanamics was added, and now when searching for @intergrated dynamics or just scrolling through the EMI recipe list (and get to the page where Int Dynamics is, the game instant closes with no error or crash report. I am playing on server which is also updated, and the server suffers no issues or crashes. just shows me leaving. I dont know if it just Intergrated Dynamics causing the problem, but I have tried to recreate the problem in single player and it does not crash me.

### latest.log

https://gist.github.com/Roners258/9536fc892acc261195a107c0480c8d8b

**Comment by Koviricsi** [comment]
Same happened to me when searching for "card" (cardboard box)

**Comment by Roners258** [comment]
> Same happened to me when searching for "card" (cardboard box)

I think then it is definitely @Intergrated Dynamics, because there is the Variable Card from Intergrated Dynamics that would have shown too. I have replicated and also crashed (on server), cannot replicate on SP.

**Comment by Leclowndu93150** [comment]
probably EMI having broken code according to the log

**Comment by Roners258** [comment]
new update seems to have fixed the problem
