### ISSUE TITLE
[Bug]: Disconnect from server: Packet Handling Error

### ISSUE THREAD

**Issue by liham10** [AllTheMods/ATM-10#1307]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-1.26-(Release)

### What happened?

- Private server hosted on a local machine, when connecting after updating from 1.25 to 1.26, successful connection.
- Both client and server are running 1.26
- When auto sugarcane farm activates pistons, disconnect from the server with Packet handling error.
- Downgraded back to 1.25 on server and client, no disconnect when pistons activate.
- When looking at server logs, player is just disconnected from server.
- If you can unload the chunks, no disconnect

Please see attached log

### latest.log

https://gist.github.com/liham10/2a544ebac8b621f0872918499d479b2a

### Developer reports

https://gist.github.com/liham10/1ff601bdf5240bc6d887c94d8f4a18d4

**Comment by liham10** [comment]
Update:
- Updated to 1.27 from 1.25, same issue encountered.
- Uninstalled pack and did fresh install, produced same result
- downgraded back to 1.25 no issue
[disconnect-2024-12-06_20.02.39-client.txt](https://github.com/user-attachments/files/18035475/disconnect-2024-12-06_20.02.39-client.txt)

**Comment by davweiss** [comment]
I have the same problem. As a temporary solution, it helped me to remove each piston.

**Comment by alekthefirst** [comment]
The current solution is to disable the recently introduced piston protection feature in ftbchunks-world.snbt. It will be in the serverconfig folder

**Comment by liham10** [comment]
- 1.27 server disabled in config, tested ok.
- updated to 2.0 and left as default, disconnect no longer occuring
