### ISSUE TITLE
[Crash]: Ars Additions Exploreres Warp Scroll

### ISSUE THREAD

**Issue by Pyroxylic** [AllTheMods/ATM-10#1309]
### Possible Fixes

Yes

### Modpack Version

1.26

### What happened?

I found a ruined warp portal structure added by Ars Additions, opened the loot barrel and tried to take the Explorer's Warp Scroll. This caused my game to crash. Loaded the world back up, have the Explorers Warp Scroll in my inventory, and every time I tried using it, it caused me to crash (four times now altogether). 

The initial crash, and subsequent 2 uses have identical crash reports, but the 4th time I crashed it had a new reason. 

The initial crash from Looting it and the Latest crash have been uploaded.

### Crash Log

https://gist.github.com/Pyroxylic/eb65010f8b7a77d82c2dd0056d63f408

### Latest.Log

https://gist.github.com/Pyroxylic/6a8e748d3fe4f8cdb05be84af38d53bd

**Comment by SwimsSwag** [comment]
Had the same thing happen to me. Everytime I use a warp scroll I crash instantly. 
[crash-2024-12-09_20.03.39-server.txt](https://github.com/user-attachments/files/18070496/crash-2024-12-09_20.03.39-server.txt)

**Comment by AarkinAsylum** [comment]
Also facing the same issue on my dedicated server running version 1.26

**Comment by AarkinAsylum** [comment]
> Also facing the same issue on my dedicated server running version 1.26

Update to the latest version 1.27 issue has been fixed for me.

**Comment by alekthefirst** [comment]
Fixed in Ars Noveau 5.3.5, released with ATM10 1.27
