### ISSUE TITLE
[Bug]: All the Mods 10-1.26 broke shaders again

### ISSUE THREAD

**Issue by leagris** [AllTheMods/ATM-10#1311]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-1.26

### What happened?

Shaders broken again
Trying to access video settings crashes the client see https://gist.github.com/leagris/abb4eb038ef01af1090fa05bc1ddb4f6#file-crash-2024-12-04_14-33-37-client-txt

### latest.log

[latest.log](https://gist.github.com/leagris/abb4eb038ef01af1090fa05bc1ddb4f6#file-latest-log)

[crash-2024-12-04_14.33.37-client.txt](https://gist.github.com/leagris/abb4eb038ef01af1090fa05bc1ddb4f6#file-crash-2024-12-04_14-33-37-client-txt)

**Comment by Varcen** [comment]
Only the Complimentary + Euphoria Patches are not working for me. The other shaders seem fine.

**Comment by leagris** [comment]
Fixed in 1.27
