### ISSUE TITLE
[Bug]: Using a Mekanism Cardboard Box on a Waystone gets the Waystone stuck in the cardboard box.

### ISSUE THREAD

**Issue by EvilGrinUK** [AllTheMods/ATM-10#1319]
### Possible Fixes

Yes

### Modpack Version

1.25

### What happened?

When using a cardboard box by right clicking on a waystone (usually entirely by accident). The waystone goes 'into' the cardboard box. However it is impossible to then remove the waystone from the box by shift right clicking as usual.

I saw a similar issue posted on the Enigmatica 6 mod issue tracker. They chose to blacklist waystones in the mekanism config to fix that problem and I think that fix would be sufficent here. No one should need to move waystones with cardboard boxes.

https://github.com/EnigmaticaModpacks/Enigmatica6/issues/2909

**Comment by alekthefirst** [comment]
Fixed by blacklisting waystones from boxes in https://github.com/AllTheMods/ATM-10/commit/d5c40d7e02debd6b8f4e33ca0f9e7ef465bd4fab
Released with ATM10 2.6
