### ISSUE TITLE
[Bug]: Menril Glass can not be crafted.

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [AllTheMods/ATM-10#132]
### Possible Fixes

Yes

### Modpack Version

0.17

### What happened?

Menril Glass can not be crafted.

When using a Drying Basin by inserting the glass into the basin and filling it with Menril Resin the glass is consumed and you still get a Menril Resin block out.

When using a Mechanical Drying Basin the glass placed in the input slot is simply ignored and it continues to produce Menril Resin blocks.

**Comment by EnderReaper64** [comment]
This also applies for the Chorus Glass, which also has an invalid recipe tag associated with it.

**Comment by WhiteFire-Sondergaard** [comment]
https://github.com/CyclopsMC/IntegratedDynamics/issues/1369

This may be a mod bug not a recipe bug in ATM
