### ISSUE TITLE
[Crash]: Accessing video settings

### ISSUE THREAD

**Issue by leagris** [AllTheMods/ATM-10#1321]
### Possible Fixes

Yes

### Modpack Version

1.27

### What happened?

Since 1.25 Client crashes when attempting to access the video settings.

### Crash Log

https://gist.github.com/leagris/3541561004d980fd51edb36ed6e590ed

### Latest.Log

https://gist.github.com/leagris/76f5c763ac43af1ce161d58cfeb00fe1

**Comment by leagris** [comment]
Problem still persist in ATM 10-2.3

- New Crash report: [crash-2024-12-12_16.50.49-client.txt](https://gist.github.com/leagris/7885e477c8880e08eeec0386a32d91a9#file-crash-2024-12-12_16-50-49-client-txt)
- New latest log: [latest.log](https://gist.github.com/leagris/7885e477c8880e08eeec0386a32d91a9#file-latest-log)

**Comment by alekthefirst** [comment]
you have a lot of duplicate mods, need to remove the old versions of those

**Comment by leagris** [comment]
Thank you I have reinstalled the mods folder entirely and the issue is gone.
I cannot explain how this happened. I use FTBA Launcher on Linux and upgraded the pack serveral times clicking the upgrade button of the application.
