### ISSUE TITLE
[Bug]: Croptopia Avocado Tree With Fast Leaf Decay

### ISSUE THREAD

**Issue by Grant-K** [AllTheMods/ATM-10#1324]
### Possible Fixes

Yes

### Modpack Version

0.30.0

### What happened?

When a Croptopia Avocado tree is grown and the leaves that arent "Avocado Crop" act like they arent connected to logs and decay as per fast leaf decay would normally.

**Comment by TheBedrockMaster** [comment]
Update the pack, you are on an old version.
