### ISSUE TITLE
[Bug]: Game disconnects from singleplayer world when doing Forbidden Arcanus ritual

### ISSUE THREAD

**Issue by RedFlakes** [AllTheMods/ATM-10#1325]
### Possible Fixes

Yes

### Modpack Version

1.27

### What happened?

After I fill up the required souls, aureal and blood, whenever I place the last item inside the forge, game disconnects with network protocol error. When I rejoin, the forge is always reset, with all previous input lost. I am playing in a singleplayer world, I tried forge upgrade to Tier 4 ritual, and Eternal Stella ritual, also as an attempt to figure out what was going on, I removed all pedestals, filled up the requirements for Forge Tier 4 ritual, and as soon as I placed the Chiseled Polished Darkstone in the forge it crashed again. Tried multiple times, crashed in all of them with inputs gone. Then I tried with pedestals, another Eternal Stella ritual, crashed again.

EDIT: By crash I mean I got disconnected with network protocol error, my game didn't fully crash
### latest.log

https://gist.github.com/RedFlakes/725af4a95b05525572c0d00ef2e6053d

**Comment by Fangzwusky** [comment]
same issue, but crafting smelter prism for ATM star on server. Server reboot needed too reconnect. same results

**Comment by Nugwa628** [comment]
from Stal (Forbidden arcanus lead dev): "resolved in f&a 2.5.11, just needs a pack update"

This should be fixed in 1.28

**Comment by TheBedrockMaster** [comment]
Let me know if this issue still occurs on 1.28

**Comment by RedFlakes** [comment]
I have just tested it again with multiple rituals on version 2.0. Definitely fixed!
