### ISSUE TITLE
[Bug]: Dark Ore not generating in the world

### ISSUE THREAD

**Issue by Alligraphic** [AllTheMods/ATM-10#133]
### Possible Fixes

Yes

### Modpack Version

0.17

### What happened?

The Dark Ore from Evilcraft is not generating in the world I tried new chunks as well.

**Comment by DaddyLongspoon** [comment]
can confirm, generated over 100 new chunks, mined for an hour, went and fetched my melanism digital miner out of frustration, added the filter *dark_ore* (which digi miner recognised, indicates it will look for evilcraft:dark_ore and evilcraft:dark_ore_deepslate). ran the miner at maxed radius, y level etc in several newly generated locations... not one ore anywhere.

**Comment by ProjectRichTea** [comment]
Same here, searched for a few hours, used digital miner too, no luck in any of the newly generated chunks.

**Comment by Mekanofreak** [comment]
updating evilcraft to the latest version (1.2.46) fix this

**Comment by cweet01** [comment]
Same here even tried digital Miner and got cobblestone only.
