### ISSUE TITLE
[Bug]: Twilight forest extreme lag

### ISSUE THREAD

**Issue by Audiomorphic** [AllTheMods/ATM-10#1332]
### Possible Fixes

Yes

### Modpack Version

1.27

### What happened?

just entered twilight forest dimension. immediately there is much lag. try to cast a spell with ars nouveau and it is multiple seconds before spell actually casts. Mobs in dimension are stopping and going.

**Comment by alekthefirst** [comment]
I believe this was fixed with journey map 6.0.0-beta.32, released with ATM10 2.1
