### ISSUE TITLE
[Bug]: Infused alloy from Mekanism not working

### ISSUE THREAD

**Issue by Exempt-AK** [AllTheMods/ATM-10#1333]
### Possible Fixes

Yes

### Modpack Version

1.27

### What happened?

I was playing in version 1.25 and got to a point I need to craft infused alloy but after adding the redstone I cannot even put the iron into the metallurgic infuser. I checked around and saw people were fixing it by restarting or deleting the Mekanism folder, non of which solved my issue, so I updated to 1.27 and still have the same problem.

### latest.log

https://gist.github.com/Exempt-AK/c5408fdcaca5d4064d5b6c1ccab493bd

**Comment by alekthefirst** [comment]
if you check in jei you will find that infused alloy no longer uses iron, this is a change from mekanism, not atm

**Comment by Exempt-AK** [comment]
You're indeed right. I guess in 1.25 it didn't show any way to create it but now it does in 1.27. Thanks for that this was driving me crazy... -.-
