### ISSUE TITLE
[Bug]: Huge server-side lag spikes followed by a crash while exploring the Twilight Forest

### ISSUE THREAD

**Issue by shade1822226911** [AllTheMods/ATM-10#1340]
### Possible Fixes

Yes

### Modpack Version

2.0

### What happened?

After updating from 1.16 to 2.0, I loaded in the Twilight Forest [this was where i saved previously so i never returned to the overworld although my base chunks were forceloaded] and was going to go kill some bosses but when I loaded some new chunks i just got absurd amounts of server-side lag [my average mspt was~100 before this so that probably made it worse] followed by a crash without any report from the game.

I had a look at the logs and the only notable thing was Iceberg failing to cast a class to the server with the first line being something about JDT eclipse gates [which I've never crafted or obtained] at 15:38:50.435 in the logs.

The only extra mods i have are:
-Custom Player Models
-Packet Fixer

### latest.log

https://gist.github.com/shade1822226911/71ed7f1ecc2bed8ec9c2bcf017e11489

**Comment by alekthefirst** [comment]
this is a consequence of a recently introduced bug in journeymap
they're still working on a fix, but in the mean time you can downgrade your journeymap version

**Comment by shade1822226911** [comment]
> this is a consequence of a recently introduced bug in journeymap they're still working on a fix, but in the mean time you can downgrade your journeymap version

Ok, I'll do that. Thanks!
