### ISSUE TITLE
[Crash]: Placing the Modular Machinery Controller crashes my client

### ISSUE THREAD

**Issue by Motytheultimate** [AllTheMods/ATM-10#1345]
### Possible Fixes

No

### Modpack Version

2.0

### What happened?

I tried placing the Modular Machinery Controller on my dedicated Server
Restarting Client/ Server doesnt help I get kicked with error in the gist.
Im not sure how to fix it or work around it to fix the Server

### Crash Log

https://gist.github.com/Motytheultimate/633aa70d13af25ea72402193974e8b20

**Comment by Motytheultimate** [comment]
I found out how it happended  i crafted the controller with the crafting regular shaped recipe. Maybe it cant get the name for the right controller. The names for the controller dont show up at all. thats however just a guess

**Comment by Motytheultimate** [comment]
also opening the controller gui crashed the game once again

**Comment by itschammyg** [comment]
> also opening the controller gui crashed the game once again

I also just crashed on a server opening the gui

**Comment by alekthefirst** [comment]
This specific crash was solved with MMR 1.1.13 in ATM10 2.4
