### ISSUE TITLE
[Bug]: Air blocks replaced by Black "Pillars"

### ISSUE THREAD

**Issue by Gwhin** [AllTheMods/ATM-10#1349]
### Possible Fixes

Yes

### Modpack Version

ATM 10

### What happened?

![Screenshot 2024-12-08 102316](https://github.com/user-attachments/assets/ca5e4634-1576-44da-b4ba-fe5126508e79)

Happened right afer i used the Waystone to teleport.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/1313
