### ISSUE TITLE
[Bug]: Xycraft Dripstone Recipe

### ISSUE THREAD

**Issue by DJT1n1** [AllTheMods/ATM-10#1357]
### Possible Fixes

Yes

### Modpack Version

2.1

### What happened?

there is a xycraft recipe that allows the extractor to extract dripstone with water underneath the block of dripstone. Whenever I set it up the extractor does not kick on. Possible Bug, should be resolvable.
![2024-12-08_14 42 00](https://github.com/user-attachments/assets/534921a6-52b1-4321-bd60-d3705622f41a)

**Comment by NJM1564** [comment]
Upside down. Water above extractor below.
