### ISSUE TITLE
[Bug]: creative issue

### ISSUE THREAD

**Issue by pokemonkiller90** [AllTheMods/ATM-10#1358]
### Possible Fixes

Yes

### Modpack Version

2.1

### What happened?

while playing in creative mode the search bar for finding things is not working at all you type to search things and nothing shows up at all but you can scroll through still and see everything i donty know if its atributed to a certain mod because it dont show anything as soo as you put a single letter into the search bar

**Comment by golhmogh** [comment]
Was also prominent in 2.4, seems to be fixed beyond 2.6.

**Comment by dinkley** [comment]
Still happening as of 4.5. 

<img width="973" height="864" alt="Image" src="https://github.com/user-attachments/assets/8d2209a5-bbe3-4ea6-b943-d1e5f2285b8c" />

No errors in client or server console.

**Comment by pietro-lopes** [comment]
In modded Minecraft, the creative search is very unstable. Use JEI to get items, Ctrl + Click on Wrench to activate cheat mode.
