### ISSUE TITLE
[Crash]: Evilcraft Spirit Furnace - Box of Eternal Closure causes Timeout (ServerHangWatchdog)

### ISSUE THREAD

**Issue by zoeliterally** [AllTheMods/ATM-10#1359]
### Possible Fixes

No

### Modpack Version

2.1

### What happened?

[Crashdump](https://gist.github.com/zoeliterally/612491083a298719cd7d1fbb20a079aa)

When smelting a Box Of Eternal Closure containing the Spirit of direwolf20 in the Spirit Furnace, the moment the process finishes, the server timed out.

### Crash Log

https://gist.github.com/zoeliterally/612491083a298719cd7d1fbb20a079aa

**Comment by alekthefirst** [comment]
This was resolved in Evilcraft 1.2.61, released with ATM10 2.7

**Comment by alekthefirst** [comment]
Evilcraft issue for reference purposes
https://github.com/CyclopsMC/EvilCraft/issues/1075
