### ISSUE TITLE
[Bug]: Ender Comb has lost it's Centrifuge recipe

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [AllTheMods/ATM-10#136]
### Possible Fixes

Yes

### Modpack Version

0.17

### What happened?

The recipe for processing ender comb has vanished from EMI, and the Centrifuge just passes it to the output as it does with anything it does not recognize.

**Comment by kollinkoko** [comment]
Due to Integrated Dynamics being added, the Ender Combs now produce Liquid Chorus instead of honey. If you have honey in your centrifuge, then the ender combs will not process.
