### ISSUE TITLE
[Bug]: Ars Noveau Lectern lag, gui issues

### ISSUE THREAD

**Issue by theoriginalspre** [AllTheMods/ATM-10#1360]
### Possible Fixes

Yes

### Modpack Version

2.0

### What happened?

After updatging to 2.0(IE i never saw it previously) ars storage lags. Possible dupes.

sometimes when loading ars storage GUI all items in my inventory will double once i click out of it then sort my inventory the doubles vanish.

I also have been having to exit and reenter the gui when trying to craft  it will add all items to the grid, but no result is displayed.

**Comment by DaddyLongspoon** [comment]
do you mean the bookworm lectern storage system?

**Comment by alekthefirst** [comment]
Likely https://github.com/baileyholl/Ars-Nouveau/issues/1478 released with Ars Noveau 5.3.6
Thusly fixed in ATM10 2.7

**Comment by theoriginalspre** [comment]
Thank you confirmed fixed when I updated to 2.7 & 2.8
