### ISSUE TITLE
[Bug]: allthemodium sight potion increases RAM consumption

### ISSUE THREAD

**Issue by Tarmaster** [AllTheMods/ATM-10#1369]
### Possible Fixes

Yes

### Modpack Version

2.1

### What happened?

After I drink allthemodium sight potion my RAM consumption increase
I tried turning off shaders and changing the amount of RAM but it didn't work
Video https://youtu.be/fVyzBuDGToU

**Comment by alekthefirst** [comment]
The effect you're seeing is not a consequence of allthemodium oresight, but rather of flying around in deep darks generally
Comparison can be seen below
Stationary in deep dark, before and after applying atm sight

https://github.com/user-attachments/assets/ddf47721-6fba-4a2b-90bf-79143d87bc48

and moving in deep dark, before and after applying atm sight

https://github.com/user-attachments/assets/8c4c7d21-9f1d-495d-bdff-cc22cbf8dbe8

(yes i did do /effect clear between these)
