### ISSUE TITLE
[Bug]: Just Dire Things Fluids

### ISSUE THREAD

**Issue by JamesSSmith** [AllTheMods/ATM-10#1374]
### Possible Fixes

Yes

### Modpack Version

2.1

### What happened?

After creating some Just Dire Things fluids in world, which you need to do as part of the ATM Star, when you pick the fluids up with a bucket, it just turns to water again. The Dire Things sensor also cannot sense what the fluid is when it is in the world, it thinks everything is water.

I can confirm this has happened with the following liquids
Polymorphic Fluid
Blaze Ember Fluid

i have no yet tried it with the others

**Comment by alekthefirst** [comment]
I am unable to reproduce this issue.
Picking up polymorphic fluid does give me a bucket of polymorphic fluid.
https://i.imgur.com/DLc6whI.mp4

**Comment by JamesSSmith** [comment]
> I am unable to reproduce this issue. Picking up polymorphic fluid does give me a bucket of polymorphic fluid. https://i.imgur.com/DLc6whI.mp4

hmm yeah it seems i cant replicate it now, i wonder if it was a client issue, after i came on again this evening after closing the client its working fine now. Ill close the bug now.
