### ISSUE TITLE
[Bug]: Hephaestus forge ritual to craft star altar won't start

### ISSUE THREAD

**Issue by DaddyLongspoon** [AllTheMods/ATM-10#1376]
### Possible Fixes

Yes

### Modpack Version

1.2.1

### What happened?

My Heph forge has been working for everything in the game, built it quite a while ago, have made all the things, levelled it right up etc..
when I did one of the recently added rituals (modularium ingot or quantum injector) I found that I needed to shuffle the positions of the relics in the slots of the forge before the forge showed me the animated white circles, indicating that the gavel will activate it..
now im onto the star altar, have all the stuff, the four resource gauges maxed out (the 100k blood took hours..) I've shuffled those four relics every which way, but I can't get the circles or start the ritual.  Its possible that I've got something slightly wrong that JEI isn't telling me, for example I got my eternal starlight loot bag from the nasty poison flower guy in the maze, maybe they look the same in JEI but only the one from the laser golem robot guy will work...
Ive been on atm discord and was told that this is known and the guys are working on it already but I don't see any report here, think maybe I add one and it might save somebody some frustration.
thanks :)

**Comment by DaddyLongspoon** [comment]
update 12/12/24.  updating to 10.2.2 did not solve this problem.  Eventually I gave up and made the automatic hephaestus forge instead, that worked right away, now ill try to do the runic star altar on that one.

**Comment by Mawarii** [comment]
Did the automatic Hephaestus work? I am stuck at the same problem...

**Comment by shade1822226911** [comment]
> Did the automatic Hephaestus work? I am stuck at the same problem...

Same here, I assume it's because no fluid input bus has the needed storage for the fluids [Like the absurd blood requirement]

**Comment by DaddyLongspoon** [comment]
I have got it working for the orange ingot for the modular machines... but you're right, no fluid hatch big enough for some of the expensive stuff...

**Comment by DaddyLongspoon** [comment]
this appears to have been addressed in 10.2.7  closing the issue thank you atm team

**Comment by BonusPlay** [comment]
Note to other people having issues with this. As of 2.8, there are multiple types of Eternal Starlight Loot Bags. They don't stack in inventory systems (like sophisticated storage / integrated dynamics), some work for this recipe, some do not.

**Comment by DaddyLongspoon** [comment]
> Note to other people having issues with this. As of 2.8, there are multiple types of Eternal Starlight Loot Bags. They don't stack in inventory systems (like sophisticated storage / integrated dynamics), some work for this recipe, some do not.

right.   there are two different plant type bosses in the middle of the huge stone maze, one tall thin one is pretty easily defeated, the other needs fire attacks, is quite tanky and gives you an effect called 'potent poison' which can kill you very quickly, these guys will each give you a loot bag, they look the same but only one of them works to make this ritual.
