### ISSUE TITLE
[Bug]: RFToolsBase Filter Module can't be changed to blacklist mode

### ISSUE THREAD

**Issue by vampire2point0** [AllTheMods/ATM-10#1380]
### Possible Fixes

Yes

### Modpack Version

10-2.1

### What happened?

When changing the mode to blacklist the button itself seems to be the only thing changing, the mode in the tooltip stays on whitelist mode en reopening the filter shows its back on whitelist mode, and putting the filter in a builder confirms its still whitelisting instead of blacklisting

**Comment by alekthefirst** [comment]
I believe this is already fixed on rftools' end and the atm10 update with that should be available in the not so distant future

**Comment by vampire2point0** [comment]
Can confirm, updated from 2.1 to 2.3 and filter can now be set to blacklist mode, Ty
