### ISSUE TITLE
[Crash]: Crash when hovering over a bookmarked ultimate induction provider

### ISSUE THREAD

**Issue by NJM1564** [AllTheMods/ATM-10#1382]
### Possible Fixes

Yes

### Modpack Version

10-2.2

### What happened?

Mouse over bookmarked "mekanism:ultimate_induction_provider".

### Crash Log

https://gist.github.com/NJM1564/243f0dc78366d19d14ab3eee645f68d1

### Latest.Log

https://gist.github.com/NJM1564/30b133828a1c80cacaa6a4f90ab72016

**Comment by alekthefirst** [comment]
Hi i am unable to reproduce this issue with hovering over a bookmarked ultimate induction provider
https://i.imgur.com/OfZgNzU.mp4
If you simply want to remove the bookmarks you can delete the bookmarks files in `config\jei\world\(local or server)\(world or servername)\`
