### ISSUE TITLE
[Feature]: Chipped versions for the new dyes

### ISSUE THREAD

**Issue by JanisChambers** [AllTheMods/ATM-10#1383]
### Feature Details

I love the new colors, but there's no Chipped variants for them, especially the stained glass.

**Comment by TheBedrockMaster** [comment]
Are you referring to Dyenamics dyes?

**Comment by JanisChambers** [comment]
Yes, the Dyenamic dyes.

**Comment by TheBedrockMaster** [comment]
We'll need [this](https://www.curseforge.com/minecraft/mc-mods/dyenamicsandfriends) mod to update to 1.21.1 NeoForge and to add compatibility with Chipped. Not planned currently.
