### ISSUE TITLE
[Bug]: Powah 'the energizing orb' quest not completing.

### ISSUE THREAD

**Issue by convict-vx** [AllTheMods/ATM-10#1389]
### Possible Fixes

Yes

### Modpack Version

2.3

### What happened?

The energizing orb quest for powah is not completing. it is asking for either a starter or a basic rod and they never got detected. i have both in inventory and the quest is not completing.Wich will  locks the quests for the resources made in the energizing orb. as u can see with the energized steel quest having the grey checkmark on it.

![powah 1](https://github.com/user-attachments/assets/91ee1500-f743-4ea6-8b4d-0cf94eed8fba)
![powah 2](https://github.com/user-attachments/assets/e6831c74-35c4-4210-841a-0be549348083)
![powah 3](https://github.com/user-attachments/assets/54746e93-f2c3-4310-9590-6d7047735899)
![powah 4](https://github.com/user-attachments/assets/2682529c-8f7f-4381-93fd-cce2e76834f2)

**Comment by Kiriao** [comment]
try use ftbquest command to remove the progress of that specific quest and it will should work fine

**Comment by TheBedrockMaster** [comment]
**"My quest is stuck/grey"**
If you have a quest that isn't completing, you need to check if you completed all of it's requirements, you can check this by clicking on the quest, and clicking the small triangle/arrow on the top left of the quest popup. That will show all requirements.

If all the requirements are met, then the quest is probably actually stuck, which sometimes happens with FTB Quests:
To complete it, you need to be an OP (/op "username" from console) or have cheats enabled (if you didn't enable cheats in the world creation, open to LAN with cheats enabled).
With that, open the quests window.
Click the pencil icon on the bottom right, which enables editing mode.
Right click the quest in question.
Click Complete Instantly.

That will complete the quest, then disable the pencil button afterwards.

**"I want the reward from the quest though"**
In that case, in the quest popup, right click the reward, and click Reset Progress, that will let you claim the reward.
