### ISSUE TITLE
[Bug]: pipez causes serious lag

### ISSUE THREAD

**Issue by Pbn-K** [AllTheMods/ATM-10#1394]
### Possible Fixes

Yes

### Modpack Version

2.3

### What happened?

I'm running a multiplayer server. 

The server TPS dropped by less than half because Pipes mode occupied an abnormal server thread. This is not an issue that has occurred since the beginning of the server, and it happened suddenly from some unknown point. 

I'm attach these files because I can't analyze the spark and log files.

spark logs : [https://spark.lucko.me/xO4BJMoWmZ](https://spark.lucko.me/xO4BJMoWmZ)
server's latest.log: See Bottom

### latest.log

https://gist.github.com/Pbn-K/dfec1026a877ced58379ec11f4654c32

**Comment by alekthefirst** [comment]
the big pipez lag really start to occur with the faster upgrades and especially when it fails to move items because the target inventory is full
i suspect this is what is happening to you

**Comment by Pbn-K** [comment]
> the big pipez lag really start to occur with the faster upgrades and especially when it fails to move items because the target inventory is full i suspect this is what is happening to you

We checked all the pipes and modified 10+ pipes with blocked exits, but the lag was not solved at all. Is there any other cause?

**Comment by alekthefirst** [comment]
if you want to hunt down singular pipez then i suggest you use observable, it will generate an itemized report of the most laggy individual things and also generate a tp command you can paste into your game to take you to them

**Comment by Pbn-K** [comment]
> if you want to hunt down singular pipez then i suggest you use observable, it will generate an itemized report of the most laggy individual things and also generate a tp command you can paste into your game to take you to them

excellent, I found 2 lag source. The exit wasn't blocked, but I think the lag was caused by too many filters and maximized speed upgrade. The issue is completely resolved. Thank you.
