### ISSUE TITLE
[Bug]: minecraft:observer false pic when placed

### ISSUE THREAD

**Issue by nico1972weimar** [AllTheMods/ATM-10#1398]
### Possible Fixes

Yes

### Modpack Version

2.3

### What happened?

![observer](https://github.com/user-attachments/assets/0a549020-8c71-453f-b1ac-23b49f8a87d0)

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/812
