### ISSUE TITLE
[Bug]: Relics wont Upgrade/reroll on  multiplayer

### ISSUE THREAD

**Issue by wolflord212312** [AllTheMods/ATM-10#1401]
### Possible Fixes

Yes

### Modpack Version

10.2.4

### What happened?

Full Logs:
https://mclo.gs/HaLDqpW
ERROR:
https://mclo.gs/CVDEuld

VIDEO:
https://cdn.discordapp.com/attachments/795789786736099328/1317384218065633383/20241214-0653-56.7114829.mp4?ex=675e7d29&is=675d2ba9&hm=5a94910c1a30499a5fc7e0502850aea1058a8f33659f524b139d365c42325a36&

### latest.log

https://mclo.gs/HaLDqpW

**Comment by alekthefirst** [comment]
This and a crashing issue is fixed with Relics: Artifacts compat 0.7.1
For clients you can manually update just that mod

**Comment by SSKirillSS** [comment]
The issue was on the side of Relics and has already been fixed in update 0.10.0.1. As for RAR-Compat, its recent update (0.7.1) addresses a different issue - a crash when using modded tools with Digging Claws. So, yea, both issues are fixed now.

**Comment by wolflord212312** [comment]
Issue resolved in latest Relics version
