### ISSUE TITLE
[Bug]: Texture for Observer is messed up

### ISSUE THREAD

**Issue by tubadstk** [AllTheMods/ATM-10#1404]
### Possible Fixes

Yes

### Modpack Version

2.4

### What happened?

Placed observers down and it shows a red image.

### latest.log

https://gist.github.com/tubadstk/10a82e0385faf2f9472618ac982db8e3

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/812
