### ISSUE TITLE
[Crash]: Attempting to mine blocks using Allthemodium pickaxe with digging claws equipped crashes the game

### ISSUE THREAD

**Issue by ajkamen** [AllTheMods/ATM-10#1405]
### Possible Fixes

Yes

### Modpack Version

0.24

### What happened?

Tried mining a block using Allthemodium pickaxe enchanted w/ efficiency 5, fortune 3, mending, and tombstone soulbound. Had digging claws equipped. Crashed when attempting to mine any block.

I'm not patient enough to read through the log myself, but i uploaded it to chatGPT and it says it might be something to do with how the digging claws buff my mining tier and how that interacts w/ Allthemodium's pickaxe mining tier.

### Crash Log

https://gist.github.com/ajkamen/cb4c51f5d94eed2589866c32c680bf13

### Latest.Log

https://gist.github.com/ajkamen/0dda393fae72c920b7165a5c46c7d07e

**Comment by alekthefirst** [comment]
See
https://github.com/AllTheMods/ATM-10/issues/1407#issuecomment-2543062881
