### ISSUE TITLE
[Crash]: JustDireThings Tools crash the game since new update

### ISSUE THREAD

**Issue by Tymeriass** [AllTheMods/ATM-10#1406]
### Possible Fixes

Yes

### Modpack Version

2.4

### What happened?

Since the new update, JustDIreThings Tools crash the Game, when you try to Mine something.
Even tryed to downgrade the JustDireThings Version no Difference between 1.5.0 and 1.5.1

No Differnce between Enhanced Tool like Unbreaking or new Crafted DireTool

Edit:

even more Mods Crash the Game. 
2nd report with used Modular Routers

### Crash Log

https://gist.github.com/Tymeriass/f49ed4ae442d8162a610db1b61c4948b
https://gist.github.com/Tymeriass/fea682b0d88ef3d96d1db6d2e74b8a18

### Latest.Log

https://gist.github.com/Tymeriass/7c3a3eec71f39040c29b85bd41b68e08
https://gist.github.com/Tymeriass/441598d2ba720ff064b42514b7757c94

**Comment by alekthefirst** [comment]
See
https://github.com/AllTheMods/ATM-10/issues/1407#issuecomment-2543062881

**Comment by alekthefirst** [comment]
See
https://github.com/AllTheMods/ATM-10/issues/1407#issuecomment-2543062881
