### ISSUE TITLE
[Crash]: Random crashing

### ISSUE THREAD

**Issue by Arcynx** [AllTheMods/ATM-10#1407]
### Possible Fixes

Yes

### Modpack Version

10-2.4

### What happened?

Randomly jade gives an error and shortly after the game crashes i have no idea why tough

### Crash Log

https://gist.github.com/Arcynx/bff02723eebf75fde3a9edc7d3afd6fd

### Latest.Log

https://gist.github.com/Arcynx/bff02723eebf75fde3a9edc7d3afd6fd

**Comment by alekthefirst** [comment]
Using digging claws with modded tools will crash you on ATM10 2.4
There might be some other relic related crashes too. If you are in single player, updating Relics: Artifacts Compat will fix the crashes. The leveling issues are being worked on.
