### ISSUE TITLE
[Feature]: Add the "AE2 Things" mods

### ISSUE THREAD

**Issue by PrefacedCorg** [AllTheMods/ATM-10#1408]
### Feature Details

Name implies

**Comment by PrefacedCorg** [comment]
“AE2 Things” likely refers to items related to Applied Energistics 2 (AE2).
1. What is Applied Energistics 2?
Applied Energistics 2 is a mod for Minecraft. It's a digital storage and automation system. The mod allows players to store and manage items in a highly efficient and organized way.
Storage Cells: These are a fundamental part of AE2. Storage cells come in different capacities and can store a vast number of different items. They are used in conjunction with storage drives to build a digital storage network. For example, a 1k storage cell can store up to 1024 of a single type of item.
ME Network: The Matter - Energy (ME) network is the backbone of the AE2 system. It consists of various components such as cables (like the ME Cable), which are used to transmit data and items between different parts of the network. The ME Controller is another crucial component that manages the overall operation of the network, kind of like a central processing unit for the storage and retrieval operations.
Import and Export Busses: These are used to move items in and out of the ME network. An Import Bus can be configured to automatically pull items from nearby containers (such as chests) into the ME network. The Export Bus, on the other hand, can send items from the network to external containers. For example, you can set up an Import Bus to take all the cobblestone from a chest and store it in the ME network and an Export Bus to take out a certain number of iron ingots and place them in a crafting table for further processing.
2. “AE2 Things” in the Context of Modding and Community
In the modding community, people often talk about “AE2 things” when they are discussing setups, configurations, and new additions to the AE2 mod. For instance, a player might share a screenshot of their elaborate AE2 storage room filled with storage drives, cells, and a complex network of cables and say “Here are some of my AE2 things.”
There are also many custom add - ons and resource packs that can change the appearance or functionality of AE2 components. These are also considered as part of the “AE2 things” that enthusiasts might explore and experiment with to enhance their Minecraft experience.
If “AE2 Things” is something other than related to the Minecraft mod Applied Energistics 2, it would depend on the specific context in which the term is being used. For example, it could potentially be an abbreviation for a company name, a project title, or something else entirely.

**Comment by TheBedrockMaster** [comment]
Please use #2 for mod suggestions.
