### ISSUE TITLE
[Bug]: error rendering on several recipes

### ISSUE THREAD

**Issue by death6007** [AllTheMods/ATM-10#1412]
### Possible Fixes

Yes

### Modpack Version

2.4

### What happened?

Several recipes give the error "error rendering".
Stone anvil is having this issue for example.
![mc_error_rendering](https://github.com/user-attachments/assets/8e954619-38b4-4a6c-bc3b-f62fb935d576)

### latest.log

https://gist.github.com/death6007/7852594eb71ff9d283d0282cb2f68fca

**Comment by alekthefirst** [comment]
Does it happen without EMI?
we dont ship EMI with ATM10

**Comment by death6007** [comment]
EMI indeed broke it.
Thanks for checking!
