### ISSUE TITLE
[Crash]: Relic Mod 

### ISSUE THREAD

**Issue by Xrezeneus** [AllTheMods/ATM-10#1414]
### Possible Fixes

Yes

### Modpack Version

2.5

### What happened?

when ı try to enter the world game crashes and ı get the message ;

The game crashed whilst load world
Error: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "it.hurts.sskirillss.relics.config.data.StatConfigData.toData(it.hurts.sskirillss.relics.items.relics.base.IRelicItem, String, String)" because the return value of "java.util.Map.get(Object)" is null

### Crash Log

https://gist.github.com/Xrezeneus/7203ac09fb09afa0d6bacadb7c10bde8

**Comment by alekthefirst** [comment]
This one is failing to load a config file
try to delete the entire relics folder in the config folder

**Comment by Sculas** [comment]
I've also lost numerous relics from my inventory with the update and had to restore to an earlier backup.
Removing the config file and, just to be sure, updating ATM10 again seems to have fixed it.

**Comment by ChimeraGaming** [comment]
Relics mod has tons of these logs on their issues page, they're working on a fix

**Comment by Xrezeneus** [comment]
I did removed config and can enter the world again thanks
