### ISSUE TITLE
[Bug]: Creativecore (ResourceKey[minecraft:command_argument_type / creativecore:string_array] and ResourceKey[minecraft:menu / creativecore:container])

### ISSUE THREAD

**Issue by felipesmk** [AllTheMods/ATM-10#1415]
### Possible Fixes

Yes

### Modpack Version

2.5

### What happened?

User tried to logon in the server and get the message ResourceKey[minecraft:command_argument_type / creativecore:string_array] and ResourceKey[minecraft:menu / creativecore:container]
![image](https://github.com/user-attachments/assets/8eb84c5d-1efb-432e-977a-45c4bff7821a)

when removes the mod he can login normally.

**Comment by alekthefirst** [comment]
either the server is not updated to 2.5 or it was incorrectly updated to 2.5
(the correct update process involved deleting the old mods folder. Creativecore mod was removed in atm10 version 2.5)

**Comment by felipesmk** [comment]
Thats it. i Didnt removed it. Thanks!
