### ISSUE TITLE
[Bug]: Inferium-Supremium Pickaxes can mine allthmodium, vibranium, and unobtainium

### ISSUE THREAD

**Issue by Link-Jon** [AllTheMods/ATM-10#1416]
### Possible Fixes

Yes

### Modpack Version

2.4

### What happened?

...Uh. I'm really just noting this because everyone else on the server says this should not be possible. I have no idea, so im noting it here.
Specifically, mystical agriculture's pickaxes can all mine at netherite teir. Thus, i had assumed they can probably mine what netherite can... so i went around the end hunting for ATM ore. Everyone else was a little surprised when i said i had a stack and a half of it...

**Comment by ChimeraGaming** [comment]
Not a bug , just a different path of progression

**Comment by DaddyLongspoon** [comment]
this also always used to (probably still does) apply to crimson iron, azure electrum, tyrian steel.

**Comment by Link-Jon** [comment]
> Not a bug , just a different path of progression

And thus is the answer, issue is unneeded.
Thank you thank yous

**Comment by TheBedrockMaster** [comment]
This is just one of those unfortunate things, but as long as they are labelled correctly in the quests it isn't a "bug".
