### ISSUE TITLE
[Bug]: Altar Bug

### ISSUE THREAD

**Issue by Atiya96** [AllTheMods/ATM-10#1417]
### Possible Fixes

Yes

### Modpack Version

2.4

### What happened?

I cannot craft seeds like Diamond or Iron Seeds in the Altar

**Comment by alekthefirst** [comment]
It seems to work fine?

https://github.com/user-attachments/assets/c82c3b6f-9eb2-43d0-99ba-2ae004162d9b

**Comment by ChimeraGaming** [comment]
We can also craft in 2.1 and 2.5 so it's a user issue. Update to latest just to be safe

**Comment by TheBedrockMaster** [comment]
Happens sometimes for some people, not sure why.

**Comment by loustak-test** [comment]
I'm getting this bug on ATM 2.20. I see no issues in server logs. It happens for both diamond seed and iron seed at least.

**Comment by TheBedrockMaster** [comment]
I’m not entirely sure, you might be able to check similar issues and see other’s solutions:
