### ISSUE TITLE
[Bug]: Pipez to Mekanism

### ISSUE THREAD

**Issue by RedAshPhoenix** [AllTheMods/ATM-10#1420]
### Possible Fixes

No

### Modpack Version

10-2.5

### What happened?

Trying to use Pipez to transfer energy to Mekanism and it won't work set up correctly tried asking for help they tried and nothing worked to fix

**Comment by alekthefirst** [comment]
Seems to work fine?

https://github.com/user-attachments/assets/3999c304-ccde-426d-9310-abdefd3c516e

**Comment by RedAshPhoenix** [comment]
> Seems to work fine?
> 
>  2024-12-15.09-05-16.mp4

Yes now try transferring power i said and quote “ Trying to use Pipez to transfer energy to Mekanism and it won't work set up correctly” so just hooking them up probes nothing

**Comment by RedAshPhoenix** [comment]
> Seems to work fine?
> 
>  2024-12-15.09-05-16.mp4

I will post a clip also

**Comment by RedAshPhoenix** [comment]
in this clip the energy configuration is set to input energy from all sides its shows RED INPUT 



https://github.com/user-attachments/assets/d46e8459-0387-4c1f-8767-0c7c95a00e45
