### ISSUE TITLE
[Crash]:2.5 Start on dedicated Server fails cloud glass has failed to load correctly

### ISSUE THREAD

**Issue by fkempf78** [AllTheMods/ATM-10#1421]
### Possible Fixes

remove cloud glass

### Modpack Version

2.5

### What happened?

start dedicated server

### Crash Log

https://gist.github.com/fkempf78/0ffd2b9c340557713615f7574a1d65ec

### Latest.Log

https://gist.github.com/fkempf78/f837725233c50494bc339451592ea4f9

**Comment by alekthefirst** [comment]
your neoforge version is too old, you have neoforge-21.1.73, and atm10 2.5 runs on 21.1.89, 2.6 runs on 21.1.90

**Comment by fkempf78** [comment]
Thanks, had not noticed the neoforge upgrade
