### ISSUE TITLE
[Bug]: Mystical Agriculture Skeleton seed recipe not working.

### ISSUE THREAD

**Issue by Adayics** [AllTheMods/ATM-10#1422]
### Possible Fixes

Yes

### Modpack Version

10-2.5

### What happened?

I have all the correct ingredients, all the soul jars are filled entirely 10/10 the middle seed is the soulium seed base but when i right click the center pedestal it doesn't do anything. I did test it and it does still make the other seeds but I havent been able to make the skeleton seeds. I saw that there have been issues with crafting some other seed recipes but I also found that this one is having some issues as well, sorry if this counts as a duplicate issue.
![2024-12-15_00 47 40](https://github.com/user-attachments/assets/505382c2-4aef-4fc2-bb5b-3ecef8137a02)

### latest.log

https://gist.github.com/Adayics/ab3e316e420de1f608c8646a7186e1b5

### Developer reports

https://github.com/BlakeBr0/MysticalAgriculture/issues/758

**Comment by Nile737** [comment]
Have you tried sending the center pedestal a redstone pulse/signal? It fixed the problem for me.

**Comment by Adayics** [comment]
> Have you tried sending the center pedestal a redstone pulse/signal? It fixed the problem for me.

Yeah, I've used a button and a lever but neither worked for me :(

**Comment by TheBedrockMaster** [comment]
This seems to be the same as other issues you've seen, sometimes some seeds just don't work for some people for some reason.
