### ISSUE TITLE
[Bug]: Connection Lost: regestrie with un known keys

### ISSUE THREAD

**Issue by BluePiru** [AllTheMods/ATM-10#1425]
### Possible Fixes

Yes

### Modpack Version

10-2.6

### What happened?

After i updated my pack to the newest version 10-2.6 i cant connect to my server.
"The server send registries with unknown keys: ResourceKey[minceaft:command_argument_type / creativecore:string_array], ResourceKey[minecraft:menu / creativecore:container]

### latest.log

https://gist.github.com/BluePiru/a8ca12fda93d417a6c2976d4953093c6

**Comment by alekthefirst** [comment]
Looks like you didn't update your server properly, the creativecore mod was removed in 2.5, and if you didn't delete the old mods folder before putting in the new, you will have mods that are no longer in atm10
