### ISSUE TITLE
[Bug]: Ars Noveau Amethyst Golem likes wandering

### ISSUE THREAD

**Issue by SszlGaming** [AllTheMods/ATM-10#1428]
### Possible Fixes

Yes

### Modpack Version

Atm10, 2.4

### What happened?

When using Ars Nouveau to create an amethyst golem - Mine seems to wander outside the stated 10 block radius from his bind point - which is a chest.  have also tried a backpack and a drawer.  Using dominion wand to connect to golem as entity and then the chest in the middle of area as home location.  He starts working in the area and is depositing shards in the inventory as expected, but he wanders beyond this area.  if there is a wall at 12 and 13 and 14 blocks away(I moved wall several times to try to resolve), he'll get stuck just pushing against the wall and not work. if reset him to home on the inventory again he starts working in the right area again.

### latest.log

https://gist.github.com/SszlGaming/8ad7c8aaafae541da442396972cf203a

**Comment by alekthefirst** [comment]
Talked with one of the Ars Noveau devs about it, they state its known, and that it should generally be fine if you enclose the golem within its area (5 blocks radius)

**Comment by alekthefirst** [comment]
Reports are that it is unlikely this will be worked on.

**Comment by alekthefirst** [comment]
Apparently they went ahead and fixed it anyway, will re-close when that Ars update gets into ATM10
