### ISSUE TITLE
[Crash]: charTyped event handler: Rendersystem called from wrong thread

### ISSUE THREAD

**Issue by BDGameDev** [AllTheMods/ATM-10#1431]
### Possible Fixes

Yes

### Modpack Version

2.5

### What happened?

When i click on the creative menu search bar everything is fine, but as soon as i try to type anything at all the game freezes for a second then crashes. i have attempted several different letters and it always crashes.

### Crash Log

https://gist.github.com/BDGameDev/12275567e8ef7ea94cd0b78e768b1d51

### Latest.Log

https://gist.github.com/BDGameDev/6142a46200f648a7613a9c639a5f8520

**Comment by alekthefirst** [comment]
The creative menu conflicts with a lot of keybinds and features from several mods and thus has a lot of crashing issues
Its recommended to stay in survival and use JEI in cheat mode instead

**Comment by firelizzard18** [comment]
For anyone else not sure how to enable cheat mode ([source](https://www.reddit.com/r/feedthebeast/comments/6pykz2/comment/dkt8xhr/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)):

> To put JEI into cheat mode CTRL+ click the wrench next to the search bar.
