### ISSUE TITLE
[Bug]: Mekanism ponder interface

### ISSUE THREAD

**Issue by biellSilva** [AllTheMods/ATM-10#1432]
### Possible Fixes

No

### Modpack Version

2.6

### What happened?

in previous versions I noticed and checked on how Mekanism was working by using the "ponder" interface, but right it disappeared, I've checked some patch notes and didn't noticed any of it mentioning that it was removed 

![image](https://github.com/user-attachments/assets/55ccd451-85a8-40cb-8794-4757f87be351)

**Comment by alekthefirst** [comment]
The mod that adds ponder isnt updated yet
