### ISSUE TITLE
[Bug]: Wilden Chimera Bug "super Boss'

### ISSUE THREAD

**Issue by theoriginalspre** [AllTheMods/ATM-10#1437]
### Possible Fixes

Yes

### Modpack Version

2.6

### What happened?

as reported by another user 2 weeks ago. The chimera does and still spawns Invisible as a super boss, only his add spawns are visible, he never leaves that state making him impossible to kill, with a ton of other added bonuses and skills, including a super poison that actually killed me.

**Comment by HelixRanmaru** [comment]
@theoriginalspre Which dimension did you spawn it in? ATM 10 has a blacklist of dimensions where Infernal mobs will not spawn. If you do spawn it in a non-blacklisted dimension, such as the Other, Beyond, or Mining dimension, it will spawn in as infernal.

**Comment by theoriginalspre** [comment]
Mining dimension first, then over world. I had to upload a backed up world directory to get rid of it as /kill killed everything but it.
