### ISSUE TITLE
[Bug] Dirty netherite scrap

### ISSUE THREAD

**Issue by theoriginalspre** [AllTheMods/ATM-10#1438]
### Possible Fixes

Yes

### Modpack Version

2.6

### What happened?

Jei shows that the ore hammer double and the crusher triples ancient debris by making it dirty scrape, but when using either the hammer makes 2 dust, and the crusher only makes 2 dust as well.

**Comment by alekthefirst** [comment]
Fixed in https://github.com/AllTheMods/ATM-10/pull/1479, released with ATM10 2.7
