### ISSUE TITLE
[Bug]: Powah Ender Cells/Gates don't work

### ISSUE THREAD

**Issue by xWaller0119** [AllTheMods/ATM-10#1439]
### Possible Fixes

Yes

### Modpack Version

2.6

### What happened?

The ender gates and cells from Powah do not work. Putting a battery or energy cell in them still shows 0/0 stored energy. Tried on both singleplayer/multiplayer. Shift clicking them in does not work either.

**Comment by Alex59S** [comment]
Hello @xWaller0119 
I am facing the same issue but what was your solution to this problem ? 

Thank you
