### ISSUE TITLE
[Crash]: game stürz einfach ab 

### ISSUE THREAD

**Issue by ricco1898** [AllTheMods/ATM-10#1442]
### Possible Fixes

Yes

### Modpack Version

2.4 (1.21.1

### What happened?

wenn irgenwelche monster kommen stürtzt das game einfach ab habe aus auch schon neu installiert hat aber nix gebracht und die neuste version können wir für unsern server leider nicht nehmen  

### Crash Log

https://gist.github.com/ricco1898/b9448bf2342a3f3770551e405de52237

### Latest.Log

https://gist.github.com/ricco1898/f753ddcf2a51f0a709e45ad1ceedff1f

**Comment by alekthefirst** [comment]
Using digging claws will crash you on that version of ATM10, i recommend you update, or alternatively don't use digging claws

**Comment by ricco1898** [comment]
die mod finde ich garnicht

**Comment by ricco1898** [comment]
habe es jetzt gefunden und die neuste version  davon insterlirt aber trd stürzt das game ab das problem ist das ich die mod nicht raus machen kann da ich sonst nicht mehr auf dem server komme auf dem ich zocke

**Comment by ricco1898** [comment]
Warum wird das Ticket geschlossen? Ich habe bis jetzt keine Lösung zu dem Problem bekommen der das behoben hat ?

**Comment by alekthefirst** [comment]
@Satherov can i bother you with this? I can't do German very well and fear that auto translate might lose technical details

**Comment by Satherov** [comment]
@ricco1898 Ich kann hier auch nicht viel mehr sagen als Alek. Die `Digging Claws` von der `Artifacts` Mod crashen in der Version. Wenn die Mod zu updaten nichts gebracht hat, dann kannst du noch versuchen das Pack auf die Version `2.6` zu updaten. Ansonsten brauchen wir neue Logs, da der Fehler in der neusten Packversion schon behoben seien sollte (wahrscheinlich auch warum Toble das Ticket geschlossen hatte)

**Comment by ricco1898** [comment]
das updaten hat nix gebracht und wenn wir den server updaten kommt keiner auf dem server

**Comment by Satherov** [comment]
Ohne logs kann ich auch nix machen. Der Fehler ist in der neusten Version behoben ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by ricco1898** [comment]
![image](https://github.com/user-attachments/assets/e94c3c40-bb58-4b35-9237-f36bae44caf4)
die umkreiste mod ist die die ich nur nehmen kann da es ja über neoforge läuft oder ist das egal ?

**Comment by Satherov** [comment]
Nein, du mod die du updaten sollst ist [`Relics: Artifacts Compat`](https://www.curseforge.com/minecraft/mc-mods/rar-compat/files/5986151)

**Comment by ricco1898** [comment]
ok ich versuche das dann mal und melde mich dann nochmal wenn es nicht geht

**Comment by ricco1898** [comment]
soll ich da dann die 0,6,1 nehmen da es keine 2.6 gibt

**Comment by Satherov** [comment]
Ich hab dir die Version verlinkt die du nehmen sollst [`rarcompat-1.21-0.7.1`](https://www.curseforge.com/minecraft/mc-mods/rar-compat/files/5989848)

**Comment by ricco1898** [comment]
aso bis jetzt geht das ganze wenn es weitere probleme haben sollte würde ich nochmal ein ticket auf machen
