### ISSUE TITLE
[Bug]: Artifacts Umbrella can no longer be used as a shield as of ATM10 2.6

### ISSUE THREAD

**Issue by Farkinell** [AllTheMods/ATM-10#1445]
### Possible Fixes

Yes

### Modpack Version

2.6

### What happened?

Umbrella from Artifacts can no longer be used as a shield. This also prevents its secondary ability from being used. When right clicking with it in the shield slot, it instead swaps with the generic curio curios slot. Especially frustrating because the umbrella doesn't work from the curio slot, it must be held in the hand or the off-hand to work.

**Comment by Farkinell** [comment]
It appears there may be further issues with the Artifacts mod, as I also cannot level up my bunny hoppers.

**Comment by alekthefirst** [comment]
Umbrella and Bunny Hoppers, and several others, have had fixes that should appear in the next pack update

**Comment by morrissimo** [comment]
Any updates on this issue? Umbrella doesn't function at all any more as of ATM10 v2.10 - (still) no shield behavior, but now it also no longer provides slowfall...!

**Comment by Farkinell** [comment]
Be sure to unlock the soft fall ability! You have to do the minigame with the connecting the dots. They changed how it works so now you have to level it up to level 5 before you can unlock the shield ability. This was actually true when I opened this bug but I didn't realize at the time.

**Comment by morrissimo** [comment]
> Be sure to unlock the soft fall ability! You have to do the minigame with the connecting the dots. They changed how it works so now you have to level it up to level 5 before you can unlock the shield ability. This was actually true when I opened this bug but I didn't realize at the time.

omg you're absolutely right! thank you for the heads up!
