### ISSUE TITLE
[Crash]: Ticking Block Entity - Cannot get property DirectionProperty [...] as it does not exist in Block{minecraft:void_air}

### ISSUE THREAD

**Issue by Silicat-git** [AllTheMods/ATM-10#1451]
### Possible Fixes

Yes

### Modpack Version

2.6

### What happened?

Playing on a server with some friends but after like the 2.5 update we started getting client crashes after teleporting. Happens in several of our bases and we cant figure out what is causing it.

### Crash Log

https://gist.github.com/Silicat-git/eee1f2cc8cf3ebc8553427daaf64af49

### Latest.Log

https://gist.github.com/Silicat-git/d8e9039a823b89adc613c69cafe5fd24

**Comment by alekthefirst** [comment]
Hi could you come to the linked issue page on the restrictions github please?
The dev is trying to reproduce it and is currently unable to

**Comment by alekthefirst** [comment]
Fixed in restrictions 7.0.3, will likely be included in next ATM10 update.
