### ISSUE TITLE
[Bug]: Relics UI not allowing to open abilities tab

### ISSUE THREAD

**Issue by death6007** [AllTheMods/ATM-10#1455]
### Possible Fixes

Yes

### Modpack Version

2.6

### What happened?

I'm currently trying to open the abilities tab to reroll/level my relics.
On the latest version I'm unable to open it while it worked in 1.23 (jumped many updates).
![relics_ui](https://github.com/user-attachments/assets/0802a2f6-6761-4351-82a3-6cb3ce48ac6a)

All non-packmods have been removed normally but issue still remains.
With the latest version of relics, i'm having the same issue.

### latest.log

https://gist.github.com/death6007/029c7de2cc4ec02af23d84a021d0776a

**Comment by SSKirillSS** [comment]
Judging by what I see in the screenshot, everything seems to be working as intended. The old stat upgrade interface no longer exists; instead, a new tab-based system is now in place, and you can find the buttons for managing stats in the top-right corner of the UI. However, not all items from the original Relics have been updated to this system. We’ve updated only 2 items from Relics and all the items included in RAR-Compat (an addon between Artifacts and Relics).
![image](https://github.com/user-attachments/assets/5f64db43-4abd-4be5-b789-eedd171d939f)

As for the items from Relics themselves, support for them will be added gradually as we update their mechanics. Right now, we are working on updating the Infinity Ham. For items that haven’t been updated yet, you can determine how good their stats are by looking at the ability quality (5 stars is the ideal rating). Unfortunately, precise stat numbers for these items won’t be visible until their mechanics are updated.
