### ISSUE TITLE
[Feature]: How can I Un-nerf Mahou Tsukai

### ISSUE THREAD

**Issue by trevorjd** [AllTheMods/ATM-10#1457]
### Feature Details

Hi folks,  a player of mine has made the Mahou Tsukai sword and mentioned that it's capped to level 60.  I've not played the mod but I understand that the consequence is that the player will simply have a 1-hit godlike weapon.  We're a casual bunch so that doesn't worry me.  Are you able to advise on what config(s) to adjust to un-nerf the sword to its default settings?  Thanks!

**Comment by TheBedrockMaster** [comment]
Please ask questions like this on the Discord server.
