### ISSUE TITLE
[Bug]: Unable to reassign jump key

### ISSUE THREAD

**Issue by Gen732741** [AllTheMods/ATM-10#146]
### Possible Fixes

Yes

### Modpack Version

0.18

### What happened?

When attempting to reassign the jump key, it shows new key selection but then changes to next key selected (left mouse, enter, etc.) before accepting selection.  Pressing the new key binding (right control) multiple times has no change (shows right control as new key, then accepts next key pressed).  Unable to change jump key to anything other than default setting.

**Comment by MakaPaka007** [comment]
I have also encountered this issue, preventing me from switching the jump and sneak keys. The selection box remains active after choosing a new key, and when you try to exit the screen, it binds the next key you press (LBM, ESC, etc.). In 1.20, the issue changed to where the key instantly unbinds whenever you try to bind L.Shift or L.Control.
