### ISSUE TITLE
[Bug]:  Ars spellbooks dont go into ars bookshelves

### ISSUE THREAD

**Issue by darrenh2** [AllTheMods/ATM-10#1461]
### Possible Fixes

Yes

### Modpack Version

10-2.6

### What happened?

Tried to put in ars spellbooks (the ones you find in other chests) into the ars bookshelves and  cant be clicked in - the spellbooks you make (i.e novce spellbook) works fine

**Comment by alekthefirst** [comment]
The Repository seems to work fine for storing both kinds of books
Its been suggested to me that you might be talking about the Scribes Table instead, i which case yeah the looted books can't go in that

https://github.com/user-attachments/assets/b2625a1a-90ba-4f9d-8348-522ffce5d8ab

**Comment by darrenh2** [comment]
No, I mean the bookshelves -  the purple spellbooks you find in the world place fine - but the green, yellow,red, orange spellbooks do not go into the bookshelves

**Comment by alekthefirst** [comment]
I can't find any single shelf, book or otherwise, added by ars noveau or its addon mods

**Comment by HelixRanmaru** [comment]
@darrenh2 can you post a photo of the shelf you are trying to do this in, along with the tooltip showing the name of the shelf? and a photo of the book/s in question?

**Comment by darrenh2** [comment]
Looks like the shelves aren't an Ars block - bilbliocraft legacy that uses archwood
![Bookshelves](https://github.com/user-attachments/assets/acf07985-d1dd-4345-b7f7-85c75dbb9d98)

These are the purple  Ars spellbooks I was talking about
![purple books go in](https://github.com/user-attachments/assets/eb24abea-fdf1-4fe0-b48f-59e9dc24f788)

These are the Ars spellbooks that don't go in
![These books do not](https://github.com/user-attachments/assets/80702ca7-c0c3-44be-91b0-51fc506e5b6a)

**Comment by HelixRanmaru** [comment]
@darrenh2 If I recall correctly, the colored ones are from Ars Elemental correct? There might just be a conflict with compatibility between bilbliocraft legacy and the Ars Elemental books. @alekthefirst Thoughts?

**Comment by alekthefirst** [comment]
Bibliocraft shelves can only take book tagges #minecraft:bookshelf_books and #minecraft:lectern_books
https://github.com/MinecraftschurliMods/Bibliocraft-Legacy/blob/3b38505c715382c45ce2ab91a196276449974f61/src/main/generated/data/bibliocraft/tags/item/bookcase_books.json
The ars elemental books do not have these tags
I'll look into adding the tags with kubejs

**Comment by alekthefirst** [comment]
Was able to make it work, ill PR the change, might see it on next update
![shel](https://github.com/user-attachments/assets/7ac93d86-4160-42a5-9d23-d8d38a7d7c3f)

**Comment by alekthefirst** [comment]
https://github.com/AllTheMods/ATM-10/pull/1465
