### ISSUE TITLE
[Bug]: Minecraft 1.21.1 some files are not mods

### ISSUE THREAD

**Issue by Diego77648** [AllTheMods/ATM-10#1464]
### Possible Fixes

Yes

### Modpack Version

69

### What happened?

Tried to load the ATM10 on original minecraft 1.21.1 and the game just says that some mod files are not mods, any idea of why is this happening?

**Comment by TheBedrockMaster** [comment]
Modpack version 69?

**Comment by alekthefirst** [comment]
Closed until further information is provided. Logs preferred. Version number casts doubt on the seriousness of the author
