### ISSUE TITLE
[Quests issues]: Wonkiness with Eternal Starlight quest "The Gatekeeper and The Gate"

### ISSUE THREAD

**Issue by alekthefirst** [AllTheMods/ATM-10#1466]
### Modpack Version

2.6

### Describe the issue

From the discord: two consecutive reports on having troubles starting the eternal starlight quest line, one was unable to complete the quest regardless of how they interacted with the gatekeeper, the other had slain the gatekeeper before the quests were added and unwilling to seek out a new gatekeeper. Personally i was only able to complete the quest by opening the gatekeepers trading ui after interacting with them in several other ways.

Personal thoughts on solutions: make the quest optional or the requirements for completion less strict.

**Comment by TheBedrockMaster** [comment]
The first quest requires you to find the structure "Portal Ruins Common" to complete. This is intended as per what Toshiba told me.
