### ISSUE TITLE
[Bug]: modular_machinery reborn blueprint

### ISSUE THREAD

**Issue by turtlez142** [AllTheMods/ATM-10#1467]
### Possible Fixes

Yes

### Modpack Version

10-2.6

### What happened?

every time i try to use the blue print to see the preview of the build it does nothing and when i check my console it just spam

### latest.log

https://gist.github.com/turtlez142/1cac6d105f58ff0d48ceb1654eec6ce3

**Comment by alekthefirst** [comment]
Would you be able to manually update modular machinery reborn and see if the issue persists?

**Comment by alekthefirst** [comment]
ok 1.1.17 breaks in other ways, please to not update :p

**Comment by alekthefirst** [comment]
Fixed in dev on MMRs end
