### ISSUE TITLE
[Bug]: Artifacts Cloud in a bottle Not working

### ISSUE THREAD

**Issue by GoldenDipper** [AllTheMods/ATM-10#1472]
### Possible Fixes

Yes

### Modpack Version

2.7

### What happened?

Cloud in a bottle was working in version 2.6 but after updating to 2.7 it has stopped working.

**Comment by alekthefirst** [comment]
The mod developer is unable to reproduce this issue, could you elaborate on how the relic doesn't work?

**Comment by GoldenDipper** [comment]
Nevermind, I guess in version 2.6 it worked without researching it but now in 2.7 you have to research it so it can work
