### ISSUE TITLE
[Crash]: Server crash on player logout

### ISSUE THREAD

**Issue by Silicat-git** [AllTheMods/ATM-10#1475]
### Possible Fixes

Yes

### Modpack Version

2.7

### What happened?

After updating to 2.7 the Server crashes when a player logs out.
Seems to have something to do with AE2 smart cables

Reverting to 2.6 fixxes the issue

### Crash Log

https://gist.github.com/Silicat-git/6a4a7ba1171fce661fd83b15372ece4a#file-crash-2024-12-20_19-36-23-server-txt

### Latest.Log

https://gist.github.com/Silicat-git/6a4a7ba1171fce661fd83b15372ece4a#file-latest-log

**Comment by alekthefirst** [comment]
Its known to happen, and already reported to ae2

**Comment by alekthefirst** [comment]
fixed in 2.8
