### ISSUE TITLE
Meat Bat for Infinity Ham question

### ISSUE THREAD

**Issue by Elrik35** [AllTheMods/ATM-10#1476]
The depleting attribute from the Meat Bat ability on Infinity Ham activates when doing damage while holding the ham depletes its charges even if if I'm not attacking with the ham. This is really prevalent when combined with the Holy Locket's passive damage to undead. Is this how its supposed to work?

**Comment by alekthefirst** [comment]
The infinite ham is currently receiving further updates and the next release of ATM10 will include those. If it does not clarify or answer your question, could you report back after that?
