### ISSUE TITLE
[Crash]: Crashing everytime i try to load in the world for some reason

### ISSUE THREAD

**Issue by Ryuusei017** [AllTheMods/ATM-10#1477]
### Possible Fixes

Yes

### Modpack Version

2.7

### What happened?

Everytime i try to load in my world it renders will 100% at the loading screen then crashes without entering the world

### Crash Log

https://gist.github.com/Ryuusei017/e11899ef7d18296c2162d2eb2de82a01

### Latest.Log

https://gist.github.com/Ryuusei017/b60f62822b7922633dd788b5d006de5d

**Comment by alekthefirst** [comment]
you will have to downgrade to 2.6
known issue with ae2, has been reported to them

**Comment by Ryuusei017** [comment]
> you will have to downgrade to 2.6 known issue with ae2, has been reported to them

ill just wait for the next update, if that fixes things

**Comment by alekthefirst** [comment]
2.8 fixed the issue by downgrading the ae2 version
