### ISSUE TITLE
2 advancements from Integrated Dynamics are broken (I'll leave this here and report to them too)

### ISSUE THREAD

**Issue by john13210** [AllTheMods/ATM-10#148]
### Possible Fixes

Yes

### Modpack Version

0.18

### What happened?

Crafting² Interface advancement
Crafting² Writer advancement

just complete as soon as you craft smth

reported to them first 
https://github.com/CyclopsMC/IntegratedDynamics/issues/1368

**Comment by john13210** [comment]
ill leave this here so ppl know this is a problem

**Comment by TheBedrockMaster** [comment]
https://github.com/CyclopsMC/IntegratedCrafting/commit/9702ef00458968239435f06a919e354299326567 Should fix this on their end.
