### ISSUE TITLE
[Bug]: New runic enchanter recipes give enchanted book with no enchantment  

### ISSUE THREAD

**Issue by JacobGroves** [AllTheMods/ATM-10#1480]
### Possible Fixes

Yes

### Modpack Version

2.7

### What happened?

According to the code seen in this change: 
https://github.com/AllTheMods/ATM-10/pull/1448/commits/369e578be8bce1b3ad791d55d784235e66070b26 
the below recipe should craft the Sharpness 5 Enchanted Book.

However in game that recipe returns just 'Enchanted Book' with no enchantment on it. 
![image](https://github.com/user-attachments/assets/259581bb-5787-436d-8cb5-f9b931090f85)

Seen above in the JEI and below in my inventory from testing the recipe myself:

![image](https://github.com/user-attachments/assets/13883426-1c5c-42ba-a42a-86b8aff70c4f)

Seems the same for all the new Runic Enchanter book recipes

**Comment by JacobGroves** [comment]
Might be a different issue, but as its related to enchantment data, ill mention here: 
The Infused Patrick Star recipe also seems broken in the JEI, have not tested this one though: 
![image](https://github.com/user-attachments/assets/cfbba6ba-923d-461f-9bc8-0bf9b08ebaa8)

**Comment by alekthefirst** [comment]
We are aware of an incompatibility between MMR recipes and Alltheleaks
temporary workaround is to disable ingredient dedupe in Alltheleaks config, if you're on a server, this also needs to be done on the server

**Comment by JacobGroves** [comment]
Ah ok thanks for the work around, ill ask my server admin to do this. 

To make sure I understood, this needs to be set on the server side, and all players need to do it client side too, or will changing it on the  server be enough? @alekthefirst

**Comment by alekthefirst** [comment]
If done only server side, the recipes will be broken in JEI but still make the correct output in the machine

**Comment by JacobGroves** [comment]
Thank you

**Comment by alekthefirst** [comment]
Recipe outputs was fixed in ATM10 2.8
Some other MMR issues not discussed in this thread will come at a later date
