### ISSUE TITLE
[Quests issues]: Ars Nouveau Quest Line Arcane pedestals quest 

### ISSUE THREAD

**Issue by CosmicNerd97** [AllTheMods/ATM-10#1486]
### Modpack Version

2.1

### Describe the issue

Quest is stuck at done 4 pedestal i crafted a total of 12 pedestals but its just stuck at four just to be sure i crafted 4 again and still nothing

**Comment by TheBedrockMaster** [comment]
**"My quest is stuck/grey"**
If you have a quest that isn't completing, you need to check if you completed all of it's requirements, you can check this by clicking on the quest, and clicking the small triangle/arrow on the top left of the quest popup. That will show all requirements.

If all the requirements are met, then the quest is probably actually stuck, which sometimes happens with FTB Quests:
To complete it, you need to be an OP (/op "username" from console) or have cheats enabled (if you didn't enable cheats in the world creation, open to LAN with cheats enabled).
With that, open the quests window.
Click the pencil icon on the bottom right, which enables editing mode.
Right click the quest in question.
Click Complete Instantly.

That will complete the quest, then disable the pencil button afterwards.

**"I want the reward from the quest though"**
In that case, in the quest popup, right click the reward, and click Reset Progress, that will let you claim the reward.

**Comment by CosmicNerd97** [comment]
Ok its fixed thanks
