### ISSUE TITLE
[Bug]: Mekanism Tier 4 Ore Processing

### ISSUE THREAD

**Issue by zoeliterally** [AllTheMods/ATM-10#1488]
### Possible Fixes

Yes

### Modpack Version

2.8

### What happened?

6 Iron Ore input

output:
tier 2: 18 ingots
tier 3: 24 ingots
tier 4: 9 ingots????

**Comment by alekthefirst** [comment]
Some numbers were accidentally switched and you're getting 0.25x of what was supposed to be on tier 4
already fixed for next version in https://github.com/AllTheMods/ATM-10/commit/4a880db567195dbdacfa0b6f3d6b7479964fc265

**Comment by zoeliterally** [comment]
Fixed 👍🏻
