### ISSUE TITLE
[Crash]: GeckoBeeRenderer Christmas Layer is crashing game because it can't be rendered

### ISSUE THREAD

**Issue by LordILarrion** [AllTheMods/ATM-10#1498]
### Possible Fixes

No

### Modpack Version

2.6

### What happened?

Walk into an area with bees, and the game crashes and restarting the game and logging in again causes same issue. If I wait a while and log back in sometimes it works, but if the bee comes back in range it crashes again. 
Have not updated the Server yet, because I need to warn my players first.

### Crash Log

https://gist.github.com/LordILarrion/e40e7c00f04027612e0b42a2051c2f6e

### Latest.Log

https://gist.github.com/LordILarrion/d0af1fef5ae902b16dcc6ec45b32a256

**Comment by LordILarrion** [comment]
Updated client and server to version 2.8 crash still happening

**Comment by alekthefirst** [comment]
This is fixed by productive bees dev but we haven't released an atm10 version with the fix yet

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/1493
