### ISSUE TITLE
[Bug]: Decaying leaves use up durability when holding ultimine key

### ISSUE THREAD

**Issue by Kraugel-x** [AllTheMods/ATM-10#15]
### Possible Fixes

Yes

### Modpack Version

0.2

### What happened?

If u keep holding the ultimite key after mining a tree with it, the decaying leaves use up the tool durability.

dont know why its in 4:3 lol
https://github.com/AllTheMods/ATM-10/assets/166866493/067d781a-679f-49c9-ab9d-c9a6dca65bf5

**Comment by 630R63** [comment]
Still happens in version 3.2

**Comment by pietro-lopes** [comment]
Check their issue tracker
[tracker list](https://github.com/AllTheMods/ATM-10/blob/main/MOD_ISSUES.md)

**Comment by TheBedrockMaster** [comment]
I believe this is a known issue with the leaf decay mod we use unfortunately.
