### ISSUE TITLE
Powah Thermo Generator Doesnt recognize lava under it (I'll leave this here and report to them too)

### ISSUE THREAD

**Issue by john13210** [AllTheMods/ATM-10#150]
### Possible Fixes

Yes

### Modpack Version

0.18

### Possible Fixes

Yes

### What happened?

Thermo Generator Doesnt recognize lava under it

reported to them first :
https://github.com/owmii/Powah/issues/243

**Comment by john13210** [comment]
ill leave this here so ppl know this is a problem

**Comment by Mithi83** [comment]
I've written a PR for that, but it hasn't been merged yet: https://github.com/Technici4n/Powah/pull/168

Btw you are reporting to the wrong github, more recent versions are maintained over here: https://github.com/Technici4n/Powah

**Comment by john13210** [comment]
i guess fixed in powah 6.0.6
