### ISSUE TITLE
[Bug]: Fortune enchantment not working on the allthemodium ore

### ISSUE THREAD

**Issue by zoanforte** [AllTheMods/ATM-10#1501]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-2.7

### What happened?

I have an allthemodium pickaxe with Fortune VIII, ive been mining allthemodium in the mining dimension but i noticed that everytime i do, the allthemodium ore only gives 1 piece, i even tried to mine an allthemodium ore in the deep dark and it is the same thing, ive played atm9 before and i know fortune enchantment works with the new ores

### latest.log

https://gist.github.com/zoanforte/78071e8debb417773cbc17a64c09320c

**Comment by alekthefirst** [comment]
I am unable to reproduce this
Mining an ore with fortune just gave me 4 raw ores
