### ISSUE TITLE
[Bug]: /curios commands not working [solution available]

### ISSUE THREAD

**Issue by AnimeTeddy** [AllTheMods/ATM-10#1505]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-2.8

### What happened?

If you try to add more curios slots with /curios add (tag) (player) nothing happens. This is already a reported issue on the Adorned (Curios) mod page. 

SOLUTION: Remove mod Adorned (Curios) and replace with Curios API continuation. 

This will fix the commands and nothing will be broken. I just did it for myself in a new instance and it works flawlessly.

![Bild_2024-12-22_144010328](https://github.com/user-attachments/assets/7fb72a7c-a50b-4752-b8c9-d345186e91a1)

**Comment by alekthefirst** [comment]
Suggestion to swap mods was brought forward to team and then promptly denied
