### ISSUE TITLE
[Crash]: Chunk generation server crash after updating to 2.9 

### ISSUE THREAD

**Issue by andremiller** [AllTheMods/ATM-10#1513]
### Possible Fixes

Yes

### Modpack Version

2.9

### What happened?

Running a dedicated server, while exploring the server crashed. I thought perhaps my world file got corrupted and started with a fresh 2.9 install, generated new world, but after logging in and taking a few steps, the server crashed again.

It looks like it could be related to an interaction between Productive Bees (Wood Solitary Nest), XyCraft (DirtFeature) and Farmer's Delight (Rich Soil Giant Tree)

Crash log is uploaded to gisthub, but here is a snippet:

```
Description: Feature placement

java.lang.NullPointerException: Cannot invoke "net.neoforged.neoforge.common.ModConfigSpec$DoubleValue.get()" because the return value of "java.util.Map.get(Object)" is null
	at TRANSFORMER/productivebees@1.21.1-13.6.7/cy.jdkdigital.productivebees.gen.feature.WoodSolitaryNestFeature.place(WoodSolitaryNestFeature.java:28) ~[productivebees-1.21.1-13.6.7.jar%23749!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.feature.Feature.place(Feature.java:168) ~[server-1.21.1-20240808.144430-srg.jar%23483!/:?] {re:mixin,re:classloading,pl:mixin:APP:xycraft_core.mixins.json:DirtFeature from mod xycraft_core,pl:mixin:APP:farmersdelight.mixins.json:KeepRichSoilGiantTreeMixin from mod farmersdelight,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.feature.ConfiguredFeature.place(ConfiguredFeature.java:28) ~[server-1.21.1-20240808.144430-srg.jar%23483!/:?] {re:classloading}
```

### Crash Log

https://gist.githubusercontent.com/andremiller/bfdcc6bb0f2dd1c9280873af94eb2769/raw/8d14bd4e01ff6c5dadf38c1bafd8086af5372512/atm10_crash_report.txt

**Comment by alekthefirst** [comment]
Xycraft and Farmers delight are likely innocents, they just have mixins far up on the stack trace

**Comment by JaisDK** [comment]
can you find the config file in your worlds serverconfig folder called `productivebees-server.toml` and find the segment `[Worldgen]` and add these two values?

```
	cherry_wood_nest = 0.05
	mangrove_wood_nest = 0.05
```

**Comment by jones-g** [comment]
I have a similar crash already on load. Happened during terrain generation and caused the internal server to crash. The world won't load now.

I don't have a productivebees-server.toml in the worlds serverconfig folder - only in the config filter of the instance. Tried editing that but it gets regenerated on launch it seems so changes are mandated to a .bak file.

Tried copying the productivebees-server.toml to the serverconfig folder of the world but this also gets moved to a .bak file and a "correct" version is put in it's place.

**Comment by andremiller** [comment]
> can you find the config file in your worlds serverconfig folder called `productivebees-server.toml` and find the segment `[Worldgen]` and add these two values?
> 
> ```
> 	cherry_wood_nest = 0.05
> 	mangrove_wood_nest = 0.05
> ```

Similar to jones-g, I don't have a productivebees-server.toml in the worlds serverconfig folder, there's only a few files in there, all starting with ftb*.

I've also tried editing the productivebees-server.toml in the ~/config folder, but that got reset during server startup.

In case it helps, I started a new world with a new seed ( -3093124618459941078 ), which ran fine for a few hours, until that too crashed when I explored:

Crash report: https://gist.github.com/andremiller/c4c40f0eadf6973ae48762aba3d1df10

**Comment by JaisDK** [comment]
what do you mean it resets? the game/server has to be closed when you change configs

**Comment by andremiller** [comment]
> what do you mean it resets? the game/server has to be closed when you change configs

The server is stopped/closed when I edit the config file. But when I then start the server, the file is updated during server startup - I can see the timestamp of the config file changes when the server starts up and those lines I added are gone.

**Comment by andremiller** [comment]
An update: I reverted to productivebees-1.21.1-13.6.6.jar on both server and client and the crash went away

**Comment by JaisDK** [comment]
did you indent the new config options to match the existing ones under [Worldgen]?

**Comment by andremiller** [comment]
> did you indent the new config options to match the existing ones under [Worldgen]?

Yes, here is the .bak file the server created of my edited config file:

https://gist.github.com/andremiller/40f6938a9958793ba0745aadc2b2d77c

**Comment by SniSnix** [comment]
I also unfortunately have the same problem, I was playing in a server with 5 other people and after 2 days of playing every time we enter the server it crashes.
I sincerely hope it will be fixed as soon as possible!

**Comment by T4tin** [comment]
> I also unfortunately have the same problem, I was playing in a server with 5 other people and after 2 days of playing every time we enter the server it crashes. I sincerely hope it will be fixed as soon as possible!

It looks like it is fixed in 2.10, but the server file is not out yet.

**Comment by SniSnix** [comment]
I tried again 2 hours ago to open the server, but unfortunately the problem remains, if anyone finds a way to fix it let us know ❤️

**Comment by alekthefirst** [comment]
Fix released with productive bees 13.6.8 in ATM10 2.10

**Comment by jones-g** [comment]
Confirming that it worked for me - loading took a bit longer but I was able to start the world and play for a few hours.

**Comment by SniSnix** [comment]
To me, the server keeps crashing, sad

**Comment by JaisDK** [comment]
share your crash report

**Comment by SniSnix** [comment]
This is the latest crash report, thank you very much for your help!
https://mclo.gs/wdzyU2T

**Comment by JaisDK** [comment]
That's an ender io crash, some item filter

**Comment by SniSnix** [comment]
So if I don't use Ender Io technically it shouldn't crash?
