### ISSUE TITLE
[Bug]: powah gates not working + other issues

### ISSUE THREAD

**Issue by Adam19lol** [AllTheMods/ATM-10#1515]
### Possible Fixes

Yes

### Modpack Version

ATM10-2.9

### What happened?

So the problems started after the 2.8 update but still remains in 2.9. I tried to use the Powah ender gates for wireless power transfer but no matter what i do, they not accepting any power from any block. I tried them in claimed chunks and unclaimed chunks too.

Other issues:
-Allthemodium source jar recipe not working
-Allthemodium bow recipe not exist (i guess this will be added later)
-Mekanism energy cubes sometimes buggy (like they not input/output power on the right side where i set them to do. Sometimes they act like the sides in the cube's config are mirrored? Like set to input on top but inputs from the bottom? I'm sure i experienced something like this.)

I tried to reinstall the pack and load back the backup. Not helped  :/

**Comment by alekthefirst** [comment]
Have you added energy storage to your powah channels?

Allthemodium source jar recipe seems to work just fine
https://github.com/user-attachments/assets/72b69d33-2439-4c9e-a579-3b992fbb0db5

Allthemodium bow is a "maybe in the future" kinda thing

Mekanism energy cube likes to remember the previously used config, but the sides are relative to the position of the user when the block was placed, so it can get confusing

**Comment by Adam19lol** [comment]
Some pictures for better understanding of the problems
![image](https://github.com/user-attachments/assets/cb084729-e517-4af6-9b3d-49593e86bc6a)
![image](https://github.com/user-attachments/assets/722c1b87-7f2e-4865-bbe3-f1ae0a62172a)
(changing the modes between extract/recieve/both also does nothing)

![image](https://github.com/user-attachments/assets/0515fb2d-1b17-4431-88a3-3d06d4f61980)
I tried the allthemodium source jar recipe (with both unobtainium and silent unobtainium plates) They don't work.
![image](https://github.com/user-attachments/assets/c594370f-dcdc-4c97-905b-ba46d2344518)
Same thing when i try to craft the Focus of Air
I was unable to recreate the problem with the energy cubes.

**Comment by alekthefirst** [comment]
Your powah setup does not have any energy storage in the channels, you need to add batteries inside to be able to move energy with powah ender cells and gates

For allthemodium source jar it needs to be normal ingots, and still i cannot reproduce this issue you have where it doesn't work

**Comment by Adam19lol** [comment]
> Have you added energy storage to your powah channels?
> 
> Allthemodium source jar recipe seems to work just fine https://github.com/user-attachments/assets/72b69d33-2439-4c9e-a579-3b992fbb0db5
> 
> Allthemodium bow is a "maybe in the future" kinda thing
> 
> Mekanism energy cube likes to remember the previously used config, but the sides are relative to the position of the user when the block was placed, so it can get confusing

For me the ars crafting recipes doesn't work. I don't know why but it keep saying no pedestals in rang...... wait wtf. I replaced the setup and it kept saying no recipe. Than i moved it away to another place (still in the same chunk) and now everything fine? WHAT?! (Yeah moving it back to it's original place is still wrong). Ok, now i really don't know what is going on...

The mekanism cube thing... yeah it makes sence now, i totally forgot about that. But the Powah gates still not working (i placed batteries in everything). The energy storage is a hardened energy cube, but it still can't work. Do you have any other ideas what could be the problem?

**Comment by alekthefirst** [comment]
Powah can be unreliable when it comes to pushing energy, does it work if you replace the hardened energy cube with something from a different mod?

**Comment by Adam19lol** [comment]
> Powah can be unreliable when it comes to pushing energy, does it work if you replace the hardened energy cube with something from a different mod?

No. I tried with different tiers, mekanism cube too, extracting energy from a generator but nothing.

**Comment by rhullah** [comment]
> But the Powah gates still not working (i placed batteries in everything).

Did you shift-click the battery in? If so your ender gate/cell should no longer say "0/0 FE".

**Comment by Adam19lol** [comment]
> > But the Powah gates still not working (i placed batteries in everything).
> 
> Did you shift-click the battery in? If so your ender gate/cell should no longer say "0/0 FE".

It never said 0/0 FE. It's always 0/(the battery's kapacity). So basically, it's still empty and not accepting energy.

**Comment by Adam19lol** [comment]
I figured it out. It needs to be an ender cell and in there i need to add the energy cube with shift right click! Thanks for everyone who tried to help me!
(That ars nouveau issue was still confusing asf lol)

Have a great day!
