### ISSUE TITLE
[Crash]: Game crashes when I activate the piston

### ISSUE THREAD

**Issue by AnatoliiKostenko** [AllTheMods/ATM-10#1518]
### Possible Fixes

Yes

### Modpack Version

1.27

### What happened?

Game crashes when I activate the piston.

### Crash Log

<script src="https://gist.github.com/AnatoliiKostenko/fed17cf030f2402e48e1716af860bb08.js"></script>

**Comment by alekthefirst** [comment]
This is a known issue with ftb chunks, and has already been fixed
Update to any version newer than the one you're on to alleviate this crash, or altearnatively if you really want to stay on 1.27, disable piston protection in ftbchunks-world.snbt, which can be found in the serverconfig folder of your save
