### ISSUE TITLE
[Feature]: add a tool tip to the easyvillagers trader block_item

### ISSUE THREAD

**Issue by demonicreaper666** [AllTheMods/ATM-10#1527]
### Feature Details

to have a tool tip added to the easy villagers trader block(s) in item form, that tells you 

> **_right click workstation on this block to allow trade restocking_**

**Comment by alekthefirst** [comment]
For clarification you are referring to this block yeah?
![image](https://github.com/user-attachments/assets/aa899d54-d733-432a-9efa-6c41f1a9940b)

**Comment by demonicreaper666** [comment]
Yes that is correct
