### ISSUE TITLE
[Bug]: Infinite Ham impossible to eat

### ISSUE THREAD

**Issue by Zlababababan** [AllTheMods/ATM-10#1528]
### Possible Fixes

Yes

### Modpack Version

2.10

### What happened?

Hello, after I update my server from version 2.8 to 2.10, the infinite ham became impossible to eat
I tried an a fresh singleplayer world and I had the same issue

I also tried the mods on it's own with only artifacts and "Relics: Artifacts Compat" (with their associated libraries) and it did not work

**Comment by alekthefirst** [comment]
The ham has received a rework and you need to unlock the regeneration ability then wait for the ham to charge a bit before its edible

**Comment by alekthefirst** [comment]
Video of ham totally being edible
https://github.com/user-attachments/assets/51df467e-a651-4391-a5e0-2f83974025ed

**Comment by Zlababababan** [comment]
Thank you for your answer. I was wondering what I was doing wrong
