### ISSUE TITLE
[Crash]: Occultism crash when trading with Otherworld Sapling Trader

### ISSUE THREAD

**Issue by Damozgit** [AllTheMods/ATM-10#153]
### Possible Fixes

Yes

### Modpack Version

0.19

### What happened?

while "trading" with the Foliot my game immediately crashed and crashes every time the world loads

### Crash Log

https://gist.github.com/Damozgit/a3ee933d1ca525a28ae968ff54dba0fa

### Latest.Log

https://gist.github.com/Damozgit/1940858bea8cd630a6cea1f00eba5cec

**Comment by TheBedrockMaster** [comment]
Do you know if this crash still occurs on the current release?
