### ISSUE TITLE
[Feature]: Apotheosis Salvagin Table

### ISSUE THREAD

**Issue by Malty44** [AllTheMods/ATM-10#1542]
### Feature Details

It would be nice if we could pipe items into the salvaging table like in ATM9. Are there any plans to reimplement this feature?

**Comment by Mitchell5200** [comment]
that was a base Apotheosis feature in mc 1.20, ask the mod dev if they intend to return it for 1.21

**Comment by doggoboiwastaken** [comment]
Just adding something-- I spoke to shadow and he said that 8.0.1 (latest apotheosis version) has this feature. I assume he just forgot it in the initial release. If you manually replace 8.0.0 with 8.0.1, it should work.

**Comment by TheBedrockMaster** [comment]
Confirmed as a bug by the dev. Fixed in Apotheosis 8.0.1.
