### ISSUE TITLE
[Crash]: Server won't start after updating to 2.11

### ISSUE THREAD

**Issue by rushcodes** [AllTheMods/ATM-10#1549]
### Possible Fixes

Yes

### Modpack Version

2.11

### What happened?

I updated my server to 2.11 by:

1. Downloading the new zip, extracting to new folder
2. Ran java -jar *.jar --installServer
3. Made a backup of my previous install
4. Deleted the following folders from my previous install: config, defaultconfig, mods, kubejs, libraries
5. Copied the new files with cp -R * ../serverfiles/
6. Started the server again

After starting the server, it seems to error out pretty quickly and shuts itself down right away.

No crash report is generated, however I will attach the latest.log

### Crash Log

https://gist.github.com/rushcodes/25a192a7ba5d6eef594d1a7ff13f4429

### Latest.Log

https://gist.github.com/rushcodes/25a192a7ba5d6eef594d1a7ff13f4429

**Comment by alekthefirst** [comment]
`java.io.FileNotFoundException: ./config/modernfix-mixins.properties (Permission denied)`
Permissions issues on the files, which has been a problem with some of our recent server packs

**Comment by alekthefirst** [comment]
Command for how to assign proper permissions can be found in https://github.com/AllTheMods/ATM-10/issues/1489

**Comment by rushcodes** [comment]
That fixed it, thank you

**Comment by Oleika009** [comment]
In #1489 is this the correct command to execute? : chmod -R +rw <server directory>
If yes, where do I have to execute it?
