### ISSUE TITLE
[Crash]: Pipe Upgrade Failure

### ISSUE THREAD

**Issue by LittleMonkeyJump** [AllTheMods/ATM-10#155]
### Possible Fixes

Yes

### Modpack Version

0.19

### What happened?

When I go to a pipe upgrade I have installed inside of a pipe. I attempt to change the Distribution setting, immediately once I click to change the setting I get kicked from the game. Will not let me back into the game for at least an hour.

### Crash Log

https://github.com/user-attachments/files/16369300/disconnect-2024-07-24_20.58.49-client.txt

**Comment by alekthefirst** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/127
Fixed in Pipez 1.21-1.2.17, released with ATM10 0.21
