### ISSUE TITLE
[Bug]: Not enough source for crafting unobtanium-allthemodium block

### ISSUE THREAD

**Issue by Ghester18** [AllTheMods/ATM-10#1553]
### Possible Fixes

Yes

### Modpack Version

2.11

### What happened?

Getting message not enough source while attempting to craft unobtanium-allthemodium block, even with 12 full source jars and me source jar
![image](https://github.com/user-attachments/assets/6657b5ce-2a0f-48c6-b1c6-a9c5c3616c9f)
![image](https://github.com/user-attachments/assets/b438a4bb-7813-44b9-826f-2147e5c9bd9f)
![image](https://github.com/user-attachments/assets/fdd9024e-52d8-4641-bd60-30b813d35f4a)

**Comment by alekthefirst** [comment]
The enchanting apparatus can only check one source jar for recipe fulfillment and this is why Allthemodium source jar that can store 100k source exists, it is required for this recipe.
