### ISSUE TITLE
[Bug]: Unusing is always "too expensive"

### ISSUE THREAD

**Issue by IBilliamI** [AllTheMods/ATM-10#156]
### Possible Fixes

Yes

### Modpack Version

0.19

### What happened?

the unusing enchantment book I grabbed off of a sword using the dis enchantment table can not be applied to anything I've tried to use it on. including a completely nbt void weapon. it always displays a "too expensive" message

**Comment by IBilliamI** [comment]
i also tried this in another world on creative mode and it costs 50 levels then tells me too expensive if I switch to survival and try the same thing. unusing can not possibly be worth that much on an empty sword

**Comment by jason13official** [comment]
Hi, I'm the developer of for Dis-Enchanting Table. Do you know which mod the Unusing enchantment comes from?

**Comment by IBilliamI** [comment]
I don’t. The book just says Minecraft as the mod, and I also had problems
with the enchantment when I grabbed it directly out of a creative menu so i
don’t think it was your mod’s fault.

**Comment by jason13official** [comment]
Thank you for the response; I hope the issue gets resolved soon!

**Comment by IBilliamI** [comment]
Thanks, me too lol

**Comment by Mitchell5200** [comment]
@jason13official  the Unusing enchant is from Evilcraft i believe

**Comment by IBilliamI** [comment]
Ftb wiki says that too so if evil craft is in the pack I imagine you’re
right
