### ISSUE TITLE
[Feature]: Server Pack for v2.12

### ISSUE THREAD

**Issue by xKOBAYASHIMARUx** [AllTheMods/ATM-10#1574]
### Feature Details

Kinda a mix between a bug and a feature, there doesn't appear to be a server pack uploaded with the v2.12 upload.

Also just as an aside, the "Best Enchanting set-up" quest (the final quest in the Apothic Enchanting line) seems to be incorrect? All the bookshelves called for do not produce a 100/100/100 enchanting table. Rather a 95/100/80 table. I didn't math it out or anything but adding another heart-forged seashelf did the trick!

**Comment by alekthefirst** [comment]
Curseforge has the server files under review. Nothing more that can be done about it

**Comment by xKOBAYASHIMARUx** [comment]
Understood, thanks for the update!
