### ISSUE TITLE
[Bug]: Server disconnect while trying to trade with Wandering Trader

### ISSUE THREAD

**Issue by Wuerfelhusten** [AllTheMods/ATM-10#1575]
### Possible Fixes

No

### Modpack Version

2.11

### What happened?

I always disconnect from my server while trying to trade with the same wandering trader. Does not happen to other ones for now.

[disconnect-2024-12-27_16.55.17-client.txt](https://github.com/user-attachments/files/18261937/disconnect-2024-12-27_16.55.17-client.txt)

### latest.log

https://gist.github.com/Wuerfelhusten/407df13202b851e85fb1da70091cbe2a

**Comment by alekthefirst** [comment]
Known bug in iron's jewlery, recommend downgrading to atm10 2.10 or updating to 2.12
Duplicate of #1540

**Comment by TheBedrockMaster** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1540
