### ISSUE TITLE
[Feature]: Apotheosis Update v8.0.1

### ISSUE THREAD

**Issue by ZFCyber1** [AllTheMods/ATM-10#1576]
### Feature Details

This update fixes a bug where pipes cannot be used with the Salvaging Table for automating Gem Dust and the various rarities. More information here: https://github.com/Shadows-of-Fire/Apotheosis/blob/1.21/changelog.md

**Comment by alekthefirst** [comment]
There's no need to tell us about mod updates, we are aware

**Comment by TheBedrockMaster** [comment]
Mods get updated as the pack does, this will be included in the next release.

**Comment by TheBedrockMaster** [comment]
I'll close this when it comes to the pack.
