### ISSUE TITLE
[Bug]: Constantly "Dying" after taking damage. 2.12 as well as 2.10

### ISSUE THREAD

**Issue by Giorgio1234** [AllTheMods/ATM-10#1578]
### Possible Fixes

Yes

### Modpack Version

2.12

### What happened?

Whenever I take any amount of damage, the game seems to think I've died, leaving me with no hearts and constantly "shaking" as if taking damage. This was happening in the 2.10 version as well as in the 2.12 version. This happens independently of me being a server operator or not. Video attached below recreating the problem. /heal seems to be the only thing that fixes it.

https://github.com/user-attachments/assets/85fb5324-15fa-44b2-b759-e081c76e98d7

https://github.com/user-attachments/assets/3745df44-448f-4f05-9cf5-bc7fcb3553ca

https://github.com/user-attachments/assets/066a39b0-0db9-4210-a9ea-917625a597cd

EDIT: It does not happen to other players on the server

### latest.log

https://gist.github.com/Giorgio1234/1c9aff92c397bf015650f2ac3cf87f13

**Comment by Giorgio1234** [comment]
Something to add is that it does not happen to other players on the server

**Comment by alekthefirst** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/154
Potential fix by adding mod also in that thread

**Comment by Giorgio1234** [comment]
> Duplicate of #154 Potential fix by adding mod also in that thread

Thank you. I had not come across this whilst creating the issue. Is the mod server-side only?

**Comment by Giorgio1234** [comment]
As per @alekthefirst 's recommendation, I've fixed the issue. As outlined in #154 , the [NaNny mod](https://www.curseforge.com/minecraft/mc-mods/nanny) installed serverside has fixed it.

**Comment by TheBedrockMaster** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/154
