### ISSUE TITLE
[Crash]: Mod 'architectury' is not available

### ISSUE THREAD

**Issue by TSSDK** [AllTheMods/ATM-10#158]
### Possible Fixes

Yes

### Modpack Version

0.20

### What happened?

When starting the client, the game returned to the launcher with an error. When only ON mod architecture all ok

### Crash Log

https://gist.github.com/TSSDK/f0d939b3d450dffbc1134678de225e6b

### Latest.Log

https://gist.github.com/TSSDK/7c8a504c3931571e1ae27f758fc8ea1e

**Comment by alekthefirst** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/130
Though given the age of the issue, unlikely to see a resolution

**Comment by TheBedrockMaster** [comment]
See https://github.com/architectury/architectury-api/issues/528 and https://github.com/Draylar/omega-config/issues/26

**Comment by TheBedrockMaster** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/130

**Comment by TheBedrockMaster** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/130
