### ISSUE TITLE
[Bug]: Weird Barrel

### ISSUE THREAD

**Issue by RegulusImpact99** [AllTheMods/ATM-10#1618]
### Possible Fixes

Yes

### Modpack Version

2.13

### What happened?

When I added a redstone torch to a barrel in crafting table for the sophisticated storage recipe then added another afterward, and a third time it changed the barrel into something weird and placeable causing a graphical glitch. 
![Screenshot 2024-12-30 093355](https://github.com/user-attachments/assets/62640292-759e-49de-8314-99798629b7fe)

**Comment by P3pp3rF1y** [comment]
Yesterday I added a check to only allow using full blocks as barrel materials. So just updating sophisticated storage should be enough to close this
