### ISSUE TITLE
[Bug]: Creative energy cube trash

### ISSUE THREAD

**Issue by Derneka** [AllTheMods/ATM-10#1625]
### Possible Fixes

No

### Modpack Version

2.11

### What happened?

Creative energy cube transform any count of energy into nothing

**Comment by Mitchell5200** [comment]
For Mekanism? it's always been like that, it's not a storage block, but when you energize it with the atm star it them becomes a Creative RF supplier.

**Comment by Derneka** [comment]
thanks for answer
