### ISSUE TITLE
[Bug]: HUD Problem

### ISSUE THREAD

**Issue by Derneka** [AllTheMods/ATM-10#1626]
### Possible Fixes

No

### Modpack Version

2.11

### What happened?

Does anybody knows how to fix that HUD error? Similar things happens in Iron Furnaces HUD and all ME terminals
![image](https://github.com/user-attachments/assets/3f90e81e-622b-488c-973d-a3e79490f45b)

**Comment by MarhzyyMC** [comment]
Only thing you can do to fix it at the moment is to reload your resource packs (F3+T).
Dupe with #1320 & #1494.

**Comment by Derneka** [comment]
> Only thing you can do to fix it at the moment is to reload your resource packs (F3+T). Dupe with #1320 & #1494.

thanks alot

**Comment by TheBedrockMaster** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/1320
