### ISSUE TITLE
[Bug]: Ruby seeds are not craftable

### ISSUE THREAD

**Issue by PocketSkeleton** [AllTheMods/ATM-10#1629]
### Possible Fixes

Yes

### Modpack Version

2.13

### What happened?

Ruby seeds from Mystical Agriculture are not craftable, using the same set up for dirt seeds and ruby seeds, following the recipe from JEI, ruby seeds simply dont craft.
![image](https://github.com/user-attachments/assets/7be7216c-e6e6-4f55-a3fa-ec9f6312d3ed)
![image](https://github.com/user-attachments/assets/a0193389-e3f6-4f23-b227-dabbbac4c2b1)

### latest.log

https://gist.github.com/PocketSkeleton/cb4740c1fa8240dd30bfde31aa8bc47c

**Comment by TheBedrockMaster** [comment]
It’s a known bug that sometimes some seeds just don’t craft for some people, I’m not sure how to fix it.
