### ISSUE TITLE
[Crash]: Network Protocal error.

### ISSUE THREAD

**Issue by NJM1564** [AllTheMods/ATM-10#164]
### Possible Fixes

No

### Modpack Version

10-0.19

### What happened?

/home d and crash.
Debug
https://gist.github.com/NJM1564/299f13fa18688f12743eb57972a135aa

Crash Log: Last crash was from hours ago.

Latest log.
[26Jul2024 00:02:07.613] [Render thread/INFO] [MonoLib/]: This line is printed by an cursee mod mixin from NeoForge!
[26Jul2024 00:02:07.641] [Render thread/INFO] [MonoLib/]: MC Version: release

### Crash Log

Unrelatted

### Latest.Log

Short log. In exsplanation.

**Comment by avsg1rl** [comment]
Only happened on occasion with .19 but it happening every time with .20. Same situation.

**Comment by alekthefirst** [comment]
Fixed in Powah 6.0.6-beta, released with ATM10 0.21
