### ISSUE TITLE
[Bug]: Pocket Storage resets item durability.

### ISSUE THREAD

**Issue by instinxx** [AllTheMods/ATM-10#165]
### Possible Fixes

Yes

### Modpack Version

.18 / .19

### What happened?

Players on my server discovered that when you place an item that has durability (Weapons / Armor / tools) into a pocket storage, it resets the durability to max, essentially repairing them. It also wipes any enchants from the item(s).

### Developer reports

https://github.com/Flanks255/pocketstorage/issues/26

**Comment by DaddyLongspoon** [comment]
actually deletes all metadata.  an enchanted book will become useless, any potion will become 'uncraftable potion'...
use it only for cobble and whatnot when you're mining, its not a reliable backpack

**Comment by instinxx** [comment]
This was closed https://github.com/Flanks255/pocketstorage/issues/26
