### ISSUE TITLE
[Bug]: Eternal water block is uncraftable

### ISSUE THREAD

**Issue by F7albert-tech** [AllTheMods/ATM-10#168]
### Possible Fixes

Yes

### Modpack Version

10-0.20

### What happened?

The Eternal water is uncraftable. Apear to be missing a tag.
![image](https://github.com/user-attachments/assets/aa9a254b-1d7c-4830-9741-001049dea9bf)

**Comment by MrLoLf** [comment]
This has been fixed in EvilCraft-1.21-neoforge-1.2.48.jar so it would be great to update to the newest version of Evil Craft

**Comment by MrLoLf** [comment]
This has been fixed @F7albert-tech and can now be closed as ATM 10 version 0.24 has now the fix implemented!
