### ISSUE TITLE
[Bug]: TrashCans

### ISSUE THREAD

**Issue by Riggs1965** [AllTheMods/ATM-10#172]
### Possible Fixes

Yes

### Modpack Version

0.20

### What happened?

Using trash can to void items from ME network caused "Network Protocol Error" kick from server (ATM10 patron server)

### latest.log

https://gist.github.com/Riggs1965/65138567053af94962305779a9c9a634

**Comment by LevyWilson** [comment]
I think our bugs are the same issue. #166 
It happened again today when a player clicked the filter icon. I am having to bring the server down and rollback otherwise no one can join.

**Comment by Riggs1965** [comment]
> I think our bugs are the same issue. #166 It happened again today when a player clicked the filter icon. I am having to bring the server down and rollback otherwise no one can join.

Sounds about right, however im the only one who cannot join this server. Unless its just when those chunks get loaded/players loading those chunks

**Comment by Riggs1965** [comment]
Duped issue. Linked above
