### ISSUE TITLE
[Bug]: IntegratedDynamic problems

### ISSUE THREAD

**Issue by Andrelyse** [AllTheMods/ATM-10#174]
### Possible Fixes

Yes

### Modpack Version

0.20

### What happened?

I.D network and when you put in enchanted books or item the system breaks down. You then need to find witch one chest it went into and take it out manualy for the system to start working again.
Looks like same thing happens when you put in some villagers also.

**Comment by alekthefirst** [comment]
Fixed in CommonCapabilities 2.9.3 released with ATM10 0.30
