### ISSUE TITLE
[Bug]: Furnace augments duplication glitch

### ISSUE THREAD

**Issue by MatteoPL** [AllTheMods/ATM-10#18]
### Possible Fixes

Yes

### Modpack Version

0.2

### What happened?

I want to apply speed augment to my gold furnace and when I start spamming right mouse button stacks of augments start dropping on the ground (I crafted only one augment).

**Comment by frogalo** [comment]
replicable. Happened to me as well on version 0.3

**Comment by frogalo** [comment]
also all augments are getting dupped not only speed

**Comment by Kevin-Marsh** [comment]
Reported to the dev and awaiting a fix.
