### ISSUE TITLE
[Crash]: ATM10 server crash on startup

### ISSUE THREAD

**Issue by Thrystan01204** [AllTheMods/ATM-10#180]
### Possible Fixes

Yes

### Modpack Version

0.23

### What happened?

Starting a server using the [itzg/docker-minecraft-server](https://docker-minecraft-server.readthedocs.io/en/latest/) the pack crash on statup.
Removing the mod Iceberg allowed the server to start properly (from the [page](https://www.curseforge.com/minecraft/mc-mods/iceberg) it says it is usable both server and client side, is this bad to remove it server side ?).

### Crash Log

https://gist.github.com/Thrystan01204/c38525f4a672ff580a50acc6796baa5f

### Latest.Log

https://gist.github.com/Thrystan01204/f20f399f02e0d6cbad1e313a198d674c

**Comment by zordem** [comment]
i have it disabled too... there was an update recently. i might give it a try again.
