### ISSUE TITLE
[Crash]: Ars Nouveau causing crashes

### ISSUE THREAD

**Issue by ThatColdFridge** [AllTheMods/ATM-10#184]
### Possible Fixes

Yes

### Modpack Version

ATM 10 0.23

### What happened?

When creating an Ars Nouveau spell glyph using the Scribe's Table it crashes the server shortly after selecting the desired glyph.

### Crash Log

https://gist.github.com/ThatColdFridge/566690fd8ce2d8f002fae377ffe6baa8

### Latest.Log

I am using Exaroton servers to host and cannot find a "Latest.log" anywhere in the files. Apologies if this is a needed thing.

**Comment by alekthefirst** [comment]
I am unable to determine which version of ars noveau this was fixed in, but it has been fixed
