### ISSUE TITLE
[Bug]: Quest achievement when crafting Fluix ME Covered Cable from AE2

### ISSUE THREAD

**Issue by samuel-casasdray** [AllTheMods/ATM-10#185]
### Possible Fixes

Yes

### Modpack Version

0.21

### What happened?

When you craft one Fluix ME Covered Cable from AE2 you get spam that you complete all quest from the AE2 page. 

### latest.log

https://gist.github.com/samuel-casasdray/26764f40f04794e52e003893e9a0dbfc

**Comment by TheBedrockMaster** [comment]
I can't reproduce this in game.
