### ISSUE TITLE
[Crash]: solo server crash on new chunk generation

### ISSUE THREAD

**Issue by GrommKrumh** [AllTheMods/ATM-10#186]
### Possible Fixes

Yes

### Modpack Version

0.23

### What happened?

after updating the modpack to 0.23 from 0.21 the solo server would crash when creation new chunk and creating new world crash as well

### Crash Log

https://gist.github.com/GrommKrumh/2bbf467a2333fb194df445a476b624c6

### Latest.Log

https://gist.github.com/GrommKrumh/13e4e8734a79b461e5fbb28c6c989ed4

**Comment by alekthefirst** [comment]
Fixed in ID 1.23.3 released with ATM10 0.37
