### ISSUE TITLE
Items not Equipable in Curios Slots

### ISSUE THREAD

**Issue by DaddyLongspoon** [AllTheMods/ATM-10#187]
### Possible Fixes

Yes

### Modpack Version

10.0.23

### What happened?

Items which historically have been equipable to a curios slot but which are not in current build of atm10.  I am compiling a list in hope that when somebody has time to look at it they can do the lot :) please do comment up others as you see them. :)

- [ ] evilcraft:effortless_ring
- [x] evilcraft:vengeance_ring
- [x] evilcraft:invigorating_pendant
- [x] evilcraft:primed_pendant
- [ ] evilcraft:spectral_glasses
- [x] hostileneuralnetworks:deep_learner
https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/issues/61
- [x] occultism:satchel
- [x] occultism:otherworld_goggles
- [x] occultism:storage_remote
- [x] simplemagnets:basicmagnet
- [x] simplemagnets:advancedmagnet
- [ ] toolbelt:belt

**Comment by Satherov** [comment]
Just as a reminder, the tool belt has its own slot. Look in the keybinds for how to access it

**Comment by TheBedrockMaster** [comment]
> Just as a reminder, the tool belt has its own slot. Look in the keybinds for how to access it

The suggestion is still to be able to put it in Curios as well, like in ATM9. Also there are other things on the list that haven't been added or stated they're not planned.

**Comment by Satherov** [comment]
> > Just as a reminder, the tool belt has its own slot. Look in the keybinds for how to access it
> 
> 
> 
> The suggestion is still to be able to put it in Curios as well, like in ATM9. Also there are other things on the list that haven't been added or stated they're not planned.
> 
> 

I tried adding all the items mentioned here, but all those ones that were skipped, no longer work when in curio, so I closed it

**Comment by DaddyLongspoon** [comment]
> > Just as a reminder, the tool belt has its own slot. Look in the keybinds for how to access it
> 
> The suggestion is still to be able to put it in Curios as well, like in ATM9. Also there are other things on the list that haven't been added or stated they're not planned.

Well I didn't know anything about this!!. (I'm on a second play thru now and I see it's in the item description now). Its own secret slot is even better of course because you could wear some second belt as well, get your bon Jovi on.  Thank you to you two champions for looking out for this issue long after it was closed, and also for taking care of my silent gear related thing..   https://github.com/AllTheMods/ATM-10/issues/807#issuecomment-2423103889
