### ISSUE TITLE
[Crash]: Server crash when player died on a broom

### ISSUE THREAD

**Issue by LevyWilson** [AllTheMods/ATM-10#188]
### Possible Fixes

Yes

### Modpack Version

0.23

### What happened?

Happened on my multiplayer server. Player states they crashed in the Nether, server crashed with the attached crashlog. Server started back up without a problem and I teleported to their location to figure out what happened. Player is unable to log back in and is continuously being disconnected. I was able to load in the chunk they crashed in. It appears the crash might have been caused by some sort of compatibility issue between the grave mod and the evilcraft mod.

![2024-08-02_03 07 23](https://github.com/user-attachments/assets/5c5349ff-1485-47de-9563-bb67080a9e04)

The crash log is from the server and the text in the latest.log is the disconnect log from the player's debug folder. We rolled the server back. They are still having issues connecting.

Edit: Player had to reinstall ATM 10 and reset their router before they could reconnect. Not sure if that's related to the server crash.

### Crash Log

https://gist.github.com/LevyWilson/bf8d89259193d71e058bfce5a0a3103e

### Latest.Log

https://gist.github.com/LevyWilson/c34bff3ba13be0e60c91e1845076b9a6

**Comment by alekthefirst** [comment]
Gravestone mod was removed with ATM10 1.0
