### ISSUE TITLE
[Bug]: Redstone dupe method

### ISSUE THREAD

**Issue by john13210** [AllTheMods/ATM-10#190]
### Possible Fixes

Yes

### Modpack Version

0.23

### What happened?

1.Craft Raw Redstone Block
2.Process it in the machine that gives you more than 4 redstone from it
3.Craft more Raw Redstone Blocks
4.Repeat 

For some reason this cheap to make block is treated as an ore, might be intentional by author but idk 
reported it to them too : https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/issues/178

**Comment by john13210** [comment]
dont know if this one is the correct autohors github for 1.21 version

**Comment by lorenashfield** [comment]
Can confirm this still works on 0.30. Best option would be to disable crafting Raw Redstone Block.
