### ISSUE TITLE
[Crash]: When opening Extended Inscriber

### ISSUE THREAD

**Issue by Mark2-0** [AllTheMods/ATM-10#191]
### Possible Fixes

Yes

### Modpack Version

ATM10 0.24

### What happened?

When opening the Extended Inscriber I'm immediately crashed out to the menu with the following error

Failed to open a screen with advanced data: java.lang.NoSuchFieldError: Class appeng.client.gui.Icon does not have member field 'appeng.client.gui.Icon INSCRIBER_BUFFER_HIGH

Game does not fully close just back to main menu

### Crash Log

https://gist.github.com/Mark2-0/39b99a71ad494559b919c6b200296794

### Latest.Log

https://gist.github.com/Mark2-0/1264647bca3c47fada6f27b53f7bf08d

**Comment by alekthefirst** [comment]
Fixed with Extended AE 1.2.1, released in ATM10 0.26
