### ISSUE TITLE
[Bug]: I Can't install new version

### ISSUE THREAD

**Issue by KzKush** [AllTheMods/ATM-10#194]
### Possible Fixes

No

### Modpack Version

ATM10

### What happened?

this error appear when i try update for new version. ( No Java executable found. Cannot execute post-installation tasks for forge. )

**Comment by shade1822226911** [comment]
if you're using the curseforge app, press the 3 dots next to the minecraft search bar and click on "repair installation". works for me

**Comment by MistyTheFox** [comment]
> if you're using the curseforge app, press the 3 dots next to the minecraft search bar and click on "repair installation". works for me

You are a goat
