### ISSUE TITLE
[Bug]: Pocket Storage duplicates items

### ISSUE THREAD

**Issue by RRanar** [AllTheMods/ATM-10#198]
### Possible Fixes

Yes

### Modpack Version

0.26

### What happened?

With Pocket storage MK3 when have only 1 item in there and same item in invertory could duplicates items with Shift+Left click on item in inventory
OS: Arch Linux 6.10.2-arch1-2
Launcher: ATlauncher 3.4.36.10-1

### latest.log

https://paste.atlauncher.com/view/9b8d8948-1cf2-4a9c-94ce-e80f7b136d4f

**Comment by instinxx** [comment]
Fixed as per dev - https://github.com/Flanks255/pocketstorage/issues/30
