### ISSUE TITLE
[Bug]: Item Duplication Glitch

### ISSUE THREAD

**Issue by instinxx** [AllTheMods/ATM-10#199]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-0.26

### What happened?

Using Pocket Storage, if you have an item in your Pocket Storage and shift Rt click more of that item from your personal inventory, it duplicates the item into PS and does not remove from you inv.

This was reported to the mod author

### Developer reports

https://github.com/Flanks255/pocketstorage/issues/30

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/198
