### ISSUE TITLE
[Bug]: mekanism oredict/MI oredict related to liqued steam incompatibility

### ISSUE THREAD

**Issue by minecrafterseppe** [AllTheMods/ATM-10#20]
### Possible Fixes

Yes

### Modpack Version

0.2-0.3

### What happened?

mekanism "liqued steam" cannot be used in
 MI steam turbines
![image](https://github.com/AllTheMods/ATM-10/assets/13523046/9d5b2a6c-3ab1-4bb0-a604-bdf2d69bfec4)
![image](https://github.com/AllTheMods/ATM-10/assets/13523046/67615b20-2d6d-4da5-8bea-e3269b9b9ec7)

**Comment by Kevin-Marsh** [comment]
Mi and mekanism aren't cross compatible.
