### ISSUE TITLE
[Bug]: Experience Comb Centrifuge Recipe Broken

### ISSUE THREAD

**Issue by shinyCranidos** [AllTheMods/ATM-10#200]
### Possible Fixes

No

### Modpack Version

0.27

### What happened?

The experience comb produced by the experience bee does not have a centrifuge recipe unlike all of the other combs.  It cannot currently be processed in to Bottle O' Enchanting like it used to be able to.

Here is what the experience combs crafting recipe currently looks like.
![2024-08-04_14 21 39](https://github.com/user-attachments/assets/17e66135-8ae2-481c-b430-198d20729899)
![2024-08-04_14 21 45](https://github.com/user-attachments/assets/fbfa935e-634b-4f9a-b86b-2eb539d5de05)

and here is what a working comb recipe looks like(glowing comb)
![2024-08-04_14 23 28](https://github.com/user-attachments/assets/c6509f34-724c-4408-9eeb-e895127c5a40)
![2024-08-04_14 23 35](https://github.com/user-attachments/assets/4db5c3be-f5e5-4c7e-b8b2-9e602ef6d1b1)

**Comment by JaisDK** [comment]
fixed
