### ISSUE TITLE
[Bug]: The game crashed whilst exception in server tick loop

### ISSUE THREAD

**Issue by QuanHai2211** [AllTheMods/ATM-10#201]
### Possible Fixes

Yes

### Modpack Version

0.27

### What happened?

![image](https://github.com/user-attachments/assets/7a436cdc-b6b9-4243-bada-ee0b208ba98e)

### latest.log

https://gist.github.com/QuanHai2211/cbefa14445ad7693ba0c877bbc6fb872

**Comment by alekthefirst** [comment]
Concurrent Modification Exception crashes generally can't be properly diagnosed with just a latest.log, but several of them have been identified and fixed in the time passed since this report and i believe it is safe to close this.
