### ISSUE TITLE
[Bug]: pocket Storage unit duplication

### ISSUE THREAD

**Issue by MikeIsSexy** [AllTheMods/ATM-10#202]
### Possible Fixes

Yes

### Modpack Version

0.27

### What happened?

Ever since version 0.25, there was a glitch with the pocket storage unit, where items are being duplicated under certain conditions. 

When you use Pocket Storage, you place one item in the unit and then shift-right-click additional of that item from your personal inventory. This copies the item into the pocket storage unit, which you can repeat until the maximum amount is removed.

**Comment by instinxx** [comment]
Duplicate issue - #199
Fixed as per dev - Flanks255/pocketstorage#30
