### ISSUE TITLE
[Bug]: Player can't connect after breaking Ars lectern

### ISSUE THREAD

**Issue by LevyWilson** [AllTheMods/ATM-10#203]
### Possible Fixes

Yes

### Modpack Version

0.23

### What happened?

Player states while moving items around in their storage, and with items on the ground around them, they broke their Ars lectern and lost connection to the game. Every attempt to log into the server lead to an immediate disconnect with "connection reset" message. I'll attach the two files I have for debugging as well as the effected inventory .dat files. Player's inventory was reverted to a backup and they can connect again.

[playerdata.zip](https://github.com/user-attachments/files/16491915/playerdata.zip)

### latest.log

https://gist.github.com/LevyWilson/e85b9d13700a533b0395dc332b1db4c8

**Comment by alekthefirst** [comment]
Fixed with Ars Noveau 5.0.7 released in ATM10 0.29
