### ISSUE TITLE
[Crash]: Servers crash randomly dunring night when no player is connected 

### ISSUE THREAD

**Issue by JeromeRoyer** [AllTheMods/ATM-10#204]
### Possible Fixes

Yes

### Modpack Version

0.27

### What happened?

2 morning of 3 I have to restart the server because he crashes randomly during night.

### Crash Log

https://gist.github.com/JeromeRoyer/fe79cb1b26a66aadf637fc3775562b7b

### Latest.Log

https://gist.github.com/JeromeRoyer/20fbf95b7b447519c7898948223dad02

**Comment by alekthefirst** [comment]
The latest.log provided was from a startup after a crash, and to solve this would require the latest.log from the session that crashed
Given the age of this issue i believe it is safe to close. If you have further issues please raise a new one
