### ISSUE TITLE
[Bug]: Duplication Glitch With Pocket Storage Unit

### ISSUE THREAD

**Issue by B2XP** [AllTheMods/ATM-10#205]
### Possible Fixes

Yes

### Modpack Version

0.27

### What happened?

If there's something inside the pocket storage. When you double-click an item from the inventory into the pocket storage while holding down the shift key, the full quantity of that item will be added to the storage; however, it won't be removed from the inventory. has an impact on all users who possess a pocket storage device, rendering the mod unplayable and unfair.

If I believe this bug started from version 0.25.

**Comment by instinxx** [comment]
Duplicate issue - https://github.com/AllTheMods/ATM-10/issues/199
Fixed as per dev - https://github.com/Flanks255/pocketstorage/issues/30

**Comment by Andrelyse** [comment]
Same issue here
