### ISSUE TITLE
[Crash]: Server crash randomly

### ISSUE THREAD

**Issue by JeromeRoyer** [AllTheMods/ATM-10#206]
### Possible Fixes

Yes

### Modpack Version

0.27

### What happened?

Farming for blockheads is in cause of the crashes.
Randomly the servers crashes.

### Crash Log

https://gist.github.com/JeromeRoyer/698d0306ceb1a7aa1035982c374b1357

**Comment by alekthefirst** [comment]
Fixed in Farming For Blockheads 21.1.1, released in ATM10 0.33
