### ISSUE TITLE
Amadron Tablet issue

### ISSUE THREAD

**Issue by cweet01** [AllTheMods/ATM-10#209]
### Possible Fixes

Yes

### Modpack Version

Newest

### What happened?

Just trying to order items through the Amdron tablet from Pneumatic and it takes the emeralds but nothing happens. I have ordered several different things with different stock levels to see but they were all the same.

**Comment by djnifos** [comment]
https://github.com/TeamPneumatic/pnc-repressurized/issues/1322

**Comment by cweet01** [comment]
Okay thank did not see that. Sorry.
