### ISSUE TITLE
[Bug]: You can't craft sticks with dark oak planks

### ISSUE THREAD

**Issue by HighQualityShadows** [AllTheMods/ATM-10#21]
### Possible Fixes

Yes

### Modpack Version

0.3

### What happened?

![image](https://github.com/AllTheMods/ATM-10/assets/173863849/7f51f4ed-8277-4923-888c-db54707d1c89)
When you try to craft sticks with dark oak planks it makes a dark oak pressure plate instead. The polymorph menu doesn't show up either.

**Comment by Kevin-Marsh** [comment]
This is an issue cause by the version of Polymorph. Updating manually will fix it for now but otherwise it will be fixed in next version.
[Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph/files/5480541)
