### ISSUE TITLE
[Bug]: Pneumatic Craft: Repressurized Heat Frame not converting water buckets to ice.

### ISSUE THREAD

**Issue by StunningAnybody5728** [AllTheMods/ATM-10#213]
### Possible Fixes

Yes

### Modpack Version

All The Mods 10-0.27

### What happened?

![2024-08-06_21 47 04](https://github.com/user-attachments/assets/fec443dd-4785-446b-a12c-f15bd2594455)
![2024-08-06_21 47 49](https://github.com/user-attachments/assets/a4aab919-8773-4241-bd2e-0d3f21bc4dbb)
The Heat Frame on a Chest is not converting a bucket of water to ice even at very low temperatures. Looking at the recipe it looks like the recipe for all cooling with the heat frames have not been set correctly. Using the heat frame to heat/smelt items in a chest works fine but not the cooling.

**Comment by StunningAnybody5728** [comment]
![2024-08-06_21 51 20](https://github.com/user-attachments/assets/7be044e4-c769-45f7-806f-8e23edef60a2)

**Comment by MrLoLf** [comment]
@StunningAnybody5728 This has been fixed in newer Versions of ATM10, and therefore can be closed.
