### ISSUE TITLE
[Quests issues]: Ars Nouveau

### ISSUE THREAD

**Issue by SolaRiix09** [AllTheMods/ATM-10#214]
### Modpack Version

1.21

### Describe the issue

For the quests of Ars Nouveau, there is a problem with the quest requiring archwood logs and planks. It seems that for the logs, a placeholder was used, the "Smart Filter" from FTB Filter System.
Thus, it's impossible de complete the quest and unlock the next ones.

Also, there is a problem with the worn notebook from the mod, it's impossible to use it in order to have the guide for the mod.

Thank you for your modpack, and I hope this could help you !

**Comment by AlgebraManiacABC** [comment]
I would like to mention that, although you can craft the smart filter, it does not advance the quest.
Luckily, since I started with cheats enabled, I was able to use `/ftbquests editing_mode true` to allow me to go into the questbook and force complete the task.
