### ISSUE TITLE
[Bug]: ME p2p tunnels not creating new frequencies 

### ISSUE THREAD

**Issue by Hennaz480** [AllTheMods/ATM-10#215]
### Possible Fixes

Yes

### Modpack Version

10-0.27

### What happened?

When shift right clicking on a P2P tunnel with a memory card it clears the memory card instead of creating a new frequency for P2P tunnels. Shown here https://medal.tv/games/minecraft/clips/iq4P7rtyPxZplYh57/d1337JuoLvoT?invite=cr-MSw2TzUsMjA4MDY3MTcs

**Comment by JoniP04** [comment]
Did you figure out how to fix this i have the same problem and noone on the discord or reddit responds/can help me out...

**Comment by Hennaz480** [comment]
Hi, yes it was due to having items in my off hand while trying to make new
channels with a memory card. So clear your off hand then try again.
