### ISSUE TITLE
[Bug]: Can't amber the wither with Amber Bee

### ISSUE THREAD

**Issue by ItsReach** [AllTheMods/ATM-10#217]
### Possible Fixes

Yes

### Modpack Version

0.27

### What happened?

I can't amber the wither, I've tried it with 16 bees in a hyperbox, in the end trapping it under the portal and I also tried in a creative test world but none seem to work. I'm currently in update 0.27. Did they change something? I tried searching for a config text file but I can't also find anything

**Comment by Magicride025** [comment]
Seems to be working now as of update 0.30 Successfully captured several mobs in amber.
