### ISSUE TITLE
[Crash]: When i kill warden the game crashes

### ISSUE THREAD

**Issue by TSSDK** [AllTheMods/ATM-10#219]
### Possible Fixes

Yes

### Modpack Version

0.28

### What happened?

without mods there is no crash

### Crash Log

https://gist.github.com/TSSDK/1a7faecef40a754b4938cfea5b76ebbc

**Comment by NJM1564** [comment]
Can verify crash.
https://gist.github.com/NJM1564/88b2952fd4170f3a9443a2ff7e8fc741
I killing it twice using the dire clicker and sword to kill it. Both times it crashed the same way.
Did drop a warden statue though. :D
