### ISSUE TITLE
[Bug]: Annihilation Plane Disappears Along With Fluix Cable It's Connected To

### ISSUE THREAD

**Issue by shhStealth** [AllTheMods/ATM-10#22]
### Possible Fixes

Yes

### Modpack Version

0.3

### What happened?

I set up an annihilation plane that breaks Certus Quartz Clusters, it has disappeared 2 times now. The first time was after the 0.2 > 0.3 update, but it happened again while playing on 0.3 after re-placing the plane.

Attached image shows how the annihilation plane is setup. I have re-added the plane and will report back if it happens again.

![2024-06-27_22 24 48](https://github.com/AllTheMods/ATM-10/assets/79993597/7fb0af6e-eae7-4295-865e-97b18ddf8551)

**Comment by Mithi83** [comment]
Sounds like https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7969. Was the plane enchanted by any chance? If so AE2 19.0.7-alpha should fix that.

**Comment by frogalo** [comment]
happened to me as well. It was enchanted. Not enchanted plane works fine

**Comment by shhStealth** [comment]
> Sounds like [AppliedEnergistics/Applied-Energistics-2#7969](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7969). Was the plane enchanted by any chance? If so AE2 19.0.7-alpha should fix that.

Yes it was enchanted, I think you're right! Thank you for your help :)
