### ISSUE TITLE
[Crash]: using a crossbow crashes the game

### ISSUE THREAD

**Issue by shade1822226911** [AllTheMods/ATM-10#220]
### Possible Fixes

Yes

### Modpack Version

0.28

### What happened?

I accidentally used my crossbow while building and crashed my game, my crossbow was enchanted with only piercing 2 and loaded with an arrow prior to the update

### Crash Log

https://gist.github.com/shade1822226911/234bb25db012118f3fe9d2e9e13eeb86

### Latest.Log

https://gist.github.com/shade1822226911/b1b08a1c60012211c88e78568521ebb7

**Comment by Andrelyse** [comment]
I got the same problem yesterday

**Comment by MrLoLf** [comment]
I tried this today, and it doesn't crash me, so it seems to have been fixed in the meantime. Can you update the modpack and try again? If it doesn't crash you anymore, you can close this issue @shade1822226911

**Comment by shade1822226911** [comment]
yep, fixed as of 0.30
