### ISSUE TITLE
[Bug]:  Just Dire Things: No Recipe for Paxel

### ISSUE THREAD

**Issue by Mahdoe** [AllTheMods/ATM-10#221]
### Possible Fixes

Yes

### Modpack Version

ATM 10: 0.28

### What happened?

After delving into Just Dire Things, I tried making a Paxel. There is no EMI recipe for either the Celestigem or the Eclipse Alloy Paxel. Combining everything inside of a crafting grid doesn't yield results.

**Comment by Kaladin1313** [comment]
The pickaxe, axe, and shovel need to be combined in a smithing table rather than a normal crafting table

**Comment by MaiNGNH** [comment]
Hello, doesn't work for me, as the smithing table doesn't allow more than two items

**Comment by ArnoldsK** [comment]
> The pickaxe, axe, and shovel need to be combined in a smithing table rather than a normal crafting table

You can't though? It doesn't allow placing any tool in the smithing template slot.

**Comment by ViRb3** [comment]
Pickaxe goes first, it can fit in the smithing template slot.

**Comment by miniatureforge** [comment]
> ?

Sup man, listen it is in JEI, its under the smithing table tab, you need all three (pick, axe & shovel) then go to the table with those in your inventory and use the bookmarked recipe from JEI and you will get it to add it all to the table. 

<img width="882" height="488" alt="Image" src="https://github.com/user-attachments/assets/dd8d61fa-f4c4-4bcf-904c-1d66de9a5381" />
