### ISSUE TITLE
[Bug]: Invisible Chests (and bed) after using /home

### ISSUE THREAD

**Issue by ChrisDeForest** [AllTheMods/ATM-10#222]
### Possible Fixes

Yes

### Modpack Version

0.28

### What happened?

I've been using /warp and /home to teleport between my new and old base, respectively, until I have my new base set up completely and can permanently move there. Some of my chests turned invisible after using /home to get to my old base. They are still there and can be used, just invisible. This also happened to my bed, but breaking and placing the bed fixed the issue. I don't want to do this with my chests because of the mess resulting from the item.
![2024-08-07_16 10 32](https://github.com/user-attachments/assets/7f23d304-c93c-4e6e-999d-2a799e234f1e)
![2024-08-07_16 10 37](https://github.com/user-attachments/assets/0e2fe5c5-3cf0-4b9d-840c-df48959d9c43)
![2024-08-07_16 10 44](https://github.com/user-attachments/assets/988ad6f3-17a3-41bd-a606-fb81d4d07971)
![2024-08-07_16 10 47](https://github.com/user-attachments/assets/3ea6dc16-ba79-4184-8312-387eefcc611e)

### latest.log

https://gist.github.com/ChrisDeForest/c3eef1f50a030d938ef991ddbe7f884b

**Comment by alekthefirst** [comment]
I am unable to reproduce this in ATM10 2.8
Unless anyone else shows up with the issue on recent versions, i believe it is reasonable to close as presumably it got fixed at some point.
