### ISSUE TITLE
[Bug]: Block Breakers not working 

### ISSUE THREAD

**Issue by Gaabysz** [AllTheMods/ATM-10#230]
### Possible Fixes

Yes

### Modpack Version

10-0,29

### What happened?

The Bloc placer and Breakers are no working!
When making a setup to autofarm C.quartz with modular routers, I noticed that the breaker module was not working, than I crafted a Advanced Block Breaker from JDT and it did not work as well.

**Comment by Seegras** [comment]
Most likely explanation: "fake players" in FTB chunks not enabled (by you) for claimed chunks.
