### ISSUE TITLE
[Bug]: Middle Mouse Button to sort inventory doesn't work

### ISSUE THREAD

**Issue by Mahdoe** [AllTheMods/ATM-10#233]
### Possible Fixes

Yes

### Modpack Version

ATM 10 0.29

### What happened?

Up until version 0.28 it was possible to sort the targeted inventory with the middle button/scroll wheel on the mouse. It stopped working in 0.29. The keybind in the controls still says it's middle mouse button, which doesn't work for any of us.

**Comment by Magicride025** [comment]
Just updated to 0.29 and it is still working for me. Maybe keybind changed for some reason for you?

**Comment by Mahdoe** [comment]
Sadly, we checked the controls and it's still supposed to be middle mouse button, which doesn't work for us. Everyone on our server is experiencing this.

**Comment by Mahdoe** [comment]
As of 0.30, this doesn't occur anymore.
