### ISSUE TITLE
[Bug]: AllTheModium Tools are not indestructible or enchantable

### ISSUE THREAD

**Issue by Mahdoe** [AllTheMods/ATM-10#235]
### Possible Fixes

Yes

### Modpack Version

ATM 0.30

### What happened?

I made my first set of Allthemodium tools (sword, pickaxe) and they lose durability. As stated in the allthemodium_book, they are supposed to be indestructible. They were indestructible in previous versions. 
It's also not possible to enchant the allthemodium tools when they're already upgraded to allthemodium so I put the enchantments Sharpness, Looting, Capturing, Life-Stealing and Scavenger on the netherite sword before upgrading it to allthemodium.

**Comment by EarthKing339** [comment]
i had the same problem, but with vibranium. i couldnt put prot 4 on my armor for no apparent reason. i went in creative mode only so i could actually use the prot 4 books i bought. didnt even say it was too expensive or anything

**Comment by Mahdoe** [comment]
It doesn't matter whether or not the tool is enchanted. It happens with unenchanted allthemodium tools too. This issue still persists as of 0.34.
