### ISSUE TITLE
[Crash]: Game crashes whilst having a trader bookmarked with villager and profession in it. And then hovering over it in EMI.

### ISSUE THREAD

**Issue by NeofastFTL-Backup** [AllTheMods/ATM-10#236]
### Possible Fixes

Yes

### Modpack Version

Modpack Version = ATM 10 - 0.29

### What happened?

Modpack Version = ATM 10 - 0.29
Forge Version = 1.21 -- 21.0.167
Easy Villagers Mod Version = easy-villagers-neoforge-1.21-1.1.15.jar
EMI Mod Version = emi-1.1.11+1.21+neoforge.jar

Reproducing the crash with Easy Villagers and EMI

1.
Get a trader from Easy Villagers.

2.
Place it and put a villager with their corresponding workstation. (Can be any) *

3. 
Break the corresponding trader with the villager and its workstation.

4. 
Bookmark the trader with the villager with A in EMI.

5.
Hover over the bookmark.

6.
Crash

### Crash Log

https://gist.github.com/NeofastFTL-Backup/db97001377e9b314edff90fc60357f77

### Latest.Log

https://gist.github.com/NeofastFTL-Backup/b39733425d1ce943db5df3e057ad65cb

**Comment by TheBedrockMaster** [comment]
https://github.com/henkelmax/easy-villagers/issues/229

**Comment by NeofastFTL-Backup** [comment]
i searched it up in closed issues and open issues. already checked that. But oke. thx for saying it
