### ISSUE TITLE
[Bug]: Magnet Card for wireless terminal always sends items to first joined player in range instead of player breaking the block

### ISSUE THREAD

**Issue by S1lencio** [AllTheMods/ATM-10#237]
### Possible Fixes

Yes

### Modpack Version

0.30

### What happened?

The magnet card for the wireless AE2 terminal always sends dropped items to the player who joined first (that is in range) instead of the player who broke the block.

Reporting this here because the mods repo hasn't been updated in 5 years.

**Comment by Mithi83** [comment]
You're probably referring to https://github.com/p455w0rd/AE2WirelessTerminalLibrary with your 5 year argument. Try this one instead: https://github.com/Mari023/AE2WirelessTerminalLibrary

**Comment by S1lencio** [comment]
Thanks, I'll open a bug report there.
