### ISSUE TITLE
[Quests issues]: AE2 Autocrafting cannot be completed

### ISSUE THREAD

**Issue by Mithi83** [AllTheMods/ATM-10#238]
### Modpack Version

10-0.30

### Describe the issue

Although I have met the criteria for the the quest "Auto-Crafting" (marked in the first screenshot with a green arrow) I cannot complete it, probably because of the dependency (see second screenshot). What makes me wonder is that the title of that dependency is "Smart Filter", but when I click it, I end up on the "Basic Cabling", which I've completed. Other dependencies correctly state the name of the  quest rather than "Smart Filter".

![quest](https://github.com/user-attachments/assets/5cf219a6-bc9e-40d9-96ca-92ad137898c1)
![quest2](https://github.com/user-attachments/assets/6fcc23ca-829c-49c5-afd3-d4714cfbe304)

**Comment by Kurunoa** [comment]
I have this same issue.

**Comment by TheBedrockMaster** [comment]
The Smart Filter part has been fixed. The rest appears to be an issue with FTB Quests. To complete the quest you will need to turn on editing mode and force complete it or reset your progress on the quest.
