### ISSUE TITLE
[Bug]: I JUST DID TORCHES! 

### ISSUE THREAD

**Issue by TheEmpireSro** [AllTheMods/ATM-10#24]
### Possible Fixes

Yes

### Modpack Version

0.3

### What happened?

I just wanted to craft torches, now I have infinite charcoal. xD
![2024-06-28_08 38 10](https://github.com/AllTheMods/ATM-10/assets/145923835/2ee97e5a-19fe-4886-b625-0aa7651ccaa9)

**Comment by Kevin-Marsh** [comment]
Could you please provide more details about how you encountered this bug? There isn't enough information to try to start duplicating it.

**Comment by DaddyLongspoon** [comment]
I have also encountered an infinite torches bug by crafting torches from (crafting interface in) qio storage machine (mekanism) it does not deplete coal/sticks at all...
