### ISSUE TITLE
[Bug]: Hyperbox chunk loading not working correctly

### ISSUE THREAD

**Issue by M4RC0Sx** [AllTheMods/ATM-10#248]
### Possible Fixes

Yes

### Modpack Version

0.30

### What happened?

Hyperbox chunk loading is not working with FTBChunks. I have an hyperbox loaded inside and outside with FTBChunks, and when I leave the hyperbox I can see it is not being loaded. I wasn't until I placed a Railcraft worldspike that the chunk loading of the interior of the hyperbox started working.

**Comment by OlickQC** [comment]
For people having that bug, just install "Chunk Loaders", those small chunk loaders are craftable but they are working good for me.
