### ISSUE TITLE
[Crash]: I crash after a few seconds of joining my single player world.

### ISSUE THREAD

**Issue by weluvlion** [AllTheMods/ATM-10#250]
### Possible Fixes

Yes

### Modpack Version

0.32

### What happened?

I would join my world, lag for a few seconds before my screen turns black and I crash. This happened 4 times in a row.

### Crash Log

https://gist.github.com/weluvlion/80b601abc0a59662eeabdd7386168538

### Latest.Log

https://gist.github.com/weluvlion/887083a2f6825cad25824fae9471a49e

**Comment by alekthefirst** [comment]
Fixed in Apothic Spawners 1.1.0, released with ATM10 0.34
