### ISSUE TITLE
[Bug]: Unable to rename Waystone

### ISSUE THREAD

**Issue by Magdapo-17** [AllTheMods/ATM-10#251]
### Possible Fixes

Yes

### Modpack Version

0.32

### What happened?

We can't give a name to the waystone, screen is black when i try.

**Comment by EarthKing339** [comment]
i thought this was just me this was happening to

**Comment by shade1822226911** [comment]
it is possible, it's just that the gui is gone. i have the same problem

**Comment by WolfyZv** [comment]
I have the same problem. I can still rename the waystone when I place it. The GUI doesn't appear, but I can still type and press enter.

**Comment by Hamude99** [comment]
Same for me on 0.34, hope they fix it, it's really annoying.

**Comment by Hamude99** [comment]
Same on 0.35, still not fixed.

**Comment by recon88** [comment]
Same happens in some configuration windows.
ESC -> Mod -> Select MouseTweaks -> Config
Window goes blurr

![2024-09-10 10h56m00s  1725958560](https://github.com/user-attachments/assets/847d7cd3-7bbe-4521-ab43-070c90d416ba)

**Comment by mentimjojo** [comment]
I believe this is still the same root cause as it was before. See:

https://github.com/AllTheMods/ATM-10/issues/251
https://github.com/TwelveIterationMods/Waystones/issues/889#issuecomment-2328795114
