### ISSUE TITLE
[Crash]: Iron's Spells and Spellbooks crash due to render error from GeckoLib

### ISSUE THREAD

**Issue by Syndrous** [AllTheMods/ATM-10#256]
### Possible Fixes

Yes

### Modpack Version

ATM 10 0.32

### What happened?

I hopped off my boat at a village and as it rendered a crash occurred with the following message:

The game crashed whilst rendering entity in world
Error: java.lang.IllegalStateException: Not building!

### Crash Log

https://gist.github.com/Syndrous/378abdf2cc738ec1354b1c4ebbd0bb7c

### Latest.Log

https://gist.github.com/Syndrous/bc352ec91565bd481d34928d4d79e2ae

**Comment by Syndrous** [comment]
I've been made aware by Iron431 that this issue is related to a rendering error with glowing entities that occurs on Geckolibs backend. They are working on a fix with no ETA. [Here is a link to brief discussion with Iron](https://github.com/iron431/irons-spells-n-spellbooks/issues/536), as well as a link to Iron's report of the [issue to Geckolibs team](https://github.com/bernie-g/geckolib/issues/606).

**Comment by Tricksz74** [comment]
also happen on 0.36 while playing on server it crash immediately after joining

[crash-2024-08-21_15.43.41-client.txt](https://github.com/user-attachments/files/16692911/crash-2024-08-21_15.43.41-client.txt)

**Comment by alekthefirst** [comment]
Fixed in Irons 3.4.5 released with ATM10 0.39
