### ISSUE TITLE
[Bug]: Brass block from AllTheOres not working on compacting drawers

### ISSUE THREAD

**Issue by M4RC0Sx** [AllTheMods/ATM-10#258]
### Possible Fixes

Yes

### Modpack Version

0.30

### What happened?

The brass from alltheores only works in compacting drawers as ingots and nuggets. Blocks do not work like the other kind of ores.

**Comment by DaddyLongspoon** [comment]
duplicate of[ #088](https://github.com/AllTheMods/ATM-10/issues/88)
