### ISSUE TITLE
[Bug]: Epic Knights mod causes connection loss when loading world 

### ISSUE THREAD

**Issue by brandonnn80** [AllTheMods/ATM-10#259]
### Possible Fixes

Yes

### Modpack Version

0.32

### What happened?

Eveything was fine before, but since i updated it to the most current version and i try to enter my world i get a connection lost screen,Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet   'clientbound/minecraft:update_recipes'.  I then tried turning off the mods i remembered adding, I then turned off the epic knights mod which fixed the problem 
![Screenshot (151)](https://github.com/user-attachments/assets/56ac76ff-d9ca-4cf0-b8ac-dfe0c4e170e2)

### latest.log

https://gist.github.com/brandonnn80/efcb2fc257f7fb3fe2e48781a0b21550

### Developer reports

https://github.com/Magistu/Epic-Knights

**Comment by EarthKing339** [comment]
this is most likely because epic knights adds ores for the armors that are already in atm10, and the game is confused
