### ISSUE TITLE
[Bug]: creative menu search bar is not working

### ISSUE THREAD

**Issue by alex28122009** [AllTheMods/ATM-10#26]
### Possible Fixes

Yes

### Modpack Version

0.3

### What happened?

![2024-06-28_19 26 02](https://github.com/AllTheMods/ATM-10/assets/174134673/f42c478d-a33a-41a1-8963-3cecdfce88bf)

**Comment by Kevin-Marsh** [comment]
This is caused by the version of EMI and Modernfix. For now you can use emi cheat mode by clicking the emi button in the bottom left of the screen to enable it. Ctrl click and left click to take items out of EMI once you have it enabled.
