### ISSUE TITLE
[Crash]: Server is crashing idk why

### ISSUE THREAD

**Issue by rodopoulos1** [AllTheMods/ATM-10#260]
### Possible Fixes

Yes

### Modpack Version

10-0.32

### What happened?

Game crashes on world i have only to walk and server crashes

### Crash Log

https://gist.github.com/rodopoulos1/468b2927f60ccd8a3aade05eac873986

### Latest.Log

https://gist.github.com/rodopoulos1/f01d91f018158d6c713a8ff7a192d3fa

**Comment by alekthefirst** [comment]
Was fixed in Sophisticated Core 0.6.25.621, released with ATM10 0.33
