### ISSUE TITLE
[Bug]: Dragon egg not spawning at end of re-fight 

### ISSUE THREAD

**Issue by LordDragon1213** [AllTheMods/ATM-10#261]
### Possible Fixes

Yes

### Modpack Version

0.33

### What happened?

Dragon egg is not spawning when completing the dragon fight more than one time.

**Comment by DaddyLongspoon** [comment]
That's not a bug, it's how the game natively behaves.  There is a mod which alters this but it isn't in atm10.  you can make a dragon egg with antimatter and hens egg (mekanism) or with an inactive dragon egg (productive bees) placed In the world and click it with dragon breath

**Comment by Koviricsi** [comment]
You can use the xycraft extractor too

**Comment by LordDragon1213** [comment]
Thanks for the info.
