### ISSUE TITLE
[Bug]: Croptopia Olive Oil Recipe Consumes All Purpose Food Press

### ISSUE THREAD

**Issue by indianakaz** [AllTheMods/ATM-10#267]
### Possible Fixes

No

### Modpack Version

0.31

### What happened?

The recipe for olive oil from croptopio requires 2x olives and 1x All purpose food press.  
it consumes the press, which i don't think it should, it should only consume the olives

**Comment by TheBedrockMaster** [comment]
Closing in favour of https://github.com/AllTheMods/ATM-10/issues/490
