### ISSUE TITLE
game crashes cannot play world.. [Crash]: Error: java.lang.IllegalStateException: Invalid block entity mcwfurnitures:furniture_storage 

### ISSUE THREAD

**Issue by h1seyn** [AllTheMods/ATM-10#269]
### Possible Fixes

Yes

### Modpack Version

10-0.33

### What happened?

my game crashes instand because of a block and my friends too.. we cant play our world we get unstand crash since 0.33 update
please fix

error code i get: cError: java.lang.IllegalStateException: Invalid block entity mcwfurnitures:furniture_storage // com.mcwfurnitures.kikoz.storage.StorageTileEntity state at BlockPos{x=-303, y=71, z=-849}, got Block{mcwfurnitures:oak_double_wardrobe}[connection=top,facing=south]

### Crash Log

https://gist.github.com/h1seyn/cbec8e99c1d4764ea08286f7059e4e42

**Comment by Mahdoe** [comment]
Hey, this is basically the same as #257.
