### ISSUE TITLE
[Bug]: trying to make a steel fluid output hatch from Modern Industrialization

### ISSUE THREAD

**Issue by TrashMagpie** [AllTheMods/ATM-10#27]
### Possible Fixes

No

### Modpack Version

0.3

### What happened?

when trying to make a steel fluid output hatch from modern industrialization it doesn't recognize the item I have the correct ingredients a steel machine casing and a steel tank but when placed in a crafting table with the casing on top and the steel tank below nothing shows in the output side, I have also checked doesn't matter where you place it in the crafting table there is no output

![image](https://github.com/AllTheMods/ATM-10/assets/90269560/29285ef4-1486-49a5-93ea-d88a03f2489d)

**Comment by TrashMagpie** [comment]
correction the output hatch only crafts in a normal crafting table not crafting on a stick, input hatch only crafts in crafting on a stick and not normal crafting table

**Comment by Kevin-Marsh** [comment]
This is an issue cause by the version of Polymorph. Updating manually will fix it for now but otherwise it will be fixed in next version.
[Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph/files/5480541)
