### ISSUE TITLE
[Bug]: EMI shift-clicking recipes in does not work with Occultism storage

### ISSUE THREAD

**Issue by CodenameCAT1** [AllTheMods/ATM-10#274]
### Possible Fixes

Yes

### Modpack Version

0.34

### What happened?

When I shift left click on an item with EMI, I cannot add its recipe to the Occultism storage's built-in crafting table. Even if I have, say, 20000 deepslate, I must manually create the shape for deepslate slabs instead of shift clicking the item from the search menu in and getting the recipe automatically.

![image](https://github.com/user-attachments/assets/67c90414-5c2a-4d82-98cd-1be11c9a8ecf)

![image](https://github.com/user-attachments/assets/9a8c1ce9-9f77-4884-bf4e-6b4439fb205e)

**Comment by klikli-dev** [comment]
This is an open feature request at occultism: https://github.com/klikli-dev/occultism/issues/1147

**Comment by klikli-dev** [comment]
https://github.com/klikli-dev/occultism/issues/1147 was just closed, and the feature added
