### ISSUE TITLE
[Bug]: wither skeleton tweaks skull fragment does not have a recipe

### ISSUE THREAD

**Issue by alex28122009** [AllTheMods/ATM-10#275]
### Possible Fixes

Yes

### Modpack Version

0.34

### What happened?

i dont know if it was intentional because it wasnt writen in changelog

**Comment by alex28122009** [comment]
actually all of the items in this mod dont have recipe

**Comment by Greytusks** [comment]
Seems to be fixed in today's 0.35 version, a recipe is now available to create the skulls from fargments.

**Comment by alex28122009** [comment]
Fixed in version 0.35
