### ISSUE TITLE
[Quests issues]: Experience bees not working 

### ISSUE THREAD

**Issue by Morticiand** [AllTheMods/ATM-10#276]
### Modpack Version

0.33

### Describe the issue

The experience honeycomb can't be processed in the centrifuge.

**Comment by JaisDK** [comment]
does the centrifuge have another fluid in it?

**Comment by Morticiand** [comment]
No, the experience comb is not even accepted by the centrifuge in the left box to be processed and goes directly to the right where the experience bottle should be

**Comment by ToshibaEC0Microwave** [comment]
This is just a game bug, not a quest issue.

**Comment by JaisDK** [comment]
it's fixed
