### ISSUE TITLE
[Crash]: with evil craft

### ISSUE THREAD

**Issue by Sage027** [AllTheMods/ATM-10#277]
### Possible Fixes

Yes

### Modpack Version

0.34

### What happened?

My game crashed when i used the enchantment remover from Evil craft. It happened when i places the Blook in to the machine, it started and then crashed. And now i cant log back in?

The game crashed whilst ticking block entity
Error: java.lang.IllegalArgumentException: Bound must be positive

### Crash Log

https://gist.github.com/Sage027/94f5b1b65a1d5859b2541396dd3732f7

### Latest.Log

https://gist.github.com/Sage027/6004a5bfd19682f83440588582600f3a

**Comment by BlueMinerHD** [comment]
Same problem here on a dedicated server. The only way to fix it was to remove EvilCraft, start the server, and then add it again (of course all EvilCraft items were gone). Last time it happened was in 0.36. It hasn't happened in 0.38 yet.

[crash-2024-08-22_22.30.13-server.txt](https://github.com/user-attachments/files/16739684/crash-2024-08-22_22.30.13-server.txt)
