### ISSUE TITLE
[Bug]: Chisel reborn blocks dont drop when broken

### ISSUE THREAD

**Issue by Seear1** [AllTheMods/ATM-10#28]
### Possible Fixes

Yes

### Modpack Version

.3

### What happened?

Chisel reborn blocks dont drop when broken ( diorite pillar and solid diorite blocks ) to be specific

**Comment by matthewperiut** [comment]
Developer of Chisel Reborn here, it is now fixed in the latest version of my mod 1.8.1, sorry for the oversight! Once this pack updates, it should work as expected
