### ISSUE TITLE
easy villager gone?

### ISSUE THREAD

**Issue by Zoetrue** [AllTheMods/ATM-10#282]
I noticed easy villager was removed from my game in 10-0.33 or something, will it comeback again and will I regain the villagers that i lost or would it be from scratch?

**Comment by TheBedrockMaster** [comment]
Easy villagers was removed intentionally, it was mentioned in the changelog for an update.

**Comment by Cm200000** [comment]
Update 10-0.32
"REMOVED EASY VILLAGERS (It will return later)"

**Comment by Zoetrue** [comment]
Thanks 🙏🏼
