### ISSUE TITLE
[Bug]: Plastic Bees seem to have no block to pollinate

### ISSUE THREAD

**Issue by Seegras** [AllTheMods/ATM-10#283]
### Possible Fixes

Yes

### Modpack Version

0.34

### What happened?

Plastic Bees seem to have no block to pollinate.

Since they're an optional PneumaticCraft quest, they should be somehow useful.

**Comment by DaddyLongspoon** [comment]
its plastic sheet, it just doesn't show in the emi.   Make one the hard way, stick it in the feeding slab.. check again, you got a thousand
