### ISSUE TITLE
[Bug]: Cant Join my Server

### ISSUE THREAD

**Issue by MrBl4ck64** [AllTheMods/ATM-10#285]
### Possible Fixes

Yes

### Modpack Version

0.32/0.33/0.34

### What happened?

I updated my server from G-Portal to the newer versions and when I try to join, I get this message:
"Failed to sync registries from the server: java.lang.NullPointerException"
With version 0.30 everything is working fine.

Any ideas or tips?

**Comment by ZsomborRajki** [comment]
If you are using a prism launcher your client might be missing a mod.

I added `disenchanting_table-merged-1.21-3.0.2` manually and it fixes the connection error for me.
