### ISSUE TITLE
[Bug]: Croptopia tools are consumed

### ISSUE THREAD

**Issue by thiago-mpinto** [AllTheMods/ATM-10#287]
### Possible Fixes

Yes

### Modpack Version

10-0.34

### What happened?

When the croptopia butter recipe is made through the integrated dynamics crafting interface, the tools are consumed

**Comment by 2chriswy** [comment]
Tools are consumed by all the related croptopia recipes not just butter.

Modpack Version
10-0.36

**Comment by JPARKISON** [comment]
Still occurring in versions: 10-0.41 and 10-0.42.

To replicate, crafting Jam in the crafting table consumes the cooking pot tool.

**Comment by TKach1** [comment]
Still occurring in version 10-0.45

Every recipe with Pan and Cooking Pot are being consumed.

**Comment by TheBedrockMaster** [comment]
Closing in favour of https://github.com/AllTheMods/ATM-10/issues/490
