### ISSUE TITLE
[Bug]: Big lag spikes

### ISSUE THREAD

**Issue by Hamude99** [AllTheMods/ATM-10#289]
### Possible Fixes

Yes

### Modpack Version

0.34

### What happened?

I keep getting big lag spikes on default rendering options and I've been trying to debug it for an hour but nothing works. Maybe I accidentally modified some video settings or something but I can't fix it and this is the only modpack I am getting lag spikes on.

**Comment by StShAzzy** [comment]
try looking for memory leaks, just a suggestion

**Comment by StShAzzy** [comment]
look for uncommon memory usage, and the minecraft client getting really close to the allocated memory limit

**Comment by Hamude99** [comment]
> look for uncommon memory usage, and the minecraft client getting really close to the allocated memory limit

I don't think it's a memory leak, still using the same amount of memory when increasing memory allocation.

**Comment by StShAzzy** [comment]
maybe too many recipes?

**Comment by Hamude99** [comment]
> maybe too many recipes?

What do you mean by that?

**Comment by StShAzzy** [comment]
> > maybe too many recipes?
> 
> What do you mean by that? Also, just discovered this: #292

so i guess it was a memory leak after all
