### ISSUE TITLE
[Crash]: When using the barrels from sophisticated to craft any item it crashes the whole server

### ISSUE THREAD

**Issue by Pryxo** [AllTheMods/ATM-10#297]
### Possible Fixes

Yes

### Modpack Version

0.36

### What happened?

i tried to craft the storage controller and in the same time where i put it into the crafting field it crashed the whole server, this happen twice now

### Crash Log

https://gist.github.com/Pryxo/4a73acf8e4b8543f2baa16db1fba9490

**Comment by connnor** [comment]
Was able to replicate this. 

Whole server crashed after moving sophisticated barrel into the crafting table.

ATM Version 0.45
Server OS: Windows 11
Java Version: JDK 21
Allocated Ram: 8GB

**Comment by alekthefirst** [comment]
Fixed in Sophisticated Storage 0.10.27.827, released in ATM10 0.53
