### ISSUE TITLE
[Bug]: Crafting table on a stick can't be placed in the Crafting on a Stick slot

### ISSUE THREAD

**Issue by Mcrtin** [AllTheMods/ATM-10#3]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-0.1

### What happened?

![image](https://github.com/AllTheMods/ATM-10/assets/66840021/2efe4cb6-7e10-420e-867a-6be87be43d0c)
Maybe this is independent from atm10 and only relates to COAS but I can't find the github repo from COAS for mc 21

**Comment by whatthedrunk** [comment]
fixed on version 0.2 which will be approved any min thanks!
