### ISSUE TITLE
[Bug]: No make Sticky Piston

### ISSUE THREAD

**Issue by jungshinyung5** [AllTheMods/ATM-10#30]
### Possible Fixes

Yes

### Modpack Version

0.3

### What happened?

No CRAFTING can create this item.
![2024-06-29_13 09 14](https://github.com/AllTheMods/ATM-10/assets/43872929/cb94abba-a703-4250-9041-2da6c0371aeb)

**Comment by Kevin-Marsh** [comment]
This is an issue cause by the version of Polymorph. Updating manually will fix it for now but otherwise it will be fixed in next version.
[Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph/files/5480541)
