### ISSUE TITLE
[Bug]: Crafting farmland uses full tool

### ISSUE THREAD

**Issue by daleamann** [AllTheMods/ATM-10#300]
### Possible Fixes

No

### Modpack Version

0.36

### What happened?

On the public ATM10 server if you craft MA farmland in the crafter - ME crafting, Backpack, regular crafting table - the hoe is used up for create 1 farmland. Tried with netherite and allthemodium hoes.

**Comment by Hallsie** [comment]
Confirmed.  Does not seem to matter which tool either.  I tried many varieties.

**Comment by LOXAMWu** [comment]
have a same problem

**Comment by alekthefirst** [comment]
Unsure on which version it was resolved on, but issue is no longer present on ATM10 2.8
