### ISSUE TITLE
[Bug]: model Magma cube in Amber to large

### ISSUE THREAD

**Issue by Steve1980nl** [AllTheMods/ATM-10#301]
### Possible Fixes

Yes

### Modpack Version

0.34

### What happened?

I put an Magma cube in amber and the model seems a bit overlapping with the other feeding slabs. 

### latest.log
![2024-08-22_01 13 56](https://github.com/user-attachments/assets/978039b8-c5bb-48bd-bfd4-df1e34cdc0b9)

_No response_

**Comment by alekthefirst** [comment]
Issue still present in ATM10 2.8

**Comment by JaisDK** [comment]
It’s perfect

**Comment by alekthefirst** [comment]
> It’s perfect

Want me to close as not planned?

**Comment by alekthefirst** [comment]
Ill take that as a yes
