### ISSUE TITLE
[Bug]: Blur mod config settings inside a world

### ISSUE THREAD

**Issue by BelleBernice** [AllTheMods/ATM-10#303]
### Possible Fixes

Yes

### Modpack Version

ATM10 0.36

### What happened?

There is some weird blur bug in the Mod config settings inside any world. I think i tryed every available config from the mods in ATM 10 and the problem is found only in "Mouse Tweaks" config. But i found the "bug" from others mods i had installed in my main instance, like BoccHUD. 

Don't know what is thing bug and i don't think there is any log info about it.

How to recreate:

1: Make a clean instance of ATM10 0.36
2: Create a New World and load in
3: Press Esc and go to the Mods tab
4: Search for "Mouse Tweaks" and click the "Config" button

Results from inside the world:
![javaw_VQLX5pw1UK](https://github.com/user-attachments/assets/74d74ea7-ecb5-4c7a-940a-bcc68827765d)
![javaw_rOeXiyq9Uo](https://github.com/user-attachments/assets/a932ae7f-4d11-4de0-9475-1f7954758876)

Results from the Main Menu button:
![javaw_eAV9TpvNNb](https://github.com/user-attachments/assets/90f3dc4f-ef9c-499b-a159-99cd6631d5d1)
![javaw_xeEr6AIeQT](https://github.com/user-attachments/assets/0e51a554-d83f-4b3a-aabe-08f55fcc828c)

**Comment by BelleBernice** [comment]
Same problem with [this issues](https://github.com/AllTheMods/ATM-10/issues/254)

**Comment by recon88** [comment]
Fix:
https://github.com/TwelveIterationMods/Waystones/issues/889#issuecomment-2328795114
