### ISSUE TITLE
[Quests issues]: ATM10 JEI

### ISSUE THREAD

**Issue by itskenny7** [AllTheMods/ATM-10#307]
### Modpack Version

0.63

### Describe the issue

is:issue is:open JEI is terrible, please add the one from ATM9. I don't like this one....

**Comment by TheBedrockMaster** [comment]
First, that isn't a version of ATM10, second, JEI has been replaced with EMI in ATM10, if you don't like it, get rid of it. Third, JEI is the one from ATM9.

**Comment by itskenny7** [comment]
What lol? It’s the JEI thats changed to EMI mod, I know that. That’s why I said that I prefer the normal JEI one like in ATM9, not sure why they decided to use EMI this time. ATM has mostly been using JEI.

The recipe systems are so confusing sometimes, need to pay attention all the time, its so confusing.

I hope the creators reconsider please. I have been a fan since the ATM6.

**Comment by aceus0** [comment]
> What lol? It’s the JEI thats changed to EMI mod, I know that. That’s why I said that I prefer the normal JEI one like in ATM9, not sure why they decided to use EMI this time. ATM has mostly been using JEI.
> 
> The recipe systems are so confusing sometimes, need to pay attention all the time, its so confusing.
> 
> I hope the creators reconsider please. I have been a fan since the ATM6.

go ahead and do it then and open a pull request
