### ISSUE TITLE
[Bug]: minecraft:tall_grass drops minecraft:short_grass when sheared or silk touched.

### ISSUE THREAD

**Issue by DaddyLongspoon** [AllTheMods/ATM-10#308]
### Possible Fixes

Yes

### Modpack Version

10.0.36

### What happened?

Trying to get some tall grass for earth essence seed, can't get some. :(

**Comment by micrwvae** [comment]
tall grass is only obtainable in savanna villages
ill revert it to the smalll grass
will hopefully be out next update
