### ISSUE TITLE
[Bug]: Console error spam

### ISSUE THREAD

**Issue by JeromeRoyer** [AllTheMods/ATM-10#315]
### Possible Fixes

Yes

### Modpack Version

0.38

### What happened?

The game console is spamed with this error :
[Server thread/ERROR] [ap.ap.st.GenericStack/]: Failed to serialize GenericStack GenericStack[what=mysticalagriculture:supremium_scythe (with patches), amount=1]: Value must be non-negative: -1

**Comment by alekthefirst** [comment]
Was an issue with items that was supposed to be unbreakable
Fixed in Mystical Agriculture 8.0.4, released with ATM10 0.39
