### ISSUE TITLE
[Bug]: Incompatible/old mods

### ISSUE THREAD

**Issue by Miuks** [AllTheMods/ATM-10#316]
### Possible Fixes

Yes

### Modpack Version

0.38

### What happened?

On launch i get 2 errors
1: sodium is incompatible with embeddium
2: iris is incompatible with embeddium

Possible solutions:
1: remove embeddium
2: update sodium to 0.6 (if possible)

**Comment by SpinHarmony** [comment]
Embeddium was already removed. I’m not sure why it would still be in your mods folders, but it is not in the pack anymore.
