### ISSUE TITLE
[Bug]: AE2 Spatial IO and Mekanism do not play well

### ISSUE THREAD

**Issue by FallenPumpking** [AllTheMods/ATM-10#32]
### Possible Fixes

Yes

### Modpack Version

0.2

### What happened?

If you enclose, for instance, a Mekanism Reactor setup in Spatial IO and then attempt to store it, seemingly random blocks are left behind, parts of cables, parts of the reactor, etc. Then trying to bring it back does the same, leaving even more blocks in the spatial dimension.

**Comment by Kevin-Marsh** [comment]
Various blocks are tagged as unmovable. This isn't a bug.
