### ISSUE TITLE
[Quests issues]: Metal Age not claiming

### ISSUE THREAD

**Issue by Mithril-Master** [AllTheMods/ATM-10#320]
### Modpack Version

0.0.36

### Describe the issue

Had a copper ingot in inventory when i looked at the Metal Age quest, when I got iron i didn't have copper and it marked as complete but i couldnt turn in because i didnt have both in inventory. now i have both and still can't turn in or move on

**Comment by TheBedrockMaster** [comment]
Sounds like an issue with FTB Quests. To complete the quest you will need to turn on editing mode and force complete it or reset your progress on the quest.
