### ISSUE TITLE
[Bug]: MA Night Vision Upgrade doesn't work

### ISSUE THREAD

**Issue by TheSadKem** [AllTheMods/ATM-10#321]
### Possible Fixes

Yes

### Modpack Version

0.38

### What happened?

I put a night vision upgrade on a prudentium helmet from MA and i tried taking it off and on but the night vision still didnt work

**Comment by Cordelya** [comment]
Also occurring for me on 0.51 - Supremium helmet with night vision augment does not actually grant night vision.

I don't have a full essence armor set, just the helmet.

![2024-09-12_20 15 49](https://github.com/user-attachments/assets/6a5a6c75-15a3-48aa-a1b0-19f2aae77673)
