### ISSUE TITLE
[Quests issues]: No Refined Storage?

### ISSUE THREAD

**Issue by itskenny7** [AllTheMods/ATM-10#322]
### Modpack Version

ATM10

### Describe the issue

Hey

I just noticed that Refined Storage is gone, any update/news on this if it will be added to ATM10? 

Thanks!

**Comment by TheBedrockMaster** [comment]
Refined Storage hasn't been updated, this isn't a quest issue or even a normal issue.

**Comment by itskenny7** [comment]
> Refined Storage hasn't been updated, this isn't a quest issue or even a normal issue.

Oh that's why sadly, I'm sorry i'm new to the forum. I don't know where to post suggestions

**Comment by TheBedrockMaster** [comment]
#2 For mod suggestions, Refined Storage would still have to be updated first before suggesting though.

**Comment by Mitchell5200** [comment]
The current plan is to wait for Refined Storage 2 to release.
