### ISSUE TITLE
[Crash]: Ars Nouveau - Brazier Relay Ticking Block Entity Crash

### ISSUE THREAD

**Issue by XSleepyEco** [AllTheMods/ATM-10#324]
### Possible Fixes

Yes

### Modpack Version

0.38

### What happened?

I'm not sure if it's appropriate for me to post crash reports here, but I thought I might post something in case others are having a similar issue.

Placed the brazier relay from Ars Nouveau and immediately the server crashed. It appears to be a ticking block entity error.

### Crash Log

1st crash: https://gist.github.com/XSleepyEco/fa75dc8c4b93222da9ad7dc4829c28a1
2nd crash (25/08/2024): Replicated the same issue within singleplayer as well. Just merely placing the brazier relay causes a crash: https://gist.github.com/XSleepyEco/f4934e97d24c5213a3043110bc53144f

**Comment by alekthefirst** [comment]
Fixed in Ars Noveau 5.0.10, released with ATM10 0.39
