### ISSUE TITLE
[Bug]: You can get literally anything you want with pattern encoders

### ISSUE THREAD

**Issue by AvogadrosTheory** [AllTheMods/ATM-10#33]
### Possible Fixes

Yes

### Modpack Version

0.3

### What happened?

basically you input any item pattern into the pattern encoder with a blank pattern available, then after the pattern is encoded you input the recipe again while not removing the encoded pattern, then you'll get the item with 0 materials needed. ps: this works only on crafting patterns

**Comment by Megovid** [comment]
Its fixed in newest AE2 version so devs just need to update mod

**Comment by frogalo** [comment]
fixed in 0.5
