### ISSUE TITLE
[Bug]: Mystical Agriculture No Output In Enchanter

### ISSUE THREAD

**Issue by slidez1337** [AllTheMods/ATM-10#330]
### Possible Fixes

No

### Modpack Version

0.38

### What happened?

Enchanter does not output any enchanted books.

https://github.com/user-attachments/assets/fd718cb9-ee83-4ceb-ba62-f727efe5fcda

**Comment by Blackladder** [comment]
Same issue for me. v 0.46
Both SP and MP

**Comment by andremiller** [comment]
MysticalAgriculture-1.21.1-8.0.5.jar includes a fix:

> Release 8.0.5 for MC 1.21.1
> Changes:
> - Fixed the Enchanter not working

**Comment by Sashashok** [comment]
still not working

**Comment by Sashashok** [comment]
![изображение_2024-09-21_161922940](https://github.com/user-attachments/assets/8ed5998a-bf48-4199-bf83-385f6ab82f2e)

**Comment by slidez1337** [comment]
fixed in 0.54
