### ISSUE TITLE
[Bug]: Farmland Silk Touch

### ISSUE THREAD

**Issue by Hallsie** [AllTheMods/ATM-10#334]
### Possible Fixes

No

### Modpack Version

0.36

### What happened?

I was looking to start Mystical Agriculture and came across the bug where crafting farmland makes your hoe disappear (already reported).  So I went with the 2nd option of making farmland and then silk touch it.  I was using Mining Gadgets laser.  When I harvest the farmland using silk touch it disappears.  I am not sure where it goes, I have removed all backpacks and everything I have that picks up items as well as my filter on my laser.

Then, when I went to use the farmland that I made when coming across the above bug, I made the farmland, one piece.  I placed that piece and then two more popped into my inventory. I did not craft 3, however two is how many I harvested with silk touch testing that out.

**Comment by Junior57-7** [comment]
You don’t have to create MA farmland in a table just right click farmland with essence and it will change to that type

**Comment by Hallsie** [comment]
Nice.  I will do that in the meantime.
