### ISSUE TITLE
[Bug]: Bug with Occultism

### ISSUE THREAD

**Issue by natSuky01** [AllTheMods/ATM-10#34]
### Possible Fixes

Yes

### Modpack Version

0.4

### What happened?

background bug with minimap of ftb mods 
![Captura de pantalla 2024-06-29 214322](https://github.com/AllTheMods/ATM-10/assets/64163468/2ca92914-71a0-4dc7-a24c-8563973e8a5b)

**Comment by frogalo** [comment]
missing new version of modonomicon where new rituals were updated https://www.curseforge.com/minecraft/mc-mods/modonomicon/files/5481761

**Comment by natSuky01** [comment]
then it is the ATM Team's option to add it. Thx for the comment

**Comment by Kevin-Marsh** [comment]
Caused by journeymap which they will fix soon.
