### ISSUE TITLE
[Bug]: Crude oil not processing

### ISSUE THREAD

**Issue by Logiwire** [AllTheMods/ATM-10#341]
### Possible Fixes

Yes

### Modpack Version

10-0.34

### What happened?

I followed the quest for the crude oil processing with pneumaticCraft. Once I assemble the refinery controller with 4 thanks placed a vortex tube with a compressor to generate heat. I placed on all the tanks the thermal laggin. The refinery tells me there is no problem. The temperature is over 100 as shown in JEI. There is no processing. The crude oil section is full but it is not processing it for the other fuels. It is ran on a server on the latest version. Tried to find information online but I could not find anything

**Comment by TheBedrockMaster** [comment]
Has this started working or is it a problem on the current release?
