### ISSUE TITLE
[Bug]: Mystical Agriculture : silicone Essence does not have any uses

### ISSUE THREAD

**Issue by DaddyLongspoon** [AllTheMods/ATM-10#344]
### Possible Fixes

Yes

### Modpack Version

10.0.38

### What happened?

The silicone essence does have a single crafting recipe revealed by clicking 'u' on it in JEI, but this recipe has no output.

**Comment by Hallsie** [comment]
I'm on 0.44 and use it to make silicon with three straight across in the middle.

What bench/workstation are you using.  I noticed a lot of recipes do not work in the Integrated Dynamics crafting grid.

**Comment by DaddyLongspoon** [comment]
> I'm on 0.44 and use it to make silicon with three straight across in the middle.
> 
> What bench/workstation are you using. I noticed a lot of recipes do not work in the Integrated Dynamics crafting grid.

Thanks, the issue was addressed.

**Comment by TheBedrockMaster** [comment]
This was originally fixed on our end but has since been fixed on the mod's end.
