### ISSUE TITLE
[Crash]: Falling through the air during login, world isnt loading then game crash and/or disconnect

### ISSUE THREAD

**Issue by CEOMikey** [AllTheMods/ATM-10#354]
### Possible Fixes

Yes

### Modpack Version

0.40

### What happened?

Game keeps crashing 10-20 seconds after loading into the world. The world doesnt seem to be loading though and im falling through the air (y keeps going down). Doesn't completely crash all the time, sometimes it just disconnects. Same thing is happening to my friend.

### Crash Log

https://gist.github.com/CEOMikey/d36675da8c132977eb9ad4b281b450b5#file-crash-2024-08-29_15-56-56-client-txt

### Latest.Log

https://gist.github.com/CEOMikey/a5bb7004b4d8409eee26e9314803178b#file-newest-log

**Comment by alekthefirst** [comment]
LegacyRandomSource crashes are generally hard to diagnose without extra effort. Some of them have been fixed since this issue was created, and given the age of this issue without further complaints, i will assume it has been resolved in one of the many mod updates since.
