### ISSUE TITLE
[Bug]: 0.41 - EMI recipe shortcuts/keybinds not functional?

### ISSUE THREAD

**Issue by Greytusks** [AllTheMods/ATM-10#356]
### Possible Fixes

Yes

### Modpack Version

0.41

### What happened?

Just updated to 0.41, left or right click is not functional in EMI interface to view recipes, so are R and U keybinds (they are set to defaults, never changed, still bound in options to R and U).

Old save or new save, same result. Reseting keybinds had no results.

**Comment by neonbladez2** [comment]
Adding onto this, I've got the same issue as well. Downgraded back to 0.40 while there's a fix for this hopefully. Like Grey said, clicking any item and using keybinds on them do not work at all.

You can load in the world fine, no errors or anything. Just cant view recipes at all.

**Comment by Greytusks** [comment]
This issue is still occuring in 0.42

**Comment by Greytusks** [comment]
A did a test on a separate copy of the pack  : 



@neonbladez2 
On 0.42 with the issue occurring on a copy of the pack made for testing this, I updated to 0.42, deleted all the config files and restarted minecraft. Upon loading the save file EMi was functional again. 

The config files are the problem here.

Seems that the old 0.40 config files are not compatible with the version of the mod that exists in o.41 and above.. So this is technically a 'fix' although it requires manual intervention. I'll close this issue since in a fresh install this is not a problem.
