### ISSUE TITLE
[Bug]:  Tool belt (tool belt mod) does not fit into belt (or any other) curio slot

### ISSUE THREAD

**Issue by DaddyLongspoon** [AllTheMods/ATM-10#36]
### Possible Fixes

Yes

### Modpack Version

10.0.4

### What happened?

crafted the tool belt, added a few pouches, tried to click it into my curios, nope..

**Comment by Seear1** [comment]
press v

**Comment by DaddyLongspoon** [comment]
> press v

hi, thanks.  I couldn't find any help from the V key :(
tool belt does not have any "slot" tag that I can see, same as crafting table on a stick didn't have until first update. 

 Devs, this is also the case with the occultism surprising satchel thing, I do not yet have endstone, so I didn't make one but I suspect it'll have the same issue.
thanks again, I love your packs.  God bless.

**Comment by HeavyDeception** [comment]
@DaddyLongspoon I don't know if you have found out already but the tool best uses a different slot that you open with a hot key it can be searched in the Key bindings under the mod name it doesn't use a Curio slot.

**Comment by DaddyLongspoon** [comment]
> @DaddyLongspoon I don't know if you have found out already but the tool best uses a different slot that you open with a hot key it can be searched in the Key bindings under the mod name it doesn't use a Curio slot.

Hi, Thanks.  I know how the mod works, I just want to be able to wear the belt in the belt slot.  like I could in atm7, 8 & 9, like I can if a make a pack and add the tool belt mod.  The bug I report here is that the belt does not fit into curio slot. Like it is supposed to.

**Comment by TheBedrockMaster** [comment]
Closing in favour of https://github.com/AllTheMods/ATM-10/issues/187
