### ISSUE TITLE
[Bug]: allthemodium enchanting

### ISSUE THREAD

**Issue by EnotScript** [AllTheMods/ATM-10#365]
### Possible Fixes

Yes

### Modpack Version

0.41

### What happened?

Items from allthemodium+addon not enchantable after upgrade.

**Comment by Satherov** [comment]
That's a known issue and will be fixed soon. Until then, you have to enchant your gear before turning it into allthemodium gear

**Comment by StyLexR6** [comment]
Still an issue on 0.46

**Comment by Satherov** [comment]
This issue was fixed in the latest version of AllTheModium. You can either update the mod manually or wait for 0.47
