### ISSUE TITLE
[Bug]: Mystical agriculture steel recepie

### ISSUE THREAD

**Issue by StyxHaven** [AllTheMods/ATM-10#367]
### Possible Fixes

Yes

### Modpack Version

0.41

### What happened?

The recepie for the steel seeds in mystical agriculture is not there, ive tried both ingots and block with no luck. on all versions, i am currently on 0.41

**Comment by Hallsie** [comment]
Looks fine in 0.44.  8 on the outside = 5 steel.  I have this running currently.

**Comment by StyxHaven** [comment]
Hallsie, the seeds themselves are what i cannot craft

**Comment by Hallsie** [comment]
OOOhhhh I got ya.  I think I made the seeds on 0.40 as I just updated to
0.44 the other day from 0.40 and I already had the seeds.  I'm assuming you
know how to make the seeds with the setup with the pedestals right?

**Comment by StyxHaven** [comment]
Oh yes, I'm very familiar with most of the mods in the pack. By now I've tried all possible recipes on the pedestals, ingot, nuggets, blocks, and I've tried with all 6 tiers of essence *(I don't have awakened yet)

**Comment by Hallsie** [comment]
Ok.  I will try tonight.

**Comment by Hallsie** [comment]
I just looked and I'm an idiot.  I made graphite essence.  GREAT!  lol.

**Comment by TheEnderHacker** [comment]
I noticed this bug as well and reported it in the Mystical Agriculture issues. Here's the thread: https://github.com/BlakeBr0/MysticalAgriculture/issues/720. The owner said it’s not their bug, but I think they described the issue here, and they believe the problem lies with ATM10.
