### ISSUE TITLE
[Bug]: Functional Storage

### ISSUE THREAD

**Issue by billsKatie** [AllTheMods/ATM-10#368]
### Possible Fixes

Yes

### Modpack Version

0.41

### What happened?

I cannot add any drawers to the controller, when I try it just changes mode from add to remove.

**Comment by Satherov** [comment]
Linking a drawer to a controller should be pretty straight forward. Are you not too far away or not hitting the controller correctly?

https://github.com/user-attachments/assets/4733ee95-1ddb-488d-b407-19d9cb123800

**Comment by billsKatie** [comment]
I was standing right next to the controller.

**Comment by billsKatie** [comment]
Close this I accidently made the wrong item...
