### ISSUE TITLE
[Quests issues]: Manganese Bee

### ISSUE THREAD

**Issue by TheProamer** [AllTheMods/ATM-10#369]
### Modpack Version

0.41

### Describe the issue

![Screenshot 2024-08-31 005331](https://github.com/user-attachments/assets/ff17001f-d74f-4a9c-977a-f7d0a86b3687)
that doesnt seems not to work.

**Comment by TheBedrockMaster** [comment]
Did you put it on a feeding slab?

**Comment by TheProamer** [comment]
no but now its working, thanks

**Comment by TheBedrockMaster** [comment]
You can close this now if it's fixed.
