### ISSUE TITLE
[Bug]: ATM10 launches as if it was vanilla Minecraft on Linux

### ISSUE THREAD

**Issue by PurpleIsSus1985** [AllTheMods/ATM-10#371]
### Possible Fixes

Yes

### Modpack Version

0.42

### What happened?

I use PolyMC on Manjaro Linux and wanted to install ATM 10. I used the built-in Curseforge downloader to get the modpack, but it appeared to simply start as if it was pure vanilla Minecraft. I tried downloading the pack manually, but still no luck.

### latest.log

https://gist.github.com/PurpleIsSus1985/48a7ec25f9a02dc0c1b41277de72a284

**Comment by PurpleIsSus1985** [comment]
For some reason the issue does not exist on Curseforge.

**Comment by McKitten** [comment]
This may actually be the case because neoforge above .26 is not visible on at least 1 client. No idea why since .31 was recommended at the time i noticed this.
