### ISSUE TITLE
[Bug]: Time wand render and book incorrect due to incomplete JDT config changes

### ISSUE THREAD

**Issue by jpenilla** [AllTheMods/ATM-10#376]
### Possible Fixes

Yes

### Modpack Version

0.41

### What happened?

The time wand from JDT cannot go to the max 256x multiplier (mentioned in the dire book) with the current config, it maxes out at 128x.
This is because in the config energy use is set to 750rf, which means for 128x it uses 96,000 rf, and for 256x it would need 192,000 rf. However, the max storage of the wand is set to 100,000 rf. My suggestion is to raise the max rf in the wand to 200,000 rf or higher.

https://github.com/AllTheMods/ATM-10/blob/b9810ebd7828628b4eac37e499ab64acd6e10b1f/config/justdirethings-common.toml#L191-L201

**Comment by alekthefirst** [comment]
The reason for the config change was to nerf the max acceleration to 128x...

**Comment by jpenilla** [comment]
Maybe it would be good to open a feature request at JDT for a dedicated max multiplier config then, to avoid confusion with the book not matching in-world behavior.

**Comment by jpenilla** [comment]
https://github.com/Direwolf20-MC/JustDireThings/pull/142

**Comment by jpenilla** [comment]
JDT v1.2.3 includes my PR adding a `time_wand_max_multiplier` config option, this should allow the ATM team to nerf the wand without the book and renderer becoming inaccurate.
