### ISSUE TITLE
[Crash]: NullPointerException because "beeIngredient" is null

### ISSUE THREAD

**Issue by Notnox** [AllTheMods/ATM-10#382]
### Possible Fixes

Yes

### Modpack Version

10-0.41+

### What happened?

When opening the modpack and trying to open the inventory or any chest, the crash occurs.

### Crash Log

https://gist.github.com/Notnox/15524fdcfeca2589d9893c04ba7a43d2

**Comment by alekthefirst** [comment]
As far as i can tell this should be fixed in productive bees https://github.com/JDKDigital/productive-bees/issues/586#issuecomment-2444467699 then released with ATM10 1.12
Though if it is not, please reopen.
