### ISSUE TITLE
[Bug]: Mystical Agriculture augments get deleted when relogging

### ISSUE THREAD

**Issue by TPpenguin** [AllTheMods/ATM-10#383]
### Possible Fixes

Yes

### Modpack Version

0.43

### What happened?

When logging out of the server and then relogging the augments on my armour stopped working so I went to the tinkering table to check them and they appeared in the UI before very quickly vanishing. Note that the server was restarted in this time.

### latest.log

https://gist.github.com/TPpenguin/15f55290d3480cac9e90e3d91a9738e6

### Developer reports

https://github.com/BlakeBr0/MysticalAgriculture/issues/715

**Comment by HNGamingUK** [comment]
Been reported to MA devs here https://github.com/BlakeBr0/MysticalAgriculture/issues/711

**Comment by andremiller** [comment]
MysticalAgriculture-1.21.1-8.0.5.jar includes a fix:

> Release 8.0.5 for MC 1.21.1
> Changes:
> 
> Fixed Augments not saving between world restarts
