### ISSUE TITLE
[Bug]: Journey Map Frame Issues

### ISSUE THREAD

**Issue by BLAKESTRFF** [AllTheMods/ATM-10#385]
### Possible Fixes

Yes

### Modpack Version

10-0.43

### What happened?

Persistent throughout all of the recent patches btw: 
Warping to Journeymap waypoints will drop FPS to 1-10, and stay that way until either the world is reloaded, or the entire instance is reloaded. 
Chunk generation seems to take a significant hit after warping, even if they were previously loaded

### latest.log

https://gist.github.com/BLAKESTRFF/80dbb25350c04663bda631defe5ea63b

**Comment by alekthefirst** [comment]
Several individual issues related to this was fixed in JM 6.0.0-beta.23, beta.24 and beta.25, released with ATM10 0.45, 0.47 and 0.49 respectively
