### ISSUE TITLE
[Bug]: chest disappears tape and card box

### ISSUE THREAD

**Issue by astec10** [AllTheMods/ATM-10#392]
### Possible Fixes

Yes

### Modpack Version

0.44

### What happened?

When using the Sophisticated Storage mod tape together with the mekanism card box the chest disappears and if you try to restart the game it crashes.

![image](https://github.com/user-attachments/assets/5f358f0e-b706-466f-93a0-f86824a16e80)

### latest.log

https://gist.github.com/astec10/0f0e6f2923290fd4f99b8defa8631e2b

**Comment by alekthefirst** [comment]
Issue seems to have been resolved in an update released after this issue was created, though i am unsure on which update specifically.
https://github.com/user-attachments/assets/1bff60b7-6dd0-4bcd-a83b-c23a06bf7ce7
