### ISSUE TITLE
[Bug]: Mystical Agriculture Seed Reprocessor Not Exporting

### ISSUE THREAD

**Issue by pankewytch** [AllTheMods/ATM-10#397]
### Possible Fixes

Yes

### Modpack Version

0.44

### What happened?

When I try to export the essence from the seed reprocessor I cannot. I have tried using vanilla hoppers, modular routers with every level of a puller, pipez (both item and universal with every level of upgrade including no upgrade), and logistical transporters via mekanism. I have tried all of these on every side of the machine (outside of the vanilla hopper that can only go on the bottom) and I cannot extract the essence. The only way I can get the essence out is to manually extract it via the ui of the reprocessor. There are no logs for this that I can see. When I connect this there is nothing in the logs.

Running this on an ubuntu server (20.04.6 LTS) if that is needed. Then connecting to it via windows and Mac machines. Cannot extract from the seed reprocessor from any of these clients.

**Comment by StyLexR6** [comment]
Still an issue on 0.46, Submitted a report to the MA github

**Comment by StyLexR6** [comment]
Still an issue on 0.47 https://github.com/BlakeBr0/MysticalAgriculture/issues/721

**Comment by StyLexR6** [comment]
Fixed with cucumber 8.0.4 with the 0.48 update.
