### ISSUE TITLE
[Crash]: Server crashes frequently since .44 associated with auto-crafting

### ISSUE THREAD

**Issue by ncottrill** [AllTheMods/ATM-10#398]
### Possible Fixes

Yes

### Modpack Version

10-0.44

### What happened?

Spark reports a hang while getting world statistics. But, I think what is happening is a thread is locking up involving auto-crafting mod Crafting Tweaks. I will include the crash log. After a few minutes, the server detects a hang and restarts.

### Crash Log

https://gist.github.com/ncottrill/7fc350fb9c0bba73178de97b0c1d468b

**Comment by alekthefirst** [comment]
Fixed in crafting tweaks 21.1.3, released with ATM10 1.12
