### ISSUE TITLE
[Bug]: There is no crafting recipe for nature's compass

### ISSUE THREAD

**Issue by Mcrtin** [AllTheMods/ATM-10#4]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-0.1

### What happened?

There is no crafting recipe for nature's compass...

**Comment by whatthedrunk** [comment]
If you update the mod it will be fixed now. We plan to update the mod in version 0.3

**Comment by TheBedrockMaster** [comment]
Has the mod been updated?

**Comment by TheBedrockMaster** [comment]
Can be closed?

**Comment by frogalo** [comment]
yes
