### ISSUE TITLE
Iron Furnace dupe (ATM10)

### ISSUE THREAD

**Issue by Megovid** [AllTheMods/ATM-10#40]
### Possible Fixes

Yes

### Modpack Version

ATM10 (0.4)

### What happened?

https://github.com/AllTheMods/ATM-10/assets/121926098/bf07c064-5213-463c-854e-4dd8241d7662

i just click furnace to upgade (its on offisial server)
Works with any upgrade

**Comment by Megovid** [comment]
All duped items rn in trash can (gone, deleted, destroyed)

**Comment by aAndrew3030** [comment]
Fixed in 0.5 version of the pack
