### ISSUE TITLE
[Bug]: Cognizant Dust wont drop.

### ISSUE THREAD

**Issue by The1stVoidRunner** [AllTheMods/ATM-10#403]
### Possible Fixes

Yes

### Modpack Version

0.45

### What happened?

I have a Supremium Sword enchanted with Mystical Enlightenment V but when I kill the wither with it then it doesn't drop any Cognizant Dusk. From my understanding, it is supposed to be a Guaranteed drop.

**Comment by pankewytch** [comment]
Idk if this helps but it is off by default in the mystical agriculture toml. By default, only the dragon drops cognizant dust.

**Comment by YocyCraft** [comment]
> Idk if this helps but it is off by default in the mystical agriculture toml. By default, only the dragon drops cognizant dust.

In ATM9sky wither drops cognizant dust

**Comment by robinhotton** [comment]
it's normal the cognizant dust drop is disabled on wither kill ?

Look just above the blue line :
![Capture d'écran 2024-09-12 211100](https://github.com/user-attachments/assets/325ac09b-3fdf-4a6c-9016-2776c6ee64b7)

**Comment by pankewytch** [comment]
I mean I am not sure about normal. However, that is the default in ATM10. You could always try to put up a pr to change the default. Not sure if they would accept that or not.

**Comment by recon88** [comment]
This is actually a bug. 
Quest Book says, the Wither AND the Dragon are dopping the essence, but Wither is disabled.
Either the Quest information needs to be fixed or the dust needs to be enabled for Withers.

![2024-09-14 16h52m14s  1726325534](https://github.com/user-attachments/assets/5fa9affb-2b85-4d64-bb50-0a0e5965beee)
