### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kingnote** [AllTheMods/ATM-10#405]
### Possible Fixes

Yes

### Modpack Version

0.38

### What happened?

I keep getting this bug idk if its just me but every update my flight augment for my MA armor disappears along with othe augments on armor

**Comment by HNGamingUK** [comment]
It's been reported directly to MA devs https://github.com/BlakeBr0/MysticalAgriculture/issues/711

**Comment by devsilvver** [comment]
I go through this every time I open my world, this morning I opened mine and when I entered the world all the augments in my MA armor disappeared
