### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by GustavoTaquiwiAriosi** [AllTheMods/ATM-10#408]
### Possible Fixes

Yes

### Modpack Version

0.46

### What happened?

The world is not initializing claiming error 
![image](https://github.com/user-attachments/assets/e2e0cb4c-17d2-4477-9c16-3910a6ce9f09)

### Crash Log

a

### Latest.Log

a

**Comment by The1stVoidRunner** [comment]
Same here.

Crash Log: https://pastebin.com/MSBpvM74

**Comment by LevyWilson** [comment]
A player on my server is getting the same crash as well after updating to .46.

[message.txt](https://github.com/user-attachments/files/16902631/message.txt)

**Comment by The1stVoidRunner** [comment]
> A player on my server is getting the same crash as well after updating to .46.
> 
> [message.txt](https://github.com/user-attachments/files/16902631/message.txt)

Yeah I get it when connecting to my own server.

**Comment by LevyWilson** [comment]
It's something wrong with Journeymap. You can disable the mod to log in. Hopefully it's fixed in .47.

**Comment by HNGamingUK** [comment]
> It's something wrong with Journeymap. You can disable the mod to log in. Hopefully it's fixed in .47.

Yeh seems it's been reported in the JourneyMap Github https://github.com/TeamJM/journeymap/issues/785

**Comment by mysticdrew** [comment]
> > It's something wrong with Journeymap. You can disable the mod to log in. Hopefully it's fixed in .47.
> 
> Yeh seems it's been reported in the JourneyMap Github [TeamJM/journeymap#785](https://github.com/TeamJM/journeymap/issues/785)

That is an unrelated issue.

**Comment by alekthefirst** [comment]
Fixed with ATM10 0.47
