### ISSUE TITLE
[Bug]: Issue with sort button in inventory

### ISSUE THREAD

**Issue by SynodicMelody** [AllTheMods/ATM-10#41]
### Possible Fixes

Yes

### Modpack Version

0.4

### What happened?

When clicking the sort button in the different block interface the slots in the interface will be treated as the inventory and items will be sorted there and in cases like the advanced block place from the mod "just dire things" item in the allow and un-allow section WILL BE DELETED PERMANANTLY.

**Comment by alekthefirst** [comment]
Was resolved by blacklisting GUIs in inventory tweaks, fixed in atm10 1.25
