### ISSUE TITLE
[Bug]: Died near ladder and the grave didn´t spawn

### ISSUE THREAD

**Issue by Manuarti** [AllTheMods/ATM-10#412]
### Possible Fixes

Yes

### Modpack Version

0.46

### What happened?

I was inside one of the structures of modern industralation and the zombie killed me when I was on a ladder, when I got back there was no trace of the grave. I am sure of this because I checked with spectator

### latest.log

<script src="https://gist.github.com/Manuarti/07a09bd36e20e4262321e7742d0244f3.js"></script>

**Comment by Manuarti** [comment]
Update for some reason instead of spawning at the height I died(bottom of stairs) appeared above the ladder

**Comment by xXxRonaldxXx** [comment]
same happens when dying "in a door" grave spawns in the first air block above -> in an underground dungeon this ist quite dumb
