### ISSUE TITLE
[Crash]: Game crashes before loading into world

### ISSUE THREAD

**Issue by itzamega** [AllTheMods/ATM-10#417]
### Possible Fixes

Yes

### Modpack Version

0.46

### What happened?

after updating the modpack, the server will not let anyone join the world and it keep crashing

### Crash Log

https://gist.github.com/itzamega/007c06fc004ef4d82d49afca55411253

**Comment by The1stVoidRunner** [comment]
#408 you can disable JourneyMap to log in. Something is wrong with it.
