### ISSUE TITLE
[Bug]: Block of Spirited Crystal takes to much Energy

### ISSUE THREAD

**Issue by Ratles-1** [AllTheMods/ATM-10#418]
### Possible Fixes

Yes

### Modpack Version

0.46

### What happened?

1 Spirited Crystal takes 1MFE to convert from Emerald, but one block of 9 crystals takes 81 MFE from emerald block (thats 4 times the nitro process!)- should be 9 MFE?

**Comment by Mithi83** [comment]
See my comment in https://github.com/Technici4n/Powah/issues/191
