### ISSUE TITLE
[Bug]: Mystical upgrade disappear after log back in game

### ISSUE THREAD

**Issue by sevy7389** [AllTheMods/ATM-10#420]
### Possible Fixes

Yes

### Modpack Version

0.047

### What happened?

I made the mystical agriculture upgrade but when you log out and back in if they are installed on sword or armour they disappear.
I tried a couple of time and was the same everytime.

**Comment by EnotScript** [comment]
Every time I re-enter they disappear.

**Comment by EnotScript** [comment]
Fixed in new version mystical agriculture.
