### ISSUE TITLE
[Bug]: crash

### ISSUE THREAD

**Issue by PeterBorges694** [AllTheMods/ATM-10#421]
### Possible Fixes

Yes

### Modpack Version

10.0.45

### What happened?

The game crashes when trying to type anything in the Minecraft item search engine, jei works correctly.

### latest.log

https://gist.github.com/PeterBorges694/9079e94f3ba9b6212d27a7391b692342/revisions#diff-6eb5aa2af122281945d8d42cc285a04af319c927fec0b2e03ce47987c39985a2

**Comment by Jackerjaw** [comment]
I have the exact same problem. Ive tried removing sodium and iris but it did not help. @PeterBorges694 Did you manage to fix it?
