### ISSUE TITLE
[Bug]: Issue with crafting uranium seeds

### ISSUE THREAD

**Issue by MartinGronning** [AllTheMods/ATM-10#424]
### Possible Fixes

Yes

### Modpack Version

10-0.47

### What happened?

Im having a simular issue to this thread https://github.com/AllTheMods/ATM-10/issues/305 . All seeds apart from uranium work fine. I am using the correct oredictionary uranium (the alltheores one). The setup recognizes uranium seeds as a valid recipe (as seen by the tooltip), but the craft won't start. I am playing on a server and we haven't messed with any configs.
![image](https://github.com/user-attachments/assets/e49198ee-7f9d-4a3f-9494-c74e147cc9e6)

**Comment by DeclanHawkes1** [comment]
i am having same issue with wood seeds, looking at altar it says it should be crafting them, the craft never starts.
