### ISSUE TITLE
[Quests issues]: Applied Energistics 2 The IO 100%

### ISSUE THREAD

**Issue by Mostey007** [AllTheMods/ATM-10#425]
### Modpack Version

10.0.47

### Describe the issue

Can't collect the reward? It is checked off in gray, but its not possible to collect.
 
![image](https://github.com/user-attachments/assets/0c990050-6611-4d84-a17e-270ec2b0b188)
![image](https://github.com/user-attachments/assets/124b66e2-8c9c-4300-b43d-2e1ee2430158)

**Comment by TheBedrockMaster** [comment]
Appears to be an issue with FTB Quests. To complete the quest you will need to turn on editing mode and force complete it or reset your progress on the quest.
