### ISSUE TITLE
[Bug]: Eternal Water and Eternal Water Bucket aren't eternal

### ISSUE THREAD

**Issue by Mahdoe** [AllTheMods/ATM-10#428]
### Possible Fixes

Yes

### Modpack Version

0.47

### What happened?

I tried using both the versions of the Eternal Water (+Bucket) from Evilcraft to spread water. I expected it to work the same way as previous versions did (not getting consumed after usage), but the items disappeared after using them.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/279
