### ISSUE TITLE
[Bug]: Prosperity Ore doesn't drop Prosperity Shards when mined using a Fortune pickaxe

### ISSUE THREAD

**Issue by Mahdoe** [AllTheMods/ATM-10#429]
### Possible Fixes

Yes

### Modpack Version

0.47

### What happened?

We tried mining Prosperity Ore with different pickaxes (Eclipse Alloy, Netherite, Allthemodium, Diamond). All of them had Fortune, so the actual Ore dropped instead of the shards. As soon as we used different pickaxes without Fortune, we were getting shards.

**Comment by McKitten** [comment]
This applies to inferium also. Any enchants on the pickaxe act as silk touch.

**Comment by WendersonHC** [comment]
test with other blocks, like prosperity in stone, end and deepslate 

in my case it only wont turn into essence when i try to mine end inferium essence, not tested yet with prosperity...

**Comment by WendersonHC** [comment]
> Make a prosperity bee and insanium bee, its well worth it

i haven't tried the bee mods yet, it seems too damn hard. IDK, i'll take a look

**Comment by Cordelya** [comment]
Found this happens also when mining end prosperity ore using a mining gadget with a prosperity upgrade turned on
