### ISSUE TITLE
[Bug]: Extreme Reactors infinte Yellorium

### ISSUE THREAD

**Issue by HypedBandit** [AllTheMods/ATM-10#441]
### Possible Fixes

Yes

### Modpack Version

0.48

### What happened?

When you have an extreme reactor and go into the input slot for yellorium/uranium and you press "inject fuel" there will appear a stack of yellorium (which you can take out and then craft blocks out of it for example)

**Comment by alekthefirst** [comment]
Issue can not be reproduced on ATM10 2.8 and has presumably been fixed in the time period between then and now

https://github.com/user-attachments/assets/9fb272ea-8ee7-4bfc-9d47-c67b297e1f2b
