### ISSUE TITLE
[Bug]: Mystical agriculture inferium end stone block doesn't break into inferium essence

### ISSUE THREAD

**Issue by WendersonHC** [AllTheMods/ATM-10#442]
### Possible Fixes

Yes

### Modpack Version

10-0.48

### What happened?

i enchanted an pickaxe with apothic enchanting (FORTUNE VII) and when i try to break an end inferium ore it turns into the block again. I think that it might don't recognize the apothic enchanting or it may be designed to be this way, if its the case i didnt know about that... 

### latest.log

https://gist.github.com/WendersonHC/b3352d6d408c6ee69d933a21d45aae96

### Developer reports

https://github.com/BlakeBr0/MysticalAgriculture

**Comment by stardustdragon96** [comment]
same problem.
