### ISSUE TITLE
[Bug]: Failed to sync registries from server

### ISSUE THREAD

**Issue by Steinar-ichiban** [AllTheMods/ATM-10#447]
### Possible Fixes

Yes

### Modpack Version

0.48

### What happened?

When I update my server to eighter 0.47 or .48, me and my friends are not able to join. We get this error message "Failed to sync registries from server: java.lang.NullPointerException". We even made a fresh install of the server but still get the same error. 

For now we play on version .46 without any issues. But really want to upgrade for better experience. So is there any fast fix for this error? For what I could find out there might be a mod mismatch between server and client.
![Skjermbilde_2024-09-08_141712](https://github.com/user-attachments/assets/5d43c0d4-3065-4ac3-a302-0aac2df6ce76)

### latest.log

https://gist.github.com/Steinar-ichiban/14b7723224580aea7d46fd91fdb95f94

**Comment by Stupefacient** [comment]
This is Java issue on client try using different launcher. Unfortunately it just happens sometime with minecraft

**Comment by Steinar-ichiban** [comment]
> This is Java issue on client try using different launcher. Unfortunately it just happens sometime with minecraft

Yes you were correct, switching to ATLauncher fixes the issue. Thank you.

**Comment by JadeWhite** [comment]
I was having this exact issue with ATM10 v0.56, Prism Launcher 8.4, MacOS Sequoia 15. Can confirm installing/launching via. Curseforge worked instead.

Ironically if I copy paste the Curseforge ATM10 Minecraft instance folder overtop of the Prism Launcher one, the prism launcher one works fine. My sus is PrismLauncher is unable to apply the patches Curseforge can or something.
