### ISSUE TITLE
[Bug]: None of the chunks loading in properly

### ISSUE THREAD

**Issue by Lokido5** [AllTheMods/ATM-10#448]
### Possible Fixes

Yes

### Modpack Version

ATM 10-0.48

### What happened?

I am having an extremely hard time playing because the chunks don't fully load in. Blocks on the surface level are fine but if it's a hill then everything under that block doesn't load in at all causing you to be able to see everything like you have an X-ray hack.
Breaking blocks also causes the texture to half load so you have a dirt block that is missing half of it's texture and this is causing my framerate to drop to 15 fps.

I have changed all of my settings in minecraft to run at "Fast" settings and "decreased" particle settings and that fails to change anything. Sometimes the framerate goes from 15 down to 0 at random moments and just crash the game and the only way for it to close the program is through task manager.

This modpack is very broken and it's running like Curseforge corrupted the installation of this mod through their website/launcher.

**Comment by alekthefirst** [comment]
This was presumably fixed when we removed Noisium in ATM10 1.22
