### ISSUE TITLE
[Bug]: enchanter not giving book enchanting

### ISSUE THREAD

**Issue by stardustdragon96** [AllTheMods/ATM-10#449]
### Possible Fixes

Yes

### Modpack Version

10.0.48

### What happened?

![erro1](https://github.com/user-attachments/assets/a0399693-6f16-4697-b106-74469f785743)
![erro2](https://github.com/user-attachments/assets/6213affa-a61b-4498-9ffe-a791d720545e)

**Comment by andremiller** [comment]
MysticalAgriculture-1.21.1-8.0.5.jar includes a fix:

> Release 8.0.5 for MC 1.21.1
> Changes:
> - Fixed the Enchanter not working

**Comment by TheBedrockMaster** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/330
