### ISSUE TITLE
[Crash]: Crash after change Dimension

### ISSUE THREAD

**Issue by fatraxx** [AllTheMods/ATM-10#45]
### Possible Fixes

Yes

### Modpack Version

10-0.5

### What happened?

everytime when i go through netherportal or use /home or /back and change dimension, the game crashes.

### Crash Log

https://gist.github.com/fatraxx/aca5e7febda8d51da5941f77109e3f02

### Latest.Log

https://gist.github.com/fatraxx/754876b61e11dc39ef6ccd6ba0b376d6

**Comment by frogalo** [comment]
All dimension changing crashes except using waystones (tried with end portal and hyperbox)
