### ISSUE TITLE
[Bug]: AEInfinityBooster Dimension Card is not working neither in the nether or in the end

### ISSUE THREAD

**Issue by bensee727** [AllTheMods/ATM-10#457]
### Possible Fixes

Yes

### Modpack Version

10-0.48

### What happened?

The dimensional card from AEInfinityBooster is not working in the nether or in the end.
I play on my server with my friends, the chunks are loaded, I even tried it in singleplayer and the problem is the same.
It says "wireless out of range".
In the overworld everything works fine, I have an infinity range booster in a wireless AP and the mentioned dimensional card in the wireless crafting terminal.
The quantum bridge works fine everywhere.

**Comment by alekthefirst** [comment]
Unable to reproduce in ATM10 2.8
