### ISSUE TITLE
[Bug]: Client disconnected with reason: The server send registries with unknown keys:

### ISSUE THREAD

**Issue by SteveStonerson** [AllTheMods/ATM-10#460]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-0.49

### What happened?

After updating the server to All the Mods 10-0.49. Clients receive the following when attempting to connect. 

[Render thread/WARN] [minecraft/ClientCommonPacketListenerImpl]: Client disconnected with reason: The server send registries with unknown keys: ResourceKey[minecraft:block / amendments:double_cake]

### latest.log

https://gist.github.com/SteveStonerson/14701055641f9101827e87b007ef4887

**Comment by Nekkusu3** [comment]
@ atm10 devs
moonlight-1.21-2.14.16-neoforge.jar is broken.
Probably best to just remove it and the corresponding mods from the ATM10 Modlist until its stable. They did a roundabout port for Neoforge but theres tons of broken things.
Please test your releases not only in a local instance! Quite annoying to fix it manually and having the server down for hours.

**Comment by SteveStonerson** [comment]
> @ atm10 devs moonlight-1.21-2.14.16-neoforge.jar is broken. Probably best to just remove it and the corresponding mods from the ATM10 Modlist until its stable. They did a roundabout port for Neoforge but theres tons of broken things. Please test your releases not only in a local instance! Quite annoying to fix it manually and having the server down for hours.

Oh, just removed amendments-1.21-1.2.10-neoforge from server and client and can now join. Seems to be stable.

**Comment by TigerWalts** [comment]
This bug didn't happen for me but it did for another player. This explains why it could have been missed.

It looks like the Double Cake block is not being registered on the client for some players. No idea yet on what determines this.

**Comment by SteveStonerson** [comment]
Fixed in All the Mods 10-0.52
