### ISSUE TITLE
[Bug]: There is no MODs or way to save XP from character in ATM-10.

### ISSUE THREAD

**Issue by SirTwsted** [AllTheMods/ATM-10#462]
### Possible Fixes

Yes

### Modpack Version

v10-0.48

### What happened?

I tried to find a way to save my XP in the mod pack, there are no mods in the pack that would allow me to do this.
I searched within J.E.I. and could not find a method to do this.  Unless I am missing something here.  🤷‍♀️
 
Please install a mod that does this.  Thank you.  🥰

**Comment by TobyD** [comment]
You can get the most advanced pump upgrade for your backpack, along with a tank upgrade to store player XP.

**Comment by EnotScript** [comment]
Pneumaticcraft: memory card, air interface.

**Comment by dgacias** [comment]
I was able to extract levels from my character in ATM10 to craft Xpetrified Orbs, here is the setup:

<img width="1344" height="885" alt="Image" src="https://github.com/user-attachments/assets/ad4d54b0-b449-4c84-bd11-4f71db3848bf" />
