### ISSUE TITLE
[Crash]: Game crash when typing in AE2 crafting terminal

### ISSUE THREAD

**Issue by TobyD** [AllTheMods/ATM-10#463]
### Possible Fixes

Yes

### Modpack Version

0.49

### What happened?

Searching anything in the AE2 crafting terminal crashes the game. Upgraded world from 0.47.

### Crash Log

https://gist.github.com/TobyD/633aa5258128b3ee084c50d3e16cc643

**Comment by valourt** [comment]
I'm getting the same issue. Upgraded from 0.48

**Comment by EnotScript** [comment]
same issue
[crash-2024-09-10_16.11.13-client.txt](https://github.com/user-attachments/files/16942403/crash-2024-09-10_16.11.13-client.txt)

**Comment by samikcay** [comment]
yeah same for me

**Comment by Satze67** [comment]
I had the same problem. I removed Amendments and Moonlight. Seems to work now

**Comment by marcos-costa94** [comment]
The crash stopped when i changed for only AE2 my storage, and stopped to use "sophisticated storage"

**Comment by marcos-costa94** [comment]
The crash stopped when i changed for only AE2 my storage, and stopped to use "sophisticated storage"

After I disconnected the "ME storage bus" from the "sophisticated storage" my terminal stopped crashing.

The sophisticated storage chests are storing a massive amount of items, and I believe that ae2 is crashing when trying to interact with these items.

**Comment by TobyD** [comment]
Removing amendments worked for me.

**Comment by alekthefirst** [comment]
Initially resolved in ATM10 0.50 and 0.51 by removing moonlight and amendments, later resolved in those mods
