### ISSUE TITLE
[Bug]: Building gadget. settings

### ISSUE THREAD

**Issue by EnotScript** [AllTheMods/ATM-10#465]
### Possible Fixes

Yes

### Modpack Version

0.49

### What happened?

Building gadget settings menu not opening. Just a blurry screen with no settings. Same problem with FPS Reducer.

**Comment by ProjectNiu** [comment]
> Go to options, accessibility settings, then change Menu Background Blur to Off
> 
> [#251 (comment)](https://github.com/AllTheMods/ATM-10/issues/251#issuecomment-2340069012)

I love you
