### ISSUE TITLE
[Crash]: Game crashes when interacting with Extreme reactors

### ISSUE THREAD

**Issue by TheMasterTM69** [AllTheMods/ATM-10#466]
### Possible Fixes

Yes

### Modpack Version

0.49

### What happened?

Breaking a reactor/turbine while its turned on - high chance of crashing a game
Sending a redstone signal to a turbine while its turned on/off - crashes game
Connecting Integrated dynamics export bus to a turbine - also crashes the game
Ive been trying to get over it but basically any interaction with this mod instantly crashes the game even to the point it corrupts the files and the modpack cannot be played until you update the version to a new pack and only then it becomes playable (aka the game will actually open and let you join the world)
All errors usually either point to sodium or anything render-related.
Its honestly first time im having this many issues with an ATM pack as every other one ran pretty much perfectly.

### Crash Log

https://gist.github.com/TheMasterTM69/881c9f8fb0d439a8c4494874086c67db

### Latest.Log

https://gist.github.com/TheMasterTM69/ca7e2f100d57cd521e37176cf58d1a9e

**Comment by alekthefirst** [comment]
Ultimately its on ER to fix this
https://github.com/ZeroNoRyouki/ExtremeReactors2/issues/171
