### ISSUE TITLE
[Crash]: Applied energistics 2 terminal Crash

### ISSUE THREAD

**Issue by marcos-costa94** [AllTheMods/ATM-10#467]
### Possible Fixes

Yes

### Modpack Version

0.49

### What happened?

When opening the AE2 terminal and typing anything into the terminal, the game freezes the image, a message about saving the world appears and then crashes.

I play on a server with 5 other people, and I was the only one who had this problem. I restored the folder, and created a new clean instance, without any customization, and still the crash continues.

### Crash Log

https://gist.github.com/marcos-costa94/6a337e4ebbe949cdf714d8ad76b770d7

### Latest.Log

https://gist.github.com/marcos-costa94/7f11983d8ecacb60aaed240ecd18a309

**Comment by marcos-costa94** [comment]
The crash stopped when i changed for only AE2 my storage, and stopped to use "sophisticated storage"

**Comment by marcos-costa94** [comment]
After I disconnected the "ME storage bus" from the "sophisticated storage" my terminal stopped crashing.

The sophisticated storage chests are storing a massive amount of items, and I believe that ae2 is crashing when trying to interact with these items.

**Comment by Hamude99** [comment]
This can also be fixed by simply removing the mod Amendments

**Comment by marcos-costa94** [comment]
> This can also be fixed by simply removing the mod Amendments

I play in server, i can't remove any mod.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/463
