### ISSUE TITLE
[Crash]: searching in crafting terminal

### ISSUE THREAD

**Issue by ktosh4577** [AllTheMods/ATM-10#468]
### Possible Fixes

Yes

### Modpack Version

0.49

### What happened?

Went to search in AE2 crafting terminal and game crashed.

### Crash Log

https://gist.github.com/ktosh4577/09e5d0f410fdeb4db8b6969df335b792

**Comment by shade1822226911** [comment]
Conflict with a mod called Amendments. Delete the mod from the files

**Comment by marcos-costa94** [comment]
I play on the server, I can't delete this mod. Because if I delete it, I can't enter the server.

**Comment by marcos-costa94** [comment]
The crash stopped when i changed for only AE2 my storage, and stopped to use "sophisticated storage"

**Comment by marcos-costa94** [comment]
The crash stopped when i changed for only AE2 my storage, and stopped to use "sophisticated storage"

After I disconnected the "ME storage bus" from the "sophisticated storage" my terminal stopped crashing.

The sophisticated storage chests are storing a massive amount of items, and I believe that ae2 is crashing when trying to interact with these items.

**Comment by ktosh4577** [comment]
I don't have a storage bus attached to anything from "sophisticated storage".

**Comment by shade1822226911** [comment]
i had the crash but it was from amendments, so i'm not sure how to fix this issue

**Comment by ktosh4577** [comment]
I removed/ renamed the Amendments jar file to .bac on both the server and client and that fixed my issue

**Comment by agusmor** [comment]
Disabling Amendments fixed it for me as well

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/463
