### ISSUE TITLE
[Bug]: Unable to use reaction chamber from ExtendedAE,  effectively locking out the quantum computer

### ISSUE THREAD

**Issue by shade1822226911** [AllTheMods/ATM-10#469]
### Possible Fixes

Yes

### Modpack Version

0.49

### What happened?

As the title says, using the reaction chamber from the mod ExtendedAE kicks you out of the world but not the game

**Comment by shade1822226911** [comment]
actually, you can still use the reaction chamber, you just have to input the ingredients via hopper or pattern provider

**Comment by pedroksl** [comment]
The issue was actually related to having a network tool somewhere in your inventory while trying to open the reaction chamber. It is fixed now and should be in the pack as soon as it updates to a newer release which I'll generate soon.
