### ISSUE TITLE
[Bug]: v0.49 & v0.50 Server Send Registries with Unknown Keys

### ISSUE THREAD

**Issue by tspurr** [AllTheMods/ATM-10#470]
### Possible Fixes

Yes

### Modpack Version

v0.50

### What happened?

Updated server and client to v0.49 and v0.50 both having the same issue upon connecting to the server. "The server send registries with unknown keys: ResourceKey[minecraft:block / amendments:double_cake]"

![image](https://github.com/user-attachments/assets/f1caa47d-dc6e-4ea7-aead-c8c89d769287)

**Comment by tspurr** [comment]
Someone else was able to log into the server and move around. They did not update to a new profile when updating the pack. They traveled to current spawn in location of my character and no kicking has occurred.

Have tried on my end doing a fresh install of the pack to a new profile and still getting the same issue on log in.

**Comment by tspurr** [comment]
Current work around is to disable the Amendments mod on client and server to run pack. Haven't seen any issues since it was a recent addition to the pack in v0.49.

**Comment by Jerbear0** [comment]
From what i heard in 0.52 this is supposedly fixed

**Comment by Japa2911** [comment]
0.52 com erro ainda. Já tentei instalação limpa, apagar arquivos, porém sem sucesso...

"0.52 with error still. I've already tried clean installation, deleting files, but without success..."

![image](https://github.com/user-attachments/assets/0477032c-e740-4458-b2d8-3dec927fcba1)

**Comment by Japa2911** [comment]
> 0.52 com erro ainda. Já tentei instalação limpa, apagar arquivos, porém sem sucesso...
> 
> "0.52 with error still. I've already tried clean installation, deleting files, but without success..."
> 
> ![image](https://private-user-images.githubusercontent.com/37105962/367791280-0477032c-e740-4458-b2d8-3dec927fcba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTYwNzQsIm5iZiI6MTcyNjQ5NTc3NCwicGF0aCI6Ii8zNzEwNTk2Mi8zNjc3OTEyODAtMDQ3NzAzMmMtZTc0MC00NDU4LWIyZDgtM2RlYzkyN2ZjYmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE0MDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMTM3NDcxZGU2Nzk1MThiYTlkZmQ0OWQ0OGYyNmQ2ZTQ0YzAyMjNiNzA5YWU5ZjdjYWYxNTM0NmQ5OTIwYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oo8sm0OyEtubG9vkIPcTn_wL1IK_Ivwqr8NvGoqQFHs)

Solução temporária foi excluindo o scritp "shattered_singularity" do lado do servidor, no caminho ./kubejs/startup_scripts/Applied Energistics

A temporary solution was to delete the "shattered_singularity" script from the server side, located at the path ./kubejs/startup_scripts/Applied Energistics.
