### ISSUE TITLE
[Bug]: Deep Learner Curios

### ISSUE THREAD

**Issue by GoncaloLP** [AllTheMods/ATM-10#472]
### Possible Fixes

Yes

### Modpack Version

0.49

### What happened?

You can't put the DeepLearner in the curios slot

**Comment by Cordelya** [comment]
I also noticed this. There's a slot for the Deep Learner, but you can't place the DL into the slot.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/416
