### ISSUE TITLE
[Crash]: Boon of the earth enchant crashes the game when used with quarry from QuarryPlus

### ISSUE THREAD

**Issue by sma342** [AllTheMods/ATM-10#474]
### Possible Fixes

Yes

### Modpack Version

0.48

### What happened?

Putting boon of the earth enchant on quarry plus crashes the game as soon as quarry tries to mine stone. The problem still occurs in 0.51.

### Crash Log

https://gist.github.com/sma342/56aa6271c0a7419d7e1bed53f4115038

**Comment by alekthefirst** [comment]
Quarry with boon no longer crashes the game, tested with ATM10 version 2.8
https://github.com/user-attachments/assets/7803f254-0416-441e-8b68-85e969449330
