### ISSUE TITLE
[Bug]: Not connecting to servers because "kubejs:shattered_singularity"

### ISSUE THREAD

**Issue by itzamega** [AllTheMods/ATM-10#476]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

"The server send registries with unknown keys: ResourceKey[minecraft:item / kubejs:shattered_singularity]

**Comment by trolhamonas** [comment]
I am also having this issue on version 0.52

**Comment by alekthefirst** [comment]
The usual cause is not updating the server correctly
Make sure old kubejs files (and other files) are removed before update as per the update guide
https://allthemods.github.io/alltheguides/help/server/#updating
