### ISSUE TITLE
[Bug]: Reaction chamber causing crash

### ISSUE THREAD

**Issue by kingnote** [AllTheMods/ATM-10#477]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

The Advanced AE reaction chamber is causing me to crash. (Failed to open screen with Advanced data: java.lang.illegalstate Exception: Screen is missing Required image: toolbox ) . I am on the latest version available to me (0.52).
![image_2024-09-11_035749067](https://github.com/user-attachments/assets/637427ab-267a-462b-94c3-c36a695e1d76)

**Comment by shade1822226911** [comment]
there is a workaround of not using the gui and inserting items via pattern provider or hoppers, for speed upgrades just shift right click the reaction chamber.

**Comment by pedroksl** [comment]
The issue was actually related to having a network tool somewhere in your inventory while trying to open the reaction chamber. It is fixed now and should be in the pack as soon as it updates to a newer release which I'll generate soon.

**Comment by shade1822226911** [comment]
now that i think about it, i did have a network tool whenever i attempted to access it. thanks for fixing it

**Comment by alekthefirst** [comment]
Fixed in AAE 0.4.4, released with ATM10 0.53
