### ISSUE TITLE
[Bug]: Scorching Caves and Deep Dark biome are swapped in natures compass

### ISSUE THREAD

**Issue by AndroidWall4680** [AllTheMods/ATM-10#479]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

When using the natures compass to search for a biome, the Deep Dark biome leads to the Scorching Caves biome and vice versa.

**Comment by alekthefirst** [comment]
Issue can not be reproduced on ATM10 2.8, natures compass takes me to correct biome

https://github.com/user-attachments/assets/7cfa254a-da55-4561-8367-6c81b05a4d0f
