### ISSUE TITLE
[Bug]: Silicon essence craft

### ISSUE THREAD

**Issue by brokenscrub** [AllTheMods/ATM-10#481]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

![image](https://github.com/user-attachments/assets/1b083ddb-6fa9-457e-9858-d315ec1def3a)
Silicon essence has a blank recipe, when using fabricator from xycraft it defaults to the blank one, voiding the essence

**Comment by RifticalRex** [comment]
most probably broken craft due to refined storage not being present. not sure though
