### ISSUE TITLE
[Bug]: Iron Jetpack's Jetpacks gone after 0.51b

### ISSUE THREAD

**Issue by TheLostWinchester** [AllTheMods/ATM-10#485]
### Possible Fixes

Yes

### Modpack Version

0.51b

### What happened?

Updated modpack to 0.51b and all the Iron Jetpack recipes are gone.
My diamond Jetpack is also gone.

### latest.log

https://gist.github.com/TheLostWinchester/c478c90b16c431e1372eb4fd32c890a5

**Comment by agusmor** [comment]
Same for me

**Comment by TheLostWinchester** [comment]
Fixed by completely reinstalling the modpack. Including the backup profiles. It is recommended to remove the folder with your world from the folder Instances > All the Mods 10 - ATM10 > saves and saving it in another place otherwise deleting and removing the backup will wipe your worlds.
