### ISSUE TITLE
[Bug]: Can't craft mystical enlightenment in the enchanter of mystical agriculture

### ISSUE THREAD

**Issue by DJ7752** [AllTheMods/ATM-10#487]
### Possible Fixes

Yes

### Modpack Version

0.51b

### What happened?

When you put all the itens required to produce the enchantment, it donsen't work.

**Comment by Cordelya** [comment]
I tried to create a Looting book earlier today using the Enchanter and couldn't craft that one.

**Comment by RussellBurkhart** [comment]
Problem still persists after update 

v0.52
