### ISSUE TITLE
[Bug]: steel seeds arent craftable

### ISSUE THREAD

**Issue by RifticalRex** [AllTheMods/ATM-10#496]
### Possible Fixes

Yes

### Modpack Version

0.51b

### What happened?

you can't craft steel seeds even can't see the recipe in EMI. The Item exists but unobtainable

**Comment by TheEnderHacker** [comment]
I noticed this bug as well and reported it in the Mystical Agriculture issues. Here's the thread: https://github.com/BlakeBr0/MysticalAgriculture/issues/720. The owner said it’s not their bug, but I think they described the issue here, and they believe the problem lies with ATM10.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/367
