### ISSUE TITLE
[Bug]: Error first launching on debian 11

### ISSUE THREAD

**Issue by SeigneurGhost** [AllTheMods/ATM-10#5]
### Possible Fixes

Yes

### Modpack Version

0.1

### What happened?

Hello,

I Test install ATM10 on my VPS (Debian 11) but i have one error :
```
root@doubiland:/home/atm10# ./startserver.sh
Error: could not open `librariesnetneoforgedneoforge%NEOFORGE_VERSION%/win_args.txt'
```
I fixed the bugged line 64 on startserver.sh by 
`"${ATM10_JAVA:-java}" @user_jvm_args.txt @libraries/net/neoforged/neoforge/$NEOFORGE_VERSION/win_args.txt nogui`

But now I have this error and I can't resolve it.
```
root@doubiland:/home/atm10# ./startserver.sh
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-exports
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens
Error: Could not find or load main class cpw.mods.bootstraplauncher.BootstrapLauncher
Caused by: java.lang.ClassNotFoundException: cpw.mods.bootstraplauncher.BootstrapLauncher

```

My Java 21 deb : jdk-21_linux-x64_bin.deb (=> oracle site)

Does anyone have an idea please?
Thanks for u help.

**Comment by 0belous** [comment]
Having the same issue on Ubuntu Server 24.04.
Tried the same thing as OP and got the same error.

Running the jar file manually seems to suggest it is corrupted
```
obelous@ubuntu:~/atm10/libraries/net/neoforged/neoforge/21.0.24-beta$ java -jar neoforge-21.0.24-beta-universal.jar
no main manifest attribute, in neoforge-21.0.24-beta-universal.jar

obelous@ubuntu:~/atm10/libraries/net/neoforged/neoforge/21.0.24-beta$ java -jar neoforge-21.0.24-beta-server.jar
Error: Invalid or corrupt jarfile neoforge-21.0.24-beta-server.jar
```

**Comment by 0belous** [comment]
Do `bash run.sh` instead of `bash startserver.sh`

**Comment by whatthedrunk** [comment]
This was my bad. Server files for 0.2 have fixed the issue. They should be approved any minute.
