### ISSUE TITLE
[Bug]:  ATM 10-0-0.5 Turtle don't dig, but crash game   (Version 0.4 is ok, Turtle work fine))

### ISSUE THREAD

**Issue by gogedo** [AllTheMods/ATM-10#50]
### Possible Fixes

Yes

### Modpack Version

ATM 10-0.5

### What happened?

Time: 2024-07-02 14:06:15
Description: Ticking block entity

java.lang.NoClassDefFoundError: net/neoforged/neoforge/common/ToolActions
	at TRANSFORMER/computercraft@1.111.0/

**Comment by Kurunoa** [comment]
Confirmed still an issue on ATM-0.6

**Comment by Kurunoa** [comment]
Confirmed still an issue on ATM-0.7
