### ISSUE TITLE
[Bug]: Theurgy cant create ATM from Netherite

### ISSUE THREAD

**Issue by sprocketaudio** [AllTheMods/ATM-10#500]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

As both Netherite and ATM have the same Sulfur tags from Theurgy (Precious Metals), shouldn't you be able to turn Netherite into ATM?

I have tried this and it doesnt work. If this is intendend, shouldn't the tags be different?

**Comment by klikli-dev** [comment]
Hi, I am the Author of Theurgy and can add some context. 

I did not add recipes for the conversion as I was not sure about balancing.
ATM devs can add recipes with datapack or using the kubejs addon.
Alternatively, as ATM is exclusive to the ATM packs, they can also suggest a default conversion rate that I can add on my end.

**Comment by sprocketaudio** [comment]
> Hi, I am the Author of Theurgy and can add some context.
> 
> I did not add recipes for the conversion as I was not sure about balancing. ATM devs can add recipes with datapack or using the kubejs addon. Alternatively, as ATM is exclusive to the ATM packs, they can also suggest a default conversion rate that I can add on my end.

Thanks for this :)
