### ISSUE TITLE
[Bug]: The Sophisticated Storage item <Storage Controller> is not craftable

### ISSUE THREAD

**Issue by Rainer8** [AllTheMods/ATM-10#503]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

I am trying to craft the Sophisticated Storage "Storage controller" and the middle item (either chest or barrel) is not accepted into the slot, thus the item is not craftable.

Reproduction: open any survival work and try crafting the Storage Controller.

![image](https://github.com/user-attachments/assets/471fecb3-7c9f-4d8e-a1d7-6f3b39e88019)

**Comment by rodopoulos1** [comment]
same here

**Comment by Arnaen** [comment]
i have the same problem, a workaround in 0.53 is to do it in the xycraft crafter, there it works. not Tested in 0.56
