### ISSUE TITLE
[Bug]: Math on Powah Spirited Crystal block broken

### ISSUE THREAD

**Issue by McKitten** [AllTheMods/ATM-10#504]
### Possible Fixes

Yes

### Modpack Version

52

### What happened?

A block of Emerald will take 81M to change into spirited.
A single Emerald will take 1M to change into spirited. 
There may be other (repeated) glitches but I got a single spirited crystal as a reward and started doing them individually even tho the thermo at that stage requires 9.

**Comment by inputTTS** [comment]
I did some research into this, looking to fix it. 

Block of emerald -> block of spirited crystal does use 81M as defined in the [source of AllTheCompressed](https://github.com/Pdiddy973/AllTheCompressed/blob/main/src/main/java/com/Pdiddy973/AllTheCompressed/data/server/CraftingRecipes.java) line 79

emerald to spirited crystal gets it's recipe from [powah directly](https://github.com/owmii/Powah/blob/1.16/src/main/resources/data/powah/recipes/energizing/spirited_crystal.json)

The emerald block recipe seems to be technically making a 0x compressed version of spirited crystal blocks, the 1x compressed version of spirited crystal block needs 9 times as much FE to energize (729M). I don't see any energizing recipes for 2x emerald block or higher.

Niotic block is 9x the cost to energize as niotic crystal, and the math continues nicely up to niotic block 3x.
Energized steel also follows the correct ratio.

**Comment by alekthefirst** [comment]
Was fixed in AllTheCompressed 4.0.1 released with ATM10 0.61
