### ISSUE TITLE
[Bug]: just dire things overlay

### ISSUE THREAD

**Issue by mirttoo** [AllTheMods/ATM-10#505]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

just dire things have opened a overlay, and i cant find any info about it, how to close/remove, its lagging my minecraft, i get like 7 fps on 
![print](https://github.com/user-attachments/assets/7443b9cc-1604-4995-a122-c2da138f4f8f)

**Comment by mirttoo** [comment]
I've already deleted my player data from the server, I've already reinstalled the modpack and still this continues

**Comment by RifticalRex** [comment]
If you mean the thing under your map its quests that you pinned. easy fix just go into quests and unpin them
