### ISSUE TITLE
[Bug]: Mystical Agriculture Upgrades bug

### ISSUE THREAD

**Issue by JojoCraftPoke** [AllTheMods/ATM-10#507]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

every time I quit and then log back into my world in ATM 10 the mystical agriculture upgrades disappear from my armor and sword.

**Comment by alekthefirst** [comment]
Known issue, already fixed in MA, expect to see it in the next atm10 release (no eta provided)
