### ISSUE TITLE
[Crash]: EMI recipe crash

### ISSUE THREAD

**Issue by Hennaz480** [AllTheMods/ATM-10#508]
### Possible Fixes

Yes

### Modpack Version

10-0.52

### What happened?

Clicking on the recipe doesn't show the recipe for the item and sometimes crashes instead of showing it. 

### Crash Log

https://gist.github.com/Hennaz480/44cd42333f190858a4180af0fc01433d

**Comment by EnderDrag0n** [comment]
Which recipe crashes game?
