### ISSUE TITLE
[Crash]: Hyperbox Causes Server Cashe

### ISSUE THREAD

**Issue by nikkel** [AllTheMods/ATM-10#51]
### Possible Fixes

Yes

### Modpack Version

0.5

### What happened?

When entering/exiting the Hyperbox it causes the server to crash. When I restart the server and log back in I'll be in the other dimention.

For instance, if I enter from the overworld it would crash, once the server restarts and I've logged in I'll be in the hyperbox dimention. If I attempt to leave it will crash when I restart and login I'll back back in the overworld.

### Crash Log

https://gist.github.com/nikkel/e1ecc515a423e5a0d141445a482833c2

### Latest.Log

https://gist.github.com/nikkel/0f855c20255b6f71e4ba2b0db761f4de

**Comment by nikkel** [comment]
If you need a more recently lastest.log I can recreate the crash and reupload both log files.

**Comment by frogalo** [comment]
Fixed in 0.6

**Comment by nikkel** [comment]
Yeah, seems to be fix!
Thanks @frogalo
