### ISSUE TITLE
[Bug]: Ore unification with Mekanism ore processing: osmium, tin, lead

### ISSUE THREAD

**Issue by Mithi83** [AllTheMods/ATM-10#512]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

I have a Mekanism ore processing setup and end up with osmium ingots from Mekanism (mekanism:osmium_ingot) rather than the one from AllTheOres (alltheores:osmium_ingot) as I would expect from what is displayed (or rather hidden) in EMI.

Input for all the following setups is Raw Osmium (obtained from Productive Bees) from AllTheOres. The same is true for other ores, such as tin and lead that are added by Mekanism. Other ores not present in Mekanism, such as silver for example are processed as expected.

Ore Processing Tier 0:
- Put Raw Osmium (AllTheOres) in Ultimate Smelting Factory and receive Osmium Ingot (AllTheOres) -> no problem

Ore Processing Tier 1:
- Put Raw Osmium (AllTheOres) in Ultimate Enriching Factory and receive Osmium Dust (Mekanism)
- Put that in a Ultimate Smelting Factory and receive Osmium Ingot (Mekanism)

Ore Processing Tier 2:
- Put Raw Osmium (AllTheOres) in Ultimate Purification Factory and receive Osmium Clump (Mekanism)
- Put that in Ultimate Crushing Factory and receive Dirty Osmium Dust (Mekanism)
- Put that in Ultimate Enriching Factory and receive Osmium Dust (Mekanism)
- Put that in a Ultimate Smelting Factory and receive Osmium Ingot (Mekanism)

Ore Processing Tier 3:
- Put Raw Osmium (AllTheOres) in Ultimate Injecting Factory and receive Osmium Shard (Mekanism)
- Put that in Ultimate Purification Factory and receive Osmium Clump (Mekanism)
- Put that in Ultimate Crushing Factory and receive Dirty Osmium Dust (Mekanism)
- Put that in Ultimate Enriching Factory and receive Osmium Dust (Mekanism)
- Put that in a Ultimate Smelting Factory and receive Osmium Ingot (Mekanism)

I haven't yet set up Tier 4 but I'd expect it to behave similarly.

My expectation would be that ores/dusts/dirty dusts/shards/crystals/clean slurries/slurries of ores added by Mekanism are unified as well, because I was quite surprised to find different osmium ingots in my AE2 storage after a while when upgrading through the different tiers of ore processing. I noticed this problem when I tried autocrafting Steel Casing (Mekanism) and it would not accept the osmium ingot (Mekanism), but this was due to me disabling substitutions in my AE2 pattern. After allowing substitutions this works, but I still consider it a bug to have two different kinds of osmium/tin/lead ingots in my AE2 storage.

### latest.log

https://gist.github.com/Mithi83/d6262fbe2381f888b595db168579b7f9

**Comment by TheBedrockMaster** [comment]
I tested a few of these and they worked as intended, please say something if any of these aren't working on the current version.
