### ISSUE TITLE
[Crash]: pneumatic craft quest crash when checking the recipe for jackhammer air

### ISSUE THREAD

**Issue by lazyKiddo67** [AllTheMods/ATM-10#515]
### Possible Fixes

Yes

### Modpack Version

All the mods 10 version 0.52

### What happened?

when i open the pneumatic craft quest and open the air quest then click on the jack hammer to get the recipe for it game crashed

### Crash Log

https://gist.github.com/lazyKiddo67/c0490a0d67b1ca9bd3bac56f5043d95c

**Comment by AndroidWall4680** [comment]
I've had the same issue
