### ISSUE TITLE
[Bug]: Mystical Agriculture 9*9 tps 0

### ISSUE THREAD

**Issue by EnotScript** [AllTheMods/ATM-10#519]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

When digging with a 9*9 modifier. The server stops for the duration of the loading. The harder the rock, the longer the digging. Not low end PC. 6c/12t, 4.5GHZ, 10gb ram 3800.

**Comment by alekthefirst** [comment]
Issue no longer present on ATM10 2.8, or if it is i am unable to reproduce it
Cannot find any relevant items MA changlogs
https://github.com/user-attachments/assets/eb573629-750f-4de3-be84-9b5b4872b658

**Comment by EnotScript** [comment]
Break deepslate

**Comment by alekthefirst** [comment]
Still nothing
Uploading Replay 2024-12-22 20-34-58.mp4…

**Comment by EnotScript** [comment]
ok i found conflict mod... my bad.  sorry for music. Initially, at the request of a person, the Vampirism mod was installed.
https://drive.google.com/file/d/1RahEYTBAj4Uu2d62iq6FP86j7EVrxuMf/view?usp=sharing
