### ISSUE TITLE
[Bug]: [10-0.6] Can not put items into iron furnace

### ISSUE THREAD

**Issue by fkamin** [AllTheMods/ATM-10#52]
### Possible Fixes

Yes

### Modpack Version

0.6

### What happened?

Can not put items into smelt slot in all types of @IronFurnaces furnaces ex. osmium dust
Fuel slot works properly

**Comment by Kevin-Marsh** [comment]
This is an issue with all dusts and thr dev is aware.

**Comment by Glittersword** [comment]
If it is items other than dust double check and make sure you don't have the blaster upgrade installed.
