### ISSUE TITLE
[Crash]: Game crashes after dragging cursor to mana potions from Ars Noveau even in inventory, chest, quest reward or NEI.

### ISSUE THREAD

**Issue by flurrya** [AllTheMods/ATM-10#521]
### Possible Fixes

No

### Modpack Version

0.49

### What happened?

The game crashed whilst rendering screen
Error: java.lang.ClassCastException: class java.lang.String cannot be cast to class net.minecraft.network.chat.Component (java.lang.String is in module java.base of loader 'bootstrap'; net.minecraft.network.chat.Component is in module minecraft@1.21.1 of loader 'TRANSFORMER' @74ebd159)
Code: -1

### Crash Log

https://gist.github.com/flurrya/bd682c2f340f2dc8561d418e9032412f

### Latest.Log

https://gist.github.com/flurrya/a051a077a5ffed7eabcee0a96a395e1d

**Comment by alekthefirst** [comment]
Issue can not be reproduced in ATM10 2.8
https://github.com/user-attachments/assets/d7bb1a10-1325-47bc-bdbf-47fc3da0503d
