### ISSUE TITLE
[Crash]: Crash while using Destruction gadget to destroy a max sized area in the nether highlands

### ISSUE THREAD

**Issue by TobyD** [AllTheMods/ATM-10#523]
### Possible Fixes

Yes

### Modpack Version

0.52

### What happened?

I was using the destruction gadget to remove a huge area of the nether highlands to look for unobtanium. The first time it worked. The second section I tried to destroy resulted in a crash. It looks like the game tried to save while the destruction was happening.

### Crash Log

https://gist.github.com/TobyD/3152d21879d17306769f34940aaaaf01

**Comment by alekthefirst** [comment]
I am unable to reproduce this, even forcing saves with the esc menu produces nothing

https://github.com/user-attachments/assets/bb3237f4-1689-4119-9d34-5064bab833e5
