### ISSUE TITLE
[Crash]: The game crashed whilst initializing game

### ISSUE THREAD

**Issue by Lupedosa** [AllTheMods/ATM-10#524]
### Possible Fixes

Yes

### Modpack Version

All the mods 10-0.52

### What happened?

I click "play", the loading screen opens up and after a few seconds it crashes with the message

"
The game crashed whilst initializing game
Error: java.lang.IllegalAccessError: class net.caffeinemc.mods.sodium.client.compatibility.checks.ModuleScanner (in module net.caffeinemc.mods.sodium.neoforge.beta._1.mc1._21.service) cannot access class net.minecraft.client.Minecraft (in module minecraft) because module net.caffeinemc.mods.sodium.neoforge.beta._1.mc1._21.service does not read module minecraft
"

### Crash Log

https://gist.github.com/Lupedosa/4b8bf9e10788b581c2f863b29d886d62

### Latest.Log

https://gist.github.com/Lupedosa/ccf89e1032f9c611943bb85a730c615c

**Comment by EnderDrag0n** [comment]
- Have you modified modpack? If yes, which mods have you added (found on internet that Valkyrien Skies can cause that crash)?
- What is your OS?

**Comment by Lupedosa** [comment]
This issue was due to my RivaTurner not being updated, thanks
