### ISSUE TITLE
[Bug]: Mystical agriculture night vision augment not working

### ISSUE THREAD

**Issue by Jocky69** [AllTheMods/ATM-10#528]
### Possible Fixes

Yes

### Modpack Version

0.53

### What happened?

I put the night vision augment in my tertium helmet but it doesn't work. It's still dark in caves and during nights.

**Comment by Arnaen** [comment]
same problem in 0.56

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/321

**Comment by Jocky69** [comment]
Hi. Sorry for the dupe. I didn't saw it. I don't know how i did it, but now they are fully functional. Not sure if it can be related with one of my resource pack. I change a few things inside my ressource pack.

Continue your good work.
________________________________
