### ISSUE TITLE
[Bug]:   Right clicking on a Diamond Furnace with a Blasting Upgrade Dupes the Upgrade

### ISSUE THREAD

**Issue by Glittersword** [AllTheMods/ATM-10#53]
### Possible Fixes

Yes

### Modpack Version

10.0.4

### What happened?

I right clicked to reinstall the Blasting Upgrade on a Diamond Furnace and it installed on the machine and spat out a duplicate upgrade.

**Comment by GadoD** [comment]
has already been fixed in current versions
