### ISSUE TITLE
[Bug]: Mythical Agriculture craft leather from cow essence recipe overshadowed / shares recipe with raw beef.

### ISSUE THREAD

**Issue by Kiveynen** [AllTheMods/ATM-10#533]
### Possible Fixes

Yes

### Modpack Version

10-0.53

### What happened?

Mythical Agriculture craft cow essence recipe for leather is overshadowed by raw beef. Both have the same formula and steaks seems to have priority.

**Comment by TheBedrockMaster** [comment]
Luckily there *should* be a button to switch the recipe.

![image](https://github.com/user-attachments/assets/01e99ab7-d8e3-4cea-9e60-2006b2bef5a6)
