### ISSUE TITLE
[Bug]: Deep Learner cannot be put into Deep Learner Slot

### ISSUE THREAD

**Issue by onyxfl98** [AllTheMods/ATM-10#537]
### Possible Fixes

Yes

### Modpack Version

0.53

### What happened?

Ever since the Deep Learner was added with Hostile Neural Networks it cannot be placed in the Deep Learner curio slot.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/416
