### ISSUE TITLE
[Bug]: can't plant mystical agriculture Certus quartz seed

### ISSUE THREAD

**Issue by Ethernel0** [AllTheMods/ATM-10#538]
### Possible Fixes

No

### Modpack Version

0.53

### What happened?

Able to craft Certus quartz seed from Mystical agriculture but seems like I can't plant them.
Tried with different farmland of different tiers 

![image](https://github.com/user-attachments/assets/fd486c62-dfe2-4c2a-a14c-282265200d65)

**Comment by dKatsuro** [comment]
Works fine for me.
It looks like you don't have enough light, try placing a light source closer.

**Comment by Ethernel0** [comment]
> Works fine for me. It looks like you don't have enough light, try placing a light source closer.
**Holy sh.., Idk why it didn't came to my mind
Yes it does work ! thanks !**
