### ISSUE TITLE
[Bug]: Guardians dealing on meka suit with Full upgrade 

### ISSUE THREAD

**Issue by tutufeli11111** [AllTheMods/ATM-10#549]
### Possible Fixes

Yes

### Modpack Version

53

### What happened?

I was going to Farm guardians with the meka suit equipped and i get damage to the bean

**Comment by alekthefirst** [comment]
Issue has since been resolved, guardians do not hurt me through the meka suit
https://github.com/user-attachments/assets/7706d3ea-aacc-40c1-b454-17503f259eb2
