### ISSUE TITLE
[Bug]: DimStorage private dimensional chests and tanks reset inventory after owner relogs

### ISSUE THREAD

**Issue by Godai009** [AllTheMods/ATM-10#551]
### Possible Fixes

Yes

### Modpack Version

0.53

### What happened?

Privatized dimensional chests or tanks work as expected until after the owner relogs. The mod seems to randomly create a new empty inventory based on some ID not related to the owner's Minecraft UUID. Public chests and tanks are unaffected.
![dimstorage](https://github.com/user-attachments/assets/5c0275c2-879b-4038-96d8-5fba28ebd18c)

**Comment by imaboon** [comment]
It happened to me, lost all loot, after changing settings like who ia the owner, privacy or frequency, and the auto collecting pick up items and void it.

**Comment by Edivad99** [comment]
Fixed in this version: DimStorage-1.21-9.0.2
