### ISSUE TITLE
When going over bottle (just a regulair water bottle no name) with cursor whilst in chest game crashes

### ISSUE THREAD

**Issue by roggeltje** [AllTheMods/ATM-10#555]
### Possible Fixes

Yes

### Modpack Version

0.49

### What happened?

When going over bottle (just a regulair water bottle no name) with cursor whilst in chest game crashes, when i accepted a quest one of these bottles apeard in my inventory and now every time i press E to open inventory my game crashes, this also happens when going over it with your cursor in a chest.

### Crash Log

The game crashed whilst rendering screen Error: java.lang.ClassCastException: class java.lang.String cannot be cast to class net.minecraft.network.chat.Component (java.lang.String is in module java.base of loader 'bootstrap'; net.minecraft.network.chat.Component is in module minecraft@1.21.1 of loader 'TRANSFORMER' @4403bff8)

**Comment by roggeltje** [comment]
Edit: it did not found any fix for it

**Comment by alekthefirst** [comment]
> Edit: it did not found any fix for it

This issue has been fixed in newer versions of atm10
