### ISSUE TITLE
[Bug]: Super Factory Manager does not work probably 

### ISSUE THREAD

**Issue by Nachhaltiger** [AllTheMods/ATM-10#562]
### Possible Fixes

Yes

### Modpack Version

10-0.55

### What happened?

Super Factory Manager does not work in the ATM10 modpack. You can open the disk or the labegun in the hand. It opens just a blur screen.

**Comment by inputTTS** [comment]
Does going into your minecraft settings in game, into accessibility, and then setting Menu Background Blur to OFF fix it?
