### ISSUE TITLE
[Bug]: extract does not work with grains infinity

### ISSUE THREAD

**Issue by Breniim** [AllTheMods/ATM-10#563]
### Possible Fixes

Yes

### Modpack Version

10-0-55

### What happened?

The xycraft extractor does not work according to JEI to extract grain infinty

![image](https://github.com/user-attachments/assets/bf7413ee-8823-4391-918f-ae4109681f04)
![image](https://github.com/user-attachments/assets/23480f0f-3583-4f94-ae31-661905e26ac6)

### latest.log

https://gist.github.com/Breniim/8953a77773c7466d82d497445f4c0df8

**Comment by peterromfeldhk** [comment]
it needs a fie under the middle block, its not shown properly in JEI :(

**Comment by Breniim** [comment]
@peterromfeldhk Good afternoon, I don't speak English fluently and I was a little confused when translating. What would this missing block be?

Could you send a print of how it should be done, if possible of course.

**Comment by peterromfeldhk** [comment]
@Breniim 
![2024-11-07_13 27 17](https://github.com/user-attachments/assets/d8678564-6195-4c6f-969a-0fc5eb4abce0)
