### ISSUE TITLE
[Crash]: Typing in Creative inventory search

### ISSUE THREAD

**Issue by TruSoggy** [AllTheMods/ATM-10#564]
### Possible Fixes

Yes

### Modpack Version

10.0.55

### What happened?

I went to the search tab and started typing. It happens everytime i try it

### Crash Log

https://gist.github.com/TruSoggy/59c0d1f3f28bf5c9db85910325fcbb17

**Comment by TheBedrockMaster** [comment]
This shouldn't still be happening in the most recent release.
