### ISSUE TITLE
[Bug]: Crash when creating allthemodium alloy tools

### ISSUE THREAD

**Issue by Gabriel-Hiss** [AllTheMods/ATM-10#570]
### Possible Fixes

Yes

### Modpack Version

0.55

### What happened?

when i craft a allthemodium alloy tools kubejs crashes the server because of the nbt i fixed the kubejs scripts
the script and error print is on the archives below
![image](https://github.com/user-attachments/assets/1740d50f-a006-4a4f-a481-e6c8137fddca)

[atm_alloy_tools.txt](https://github.com/user-attachments/files/17085967/atm_alloy_tools.txt)

**Comment by Blade-jpeg** [comment]
Every time I create the atm weapons I play for a while get off and then when I get back onto the server they are gone out of my inventory
