### ISSUE TITLE
[Bug]: Bees Not Producing Pollen

### ISSUE THREAD

**Issue by Wolfepupkitten** [AllTheMods/ATM-10#587]
### Possible Fixes

Yes

### Modpack Version

10-0.56

### What happened?

After putting pollen sieves into the advanced beehives the bees are producing copies of the leaves. I let them run for a bit and they kept making leaves but no pollen. 

### latest.log

No idea how 

### Developer reports

I'm on mobile idk their GitHub but it's Productive bees

**Comment by alekthefirst** [comment]
Fixed in productive trees 0.5.3, released with ATM10 1.0

**Comment by Crunchpodx** [comment]
I'm running adv beehives with expansion with 2 omega productivity upgrades, a simulation (didn't realize the omegas do the same thing) and a sieve but I'm only getting leaves in the box.
