### ISSUE TITLE
[Bug]: ATM Alloy paxel does 25 damage and not 71 damage as indicated in JEI

### ISSUE THREAD

**Issue by DaddyLongspoon** [AllTheMods/ATM-10#590]
### Possible Fixes

Yes

### Modpack Version

10.0.56

### What happened?

Made the atm alloy paxel, it's not as great as it should be.  In fact it does the same damage as the awakened supremium paxel it was made from, so all the alloys, the diamonds, the smithing templates.. don't really do anything except make it prettier.

![IMG_1381](https://github.com/user-attachments/assets/2685f911-6880-48a8-81c1-4087f9077079)

^the one in JEI

![IMG_1382](https://github.com/user-attachments/assets/8c4ea96c-61a2-48d6-a23c-c09ecb7698b5)

^the one I got out of the ars enchanter.

**Comment by YocyCraft** [comment]
There's another issue where Alloy Paxels can't increase mining speed for woods and dirts correctly. Reported to Allthemodium repository a month ago but no response.

https://github.com/AllTheMods/AllTheModium/issues/93

**Comment by TheBedrockMaster** [comment]
It does the right amount of damage for me in the newest ATM10 release.
