### ISSUE TITLE
[Crash]: Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by bbarry** [AllTheMods/ATM-10#591]
### Possible Fixes

Yes

### Modpack Version

atm10-0.56

### What happened?

Started game, moved mouse a little and maybe stood there in my home cave for a minute?

### Crash Log

https://gist.github.com/bbarry/9f3963804137a3ea52ff813827f9ff2e

### Latest.Log

https://gist.github.com/bbarry/661008eef8d8865994501386abe5bd93

**Comment by bbarry** [comment]
Last time I remember this happening it was fish falling in a cave somewhere and leaving bloodstains?

Looks vaguely bumblezone related this time.

**Comment by alekthefirst** [comment]
Unless the issue can be reproduced in current versions of ATM10, i will consider this stale and closed.
