### ISSUE TITLE
[Crash]: Placing energy battery (Integrated dynamics) crash the game

### ISSUE THREAD

**Issue by YocyCraft** [AllTheMods/ATM-10#596]
### Possible Fixes

Yes

### Modpack Version

0.56

### What happened?

As the title

### Crash Log

https://gist.github.com/YocyCraft/6d4199d79f51fa13fd5064d2b4eb0289

### Latest.Log

https://gist.github.com/YocyCraft/071d0e8dde008c56fcf21c161313c2ce

**Comment by YocyCraft** [comment]
Fixed (but why this issue isn't closed?)

**Comment by TheBedrockMaster** [comment]
We don't always know the second a crash no longer happens.
