### ISSUE TITLE
[Bug]: Foregoing addons

### ISSUE THREAD

**Issue by Marconi99** [AllTheMods/ATM-10#598]
### Possible Fixes

Yes

### Modpack Version

10.0-56

### What happened?

The system doesn't identify when addons craft ends, so I get cancel by myself
![2024-09-25_10 25 48](https://github.com/user-attachments/assets/a08b74c4-5deb-4b50-9408-4981e8903ba3)

**Comment by DaddyLongspoon** [comment]
I had this same issue too..   I just took the patterns back to the pattern terminal and remade them, dropping the add-on which had been returned from the machine onto the result slot in the pattern, there's some subtle difference between the one you get and the one the jet draws in there.
