### ISSUE TITLE
[Bug]: Pink slime bee uses just flowers for pollination

### ISSUE THREAD

**Issue by AlmanaX-21** [AllTheMods/ATM-10#599]
### Possible Fixes

Yes

### Modpack Version

0.57 (Latest as of date)

### What happened?

Pink Slime Bees (Pink Bee) uses flowers for pollination.

This could be an oversight or intended but I think it should use a pink slime block or fluid pink slime

**Comment by DaddyLongspoon** [comment]
its been this way since at least atm7...
and the slimy bee also licks any flower to polinate.
