### ISSUE TITLE
[Crash]: Game Crashes When Cursor is Over Schematic Analyzer 

### ISSUE THREAD

**Issue by ProjectNiu** [AllTheMods/ATM-10#601]
### Possible Fixes

Yes

### Modpack Version

.57

### What happened?

When the cursor hovers over "Schematic Analyzer" (Minecolonies) the game crashes. I did add Minecolonies to the pack around 7 days ago and it happened back then too. I don't know if it is because I added it to the pack before it was officially added. 

https://github.com/user-attachments/assets/855f6d1e-db11-43a7-9fbc-8a295e22023f

### Crash Log

https://gist.github.com/ProjectNiu/24b10fd61bab947bb7642e5820c51b23

### Latest.Log

https://gist.github.com/ProjectNiu/d739640d61478a0c3e33894e019ed2d2

**Comment by TigerWalts** [comment]
Fixed in Minecolonies 1.1.709

- https://www.github.com/ldtteam/minecolonies/issues/10276
