### ISSUE TITLE
[Bug]: Philosopher's Fuel not craftable

### ISSUE THREAD

**Issue by dennis6981** [AllTheMods/ATM-10#609]
### Possible Fixes

No

### Modpack Version

0.57

### What happened?

Philosopher's Fuel cannot be crafted with the Eclipse Ember filled Dark Tank.

![2024-09-26_18 04 27](https://github.com/user-attachments/assets/c24b4841-3a30-44c0-ac9a-565d81e2646e)
![2024-09-26_18 04 05](https://github.com/user-attachments/assets/3efa1008-7af0-4aaa-8681-f0e058f42c4e)

**Comment by alekthefirst** [comment]
Put the tank on the ground
then pick it back up
it will be usable in the craft

the tank you have is probably missing the capacity tag, which it will get by doing the above
source: me, who had this issue yesterday

**Comment by dennis6981** [comment]
Thanks :+1:
