### ISSUE TITLE
[Bug]: Productive Bees Mod. The WannaBee doesn't duplicate with BaBee Upgrade.

### ISSUE THREAD

**Issue by RealPecka** [AllTheMods/ATM-10#615]
### Possible Fixes

Yes

### Modpack Version

10-0.57

### What happened?

Not sure if it's intended but the WannaBee doesn't duplicate with BaBee upgrade like it did in older modpack versions.

**Comment by alekthefirst** [comment]
BaBee only works with bees that use regular flowers for breeding. WannaBee does not and this is intended behavior
