### ISSUE TITLE
[Bug]: MA Steel Seeds recipe

### ISSUE THREAD

**Issue by MikkelAndersn** [AllTheMods/ATM-10#624]
### Possible Fixes

Yes

### Modpack Version

0.59 (latest as of 28-09-24)

### What happened?

![image](https://github.com/user-attachments/assets/93af559a-b812-474f-aec4-129f9b25856b)
The recipe for the steel seed only takes the steel from Modular Force Field mod and not the AllTheOres steel.
I dont know if you can even use that steel, i just know the ATO steel dont work.

**Comment by njasak** [comment]
Hope they fix it soon

**Comment by shade1822226911** [comment]
there is a workaround by using the mekanism oredictionifier and putting "c:ingots/steel" without quotes in the filter, then putting any steel while making sure the filter is set to mffs steel
