### ISSUE TITLE
[Bug]: ExtendedAE Recipes

### ISSUE THREAD

**Issue by FDALynch** [AllTheMods/ATM-10#625]
### Possible Fixes

Yes

### Modpack Version

10-0.59

### What happened?

The ExtendedAE mod recipes are not appearing in JEI

Example: I can't see and make the ME Extended Interface, because the recipe doesn't exist in Crystal Assembler

**Comment by Sage027** [comment]
yes you also cant craft the me extended pattern access terminal for the ATM STAR

**Comment by Pumpkin7266** [comment]
yeah need to readd EMI for now to see the recipes

**Comment by FDALynch** [comment]
I managed to fix it, you have to use the FTB Mod

https://www.curseforge.com/minecraft/mc-mods/ftb-jei-extras
