### ISSUE TITLE
[Bug]: Rubies don't generate, effectively locking out chromium automation to centrifuging redstone

### ISSUE THREAD

**Issue by shade1822226911** [AllTheMods/ATM-10#626]
### Possible Fixes

Yes

### Modpack Version

0.59

### What happened?

Rubies don't seem to generate anywhere, i also tested with digital miners from Mekanism, which means that chromium production is limited to either bees or centrifuging redstone for a 50% chance at ruby dust (which actually can't turn back to regular rubies).
![image](https://github.com/user-attachments/assets/d2aca010-0d39-4c70-b312-46a9a6f3f239)
![image](https://github.com/user-attachments/assets/916768e9-00ed-44d8-aa48-2da099847ef6)
![image](https://github.com/user-attachments/assets/82f0abad-1b8d-4321-ad66-de556b8abbfb)

**Comment by Pumpkin7266** [comment]
they generate in the mining dimension

**Comment by shade1822226911** [comment]
ok let me check that out

**Comment by shade1822226911** [comment]
ok it worked, thanks!

on an unrelated note, are you also getting minecolonies rice teleported to you when you use an magnet?
