### ISSUE TITLE
[Bug]: The game cannot proceed any further.

### ISSUE THREAD

**Issue by jungshinyung5** [AllTheMods/ATM-10#63]
### Possible Fixes

Yes

### Modpack Version

0.7

### What happened?

I'm sorry in advance because I'm using a translator.
this is single play.
I made an item called Atomic Disassembler.
And right after that,
Right-click ME Patton providerto exit the game.
crash-reports also doesn't form.

![2024-07-05_00 03 27](https://github.com/AllTheMods/ATM-10/assets/43872929/31de3ba3-76ed-4cc2-838d-0531c76ff5d8)
![2024-07-05_00 03 44](https://github.com/AllTheMods/ATM-10/assets/43872929/700ae2b2-1ddc-4962-9064-3554a2578216)
![2024-07-05_00 03 58](https://github.com/AllTheMods/ATM-10/assets/43872929/62bd411d-a621-46ee-91dc-9f0f32217fa5)
![2024-07-05_00 04 28](https://github.com/AllTheMods/ATM-10/assets/43872929/e8c8a52a-9a61-4cbc-a305-e319cd1747c6)

The last picture is my progress.

I've done this a lot, and this first happened after making the stuff I mentioned earlier and it's still repeating.

If you delete this item again, the bug will continue.

I love ATM9 to the point where I played it for 700 hours.
I hope the error is fixed quickly.
Thank you.

### latest.log

https://gist.github.com/jungshinyung5/93d1c0553e6cb8c4598b81e3d5a72611

**Comment by Kevin-Marsh** [comment]
This was a bug with Applied Flux and is now fixed.
