### ISSUE TITLE
[Bug]: AE2 absolutely spams server terminal when ME system is unloaded

### ISSUE THREAD

**Issue by LevyWilson** [AllTheMods/ATM-10#630]
### Possible Fixes

No

### Modpack Version

.59

### What happened?

Was unloading chunks in my server to increase TPS and when I unloaded one chunk with this ME system in it, the terminal got absolutely spammed with thousands of lines of "[Server thread/ERROR] [appeng.api.stacks.AEKey/]: Failed to deserialize AE key" messages. I have no idea what could be causing this besides the ME just not being chunk loaded. 

### latest.log

https://mclo.gs/FXD22fq

**Comment by alekthefirst** [comment]
this looks like an ME system with a bunch of broken relics in it
happened a few updates back
just export them into a trash bin

**Comment by LevyWilson** [comment]
That was it. Also old shattered singularity recipes in their ME. Finally found them all and the error is gone.
