### ISSUE TITLE
[Bug]: in Mystical Agriculture, monsters do not drop Inferium Essence. 

### ISSUE THREAD

**Issue by Floatingcolon** [AllTheMods/ATM-10#631]
### Possible Fixes

Yes

### Modpack Version

0.60

### What happened?

Hello, I would like to ask, in Mystical Agriculture, monsters do not drop Inferium Essence. Has this not been added yet, or is it specifically set up like this?

**Comment by alekthefirst** [comment]
the inferium drop rate is set to 0 in the mystical agriculture config file yes

**Comment by Floatingcolon** [comment]
> Inferium 的掉落率在 Mystical Agriculture 配置文件 yes 中设置为 0

Thank you for your method, otherwise relying on planting or mining would be too time-consuming
