### ISSUE TITLE
[Crash]: Pressing F3 in the other dimension causes crash

### ISSUE THREAD

**Issue by YocyCraft** [AllTheMods/ATM-10#635]
### Possible Fixes

Yes

### Modpack Version

0.60

### What happened?

As the title

### Crash Log

https://gist.github.com/YocyCraft/e71730f8b1d9f2659762b8a5761aaec3

### Latest.Log

https://gist.github.com/YocyCraft/36bfcf20fc40702cc86edbc7f7a0f2b7

**Comment by alekthefirst** [comment]
Has been reported to Terra Blender
https://github.com/Glitchfiend/TerraBlender/issues/183
