### ISSUE TITLE
[Bug]: Silicon recipe from modern industrialization doenst work

### ISSUE THREAD

**Issue by tutufeli11111** [AllTheMods/ATM-10#636]
### Possible Fixes

Yes

### Modpack Version

0.60

### What happened?

i was going to make the silicon in the eletric blast furnance from modern industrialization and the recipe doesnt go, i placed quartz dust and carbon dust, and that doesnt work.
![2024-09-29_13 58 00](https://github.com/user-attachments/assets/541bbf16-b80b-4c8b-a89f-897dd56837a5)
![2024-09-29_13 58 06](https://github.com/user-attachments/assets/12e532a3-7050-4ddb-a0ac-922123a3a106)
![2024-09-29_13 58 09](https://github.com/user-attachments/assets/497dc5ff-b4bd-4c71-9fa7-c1af4e181dcc)
![2024-09-29_13 58 30](https://github.com/user-attachments/assets/f255af2e-0f2e-44a7-a638-2e24cb935206)

**Comment by cameron581** [comment]
It’s probably because of the overdrive add on, remove that and it’ll probably go.

**Comment by shade1822226911** [comment]
i've also had this issue although i've already fixed it after realizing the overdrive addon causes this with basically every machine whenever you try to change the recipe the machine is making after building up efficiency. basically cameron581's solution
