### ISSUE TITLE
[Bug]: cant craft silicon seed from Mystical Agriculture

### ISSUE THREAD

**Issue by demonslayer2121** [AllTheMods/ATM-10#637]
### Possible Fixes

No

### Modpack Version

0.60

### What happened?

my friend tried to craft the silicon seed and he found out he couldnt even craft it

**Comment by bbarry** [comment]
To clarify, the silicon seed requires EnderIO Silicon which seems to be disabled.

All other recipes that use Silicon are changed to use the tag `c:silicon`

**Comment by Redeye123** [comment]
Can confirm . Even when trying to use the silicon that you can craft from AE2 it doesnt work .

![image](https://github.com/user-attachments/assets/40553871-32ed-4ce3-b3c4-fd538ae861e8)
