### ISSUE TITLE
[Crash]:  MineColonies issues

### ISSUE THREAD

**Issue by BonesNTea** [AllTheMods/ATM-10#638]
### Possible Fixes

Yes

### Modpack Version

10-0.60

### What happened?

Crashed while breaking/ placing plantation block from mine colonies, it told me the block was null. Went to log back in but keep getting the following crash report- "The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "journeymap.api.v2.common.waypoint.WaypointGroup.isEnabled()" because the return value of "journeymap.common.waypoint.WaypointImpl.getGroup()" is null"

### Crash Log

[---- Minecraft Crash Report ---- // Don't do that.  Time: 2024-09-29 17:43:23](https://gist.github.com/BonesNTea/2d44e54ddd1900cb3d5ac3770cd64684)

**Comment by alekthefirst** [comment]
related to https://github.com/AllTheMods/ATM-10/issues/605
