### ISSUE TITLE
[Bug]: Minecolonies Buildings can't finish if they require a lantern due to some mod changing base game lantern 

### ISSUE THREAD

**Issue by plantasia124** [AllTheMods/ATM-10#639]
### Possible Fixes

Yes

### Modpack Version

0.60

### What happened?

Building some colonies with the high magic preset and some buildings require lanterns as a resource. It does not recognize lanterns in any inventory in the builders shack as viable for the construction, and using the autofill option to pull it from the inventory works for a moment, but then will revert to missing. It is able to complete if the player places them manually where they need to go in the build, but future build may be difficult to understand where they go

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/634
