### ISSUE TITLE
[Crash]: Looks to be (not JM) hanging after (not wither incident) any death

### ISSUE THREAD

**Issue by McKitten** [AllTheMods/ATM-10#642]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-0.60

### What happened?

As per comments in curseforge (#6714135) the blast proof glass was less blast proof then last time i tried using it (atm6?) and the wither killing me caused a hang of my character (server goes on fine) rather then resetting my position.
I've tried rebooting the server, restoring my file from backup, and I eventually gave up and let it just hang.
I didn't have to wait long.
I am hoping the logs help.

### Crash Log

https://gist.github.com/McKitten/647837faf91783d70eb563bafa69ff34

### Latest.Log

https://gist.github.com/McKitten/60fd07349b2f841f66fe16706727ae28

**Comment by alekthefirst** [comment]
https://github.com/AllTheMods/ATM-10/issues/605#

**Comment by McKitten** [comment]
I can confirm it is not journeymap as in as much as It happened again (the hang after death)
I had the smarts to look at the 3 logs (latest/debug/console) and not a single one states that anything is wrong.
https://cdn.discordapp.com/attachments/603166851576496151/1290486947298414706/2024-10-01_11.33.50.png?ex=66fca320&is=66fb51a0&hm=fddbe580d9c5c90e2f6757844d31b8dd055a19839ef19eba7d678e77061b40c5&
says otherwise tho

**Comment by McKitten** [comment]
Grr so the markdown was working.

**Comment by McKitten** [comment]
Fixed with .61
