### ISSUE TITLE
[Bug]: Searching Spatial Anchor in EMI crashes game

### ISSUE THREAD

**Issue by BinLox** [AllTheMods/ATM-10#645]
### Possible Fixes

Yes

### Modpack Version

0.55

### What happened?

Literally the title.

### latest.log

https://gist.github.com/BinLox/f7d39aa695e104c6c793c58ef96075f6

**Comment by asphy396** [comment]
This is a non-issue as EMI was removed in 0.59 in favor of JEI only.
