### ISSUE TITLE
[Bug]: Unable to craft nexium emitter & philosopher's fuel

### ISSUE THREAD

**Issue by Tiica** [AllTheMods/ATM-10#652]
### Possible Fixes

Yes

### Modpack Version

0.60

### What happened?

I tried to craft the nexium emitter and philosophers fuel for the atm star yesterday when I noticed that even though I had all the items it wouldn't let me craft it. I then checked the ATM discord to see if anybody else had this issue. I found a message by iamDevon that had the same issue to which Siann responded and mentioned that this is probably an NBT issue. https://discord.com/channels/254530689225981953/1236826820200894496/1290129725615902731

This probably worked in a previous version as I saw Pilpoh being able to craft the atm star in one of his newest videos 

![image](https://github.com/user-attachments/assets/f47d6074-cc82-4642-9a51-8bb16aa914e6)
![image](https://github.com/user-attachments/assets/03dd1e31-d36e-47a7-8d6a-31472d87166c)
![image](https://github.com/user-attachments/assets/d660358e-515f-4ed9-b4cf-23b762c9c3f1)

**Comment by Tiica** [comment]
oh thanks for the info. Then I can at least finish one of the items or both if I just make new terminals. As for the terminal, I was pretty sure that I have them in the right order but I'll double check that

**Comment by BenevolntReaper** [comment]
Pretty sure for the terminal, you have to craft them all but you can't put them in your inventory, as in they can't be charged. Once you've completed the final craft, as in made the universal terminal, then you can charge that item. At least that worked worked for me.

**Comment by Tiica** [comment]
> Pretty sure for the terminal, you have to craft them all but you can't put them in your inventory, as in they can't be charged. Once you've completed the final craft, as in made the universal terminal, then you can charge that item. At least that worked worked for me.

yeah I tested it again and you are correct having the first universal terminal charged was no issue but the others you add are not allowed to have a charge. I will still leave this issue open because I still think this is not the way it was intended

**Comment by peterromfeldhk** [comment]
so what to do with the other 19 universal terminals that are now unusable because they got charged during the assembly

**Comment by Tiica** [comment]
@peterromfeldhk if you didn't charge all of them before the final assembly they should still be usable. As long as the last terminal you add isn't charged it should still work I believe. 
If not:
![yeet-lion-king](https://github.com/user-attachments/assets/c34f2d36-8739-430b-9dca-064328cc74c6)

**Comment by peterromfeldhk** [comment]
i think if you guys change the recipe to just require an uncharged tablet it will be better UX, that way people wont get in this weird NBT situation and have to look up a github issue to find the solution

**Comment by Tiica** [comment]
I think if you use an uncharged one you would have even more issues with nbt since most players have wireless inv charging at that point and you would end up with charged terminals even tho you need them to be uncharged. If they would make both possible there are probably even more issues with nbt than there already are. I've not worked with any mods directly before so I'm not entirely sure how all the nbt stuff works but it might not be as easy from a dev's/creators perspective as it sounds on paper.

**Comment by peterromfeldhk** [comment]
the charged inv is what got me there in the first place, if its uncharged i figure out a way to keep it uncharged
