### ISSUE TITLE
[Crash]: crash on journeymap waypoint on a server

### ISSUE THREAD

**Issue by NandoB01** [AllTheMods/ATM-10#653]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-0.59

### What happened?

when i try to join the server, the last thing i see is Save and then the game closes 

### Crash Log

https://gist.github.com/NandoB01/ab7738eff02935d6e6e95586f077d9c0

### Latest.Log

https://gist.github.com/NandoB01/d34b0afebb6106550c805a4753980f62

**Comment by alekthefirst** [comment]
This issue is allegedly fixed in the latest version of JM, try manually updating that

**Comment by NandoB01** [comment]
or is updated in verion 61?

**Comment by alekthefirst** [comment]
0.61 doesn't exist yet, 0.60 released before JM made the fix

**Comment by NandoB01** [comment]
so now i need to wait untill ATM 10 updated to 0.61

**Comment by NandoB01** [comment]
who know's when the pack will be uptdated to 0.61?

**Comment by TheBedrockMaster** [comment]
> who know's when the pack will be uptdated to 0.61?

Yesterday
