### ISSUE TITLE
[Bug]: Quantum Crafter

### ISSUE THREAD

**Issue by ViniciusWGGT** [AllTheMods/ATM-10#654]
### Possible Fixes

Yes

### Modpack Version

10-0.60

### What happened?

The block Quantum Crafter from Advanced AE have a bug with the patterns. When a put the patters and config them, the block works normaly, but after quit the world and rejoin the same world the patterns inside disappears, i don't know why this happens.

**Comment by pedroksl** [comment]
This bug has been fixed since the last release three days ago. Still waiting for ATM to update to the latest version that contains the fix.
