### ISSUE TITLE
[Bug]: Induction Card sometimes takes all return inventory 

### ISSUE THREAD

**Issue by frogalo** [AllTheMods/ATM-10#66]
### Possible Fixes

Yes

### Modpack Version

0.7

### What happened?

When insterting induction card from @AppliedFlux sometimes it bugs and takes all return slots (that no longer can be used)

BUGGED
![image](https://github.com/AllTheMods/ATM-10/assets/24301307/2d215d09-5aab-47b2-b848-afc5014b5756)

NORMAL
![image](https://github.com/AllTheMods/ATM-10/assets/24301307/d0647559-3451-458e-836d-cc3070a837ef)

**Comment by alekthefirst** [comment]
This is intended on applied flux's end
https://github.com/GlodBlock/ExtendedAE/issues/296#issuecomment-2509554830
