### ISSUE TITLE
[Bug]: Patchouli Extreme Reactor Guide Book no longer appearing

### ISSUE THREAD

**Issue by DartIkari** [AllTheMods/ATM-10#660]
### Possible Fixes

Yes

### Modpack Version

.60

### What happened?

![image](https://github.com/user-attachments/assets/f3e0afeb-0bd8-41da-81f7-755d08df9778)

I had The Extreme Guidebook or whatever it was called for Extreme Reactors, had not needed to look at it again until today but found my book was not working. The recipe for it does not exist in JEI anymore, and the book I have now is invalid. It was working on a previous version however. I believe it was .57 or .58.

**Comment by pr0saic** [comment]
It was removed by the mod developer until Patchouli got updated, they haven't added it back yet: https://github.com/ZeroNoRyouki/ExtremeReactors2/issues/175
