### ISSUE TITLE
[Bug]: Can't extract items from Blood Infuser

### ISSUE THREAD

**Issue by tjosias** [AllTheMods/ATM-10#662]
### Possible Fixes

Yes

### Modpack Version

10-0.61

### What happened?

Can't extract any output of the Blood Infuser from EvilCraft automatically. I want to automate recipes with it, but I am only able to extract the outputs manually.

I can automatically input the items needed, can also extract the blood automatically, just not the item output.

![Blood Infuser](https://github.com/user-attachments/assets/7402228d-2c6c-4c36-b09a-c5971e09fecc)

I've tried Super Factory Manager, Pipez, ME Import Bus and Modular Routers to try extracting, but none of it works.

**Comment by alekthefirst** [comment]
output can only be automated through the bottom side of the infuser

**Comment by tjosias** [comment]
You're a star, fixed xD

![fixed](https://github.com/user-attachments/assets/44ff6670-0e7a-46f1-86ed-75bc6abd9290)

**Comment by tjosias** [comment]
Closed since a work-around is possible.
