### ISSUE TITLE
[Crash]: Pressing F3 causes a crash when in The End

### ISSUE THREAD

**Issue by sludgepudge** [AllTheMods/ATM-10#663]
### Possible Fixes

Yes

### Modpack Version

0.61

### What happened?

When pressing F3 it causes everything to crash immediately. Pressing F3 in the overworld and the Nether doesn't cause any crash at all.

### Crash Log

https://gist.github.com/sludgepudge/631f98bc677d79b9d0c3d81cd551c64e

### Latest.Log

https://gist.github.com/sludgepudge/af2cc729b78748752647f06a210caf9d

**Comment by alekthefirst** [comment]
Its a known issue with terra blender
