### ISSUE TITLE
[Bug]: Mekanism's Chemical Dissolution Chamber breaks with Speed Upgrades

### ISSUE THREAD

**Issue by tjosias** [AllTheMods/ATM-10#667]
### Possible Fixes

Yes

### Modpack Version

10-0.61

### What happened?

When trying to make chemicals, like Hydrofluoric Acid inside of Mekanism's Chemical Dissolution Chamber, it will use 1562 mb of Sulphuric Acid instead of the recipe's 100mb.

This only occurs when adding speed upgrades. Otherwise the recipes will work fine only if not using speed upgrades inside of the Chemical Dissolution Chamber.

**Comment by superbrotherx4** [comment]
That's actually just the way it works and doesn't explain it. Install gas upgrades and at max it'll require less than 100mb instead

**Comment by DarkDrinker** [comment]
I have found it's not consistent at all. A recipe for the same acid he talks about, 900 mB sulfuric acid and and a fluorite block should give 9000mB. But i am left with acid when the recipe is done. No upgrades. First time it was 180mB acid left, second try(same machine) it was 220. Also when not using a block, regular fluorite, i seem to have to little for the recipe. Hope this helps clearing up. 
Img for context:
![Screenshot 2024-10-02 195933](https://github.com/user-attachments/assets/9e2bd1c4-ebd8-42aa-a0be-b7f3e824d6b6)

**Comment by superbrotherx4** [comment]
"Note that while JEI may suggest that recipes have a constant cost, there is actually a small variance in gas consumption with every craft. While theoretically it may consume up to 33% more than the listed value, most often the variation is small enough to not be noticeable over a large number of operations. The consumption of Sulfuric acid per operation scales with the number of speed upgrades. 10x speed = 10x gas cost."
That is directly from the Mekanism wiki, which is a little old, but is correct. It is indeed random but overall gas upgrades take it back to requiring around the correct amount.

**Comment by DarkDrinker** [comment]
Well... so you have to factor in a variance when making autocrafting with AE? damn. Also you have no way of getting excess chemical out without breaking it. Irritating. Haven't met this problem with any other machine using chemicals, only this one.

**Comment by superbrotherx4** [comment]
As far as I know it is the only machine that accepts the gas upgrades so I'd say its the only machine that does this and it seems so random. What you can do is set it so the recipe puts in definitely more than it would need and you'd be guaranteed to get an output, and just have a different machine for each different input fluid/gas.

**Comment by tjosias** [comment]
That's unfortunate... 

My first time figuring out Mekanism Fusion Reactors and such. Things like this make learning this harder than what it needs to be.

**Comment by DarkDrinker** [comment]
I checked ATM9 to see if this is an intended feature. It was.
