### ISSUE TITLE
[Bug]: EnderIO Alloy Bees Not Craftable as of update 0.61

### ISSUE THREAD

**Issue by DJAscendance** [AllTheMods/ATM-10#672]
### Possible Fixes

Yes

### Modpack Version

0.61

### What happened?

The EnderIO Alloy Bees recipe's were broken with this update, they are no longer craftable. 
![image](https://github.com/user-attachments/assets/419cc065-21f0-4286-91a2-14c8ecc5cb39)
![image](https://github.com/user-attachments/assets/6282e71b-334b-4ca8-bbff-3b409e8d3433)

Yesterday before I updated they were all craftable in the EnderIO Alloy Smelter. 

Sorry if I havent included enough info, its my first bug report. Ty <3

### latest.log

https://gist.github.com/DJAscendance/45c0dfd6e883ee502a21924c6c5b9d21

**Comment by DJAscendance** [comment]
Also adding to this, EnderIO Fluid conduits aren't functioning, and I believe the energy conduits will output their max rated FE/T even with less power being put into it.

**Comment by Rover656** [comment]
Apologies, it looks like the recipe changes we've made in Ender IO 7.0.7 have broken the bees, I'll push that info to the relevant parties tomorrow. As for the conduit issues, could you specify exactly what these problems are so we can take a look as we made some conduit bugfixes in this version which might've caused a regression. Thanks!

**Comment by DJAscendance** [comment]
Sure, yeah when I had a basic extreme reactor 5x5x5 external outputting aprox 9-10k FE/t when using the highest tier energetic alloy conduits they put 48k FE/t into all of the tiers of Mekanism energy cubes, even though the reactor was showing the lower level of power. (I havent tried the lower tier conduits) 

It should also be noted that they have lost their "clear fluid" check mark from the block/conduit GUI

**Comment by Rover656** [comment]
I appreciate the details, I'll try and look at this when I get some time and work out what might be causing these problems. Thanks!

**Comment by DJAscendance** [comment]
I appreciate you all!
