### ISSUE TITLE
[Bug]: Primal Coal isn't affected by Fortune

### ISSUE THREAD

**Issue by Jason-Bane** [AllTheMods/ATM-10#675]
### Possible Fixes

Yes

### Modpack Version

Allthemods 10-0.61

### What happened?

Even though that the description on the quest page says that Primal coal is affected by fortune, It still only drops 3, despite fortune level.

**Comment by ToshibaEC0Microwave** [comment]
In current version on my own test I am getting 4 sometimes with Fortune III.
