### ISSUE TITLE
[Bug]: paintings won't place

### ISSUE THREAD

**Issue by shade1822226911** [AllTheMods/ATM-10#676]
### Possible Fixes

Yes

### Modpack Version

0.61

### What happened?

no matter how hard i try and right click, paintings won't place

**Comment by Yakaita** [comment]
i also had this issue. on .60, currently on .64 and still cant place

**Comment by PieIsAwesome7102** [comment]
Have had this issue since around .53, now on 1.0 and still can't place paintings. Single-player worlds or a server. A friend of mine also couldn't on a different server.

**Comment by PieIsAwesome7102** [comment]
Bug persists on version 1.6

**Comment by shade1822226911** [comment]
idk what version fixed it, but it's fixed
