### ISSUE TITLE
[Bug]: certain tabs not showing in the quest menu

### ISSUE THREAD

**Issue by lv99Abra** [AllTheMods/ATM-10#680]
### Possible Fixes

Yes

### Modpack Version

10-0.54

### What happened?

specifically, the building tips tab is not showing in my friends game, but it shows in mine, i have tested with another world. the tab is not available for either of us in his multiplayer world, nor his single player world on his computer. but works on my single player world. not 100% sure if a bug or something else going on. but would really like to have access as he is new and that would give him a lot of stuff to play with

**Comment by TheBedrockMaster** [comment]
Probably a problem with his instance, try repairing the profile or copying the quest files over.
