### ISSUE TITLE
[Feature]: The two types of yellow uranium ingots are not interchangeable, and the Fluidizer can only use this type of yellow uranium ingot that cannot be synthesized

### ISSUE THREAD

**Issue by Floatingcolon** [AllTheMods/ATM-10#685]
### Feature Details

The two types of yellow uranium ingots are not interchangeable, and the Fluidizer can only use this type of yellow uranium ingot that cannot be synthesized.
![1](https://github.com/user-attachments/assets/42468918-6b30-4e70-8205-ab40038dae52)

![2](https://github.com/user-attachments/assets/05df35bb-d941-4d89-b6d7-2ad3a1037363)

![3](https://github.com/user-attachments/assets/034bffcf-18b3-473e-a95a-70952cd599c2)

![4](https://github.com/user-attachments/assets/181a342f-1139-4b2e-af9d-80aac26fee25)

![5](https://github.com/user-attachments/assets/ad8b610c-7bb1-4fda-9e97-fa5b2339cfdb)

**Comment by shade1822226911** [comment]
pretty sure this is a bug, not a feature request
