### ISSUE TITLE
[Bug]: Formation plane not placing blocks

### ISSUE THREAD

**Issue by OkusoFred** [AllTheMods/ATM-10#688]
### Possible Fixes

No

### Modpack Version

0.60

### What happened?

Formation panel is not working, even if set on filter and etc. .
Noticed this while playing on server, after some time i tried on singleplayer, same.
FTB chunks not claimed. and set "True" in FTB chunks settings for "Allow all fake players"

**Comment by superbrotherx4** [comment]
Are you using it on a subnet? Formation Planes don't pull from storage. The in-game explanation shows a little more about it

**Comment by OkusoFred** [comment]
> Are you using it on a subnet? Formation Planes don't pull from storage. The in-game explanation shows a little more about it

No, i'm not using it on a subnet, but while i'm place formation plane in first time in current network - it places the first block from net (when i set filter in it/replace f.plane - it stops placing blocks).

**Comment by pr0saic** [comment]
Fairly sure this is intended behaviour from AE2, it only places items as they enter the network, like a storage bus.
