### ISSUE TITLE
[Bug]: Boon of the Earth and Modular Routers to spawn infinite ores

### ISSUE THREAD

**Issue by LogicEngineer** [AllTheMods/ATM-10#691]
### Possible Fixes

Yes

### Modpack Version

10-0.61

### What happened?

It's way too easy to generate ores (no cost after setup).

Put Silk Touch and Boon of the Earth enchantments on a pick axe and craft it into a breaker module. 
Use the breaker module and a placer module to have one modular router do the following:
 place a block of stone, 
mine the stone with the Silk Touch / Boon of the Earth breaker module, 
get the stone back, WITH A CHANCE OF SPAWNING AN ADDITIONAL ORE, 
repeat. Profit.

![Screenshot 2024-10-04 185943](https://github.com/user-attachments/assets/1b0b32f1-a5a9-4115-832a-f277d574633b)
![Screenshot 2024-10-04 190020](https://github.com/user-attachments/assets/d1b67044-6ee8-4e36-ae32-b0ba97e1471c)
![Screenshot 2024-10-04 190324](https://github.com/user-attachments/assets/51359bb4-e0a9-4c7d-af08-391b3ead3f6b)

**Comment by alekthefirst** [comment]
This is known and generally considered as a feature
