### ISSUE TITLE
[Crash]: Cannot invoke "appeng.api.stacks.AEKey.getDisplayName()" because "this.record" is null

### ISSUE THREAD

**Issue by Erelaszun** [AllTheMods/ATM-10#692]
### Possible Fixes

Yes

### Modpack Version

10-0.62

### What happened?

Crash when searching in Creative:

Crash log, and Latest Log included.

### Crash Log

https://gist.github.com/Erelaszun/3cc8244e111ee1a706f08d286e0c7816

### Latest.Log

https://gist.github.com/Erelaszun/86bf654bee2a27d2dcfdead035c3db13

**Comment by Neftu** [comment]
is there any known fix or workaround for this?

**Comment by Erelaszun** [comment]
I found my own temp fix for this issue:

Remove the following files:

<instance>/kubejs/server_scripts/mods/ExtendedAE/InfinityCellRecipes.js
<instance>/kubejs/startup_scripts/ExtendedAE/InfinityCells.js

Creative search will work, but laggy. Temp fix until a response.
