### ISSUE TITLE
[Bug]: Forbidden and Arcanus recipies are broken

### ISSUE THREAD

**Issue by Hamude99** [AllTheMods/ATM-10#696]
### Possible Fixes

Yes

### Modpack Version

0.62

### What happened?

Most of the Forbidden and Arcanus items just don't have a recipe in JEI.

**Comment by Nailzk** [comment]
+1

**Comment by Hamude99** [comment]
Fixed in 0.63

**Comment by Corn-on-the-Orb** [comment]
@Hamude99 would you be able to tell me how you managed to fix this? I have been trying for the life of me to fix it in my singleplayer but cant figure it out
