### ISSUE TITLE
[Bug]: Iron jetpacks lack of crafting, only able to craft coils and leather strap

### ISSUE THREAD

**Issue by gabriel-meirax** [AllTheMods/ATM-10#697]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-0.62

### What happened?

only the recipes for coils and leather strap are able to craft, I tried to craft a wooden jetpack but it is impossible.

**Comment by Caleb-JC-Hussey** [comment]
How was this fixed? I'm trying to figure out how I somehow made this happen through my changes.
