### ISSUE TITLE
[Bug]: Mystical Agriculture seeds wont reproduce on essence farmland

### ISSUE THREAD

**Issue by K4LLy** [AllTheMods/ATM-10#699]
### Possible Fixes

Yes

### Modpack Version

All the Mods 10-0.62

### What happened?

Updated the pack from Version 0.54 to 0.62. Before the update all mystical agriculture seeds had their chance of "reproduce" when placed on their respective essence farmland. Now i only get the essence and no extra seeds. Noticed that behavior in survival an on a server. Manually breaking the seeds instead of using the harvester pylon has no effect on the droprate of the extra seeds.

Steps to reproduce:
- load a world
- create a field with a seed of choice (e.g. netherite seed)
- use all different essences on the farmlad for best results
- for faster results use a harvester pylon with chest on top and supremium hoe
- /gamerule randomTickSpeed 3000
- the field grows rapidly, the pylon does its thing but no extra seeds

**Comment by SuperFakeSMozza** [comment]
Go into config\mysticalagriculture-common.toml and look at line 16 "secondarySeedDrops" and change false to true

**Comment by K4LLy** [comment]
Ty. The setting was indeed set to false. 
Is this intended from the modpack?

**Comment by SuperFakeSMozza** [comment]
It's the default setting but hey if you wanna change it then it's your game to play
