### ISSUE TITLE
[Bug]: Right Clicking Iron Chest Plate, Returns to Inventory

### ISSUE THREAD

**Issue by FallenPumpking** [AllTheMods/ATM-10#7]
### Possible Fixes

Yes

### Modpack Version

0.2-0.60

### What happened?

Right clicked Iron Chest Plate to put on. No other chest piece was equipped. Armor returns to inventory instantly. Can however, manually place chest piece in the slot.

**Comment by Arashlf** [comment]
Same happened with other armor.
Cannot wear armor using right-click.

version: 0.11

**Comment by alekthefirst** [comment]
While its not clear which version it was resolved in, this has been solved
https://github.com/user-attachments/assets/c7959ffa-3d62-4603-9e43-cb6580e5a4c4
