### ISSUE TITLE
[Bug]: Upgraded 0.6 - 0.9, pack will not boot due to duplicate kubejs script. 

### ISSUE THREAD

**Issue by Kurunoa** [AllTheMods/ATM-10#71]
### Possible Fixes

Yes

### Modpack Version

0.9

### What happened?

Upgraded 0.6 - 0.9, pack will not boot. - RESOLVED, posting for history.

getting "java.lang.IllegalArgumentException: Duplicate key 'kubejs:universal_press' in registry 'minecraft:item'!"
 
Log contains: 

[11:50:16] [INFO] Loaded script startup_scripts:ae2/universal_press.js in 0.063 s
[11:50:16] [INFO] Loaded script startup_scripts:Applied Energistics/Universal_Press.js in 0.001 s

Asked in #ATM10-techsupport, DJNifo informed me that Latest exports don't have the ae2 one, only the Applied Energistics one.

Removed the obsolete script folder kubejs\ae2, it booted right up.

**Comment by Kevin-Marsh** [comment]
A clean install and copy your save file over to the new instance will fix this.
