### ISSUE TITLE
[Crash]: code error 1

### ISSUE THREAD

**Issue by Error404Sans666** [AllTheMods/ATM-10#712]
### Possible Fixes

Yes

### Modpack Version

0.64

### What happened?

every time i try to launch the game , the game crash with the code error 1 . If someone have the same thing who fixed it or how have the same but is stuck like me i would like to hear it !

Thanks for your time

### Crash Log

https://gist.github.com/Error404Sans666/b72769d250c8b382ba68bc3f7bce9cd7#file-gistfile1-txt

**Comment by alekthefirst** [comment]
update your video driver, make sure to grab them from https://www.amd.com/en/support/download/drivers.html

if your primary gpu brand is not amd then go into the windows graphics setting and make sure your game is actually running with the nvidia/intel gpu

**Comment by Error404Sans666** [comment]
> update your video driver, make sure to grab them from https://www.amd.com/en/support/download/drivers.html
> 
> if your primary gpu brand is not amd then go into the windows graphics setting and make sure your game is actually running with the nvidia/intel gpu

i feel so dum to ask a such simple question 😅 but thank you a lot !
