### ISSUE TITLE
[Quests issues]: Piglich and chicken prediction quest get triggered with any prediction

### ISSUE THREAD

**Issue by Motytheultimate** [AllTheMods/ATM-10#713]
### Modpack Version

0.64

### Describe the issue

The piglich prediction quest and the chicken prediction quest get completed as soon as you collect any prediction.
So I searched the quest json and found the following:
`tasks: [{
id: "1F4B02AFDFD7CDBE"
item: { components: { "hostilenetworks:data_model": "hostilenetworks:chicken" }, count: 1, id: "hostilenetworks:prediction" }
type: "item"
}]`

`tasks: [{
id: "1AEFD81CDB3EA4CD"
item: { components: { "hostilenetworks:data_model": "hostilenetworks:allthemodium/piglich" }, count: 1, id: "hostilenetworks:prediction" }
type: "item"
}]`

while the working quest task looks like this:
`tasks: [{
id: "65912C9360C5C8F4"
tem: { components: { "hostilenetworks:data_model": "hostilenetworks:zombie" }, count: 1, id: "hostilenetworks:prediction" }
**match_components: "strict"**
type: "item"
}]`
So my guess would be that the 	
match_components: "strict" 
is missing for them

**Comment by Motytheultimate** [comment]
I tested it and it seems to be as I guessed it with the strict match it wont trigger until you really get the piglich prediction

**Comment by TheBedrockMaster** [comment]
Already noted, but thank you

**Comment by Motytheultimate** [comment]
in the new Version there is also the soul lava bee egg in chapter 2
thats missing the strict parameter
