### ISSUE TITLE
[Bug]: Cannot craft Magical Soil

### ISSUE THREAD

**Issue by RussellBurkhart** [AllTheMods/ATM-10#714]
### Possible Fixes

Yes

### Modpack Version

0.64

### What happened?

Magical Soil requires Moonlight Magic Crepe Myrtle Saplings now
There are no recipes for Productive Trees past the Purple Crepe Myrtle Saplings in the quest line
Checked JEI for the recipes of the previous step and no recipes available
When you "Click for Recipes" it only shows a recipe you need the sapling for

**Comment by TheBedrockMaster** [comment]
https://github.com/JDKDigital/productivetrees/issues/21#issuecomment-2387100959

It will be added to the quests.
