### ISSUE TITLE
[Bug]: 0.64 Mods not showing in inventory

### ISSUE THREAD

**Issue by DanHughes5698** [AllTheMods/ATM-10#716]
### Possible Fixes

Yes

### Modpack Version

0.64

### What happened?

Not sure if its even a bug or intended but when you hover over an item in your inventory or chest normally at the bottom it would say what mod its from, however it doesn't seem to be doing this as it only displays it in JEI. As someone relatively new to modded Minecraft when I see a new item I like to know straight away what mod its from.

![2024-10-08_13 59 52](https://github.com/user-attachments/assets/0fc66629-bd05-4464-90d9-3d0a0f194219)
![2024-10-08_13 59 39](https://github.com/user-attachments/assets/7a76d68d-c374-486e-ad5d-eff70cf6b71a)
![2024-10-08_13 59 45](https://github.com/user-attachments/assets/6fe08df6-ee49-456b-aea7-ad460609a4a3)

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/633
