### ISSUE TITLE
[Bug]: oak drawer cannot be crafted using oak planks

### ISSUE THREAD

**Issue by MatteoPL** [AllTheMods/ATM-10#72]
### Possible Fixes

Yes

### Modpack Version

0.9

### What happened?

I can't craft oak drawer using oak planks this is the only drawer recipe that don't work other like birch works.

**Comment by dodomans** [comment]
yeah i noticed, it looks like the oak drawer wants any productive trees planks, and not oak for some reason

**Comment by PianoHallvard** [comment]
Same here

**Comment by DaddyLongspoon** [comment]
I suspect you guys are all trying to make the drawers in some crafting computer, ae2, qio etc, semi says you're going to get functional drawers but when you pull it out you have a cupboard... 
if you do it on regular crafting table, on a stick or vanilla then you get the little circular arrow to switch between multiple outcomes from the same crafting recipe..

**Comment by MarobsKoco** [comment]
Version 0.10 Recipe is Taged as planks. not as oak planks
![Oak Drawer](https://github.com/user-attachments/assets/9ec05a93-e53f-4420-b687-7f4e90e26b3e)

**Comment by MarobsKoco** [comment]
Fix: go to ur ATM 10 folder and go to kubejs\server_scripts\mods\. Make a folder called "functional storage". In folder functional storage make a file called Recipes.js and put copy the code below in to it and restart ur game.


`// This file repairs the oak drawers recipes in All The Mods 10 (ATM10)

ServerEvents.recipes(allthemods => {
	allthemods.remove({ id: 'functionalstorage:oak_1' }) // Removes the old recipe for 1x1 oak drawer
	allthemods.remove({ id: 'functionalstorage:oak_2' }) // Removes the old recipe for 1x2 oak drawer
	allthemods.remove({ id: 'functionalstorage:oak_4' }) // Removes the old recipe for 2x2 oak drawer
    allthemods.shaped('functionalstorage:oak_1', ['aaa', 'aba', 'aaa'], {
      a: "minecraft:oak_planks",
      b: "minecraft:chest"
    }) // Add the new recipe for 1x1 oak drawer
    allthemods.shaped('functionalstorage:oak_2', ['aba', 'aaa', 'aba'], {
      a: "minecraft:oak_planks",
      b: "minecraft:chest"
    }) // Add the new recipe for 1x2 oak drawer
    allthemods.shaped('functionalstorage:oak_4', ['bab', 'aaa', 'bab'], {
      a: "minecraft:oak_planks",
      b: "minecraft:chest"
    }) // Add the new recipe for 2x2 oak drawer
  })`

**Comment by dodomans** [comment]
> I suspect you guys are all trying to make the drawers in some crafting computer, ae2, qio etc, semi says you're going to get functional drawers but when you pull it out you have a cupboard... if you do it on regular crafting table, on a stick or vanilla then you get the little circular arrow to switch between multiple outcomes from the same crafting recipe..

nope, tried crafting in crafting table early on and found out it wouldnt use oak planks

**Comment by Kevin-Marsh** [comment]
This will be patched in the next version until the dev fixes it.

**Comment by PianoHallvard** [comment]
It's still currently bugged since polymorph was removed

**Comment by Kevin-Marsh** [comment]
Update your pack
