### ISSUE TITLE
[Crash]: Crash from Potion Brewer(Industrial Foregoing)

### ISSUE THREAD

**Issue by wcream3** [AllTheMods/ATM-10#732]
### Possible Fixes

Yes

### Modpack Version

.65

### What happened?

At first the server me and a few friends play on crashed, then when I tried to join after reboot, started to crash when I tried to join every time. When the friend who owns the server was home, the console informed him of the block responsible which happened to be the potion brewer from Industrial Foregoing. He replaced the block with air and it fixed the server. Due to not having proper perms to perform the test on the server, I recreated it in singleplayer. With a tier 2 speed addon and tier 2 efficiency addon installed, I brewed roughly 2 inventories of regen potions until the game crashed. I'm not sure if it started to save BECAUSE it was crashing or if it crashed when the game tried to save, but it happened at the same time. 

### Crash Log

https://gist.github.com/wcream3/f0a1466167c2e59436c2b4984d689d83

### Latest.Log

https://gist.github.com/wcream3/d431a3cb174b022fbceb94c4d61b3783

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/681
