### ISSUE TITLE
[Bug]: Extreme Reactors block texture

### ISSUE THREAD

**Issue by M0diis** [AllTheMods/ATM-10#734]
### Possible Fixes

Yes

### Modpack Version

10-0.65

### What happened?

Extreme Reactors texture doesn't appear until the block is updated when playing in multiplayer.

https://github.com/user-attachments/assets/09bf4ef8-ac05-4a35-b35d-ea39e79a0bda

**Comment by zordem** [comment]
Pretty sure this is a bug with the Extreme Reactors mod itself. Someone created an [issue](https://github.com/ZeroNoRyouki/ExtremeReactors2/issues/166) about this but they closed it on the same they. You might want to reopen one. Im sure the chances that the ATM maintainers can fix this are slim.
