### ISSUE TITLE
[Crash]: simple clicker [Just Dire Things}

### ISSUE THREAD

**Issue by MOH1412** [AllTheMods/ATM-10#74]
### Possible Fixes

Yes

### Modpack Version

0.9

### What happened?

the world crash after set up clicker to right click [air]
i cannot login the world anymore
everytime i login ,it crash before rendering the world

### Crash Log

https://gist.github.com/MOH1412/6eaf58ea9422a0346e2f443fd4f64629

**Comment by Kevin-Marsh** [comment]
This should be fixed in the latest version
