### ISSUE TITLE
[Bug]: cooking for blockheads cooking pot one use only

### ISSUE THREAD

**Issue by gbusrt** [AllTheMods/ATM-10#744]
### Possible Fixes

Yes

### Modpack Version

ATM10 0.66

### What happened?

trying to make jam for toast, cooking pot only usable once

**Comment by anivlys** [comment]
These should actually be the Croptopia cooking utensils, but even in 1.0 they are still one time use only.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/490
