### ISSUE TITLE
[Bug]: mimic drops are broken

### ISSUE THREAD

**Issue by thisKid619** [AllTheMods/ATM-10#748]
### Possible Fixes

Yes

### Modpack Version

10-0.66

### What happened?

the mimics from the artifact mod only drop the hunters belt from the relics mod and nothing else

**Comment by jinkhya** [comment]
Hello
I talked to the dev of Relics: Artifacts Compat which is causing this problem and they're working on a fix for it. Probably out soon :D

**Comment by Amiri000** [comment]
there is a fix for! https://www.curseforge.com/minecraft/mc-mods/rar-compat/files/5805300
