### ISSUE TITLE
[Crash]: Internal server crashes when opening ME-Craftingterminal.

### ISSUE THREAD

**Issue by JogiWanKenobi** [AllTheMods/ATM-10#75]
### Possible Fixes

Yes

### Modpack Version

0.9

### What happened?

Title

### Crash Log

https://gist.github.com/JogiWanKenobi/c729f6501929b0822c9b3b1044189186

### Latest.Log

https://gist.github.com/JogiWanKenobi/c86c3821910b754a2f7621946d35dec6

**Comment by alekthefirst** [comment]
Was resolved in ATM10 0.12 or 0.13 depending on which release AE2 had their fix in (changelogs not clear)
