### ISSUE TITLE
[Bug]: Moved too quick

### ISSUE THREAD

**Issue by Cebio** [AllTheMods/ATM-10#750]
### Possible Fixes

Yes

### Modpack Version

0.66

### What happened?

	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.4, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1483216912 bytes (1414 MiB) / 3221225472 bytes (3072 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5950X 16-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.00
	Number of physical packages: 1
	Number of physical CPUs: 12

This is the server i have and me and my friends getting randomly "moved too quick" notification and causes server to lag for a bit taking us back to some time. Is there something i can do?

**Comment by pr0saic** [comment]
This is usually caused by a player with a bad connection or the server doesn't have enough resources to keep up with players loading chunks quickly
