### ISSUE TITLE
[Bug]: Silent Gear Tip Upgrades do not increase harvesting level

### ISSUE THREAD

**Issue by Caeldeth** [AllTheMods/ATM-10#755]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

Tip upgrades do not upgrade harvesting level on Silent Gear tools.  E.g., add a diamond tip to a tool with a stone pickaxe head, and the harvest tier remains at stone.  This contradicts the newly added quest description:
```
"Tip Upgrade Blueprint
For when you don't find 3 diamonds

The Tip Upgrade is used to increase the mining level of a tool.  For example if you have an iron pickaxe, with 1 diamond, you can make a Diamond Tip Upgrade and place it on your pickaxe.  This will allow it to mine Obsidian, as well as give it a stat boost.
```
----
screenshot
![tool screenshot 1](https://github.com/user-attachments/assets/1295f174-5f34-4e00-82c9-7135b0a49d55)

### latest.log

https://gist.github.com/Caeldeth/e29dffa7032bfee9fc939f39e3783f6a

### Developer reports

https://github.com/SilentChaos512/Silent-Gear/issues/716

**Comment by TheBedrockMaster** [comment]
I'm pretty sure the description you put is from ATM9 but yes, the same applies in the ATM10 quest.

**Comment by Caeldeth** [comment]
Had to check I wasn't crazy since I have both installed!
ATM 9:
![atm9](https://github.com/user-attachments/assets/ce287471-d977-4ebe-b51b-a2180ba3a44e)
vs ATM10:
![atm10](https://github.com/user-attachments/assets/dd1ffb15-f900-42ab-a782-9fc3f0d9c4cf)
