### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jakeoakes** [AllTheMods/ATM-10#76]
Type of Suggestion: Mod
Modpack: ATM10 
Suggestion: Add the XP tome
Link: https://www.curseforge.com/minecraft/mc-mods/xp-tome

Type of Suggestion: Mod
Modpack: ATM10 
Suggestion: Add EX Reactors
Link: https://www.curseforge.com/minecraft/mc-mods/extreme-reactors

Type of Suggestion: Mod
Modpack: ATM10 
Suggestion: Add ex pattern provider
Link: https://www.curseforge.com/minecraft/mc-mods/ex-pattern-provider

**Comment by TheBedrockMaster** [comment]
#2 For Mod Suggestions.
