### ISSUE TITLE
[Crash]: CrafingTweaks all 20 Minutes Server Timeout

### ISSUE THREAD

**Issue by bomber1992** [AllTheMods/ATM-10#762]
### Possible Fixes

Yes

### Modpack Version

0.66 / 1.0

### What happened?

My server timeout constantly every 20 minutes with the reason CraftingTweaks / WatchDogs

### Crash Log

https://gist.github.com/bomber1992/fcf1e33d9bf133d12833a5c66f281266

**Comment by ChrisMeta** [comment]
We have the EXACT same issue here.
