### ISSUE TITLE
[Bug]: Silent Gear mining level not correct

### ISSUE THREAD

**Issue by Schrimpes** [AllTheMods/ATM-10#763]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

I made a pickaxe out of obsidian and it should have the mining level obsidian. is also displayed in the tooltip. However, it only has mining level stone. not even iron.
![grafik](https://github.com/user-attachments/assets/8253c35c-5695-4a6c-97e9-0f65fe57f263)

**Comment by Schrimpes** [comment]
The magnetic trait of the rod also don't work.

**Comment by TheBedrockMaster** [comment]
https://github.com/SilentChaos512/Silent-Gear/issues/725
