### ISSUE TITLE
[Bug]: I can not craft the Stellarite Bee

### ISSUE THREAD

**Issue by DJ7752** [AllTheMods/ATM-10#766]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

When I try to craft stellarite bee it gives me an error and I can't make it. This error has been present for several updates.

**Comment by alekthefirst** [comment]
Issue has presumably since been resolved, and the craft works fine
https://github.com/user-attachments/assets/61609f43-99eb-449d-a0b9-37d29099ab13
