### ISSUE TITLE
[Crash]: Wiped and started a new server and give feature placement issues

### ISSUE THREAD

**Issue by mike3d2008** [AllTheMods/ATM-10#772]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

was starting a new server on my desktop but wont gen a crash file so and to copy and paste from console. something wrong with feature placement is all i know. but when i wiped the world folder it went away but there was still lingering issue when i tried to use chunky to pregen my world were it would hung so i assume there are items causing the world to hang up in generation.

### Crash Log

https://gist.github.com/mike3d2008/18010328e644cd9b4fa37126e24b2b55#file-crash-report

### Latest.Log

https://gist.github.com/mike3d2008/64d2128abc1dfac8c9435fc526899e7b#file-2024-10-14-6-log

**Comment by alekthefirst** [comment]
Fixed in a series of updates to individual mods that add to world gen in ATM10 1.26
