### ISSUE TITLE
[Bug]: Virus found in ATM10 Server 1.0 Version

### ISSUE THREAD

**Issue by Atomkraftzwerg1** [AllTheMods/ATM-10#773]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

I downloaded the 1.0 zip file for ATM10 Server and after i startet the .bat file Bitdefender pops up und stopped the process.
i added a picture of the report, i tried it twice get sure. Even the 0.66 version is corrupted Bitdefender says. O.o
![Virus Name](https://github.com/user-attachments/assets/2ef6bbe9-52ee-46c1-857f-a378faef8740)

**Comment by ChapsJust** [comment]
I have no problem with multiple anti-virus, maybe false positive ?

**Comment by Atomkraftzwerg1** [comment]
I will try another online scanner later, had not much time yesterday. I hope i can try it today

**Comment by Xplodin** [comment]
definitely false positive, bitdefender isnt great
