### ISSUE TITLE
[Bug]: Wandering traders just straight up don't spawn

### ISSUE THREAD

**Issue by shade1822226911** [AllTheMods/ATM-10#779]
### Possible Fixes

Yes

### Modpack Version

0.66

### What happened?

I've looked at all the things i might have done to stop wandering traders spawning, but nothing i've done has prevented them from spawning.
I've checked my pylons, tried utilitrarian carpets and checked for trapped ones, and made sure i had no active restraining orders, and yet they still don't spawn.
I think this has been happening to me since (unsure) probably after 0.59

**Comment by gotoss08** [comment]
Well, for me it's actually spawned. But delay between spawns was veeery long. something about 20 irl hours. I also placed few bells around the entrance of my base, just in case

**Comment by shade1822226911** [comment]
i decided to spawn one with commands but an hour or two after spawning them one finally spawned with their llamas, that was the only one that spawned though.
maybe it's related to the day/night cycle considering i have an ars nouveau setup to force daytime and clear weather.

**Comment by zordem** [comment]
i waited forever too for one to spawn. ive searched the internet for possible solutions and nearly gave up. but magically after 
 a server restart (due to an unrelated reason) one showed up at my base. maybe some mod might accidentally interfer with trader spawns?
