### ISSUE TITLE
[Bug]: Corail Seed Bags giving Unobtainable Seeds

### ISSUE THREAD

**Issue by ibaldwin** [AllTheMods/ATM-10#784]
### Possible Fixes

Yes

### Modpack Version

10-1.0

### What happened?

I got Cobalt Seeds from a Corail Tombstone Bag of Seeds, and its looking like Cobalt has no use in the pack currently. Maybe something to look at?
![image](https://github.com/user-attachments/assets/2c9587ba-6c9a-42b3-92f3-36dce5bc9a75)

**Comment by Corail31** [comment]
If it can help, the seeds in the bag are from the item tag "tombstone:seeds" (so, they can be edited).
