### ISSUE TITLE
[Bug]: Chunk loading keeps freezing 

### ISSUE THREAD

**Issue by asineth0** [AllTheMods/ATM-10#787]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

I'm trying to pre-generate the chunks for my ATM10 server and have noticed that it will keep freezing while trying to generate the chunks. The server stays completely responsive during the freeze and it is just chunk loading that freezes up, not even existing chunks will load during the freeze. It usually lasts 10-30 seconds and then will continue loading chunks until it freezes again after another 10-30 seconds. 

I've tried two different mods for pre-generation: Chunky & Chunk-Pregenerator (both from CurseForge, 1.21, for NeoForge). They both have the same issue. After investigating, I **removed both mods and experienced the same behavior** just by flying around. Tested on two dedicated servers with G1GC and ZGC flags, no difference. Issue is reproducible in single player on a Windows client. RAM allocated was 12GB for both clients.

A bit of a shot in the dark but perhaps there is a cap on the number of chunks allowed to be loaded at a time? It seems to get stuck around 5125:
```
[TaskName: overworld][Shape: Square]
[Dim=Overworld] [Task Type: Fast Check Gen]
[Task: Current/Total: 1,420/400,815]
[Speed: 1.71 Chunks/t]
[Loaded (Chunks | Region Files | POI): 4647 | 31 | 67224]
[Working Area: From[X=512, Z=512], To[X=1024, Z=1024]]
[Time Left Main, Running: 03:14:19, 00:01:05]
[Ram Usage: 7250 MB / 10240 MB][Ticks: 44657 | 2319]
[Listen][Mute][Pause][Resume][Stop][Continue][Remove]
```

Any ideas?

### latest.log

https://gist.github.com/asineth0/f45255fdc2e2e3fd7da797a4f0ecffe2

**Comment by mike3d2008** [comment]
having similar issues here, i know with using chunky i was having the same issue on Modpack ATM 10 ver 1.1 on seed -4603542352546017244 at location x1274 z-1024, idk if your cramming alot of stuff or its trying to gen to many things, i had to stop my generator and shut the server down and restart it and go to the spot and check it out, same with other spot, i tried it in single player and found it to slowly gen also. so something is causing slow terrain gen. Pls ATM team, figure out was causing terrain gen lag and stalls. i even remove chunky and wipe the map and reloaded it with the same seed and have the same issues. please look into this.

**Comment by mike3d2008** [comment]
[debug.log](https://github.com/user-attachments/files/17441175/debug.log)
[latest.log](https://github.com/user-attachments/files/17441176/latest.log)
heres my logs for my post above

**Comment by alekthefirst** [comment]
Resolved by workaround with All The Leaks in ATM10 1.22, then later solved by the individual mods causing these freezes
