### ISSUE TITLE
[Quests issues]: Quest Images overlapping text.

### ISSUE THREAD

**Issue by MarhzyyMC** [AllTheMods/ATM-10#789]
### Modpack Version

1.1

### Describe the issue

Several quest images are overlapping the quest text.

![2024-10-1605-04-24](https://github.com/user-attachments/assets/7d0db047-49ef-4dd9-9fdd-2eef271ade80)

- **Welcome** - Welcome to All The Mods 10!
- **Allthemodium** - Allthemodium, Allthemodium Smithing Template, Allthemodium Ingot, Teleport Pad, Vibranium Smithing Template, Vibranium Ingot, Unobtainium Smithing Template, Unobtainium Ingot, Hephaestus Forge, Enchanting Apparatus, Dissolution Chamber and Energizing Orb
- **Bounty Board** - Kill 100x Zombie, Kill 100x Skeleton, Kill 100x Creeper, Kill 100x Spider, Kill 100x, Witch, Kill 100x Blaze, Kill 100x WIther Skeleton, Kill 100x Enderman and Kill The Wilden Chimera
- **Building Tips** - Glass, Logs, Metal and Gem Blocks, Blocks!, Colored Blocks, Stone Blocks, Building Tips!, Decoration!, Tools!, Paxel, Light Sources, Macaw's Mods and Decor Mods!
- **Chapter 1: The Beginning** - Welcome to Getting Started!, Archaeology, Basic Ore Doubling, The Metal Age, The End and Kill The Warden
- **Chapter 2: The ATM Star** - !ALL IMAGES!
- B**asic Tools** - Basic Tools!
- **Silent Gear** - Silent Gear, Blueprint Paper, Salvager, Recrystallizer, Material Grader, Repair Kits, Alloy Forge and Starlight Charger
- **Basic Storage** - Storage Controller, Controller Access Point, Linking Tool, Drawers, Functional Storage, Vanilla Storage, Sophisticated Storage, Sophisticated Backpacks, Storage Controller
- **Applied Energistics 2** - Applied Energistics 2, The Storage, Autoi-Crafting, 1M Storage Component, Spatial IO and The IO
- **Basic Logistics** - Pipez, Item Importing, Fluid Importing, Energy Importing, Logic Cable, Integrated Dynamics, Mekanism, Pressurized Tubes, Thermodynamic Conductors, Universal Cables, Logistics, Laser Connector, Laser Node, Laser IO, Laser Wrench, Basic Filter, Mod Filter, Counting Filter, Tag Filter, Chemical Card, Fluid Card, Item Card, Energy Card and Redstone Card
- **Integrated Dynamics** - Integrated Dynamics
- **Modular Routers** - Modular Routers, Routers for Farming, Router for Mining, Augments, Routers for Mob Farms and Upgrades
- **Pylons** - Pylons, Infusion Pylon, Expulsion Pylon, Harvester Pylon and Interdiction Pylon
- **Apothic Spawners** - Apothic Spawners
- **Food and Farming** - Cake, The Planter, The Start of a Fisher, Food and Farming, Making a Kitchen, with a book, THE BEST THINGS SINCE SLICED BREAD and Purchasing Farm Supplies
- **Hostile Neural Networks** - Hostile Neural Networks!, Creating Loot and Piglich Prediction
- **Mystical Agriculture!** - Mystical Agriculture!, Prosperity Shards, Prosperity Seed Base, Machine Upgrades, Infusion Altar, Inferium, Tinkering Table, Infusion Crystal, Prudentium, Tertium, Imperium, Supremium, Awakened Supremium, Master Infusion Crystal, Insanium and Creative Essence
- **Productive Bees** - Productive Bees!, Advanced Beehive, Honey Treat and Upgrade Base
- **Extreme Reactors** - Welcome to Extreme Reactors!, Reactor Building Components, Our First Reactor, Rossinite, The Turbine, Insanite Block and Reprocessor Controller
- **Generators N Furnaces** - Augment: Blasting, Augment: Smoking, Augment: Factory, Augment: Generator, Augment: Speed, Augment: Fuel Efficiency and The Furnace
- **Industrial Foregoing** - Industrial Foregoing, 
- J**ust Dire Things** - Upgrade: Blank, VoidShimmer Goo, Shadowpules Goo, Primogel Goo and Blazebloom Goo
- **Mekanism** - Mekanism, Heat Generator, Metallurgic Infuser, Energy Tablet, Robit, Chargepad, Custom Portals!, Digital Miner, Jetpack, Configurator, Quantum Entangloporter, Atomic Disassembler, Advanced Solar Generator, Solar Generator, Steel, Wind Generator, Bio-Generator, Basic Universal Cable, Advanced Universal Cable, Ultimate Universal Cable, Elite Universal Cable, Basic Mechanical Pipe, Basic Pressurized Tube, Advanced Pressurized Tube, Ultimate Pressurized Tube, Elite Pressurized Tube, Basic Logistical Transporter, Basic Thermodynamic Conductor, Advanced Thermodynamic Conductor, Ultimate Thermodynamic Conductor, Elite Thermodynamic Conductor, Basic Energy Cube, Basic Tier Installer, Basic Chemical Tank and Basic Fluid Tank
- **Mekanism: Reactors** - Mekanism: Reactors, Antimatter Pellet, Completing the Matrix, The Fusion Reactor, I Think We're Ready, Uranium and Fissile Fuel
- **PneumaticCraft** - PneumaticCraft: Repressurized, Generating Pressure, The Pressure Chamber, Plastic and Using Assembly Lines
- **Powah** - Welcome to Powah!!! and The Energizing Orb
- **RailCraft** - RailCraft, Rails!, Tracks!, Carts 'N' Trains! and Machines
- **Apothic Enchanting** - Enchanting with Apothic, Infusion Enchanting, Best Enchanting set-up
- **Ars Nouveau** - Welcome to Ars Nouveau!, Scribe's Table, Source Gems, Source Jar, Arcane Pedestals, Ritual Brazier and Enchanting Apparatus
- **Artifacts** - Artifacts
- **EvilCraft** - Welcome to EvilCraft, Colossal Repairs, Infusion Cores, Vein Sword, The Blood Infuser, Blood Brooms, Vengeance Pickaxe, Capturing Spirits, Effortless Ring, Upgrading Machines, Rank 2: More Bloood, Creating Spawn Eggs, Mob Farms using Blood, Rank 3: Even More Blood, Garmonbozia and Rejuvenated Flesh
- **Iron's Spells 'n Spellbooks** - Lightning, Fire, Classes, Iron's Spells 'n Spellbooks, Ender, Ice, Holy, Blood, Evocation, Nature, The Last Class..., The Dead King, Catacombs, Evoker Fort, Mountain Tower, Adventure Time, Village, Mangrove Hut, Pyromancer Tower, On a Highway to... Ancient Battleground and Ancient Knight
- **Occultism** - Empty Soul Gem, New Tools for New Ores, Chalking It Up, Demon Mining, The Marid Crusher and Upgrading Out Magical Storage
- **Relics** - Relics, Overworld, The Nether and The End
- **Theurgy** - Divination Rods, Item Movement, Wires go here, Wires go there, Logistics with Mercury, Fluid Movement, Digestion Vat, Fermentation Vat, Incubator, Alchemical Sulfurs, Making Sal Ammoniac, Desalination Plant and Heat
- **The Bumblezone** - Into the Hive, Howling Constructs, Floral Meadow, Pollinated Pillars, Pollinated Fields, Hive Pillar, Hive Wall, Lakes of Sugar! (Water) and Crystal Canyons

Most of them only show up when zoomed in.
And yes, I spent over 2 hours doing this 😆

**Comment by TheBedrockMaster** [comment]
That's a bug with FTB Quests, we're waiting for a fix. You really didn't have to make this list 😅
