### ISSUE TITLE
[Quests issues]: Welcome tab not updated.

### ISSUE THREAD

**Issue by Kilvis** [AllTheMods/ATM-10#79]
### Modpack Version

0.9+new commits

### Describe the issue

In the welcome tab of the questline the welcome quest says "All The Mods 9" instead of "All The Mods 10":
![image](https://github.com/AllTheMods/ATM-10/assets/76570572/ed5b6308-d611-4aab-a8e8-95018bec7888)

**Comment by TheBedrockMaster** [comment]
Will be fixed by: https://github.com/AllTheMods/ATM-10/pull/80
