### ISSUE TITLE
[Bug]: Failed to connect: Channel of mod "NaturesAura" (Server)

### ISSUE THREAD

**Issue by SpicyPineapple45** [AllTheMods/ATM-10#790]
### Possible Fixes

Yes

### Modpack Version

1.1

### What happened?

When joining my server, me and my friend both get the error "_failed to connect: Channel of mod "NaturesAura" failed to connect: This channel is missing on the server side, but required on the client!_". I have tried backing up the server, reinstalling the server modpack, reinstalling my client modpack, and nothing has worked. There is also an error when joining that says "_Incompatible client! Please use NeoForge 21.1.68_", the incompatible client error still appears even when changing to the version it says to use? I've also changed to NeoForge 21.1.71 with no luck.

The server was working just fine a few hours ago before on 1.0 but is now essentially bricked since updating to 1.1, and the issue happens for everyone trying to join.

### latest.log
(https://gist.github.com/SpicyPineapple45/650440ac4b3ef18cedef73d157e14c12)

**Comment by alekthefirst** [comment]
This was highly likely an issue of server not being updated to 1.1 yet and thus not having natures aura
