### ISSUE TITLE
[Bug]: Pack Neoforge version wrong

### ISSUE THREAD

**Issue by majestic44** [AllTheMods/ATM-10#791]
### Possible Fixes

Yes

### Modpack Version

10-1.1

### What happened?

After updating the Modpack to Version 10-1.1 and the server files to the version to files attached to modpack it gives error that Client Neoforge Version is wrong.

![image](https://github.com/user-attachments/assets/e06b43e7-f656-4acd-a5fd-4c0406e00e28)
![image](https://github.com/user-attachments/assets/977d7118-598b-48d1-85a2-378bfdeb96f0)

Lost Connection when attempting to connect to my server.
![image](https://github.com/user-attachments/assets/47ad2d86-cb72-448d-9914-dce94da398b1)

### latest.log

https://gist.github.com/majestic44/14b3ae49e7f5b944d122d7dd902f537d

**Comment by KhiGamma** [comment]
Hello,

We've got the same issue on our server with a friend.
The Neoforge version for the client (ATM10 1.1) is 21.1.69, whereas the one for the server (still ATM10 1.1) is 21.1.71.

We got the same error message, leading us to update the Neoforge version for our client to 21.1.71. But we still got the same message even though our client gives us the correct Neoforge version.

**Comment by streamkiller** [comment]
Downgrading server to neoforge 21.1.69 doesn't work, basically the client pack needs to be updated to .71 for it to be fixed.

**Comment by TheBedrockMaster** [comment]
This should be fixed in the next release which is coming soon™️

**Comment by mrconnerton** [comment]
I had this same issue but with `21.1.72`. The problem was when I updated the server, I overwrote the existing server files with the new ones instead of creating a whole new server directory and copying my world over to it.
