### ISSUE TITLE
[Bug]: Living Things causes Velocity Proxy to no longer allow players to connect to ATM10 servers

### ISSUE THREAD

**Issue by LevyWilson** [AllTheMods/ATM-10#792]
### Possible Fixes

Yes

### Modpack Version

1.0-1.1

### What happened?

Since updating my server to 1.0 and later 1.1, I couldn't connect through Velocity, which I'd been able to do easily before. Through process of elimination by disabling the added mods in 1.0, I discovered disabling Living Things allows connections again. I don't know if it's specifically to do with the mod or if there's some kind of conflict with commands, but the simple fix for me was to just disable the mod on the server.

### latest.log

https://gist.github.com/LevyWilson/f5471171010818d65d1ca7ba62dc6d5b

### Developer reports

https://github.com/tristankechlo/LivingThings/issues/48

**Comment by tristankechlo** [comment]
LivingThings received an update on 2024-10-18, the problem should be fixed with the modversion 2.1.3
