### ISSUE TITLE
[Quests issues]: Fusion reactor does not produce 200 MRF/t

### ISSUE THREAD

**Issue by TarcisMoreda** [AllTheMods/ATM-10#794]
### Modpack Version

1.1

### Describe the issue

I followed the quest line and made a fusion reactor with direct D-T Fuel injection.
The quest says it can generate up to 200 MRF/t with 500 mb/t if D-T Fuel but it generates 80 MRF/t max.
![Fusion not good ( - Imgur](https://github.com/user-attachments/assets/d53ad42d-7f46-4374-b08f-ac151d4750ab)

**Comment by LordCorellon** [comment]
It was nerfed several versions ago, I'm not sure if it was intentional or not but it's been 80MRF/t for a while, if it was intentional I agree the quest should be updated with the new description

**Comment by Fangzwusky** [comment]
Pretty sure this is intended. as they labeled the parts with Reduced energy production. Guessing quest is copy pasted from ATM9. so probably just a typo in quest.

I got same results, fission reactor is also nerfed. But Turbine does not list any nerfs, it has a tag for increased production speed. They might want us too use water cooled Fusion reactor for higher yield and complexity.

**Comment by TheBedrockMaster** [comment]
This was changed after the quests were in ATM10, they will be updated at some point.

**Comment by SeanLatimer** [comment]
What was the reason for nerfing reactors in the first place?

If anything it feels like punishing the player for running a more complex reactor vs buffing the less viable solutions to closer match the more difficult to run setups.

**Comment by FireBall1725** [comment]
Hey ATM team 👋 , I noticed SeanLatimer's message was deleted, but I actually have a similar question. In previous ATM versions, this feature wasn’t nerfed, which allowed me to build some cool setups powered by a ComputerCraft app. Part of the fun was managing the risks—especially since messing up with this reactor can get serious! Now, in ATM10, it’s so heavily limited that the program I used barely functions—I can’t even set up a full Mekanism fission reactor. Is there any chance this nerf could be reconsidered?

**Comment by TheBedrockMaster** [comment]
> Hey ATM team 👋 , I noticed SeanLatimer's message was deleted, but I actually have a similar question. In previous ATM versions, this feature wasn’t nerfed, which allowed me to build some cool setups powered by a ComputerCraft app. Part of the fun was managing the risks—especially since messing up with this reactor can get serious! Now, in ATM10, it’s so heavily limited that the program I used barely functions—I can’t even set up a full Mekanism fission reactor. Is there any chance this nerf could be reconsidered?

This isn't the place to ask. The nerfs are staying, however if you have some changes you want made feel free to make a new feature request issue.
