### ISSUE TITLE
[Bug]: Iron furnaces Augment Dupe

### ISSUE THREAD

**Issue by zain-zzz** [AllTheMods/ATM-10#8]
### Possible Fixes

Yes

### Modpack Version

0.1

### What happened?

Iron furnaces don't seem to consume the augment when you right click on the furnace. Example video attached.

https://github.com/AllTheMods/ATM-10/assets/94076149/a38e1dea-0149-4b96-b043-7b83461b9c9a

### latest.log

https://gist.github.com/zain-zzz/a9505f7eb264c4957a35daf20c389c46

**Comment by zain-zzz** [comment]
Bug is still present in 0.2!

**Comment by frogalo** [comment]
Still present in 0.3

**Comment by Kevin-Marsh** [comment]
This has been reported to the dev and we are awaiting a fix.
