### ISSUE TITLE
[Bug]: Corail seed bags give high level Myst agriculture seeds

### ISSUE THREAD

**Issue by KaiAndreas1** [AllTheMods/ATM-10#800]
### Possible Fixes

Yes

### Modpack Version

10-1.1

### What happened?

the item Bag of seeds from Corail gives many different seeds from Mystical agriculture and I am fairly sure this is not intended behavior.

so far i have gotten both allthemodium and unobtanium seeds as well as,
Neutronium
Dragon egg
HDP Graphite

I have also gotten seeds from mods that are not in this mudpack yet:
Botania
astral sorcery
Tinkers construct
Draconic evolution

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/784
