### ISSUE TITLE
[Bug]: Reoccuring Quests after have been completed

### ISSUE THREAD

**Issue by SatansRightNut** [AllTheMods/ATM-10#801]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

When completing quests ahead of time, there can be a bug that makes it so the quests completed continue to pop up over and over again until the world is exited.

**Comment by kcjennin** [comment]
This is also happening on 1.1.

I've attached a server crash log related.
[crash-2024-10-17_06.33.15-server.txt](https://github.com/user-attachments/files/17407175/crash-2024-10-17_06.33.15-server.txt)

It doesn't trigger immediately, it's possible it is trigged by completing a quest.

**Comment by TheBedrockMaster** [comment]
Yeah, that happens sometimes with FTB Quests, you can relog to fix the issue or your game will usually eventually crash.
