### ISSUE TITLE
[Bug]: Digging Claw & Onion rings do not seems to have any effects on this modpack.

### ISSUE THREAD

**Issue by Xiarno** [AllTheMods/ATM-10#803]
### Possible Fixes

Yes

### Modpack Version

1.1

### What happened?

Using the Digging Claw and/or Onion Ring do not give any mining bonus whatsoever. Mining speed is not increased with neither and the digging claw do not increases the block mining level with hand to stone.

This only occurs on the modpack. With the mod by itself, everything works as expected.

### Developer reports

https://github.com/ochotonida/artifacts/issues/333

**Comment by Xiarno** [comment]
I can confirm after trying it on an instance with only the Artifacts mod that this occurs in the ATM10 modpack configuration. The mod alone by itself is working as expected.

**Comment by SSKirillSS** [comment]
Hi, as far as I know, ATM10 uses Artifacts with RAR-Compat installed, making it compatible with Relics. This changes the mechanics of the items, so they not work as you expect. You can hover over the item and hold shift to view its abilities.

**Comment by Xiarno** [comment]
> Hi, as far as I know, ATM10 uses Artifacts with latest RAR-Compat installed. This changes the mechanics of the items, so they not work as you expect. You can hover over the item and hold shift to view its abilities.

Yeah I know. I looked at the effect and none of them work as their description says.

**Comment by Xiarno** [comment]
> Hi, as far as I know, ATM10 uses Artifacts with latest RAR-Compat installed. This changes the mechanics of the items, so they not work as you expect. You can hover over the item and hold shift to view its abilities.

To get more into details on it not working.

The Digging Claws description is:
> Strengthens the relic holder's hands, allowing for more efficient block breaking.

With the ability, Speed Mining, mentioning "Increases block mining speed". I tested and timed it and it has no effect on the mining speed at all, even at max possible level.



For the Onion Ring, the description is:
> Increases the efficiency of block mining for the relic holder when their hunger level is sufficiently high.

With the ability, Miner's Hunger, mentioning "Increases mining speed based on the player's hunger". Again, there is no difference in speed between mining at max hunger and mining at zero hunger.

**Comment by alekthefirst** [comment]
Both of these relics have since received updates
