### ISSUE TITLE
[Bug]: Mismatch in Neoforge between server and client

### ISSUE THREAD

**Issue by streamkiller** [AllTheMods/ATM-10#805]
### Possible Fixes

Yes

### Modpack Version

1.1

### What happened?

I wanted to boot a server with friends but we get neoforge mismatch when trying to connect to the server.
After investigating the server pack on the curseforge uses the neoforge-21.1.71-installer.jar
While the client uses the 21.1.69 version, because of this you can't install freshly currently.

I am downloading the 21.1.69 version of neoforge and will look if i install the server with that .jar if it works.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/791
