### ISSUE TITLE
[Feature] Silent Gear MA Seeds

### ISSUE THREAD

**Issue by DaddyLongspoon** [AllTheMods/ATM-10#807]
Can we please have MA essence for the silent gear metals? we've historically had seeds/essence for crimson iron, azure silver etc. They're not turning up in the mining dimension. (or maybe a couple of bees? that'd be even nicer)

and please consider giving silent gear support to the atm metals again? its been such a long time.  They needn't be so OP as they were in atm6, there's only the vanilla dragon after all..Just something around on par with tyrian steel in a different colour, maybe indestructible trait..?

thanks so much for considering, love your work. God bless.

_Originally posted by @DaddyLongspoon in https://github.com/AllTheMods/ATM-10/issues/2#issuecomment-2420104449_

**Comment by Krotu** [comment]
not related to seeds, but the silent gear metals also worked with mekanism ore processing in atm9 but the recipes are missing in atm10, I presume those metals had interactions with other mods which may also be missing.

**Comment by DaddyLongspoon** [comment]
thanks mr bedRockMaster, legend.. only took a couple of hours

**Comment by DaddyLongspoon** [comment]
PS Also thanks to Satharov for taking care of that second paragraph there, I considered that one a long shot.  Champion!!
