### ISSUE TITLE
[Bug]: Book of Natural Aura doesn't work

### ISSUE THREAD

**Issue by indygwyn** [AllTheMods/ATM-10#815]
### Possible Fixes

Yes

### Modpack Version

1.1

### What happened?

JEI doesn't show the recipe, but the default recipe (paper, paper, leather, oak sapling) works.  However you just get an unusable patchouli:guide_book with a Book ID of null.

**Comment by indygwyn** [comment]
Update, I was able to give myself the correct book via 
`/give player patchouli:guidebook[patchouli:book="naturesaura:book"]`

**Comment by pr0saic** [comment]
This seems to be a bug in Natural Aura, I have suggested a fix, hopefully fixed next version

**Comment by pr0saic** [comment]
This is fixed in the newest Natural Aura version
