### ISSUE TITLE
[Bug]: Applied Energistics quests

### ISSUE THREAD

**Issue by Krotu** [AllTheMods/ATM-10#817]
### Possible Fixes

Yes

### Modpack Version

1.1

### What happened?

None of the quests that are off the main chain seem to flagged correctly and do not complete.
"Auto-crafting"
"The IO"
"Spacial IO"
all have the dependency "ME Glass Cables", but when clicked it goes to "Basic cabling", the glass cabling quest seems to be missing or was renamed to "Advanced Cabling".

**Comment by jerryjjr** [comment]
I'm not sure if this is related, but clicking on the "collect rewards" button at the top left started a never ending cycle of AE2 quests "completing"  (also version 1.1)
