### ISSUE TITLE
[Bug]: Bees and EMI

### ISSUE THREAD

**Issue by Nile737** [AllTheMods/ATM-10#82]
### Possible Fixes

Yes

### Modpack Version

0.9

### What happened?

If you look at the uses and recipes for productive bee eggs EMI can't tell the difference between the different eggs.
![image](https://github.com/AllTheMods/ATM-10/assets/104466631/347708b4-c0ff-4899-9905-48f9c0b86d72)

### latest.log

https://gist.github.com/Nile737/1863835e4b8e61bf537671ba00037d15

**Comment by aAndrew3030** [comment]
If your still having issues with this in the modpack version .11, you can try resetting your EMI config
