### ISSUE TITLE
[Bug]: Master Infusion Crystal Dupe

### ISSUE THREAD

**Issue by AspireVibeez** [AllTheMods/ATM-10#820]
### Possible Fixes

No

### Modpack Version

1.1

### What happened?

When crafting essence with Master Crystal in a crafting table on a stick, if you tab to do the same recipe it gives you more crystals depending on how many times you hit tab.

**Comment by alekthefirst** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/138
