### ISSUE TITLE
[Crash]: Server crashing after player connects

### ISSUE THREAD

**Issue by Krakys1** [AllTheMods/ATM-10#825]
### Possible Fixes

Yes

### Modpack Version

1.2

### What happened?

I updated server (from 1.1 to 1.2) that I was playing on with my friend - I was hosting it on my PC.  I placed down atomic reconstructor from Actually Additions (but I don't think that this was the cause of the crash) and few seconds later the server crashed. When I start the server, it runs perfectly fine (I can send commands and the server does respond to them), but as soon as any of us join, the server immediately crashes. This means that we cannot join the server as of right now (but I made a backup that is working before).
Note: The server was working for a while before these crashes broke it. 
Note: Server with ATM version 1.1 worked just fine without any issues.

### Crash Log

https://gist.github.com/Krakys1/d07a162e596926ba20d878a5df664270

### Latest.Log

https://gist.github.com/Krakys1/e92ad74aea45b9dbb0c219c3c112f984

**Comment by Mrbysco** [comment]
Should be fixed in the next version of AA
