### ISSUE TITLE
[Bug]: Pillager tower inside of village

### ISSUE THREAD

**Issue by Paradunox** [AllTheMods/ATM-10#826]
### Possible Fixes

Yes

### Modpack Version

1.2

### What happened?

I created a new world and spawned next to a village and there was a pillager tower clipping through one of the houses and pillagers were attacking the villagers.
Seed: -5346042030298901470
Coordinates: 41 64 102

![2024-10-19_10 26 49](https://github.com/user-attachments/assets/d90d61b0-4b8d-4335-93ae-1c051800be97)
![2024-10-19_10 26 57](https://github.com/user-attachments/assets/c24addfb-e269-43e9-9983-c7ffb8b807c0)
![2024-10-19_10 27 02](https://github.com/user-attachments/assets/a081bde0-74ae-46c1-9016-061967c30e74)
![2024-10-19_10 36 38](https://github.com/user-attachments/assets/59ae53f8-d892-4218-8c16-ab23f45741ef)
![2024-10-19_10 36 47](https://github.com/user-attachments/assets/764d13b7-247d-4d89-8c20-0b173b84c6e7)

**Comment by zordem** [comment]
i dont think this is fixable by the atm maintainers

**Comment by TheBedrockMaster** [comment]
Ok
