### ISSUE TITLE
[Crash]: Waystone 

### ISSUE THREAD

**Issue by Olper02** [AllTheMods/ATM-10#83]
### Possible Fixes

Yes

### Modpack Version

0,9

### What happened?

Used a waystone to teleport from one place too another (8032m) crashed before ariving

### Crash Log

https://gist.github.com/Olper02/2275d73ccced2ac6f9dad5c5cea81ada

### Latest.Log

https://gist.github.com/Olper02/39cbbea80dbdffacc03bd9566b88a337

**Comment by Kevin-Marsh** [comment]
This will be fixed in the next version of the pack with an update to the relics mod.
