### ISSUE TITLE
[Bug]: Can't load into world after updating to 1.2

### ISSUE THREAD

**Issue by alpha-pvp** [AllTheMods/ATM-10#830]
### Possible Fixes

Yes

### Modpack Version

1.2

### What happened?

I updated from 1.1 to 1.2 and get an error message (images attached).
![Screenshot 2024-10-19 224108](https://github.com/user-attachments/assets/f7422a00-68fc-42e0-befc-3a7f58662844)
![Screenshot 2024-10-19 224049](https://github.com/user-attachments/assets/af73778f-917c-4bdd-bdde-e39e1e57e50a)

### latest.log

https://gist.github.com/alpha-pvp/5bbb72b7289d53d6485a6a60b33dd0f2

**Comment by JakeStensrud** [comment]
I am also getting this error. This affects 1.2 and 1.3 as far as I can tell. I can't start a new world on these versions either, the game immediately crashes. I tried more ram, around 13 GB's, but that didn't work either. Would love to see this fixed in 1.4!
