### ISSUE TITLE
[Bug]: no Data Model for Tangled Hatred

### ISSUE THREAD

**Issue by DeclanHawkes1** [AllTheMods/ATM-10#832]
### Possible Fixes

Yes

### Modpack Version

10.1.2

### What happened?

When trying to create a Hostile Neural Networks model of the Tangled Hatred in the Eternal Starlight zone, you are instead given a message of 'No know models exist for this specimen.'. JEI shows a model should exist and the loot available from the prediction (in this case vines for the Chain of Souls to make multiple ATM stars) but you can't create the model from the Tangled Hatred mob.

**Comment by shade1822226911** [comment]
it does exist, just use the model at the BOTTOM of the hatred, not any other segment only the base

**Comment by DeclanHawkes1** [comment]
> it does exist, just use the model at the BOTTOM of the hatred, not any other segment only the base

I have tried the bottom, literally standing beside it right clicking the base and the ground. I will try again thank you.

**Comment by shade1822226911** [comment]
You're welcome. also let me try to get a pic of where to click to get the model. might take like 10 mins

**Comment by DeclanHawkes1** [comment]
> You're welcome. also let me try to get a pic of where to click to get the model. might take like 10 mins

I got it, had to really spam the right click on the ground and finally got it

**Comment by shade1822226911** [comment]
> > You're welcome. also let me try to get a pic of where to click to get the model. might take like 10 mins
> 
> I got it, had to really spam the right click on the ground and finally got it , Thank you again!

You're welcome! 

Guess I don't need the picture anymore.

**Comment by DeclanHawkes1** [comment]
Closed now that [shade1822226911](https://github.com/shade1822226911) gave me the solution.
