### ISSUE TITLE
[Crash]: The game crashed whilst initializing game Error: java.lang.IllegalStateException: Mod 'architectury' is not available!

### ISSUE THREAD

**Issue by OBS3SS1ON** [AllTheMods/ATM-10#839]
### Possible Fixes

Yes

### Modpack Version

1.3

### What happened?

Hi i have architectury-13.0.6-neoforge on folder. but.
client load and get The game crashed whilst initializing game
Error: java.lang.IllegalStateException: Mod 'architectury' is not available!

### Crash Log

https://gist.github.com/OBS3SS1ON/c0b143721b5259a71f003694f8c2fb37

### Latest.Log

https://gist.github.com/OBS3SS1ON/7544e10970a5db7d256ac3ba23f982ef

**Comment by OBS3SS1ON** [comment]
Thx fixed on version 1.4

**Comment by alekthefirst** [comment]
Duplicate of https://github.com/AllTheMods/ATM-10/issues/130
Glad that it got fixed for you
