### ISSUE TITLE
[Feature]: Encourage to use armory cabinet + AE2 storage bus via quest

### ISSUE THREAD

**Issue by Yukari7777** [AllTheMods/ATM-10#846]
### Feature Details

It would be great to make a tutorial about such OP armory cabinet + storage bus combo in AE2 chapter.
Armory cabinet has 4096 non-stackable-only item slots. 
It significantly reduce the amount of works about storage managements 

Also it's easy to setup as following:
1. Get ME network ready and connect some cable.
2. Attach armory to ME storage bus.
![image](https://github.com/user-attachments/assets/e4dd3427-9d63-4152-bff5-609ea85a78ee)
3. Set priority to somewhat really high value.
![image](https://github.com/user-attachments/assets/b35be588-d632-4bde-9d3b-a3f3b958e2fc)
![image](https://github.com/user-attachments/assets/a465f98b-0714-46cb-bb2d-2ee0b2a4bb5c)

I'd like to share this tip as it is seemingly not well-known.

**Comment by Yukari7777** [comment]
Closed as it has tps drop issue.

**Comment by TheBedrockMaster** [comment]
True, but I would like to make a quest for it that doesn't encourage it
