### ISSUE TITLE
[Bug]: Wood and Uranium seeds cannot be activated with wand or redstone

### ISSUE THREAD

**Issue by eqdie** [AllTheMods/ATM-10#847]
### Possible Fixes

Yes

### Modpack Version

ATM 10-1.4

### What happened?

Wood seeds and Uranium seeds cannot be made at all. I am playing on a multiplayer server when I found the issue. I went into a singleplayer world and the issue persisted.

**Comment by Fangzwusky** [comment]
same, infusion altar recognizes the recipes, and says Uranium seed. But will not start crafting. all other I tried work

**Comment by pr0saic** [comment]
Works fine for me, have you got any other mods that modify uranium?
![1](https://github.com/user-attachments/assets/5a3e6865-b761-477e-9b75-f5f6acd57be7)
![2](https://github.com/user-attachments/assets/587100b7-d05b-4614-9c2d-2a108f957b65)

**Comment by jacojazz** [comment]
Also didn't work for me for Certus Quartz seeds. Placed all the items in the stands, seed base in the middle, lever on but nothing. If I hover over the centre altar it says "Certus Quartz seeds" but doesn't actually make them. (Version 1.5)

**Comment by tyler489** [comment]
Also does not work for silver seeds, the recipe shows, but cannot start.
V1.5 As well

**Comment by schwetim** [comment]
Also does not work for tin seeds, V1.5 As well.

**Comment by eqdie** [comment]
> Works fine for me, have you got any other mods that modify uranium? ![1](https://private-user-images.githubusercontent.com/60778064/378623334-5a3e6865-b761-477e-9b75-f5f6acd57be7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDMzNTcsIm5iZiI6MTcyOTY0MzA1NywicGF0aCI6Ii82MDc3ODA2NC8zNzg2MjMzMzQtNWEzZTY4NjUtYjc2MS00NzdlLTliNzUtZjVmNmFjZDU3YmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDAwMjQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyODZmYmZkMTQxOTNiYzIwZjAyZTc3NzI2NDIzNjAyMDMyZDM0YjU3YTA0Nzk5Y2E1YmU2ODBhODJkMzRmOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RlJkNkCC2lJ0X1j5up0_j24HtwUpNH0rSxJL-9jUgvk) ![2](https://private-user-images.githubusercontent.com/60778064/378623377-587100b7-d05b-4614-9c2d-2a108f957b65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDMzNTcsIm5iZiI6MTcyOTY0MzA1NywicGF0aCI6Ii82MDc3ODA2NC8zNzg2MjMzNzctNTg3MTAwYjctZDA1Yi00NjE0LTljMmQtMmExMDhmOTU3YjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDAwMjQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNGYwNmUwNjFkZjA0ZGRhMmFkMmE2NGNkYWQzMGM3YjYyMjQzZjMxZmY0OTYwMzMzODBhNTNhYjY2YjFjNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J8ht4OQt8ot_mvE2moeZePRfMeAH0GjwuPzBdp9vYWI)

Nope, just got all the mods that come with the modpack. As others describe, it'll show the name "Uranium Seed" when hovering over the altar but nothing will be made

**Comment by TheBedrockMaster** [comment]
Let me know if you have any similar issues in version 1.8, closing for now.

**Comment by Atiya96** [comment]
> Let me know if you have any similar issues in version 1.8, closing for now.

Still same issue
