### ISSUE TITLE
[Bug]: Obsidian Bee doesn't work

### ISSUE THREAD

**Issue by frogalo** [AllTheMods/ATM-10#85]
### Possible Fixes

Yes

### Modpack Version

0.9

### What happened?

Obsidian bee when put in the hive does not output the obsidian

**Comment by DaddyLongspoon** [comment]
nb.. has no 'flowering item' in the EMI.  same bug as we've experienced many times with productive bees eg titanium bee with atm8

**Comment by DaddyLongspoon** [comment]
this appears to have been addressed in 10.0.10, im getting obsidian dust from the bees now
