### ISSUE TITLE
[Bug]: Clicking on Tool Rack (Cooking for Blockheads) with some items causes the item to vanish (details below)

### ISSUE THREAD

**Issue by Shinino** [AllTheMods/ATM-10#852]
### Possible Fixes

Yes

### Modpack Version

1.0-1.4

### What happened?

I had Advanced Universal Pipes in hand while clicking on a tool rack to pick up the Configurator from Mekanism. When I did this, the pipes vanished. I've tested with other items, and expected behavior is that the item in-hand will go onto the tool rack.

The only thing I can think of is that these pipes cannot go on the toolrack, so it just poofed the items.

**Comment by ardaniel** [comment]
Can confirm that this happens with stock Minecraft torches. Grabbing a tool off the rack with something that isn't able to replace it in your hand just eats it. I checked my Prism Launcher console and do not see any relevant errors, sadly.
