### ISSUE TITLE
[Bug]: Bag of Seeds - Corail Tombstone Drops All Seeds

### ISSUE THREAD

**Issue by zeziba** [AllTheMods/ATM-10#853]
### Possible Fixes

Yes

### Modpack Version

1.5

### What happened?

The bag of seeds in my game world is dropped all mystic ag seeds.

I have 3 skeleton spawners in a poe enhanced with apoth and then am using the Holy Locket from relics to kill them and as a result they drop a ton of bags of seeds.

The bag of seeds has dropped each tier level of seed from 1-6. It even dropped a gaia seed, allthemodium+ and a bunch of other ones. I get that those seeds in particular are gated behind the crux but I have also gotten all the seeds needed for powah as well.

From what I am seeing in game I should not be getting a huge variety of these seeds as they are not in game, rightfully so as those mods are not in the pack.

### latest.log

n/a

**Comment by zeziba** [comment]
Could also be related to #849 as many of the seeds are also related to mods that are not in the pack.

**Comment by TheBedrockMaster** [comment]
> Could also be related to #849 as many of the seeds are also related to mods that are not in the pack.

Seems to be unrelated.

Dupe: https://github.com/AllTheMods/ATM-10/issues/784
