### ISSUE TITLE
[Crash]: Immersive Engineering Garden Cloche

### ISSUE THREAD

**Issue by indygwyn** [AllTheMods/ATM-10#856]
### Possible Fixes

Yes

### Modpack Version

1.5

### What happened?

Built IE Cloche, connected to sink with universal pipez, ender gate for energy.  Inserted soil soil, inserted wither rose, immediate crash.  Crash upon login after that.

### Crash Log

https://gist.github.com/indygwyn/cee14660d0068790d62821bad3ee6319

### Latest.Log

https://gist.github.com/indygwyn/b8427c32fffd83836d60f54bd70ce0fe

**Comment by indygwyn** [comment]
I've been able to duplicate this.  Will try again with a normal crop and see if it's just a cloche problem or specific to what is being grown in the cloche

**Comment by Nlcko** [comment]
I had the same issue. So, what did you do to recover your save? Is there a way to unload the chunk where the cloche is and remove it?

**Comment by entwinedent** [comment]
I also had the same problem but it was regular sand and a reed in a garden cloche. Tried too reload crashed again. Here is the crash report 
[crash-2024-10-22_16.19.17-client.txt](https://github.com/user-attachments/files/17481772/crash-2024-10-22_16.19.17-client.txt)

**Comment by ItsaBlitzz** [comment]
Same issue on my end with sand and cactus.

**Comment by indygwyn** [comment]
> I had the same issue. So, what did you do to recover your save? Is there a way to unload the chunk where the cloche is and remove it?
> 
> -- Block Entity Details -- Details: Name: immersiveengineering:cloche_master // blusunrize.immersiveengineering.common.blocks.metal.ClocheBlockEntity Block: Block{immersiveengineering:cloche}[facing=north,multiblockslave=false] Block location: World: (94,0,513), Section: (at 14,0,1 in 5,0,32; chunk contains blocks 80,-64,512 to 95,319,527), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023) Block: Block{immersiveengineering:cloche}[facing=north,multiblockslave=false] Block location: World: (94,0,513), Section: (at 14,0,1 in 5,0,32; chunk contains blocks 80,-64,512 to 95,319,527), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)

So, I run with a Server, so what I do is shutdown my client and my server.  Move the IE jar from mods folder to mods.off folder, start server (this will delete all IE blocks from your world, it's a pain if you've put all your tools in a toolbox like I did).  Then on the client side I do the same but by just turning off the mod in the Launcher (I use Prism).  Then I bring up the server, bring up the client and login.  If I don't do both the client and the server there's something leftover somewhere that causes the client to still crash.  Once I'd done the to remove the offending blocks from the world saves then I put the mod jar back in and play as normal (but I'm avoiding IE till I hear this is fixed).  I had a similar problem when they first added ActuallyAdditions I made the atomic restructurizer thing and got a crash as soon as I placed the  block.

**Comment by seals55** [comment]
Same issue here, soul soil + wither rose. Once it started growing, crash to desktop. Once my brother got close enough, crash to desktop.

My crash: https://mclo.gs/ngxjRvx

My brother's crash: https://mclo.gs/UjUxQpx

Playing v1.6 on a server.

**Comment by Beffa90** [comment]
Same crash for me; Wither Rose + Soul Soil in a Cloche with Mekanism ultimate energy cables hooked up to it. I've been able to duplicate the crash 4 times. Attached my crash report.
[crash-2024-10-24_10.48.29-client.txt](https://github.com/user-attachments/files/17504272/crash-2024-10-24_10.48.29-client.txt)

**Comment by Nlcko** [comment]
> > I had the same issue. So, what did you do to recover your save? Is there a way to unload the chunk where the cloche is and remove it?
> > -- Block Entity Details -- Details: Name: immersiveengineering:cloche_master // blusunrize.immersiveengineering.common.blocks.metal.ClocheBlockEntity Block: Block{immersiveengineering:cloche}[facing=north,multiblockslave=false] Block location: World: (94,0,513), Section: (at 14,0,1 in 5,0,32; chunk contains blocks 80,-64,512 to 95,319,527), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023) Block: Block{immersiveengineering:cloche}[facing=north,multiblockslave=false] Block location: World: (94,0,513), Section: (at 14,0,1 in 5,0,32; chunk contains blocks 80,-64,512 to 95,319,527), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
> 
> So, I run with a Server, so what I do is shutdown my client and my server. Move the IE jar from mods folder to mods.off folder, start server (this will delete all IE blocks from your world, it's a pain if you've put all your tools in a toolbox like I did). Then on the client side I do the same but by just turning off the mod in the Launcher (I use Prism). Then I bring up the server, bring up the client and login. If I don't do both the client and the server there's something leftover somewhere that causes the client to still crash. Once I'd done the to remove the offending blocks from the world saves then I put the mod jar back in and play as normal (but I'm avoiding IE till I hear this is fixed). I had a similar problem when they first added ActuallyAdditions I made the atomic restructurizer thing and got a crash as soon as I placed the block.

I found myself the same way to fixe it. I looked for another way for my knowledge to log with a console but apparently the only way would be to put it on a server to get it. I didn't lose too much. I had only a coke oven, the workbench and the cloche so i was not really an issue to do it again. I needed to duplicate my only one wither rose for my skeleton bee, i was lazy to make some chicken with a wither. :)

**Comment by pr0saic** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/6081

**Comment by jigokusaru** [comment]
Is there anything I can do while waiting for the update? I just tried to grow carrots in the cloche and crashed when the carrot was about to produce. I don't want to remove anything, and Curse Forge seems to be behind on that patch update mentioned. The patch is for 1.21.3 and the pack is stuck in 1.21.1. I don't know what to do my world is frozen until the update.

**Comment by jigokusaru** [comment]
NVM curse just was being dumb, i restarted it and it fixed everything

> Is there anything I can do while waiting for the update? I just tried to grow carrots in the cloche and crashed when the carrot was about to produce. I don't want to remove anything, and Curse Forge seems to be behind on that patch update mentioned. The patch is for 1.21.3 and the pack is stuck in 1.21.1. I don't know what to do my world is frozen until the update.
