### ISSUE TITLE
[Feature]: Dimensional Miners should mine Allthemodium Ore and Vibranium Ore

### ISSUE THREAD

**Issue by Nezkrul** [AllTheMods/ATM-10#858]
### Feature Details

I noticed in previous versions you guys updated the occultism dimensional miners to be able to get ATM ore and Vibranium ore, but you still broke it for All The Mods 10.  Can you re-fix 10 so we can get the ore with them?

**Comment by Satherov** [comment]
Eldritch Ancient Miner can drop raw allthemodium, vibranium and unobtainium blocks
