### ISSUE TITLE
[Crash]: Stuck when craft holding shift

### ISSUE THREAD

**Issue by mmouradev** [AllTheMods/ATM-10#86]
### Possible Fixes

Yes

### Modpack Version

0.10

### What happened?

When you craft things when holding SHIFT to make a stack the game gets stuck forever

![image](https://github.com/user-attachments/assets/abb9ae46-600d-4c5a-be98-13b83a0b2f78)

### Crash Log

none

**Comment by Kevin-Marsh** [comment]
Fixed in newer versions
