### ISSUE TITLE
[Bug]: Ars Nouveau Drygmy Henge broken - causes crash - no report generated

### ISSUE THREAD

**Issue by Innercord829** [AllTheMods/ATM-10#861]
### Possible Fixes

Yes

### Modpack Version

1.5

### What happened?

Upon right clicking on an a mossy cobblestone to summon a drygmy to begin creating the drygmy henge, the game errors out, but removes the save from the world selection, requiring you to restart the game. If this is done within a hyper box the game "crashes" getting stuck in a loop and resulting in you having to kill the instance, however this does create the henge and spawn the drygmy, the second time you click it crashes the same way. Within the overworld it just consumes the charm and doesn't succeed upon loading up the game again. The game does not produce a crash report either time, as the overworld doesn't cause it to crash, and the second one never finishes writing the report since you have to kill the instance. There are no images that I believe would be helpful. TO REPRODUCE: Just right click a mossy stone with a drygmy charm, both in overworld and within a Hyperbox

### latest.log

https://gist.github.com/Innercord829/0adf3aa99cf128a2c805725fea8dd597

**Comment by Kyassady** [comment]
i had this problem but it was way stranger then yours, and i got a crash report! i´ll put it in here.
also i reported this in ars nouveau github also.
this is the exact same issue i opened there:

i started a drygmy farm and used 1 Drygmy charm in a mossy stone, the henge was formed and the drygmy worked fine! when i tryied to add a second Drygmy my world crashed and i can't re-join. the console gave this entries:

[Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_entity_data'

versions:
MC-1.21.1
Neoforge-21.1.72
Ars versions-5.2.0
ars nouveau 5..0
ars additions 1.21.0-21.0.2
ars ocultas 2.0.1
ars elemental 0.7.0.7

Modpack: Allthemods10


https://mclo.gs/xnkWx3X


hope this help

**Comment by alekthefirst** [comment]
This was fixed in either Ars Noveau 5.2.1 or 5.2.2 https://github.com/baileyholl/Ars-Nouveau/issues/1454 released likely with ATM10 1.7
