### ISSUE TITLE
[Bug]: Seed bags, Unusable seeds

### ISSUE THREAD

**Issue by Fangzwusky** [AllTheMods/ATM-10#862]
### Possible Fixes

Yes

### Modpack Version

1.5

### What happened?

Opening seed bags I get a ton of mystical agriculture seeds. Including non craftable and non usable ones for materials not listed. and Cruxes not craftable. like Pig Iron seeds, Aquamarine seeds, Neutronium Tier6 seeds.

This feels like a bug as these are not craftable or usable as pig iron and neutronium is not even listed. and crux cant be crafted.

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/784
