### ISSUE TITLE
[Bug]: Immersive Engineering Steel Armor has broken levels of armor points

### ISSUE THREAD

**Issue by ImMorphi** [AllTheMods/ATM-10#863]
### Possible Fixes

Yes

### Modpack Version

1.4

### What happened?

Creating steel armor from immersive engineering has high levels of armor points for e.g. the helmet alone has +231 armor.

![image](https://github.com/user-attachments/assets/1b10a94a-c3c4-407a-bafe-f6d123823a44)

**Comment by pr0saic** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/6083
