### ISSUE TITLE
[Bug]: Enchanting apparatus doesn't see the recipe for the Ars Elemental spell book upgrade 

### ISSUE THREAD

**Issue by Nootaro** [AllTheMods/ATM-10#866]
### Possible Fixes

idk

### Modpack Version

All the Mods 10-1.5

### What happened?

What the title says. Yes, the enchanting apparatus is set up properly. So far every single craft has been successful but for some reason the netherite upgrade for the spell book won't work. It just gives the "No recipe found. Pedestals must be within 3 blocks." message in chat. It's not a new bug either, has been around for a couple weeks for sure. Again, I'm fairly certain there is nothing wrong with my setup since I did this before in ATM 8 or 9. 

![image](https://github.com/user-attachments/assets/c6a8f1b2-1937-43f7-8c91-cdac59de7924)

### latest.log

https://gist.github.com/Nootaro/a7db44939b87d1d5aa975c4625cf6a96

**Comment by funcraft35** [comment]
I'm playing on Craftoria 1.24.1(MC 1.21) 1. I'm having the same issues with the enchanting apparatus with different rece[ies. How did you resolve this? Is it a fix in the files or just how I built it(currently it's the same as the one in your picture)?

**Comment by Nootaro** [comment]
@funcraft35 Yeah sadly I can't help you with that. A few patches later it just worked so the maintainers must have squashed that bug? The enchanting apparatus is for sure built correctly though.
