### ISSUE TITLE
[Bug]: Nether Quartz Seeds

### ISSUE THREAD

**Issue by ZarkxWorld** [AllTheMods/ATM-10#868]
### Possible Fixes

Yes

### Modpack Version

ATM10 v1.5

### What happened?

![image](https://github.com/user-attachments/assets/9b866844-335f-4d1a-8a3d-99b3e48bddaa)
When attempting to perform the seed creation ritual for quartz with Mystical Agriculture, it simply doesn't work. However, when replacing the quartz with glowstone dust, it was created without any issues. This problem only occurs with the quartz seeds.

**Comment by izumaa** [comment]
Also Certus Quartz Seeds, Brass, and Silver

**Comment by TheBedrockMaster** [comment]
Happens sometimes for some people, not sure why.
