### ISSUE TITLE
[Feature]: Baubles with body slots

### ISSUE THREAD

**Issue by thisKid619** [AllTheMods/ATM-10#870]
### Feature Details

It would be nice to have items like the midnight robe from the artifacts mod or the backpack from sophisticated backpacks also fit into the body bauble slot. As far as I've seen there aren't hardly any body slot baubles and it feels like a wasted space.

**Comment by TheBedrockMaster** [comment]
They go on your back though, if there are any that should go in the body slot and don't go on the back slot let me know
