### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by ItsaBlitzz** [AllTheMods/ATM-10#873]
### Possible Fixes

Yes

### Modpack Version

1.5

### What happened?

Put a cactus in the garden cloche and it instantly crashed

### Crash Log

https://gist.github.com/ItsaBlitzz/fb0a500abb6f8aa28f674551242eee60

**Comment by Jason-337** [comment]
garden cloche crashed my client too when i tried to grow wheat seeds in it too on a server and anybody that goes in the chunks close to it crash out too

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/856
