### ISSUE TITLE
[Bug]: Gavels dont have uses

### ISSUE THREAD

**Issue by PrincesaRose** [AllTheMods/ATM-10#875]
### Possible Fixes

Yes

### Modpack Version

1.5

### What happened?

Forbidden & Arcanus gavels dont have uses left to craft the forge, the gui seems bugged.
![zadazdazdazdaz](https://github.com/user-attachments/assets/39a02f16-7008-4863-81c1-386337c78feb)

**Comment by pr0saic** [comment]
https://wiki.valhelsia.net/external-mods/forbidden-and-arcanus/wiki/items#blacksmith-gavel

**Comment by pr0saic** [comment]
https://github.com/stal111/Forbidden-Arcanus/issues/446

**Comment by pr0saic** [comment]
Fixed in 1.21.1-2.5.8-beta
