### ISSUE TITLE
[Bug]: Being redirected to the multiplayer page after interacting wtih XNet connector

### ISSUE THREAD

**Issue by FilippiLucas** [AllTheMods/ATM-10#877]
### Possible Fixes

Yes

### Modpack Version

1.6

### What happened?

When trying to interact with the XNet connector on my single player world I'm instantly redirect to the multiplayer page and i get the error "Connection Lost".

### latest.log

https://gist.github.com/FilippiLucas/d94a4c9d69e334f02987cf5ec6182b8c

**Comment by pr0saic** [comment]
![image](https://github.com/user-attachments/assets/bd3c3aa3-efd8-4698-b966-ce5c2106595c)

**Comment by pr0saic** [comment]
https://github.com/McJtyMods/XNet/issues/609

**Comment by Verkleckert** [comment]
Hi i also found the bung and just saw that it got fixed in mod version 7.0.1 on the issue that @pr0saic mentioned
