### ISSUE TITLE
[Crash]: Immersive Engineering Garden Cloche

### ISSUE THREAD

**Issue by Jason-337** [AllTheMods/ATM-10#883]
### Possible Fixes

Yes

### Modpack Version

1.7

### What happened?

Immersive Engineering Garden Cloche crashes client on starting. You can place the machine down and connect everything up to it just fine, you can open the interface without any issues as well. The problem seems to start as soon as it starts to grow whatever is placed in it. I created a few single player worlds and tried the same operation with a cactus, flower, wheat seeds, beet seeds and Nether wart with the same result of a full client crash. I adjusted the particles and display settings and removed shaders on each single player world i tested on and got the same result of a crash.

### Crash Log

https://gist.github.com/Jason-337/fc0236d5a8fb2601ceb064af8bd6edca.js

**Comment by psperneac** [comment]
+1 exactly what OP said. 

I installed pack again from fresh 1.7, copied save; loaded world, world shows up for ~1-2 seconds then it shortly displays 'Saving' and game closes.

**Comment by psperneac** [comment]
[latest.log](https://github.com/user-attachments/files/17514262/latest.log)

here's log

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/856
