### ISSUE TITLE
[Bug]: Prismarine Shards and Crystals have the same recipe using essence, and you can't make the shards.

### ISSUE THREAD

**Issue by epilimic** [AllTheMods/ATM-10#884]
### Possible Fixes

Yes

### Modpack Version

1.5

### What happened?

The crafting recipes are identical for prismarine shards and prismarine crystals, 3 essences across the middle. I can only get the crystals via this recipe and not the shards.

**Comment by epilimic** [comment]
The same thing happens with rabbit essence, all 3 recipes are the same with 3 essences going across but the only item you can make is rabbit meat and not the feet nor the hides.

**Comment by alekthefirst** [comment]
This has since been resolved
![image](https://github.com/user-attachments/assets/14afd60f-b713-4318-8b24-2ffe5e1f977a)
![image](https://github.com/user-attachments/assets/4ba533a6-cbfe-4572-8d11-eb9999590518)
