### ISSUE TITLE
[Bug]: Immersive engineering Ark Furnace can not be build due to absence of steel blocks. The ones that the game has is not recognized by Immersive Engineering mod.

### ISSUE THREAD

**Issue by papajs28** [AllTheMods/ATM-10#885]
### Possible Fixes

Yes

### Modpack Version

1.21.1

### What happened?

The furnace is not forming and when blocks are in inventory the engineers manual not recognizing.

**Comment by Fangzwusky** [comment]
Works for me, placed all blocks and clicked indicated block with hammer too form. no issues with steel blocks in pack. 1.6 and 1.7

**Comment by shade1822226911** [comment]
try the oredictionifier or whatever it's called from mekanism and set the tag to steel blocks and set the item to the immersive engineering steel block
