### ISSUE TITLE
[Bug]: Relic making block unbreakable

### ISSUE THREAD

**Issue by Dj-Lv** [AllTheMods/ATM-10#888]
### Possible Fixes

Yes

### Modpack Version

1.6

### What happened?

Hello,

Unfortunately I'm not entirely sure this is proper formatting and whatnot.

The Onion ring relic I had found day 1, apparently at some point maxed it out. I was trying to mine glowstone and the block just instant replaced. There were people in discord who saw it as well. It happened with dirt, and sculk I noticed as well.
Taking off the ring worked. I just wanted to bring awareness in case of others experiencing this.

DJ

**Comment by alekthefirst** [comment]
The onion ring has since received corrections in RAR-Compat 1.21–0.5.1 in ATM10 1.7 and RAR-Compat 1.21–0.8 in ATM10 2.7
