### ISSUE TITLE
[Crash]: Game crashes on Startup

### ISSUE THREAD

**Issue by Tibet1510** [AllTheMods/ATM-10#890]
### Possible Fixes

Yes

### Modpack Version

1.7

### What happened?

Since 1.0, but maybe even before that the game occassionally (more than 80% of the time) crashes on Startup.
It happens after the first micro-lag when registering xycraft (sometimes at this step aswell), the last step before it launches the menu, it will just freeze, and not do anything until it is closed.
Reinstalling the game fixes this issue most of the time.
Is however a major pain in the ass, because it resets all my settings and the server list.
It doesnt create any crash logs afaik, due to it crashing on startup.

### Crash Log

Not created, due to Crash on Startup

**Comment by Fangzwusky** [comment]
I would allocate more memory too the pack. Then next try install it on a different drive. And if problem persists I might run a memtest, sounds like your files might be getting corrupted.

**Comment by Tibet1510** [comment]
My memory was already set to about 16GB, I have 32GB of Memory in my System.
I did allocate 4 GB more but that didnt help, reducing it down to 12GB didnt help either.
Funny thing is I deleted ATM from my games SSD, and installed it in my data HDD, that seemed to fix it.
I restarted the game multiple times, restarted my pc aswell , didnt cause a crash at all.
Now I reinstalled it back to my SSD and it doesnt seem to work again, considering all my other games work fine, (even stuff like cyberpunk with 30+ mods) I honestly dont know if the reason is on my end or in the code.

And I dont believe it has to do anything with my memory, I do not have any other problems on my computer that could be attributed to that, but I will run memtest from the boot menu tomorrow just to be sure.

**Comment by Tibet1510** [comment]
You were right, sadly it was my SSD that is slowly dying.
Never had any issues with it before this startup problem. I used Samsung Magician and it had like 20 Bad sectors after a full scan.
Now I installed ATM on a different SSD and it does not crash anymore.
So thanks for the input ^^
