### ISSUE TITLE
[Bug]: Everything is green on lower light levels 

### ISSUE THREAD

**Issue by Motytheultimate** [AllTheMods/ATM-10#892]
### Possible Fixes

Yes

### Modpack Version

1.7

### What happened?

I upgraded to the latest version of the pack. 
And everything went green.
I cant find any option in the video settings that would disable this.
Does someone know what this shadow/fog/lightning is?
![2024-10-24_21 11 00](https://github.com/user-attachments/assets/d6e9d748-71d8-4b19-ae51-d8a50128ab32)

**Comment by PrincesaRose** [comment]
do you wear night vision googles ?

**Comment by ZarkxWorld** [comment]
Yep, all is green with vision googles after 1.7 modpack upgrade

**Comment by Motytheultimate** [comment]
i see then its my issue, i liked it better without the green but its okay

**Comment by ZarkxWorld** [comment]
that's not ur issue, i've green screen too
