### ISSUE TITLE
[Bug]: enrichment chamber not processing alltheores uranium

### ISSUE THREAD

**Issue by augu520** [AllTheMods/ATM-10#895]
### Possible Fixes

Yes

### Modpack Version

1.7

### What happened?

going through mekanism reactor quest line and i can't get yellow cake uranium because alltheores uranium is not getting processed, tried with ingots, raw version, blocks and dust, nothing works

**Comment by TheBedrockMaster** [comment]
Uranium Ingots in an Enrichment Chamber works for me
