### ISSUE TITLE
[Bug]: xycraft extractor and grains of infinity

### ISSUE THREAD

**Issue by thisKid619** [AllTheMods/ATM-10#897]
### Possible Fixes

Yes

### Modpack Version

10-1.7

### What happened?

the xycraft extractor will not generate grains of infinity no matter how the blocks are placed. creating the structure floating also does not fix this issue

**Comment by FilippiLucas** [comment]
Below the obsidian block you have to put a netherrack and set it on fire.

**Comment by TheBedrockMaster** [comment]
I can reopen this if needed.
