### ISSUE TITLE
[Bug]: Green Vision with night vision googles

### ISSUE THREAD

**Issue by ZarkxWorld** [AllTheMods/ATM-10#899]
### Possible Fixes

Yes

### Modpack Version

ATM10 v1.7

### What happened?

After updating to version 1.7 of the pack, using the night vision goggles from the Artifacts mod makes everything dark appear in a green hue.

**Comment by SeritoCat** [comment]
I have after the update glasses in general ceased to have any effect on the game, that they are there, that they are not - it is always dark

**Comment by jacojazz** [comment]
Same here, 1.7

**Comment by shade1822226911** [comment]
For me it happens with the mekasuit night vision module but it gives the sky a green hue instead of anything dark

**Comment by TheBedrockMaster** [comment]
This is intentional on the mods end however I believe the do intend to change some things about it.
