### ISSUE TITLE
[Bug]: AllTheOres "Dirty * Dust" don't go into Mekanism Enrichment Chamber

### ISSUE THREAD

**Issue by polonium-dev** [AllTheMods/ATM-10#9]
### Possible Fixes

Yes

### Modpack Version

0.2

### What happened?

AllTheOres adds some Dirty Dusts for the Mekanism 3x, 4x and 5x Ore Duplication. But those dust just don't go into the enrichment chamber, so they're completely useless.
![grafik](https://github.com/AllTheMods/ATM-10/assets/75094378/50f2f926-df39-4066-a2a1-39d013c185a5)
As you can see, this dust does not have any uses in EMI
![grafik](https://github.com/AllTheMods/ATM-10/assets/75094378/5c205641-e1c5-4b40-88d5-d498ae67609b)

**Comment by Kevin-Marsh** [comment]
This requires kubejs for our unification scripts to be implemented.
