### ISSUE TITLE
[Bug]: ancient polished stone is unmineable and excessive other dungeon and pyramid spawns

### ISSUE THREAD

**Issue by Girlgamerb** [AllTheMods/ATM-10#905]
### Possible Fixes

Yes

### Modpack Version

1.7

### What happened?

i found 26 dungeons and 8 pyramids really close to one another 
![Screenshot (5)](https://github.com/user-attachments/assets/2ed6fed6-345e-4187-9f4c-3d58c5019b08)

there are chests in the other dungeons that are in assessable because you cannot mine the ancient polished stone
![Screenshot (3)](https://github.com/user-attachments/assets/8e507dc7-dc2e-4d97-8fdf-a6c2deec7762)

**Comment by TheBedrockMaster** [comment]
The dungeon spacing has been fixed and the ancient stone bug has been reported already.
