### ISSUE TITLE
[Crash]: Garden Cloche crashing

### ISSUE THREAD

**Issue by danielsartor** [AllTheMods/ATM-10#907]
### Possible Fixes

Yes

### Modpack Version

1.7

### Description:
I have a Sink with a Fluid Pipe (from Pipez mod) connect to back, I added a dirt and a Poppy flower inside, soon after I added a Ender Gate (Nitro) for energy on top of it then it crashed. I cannot open the game because it crashes immediately.

### Crash error:
The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: The class blusunrize.immersiveengineering.client.utils.TransformingVertexBuilder does not implement interface VertexBufferWriter, which is required for compatibility with Sodium (see: https://github.com/CaffeineMC/sodium-fabric/issues/1620)

### Crash Log

https://gist.github.com/danielsartor/136504b674ae8253675bca83d7b6dc7f

**Comment by baltrau** [comment]
This happened to me aswell, the world is corrupted can not launch it, it crashes immediately.

**Comment by danielsartor** [comment]
> This happened to me aswell, the world is corrupted can not launch it, it crashes immediately.

I manage to restore with simple backups, but it's good to report the issue. I'm afraid to test again with different setup, but I cannot farm flowers another way :(

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/856
