### ISSUE TITLE
[Bug]: Immersive Engineering Sealed Crate Item Deletion

### ISSUE THREAD

**Issue by DaniellePashayan** [AllTheMods/ATM-10#910]
### Possible Fixes

Yes

### Modpack Version

1.7

### What happened?

I found an Immersive Engineering wooden storage crate in a village. After sealing the contents with a hammer, i broke the crate. In my inventory, the tool tips showed the items in the crate. Upon placing the crate back down, the items inside the crate disappeared / were deleted.

Issue does not occur when Immersive Engineering is the only mod installed.

### latest.log

https://gist.github.com/DaniellePashayan/3e4ca52059e110f535768c501b6e4d32

### Developer reports

https://github.com/BluSunrize/ImmersiveEngineering/issues/6088

**Comment by DerpyFrood0421** [comment]
Had a very similar bug. Put sealed crates full of stuff (verified via tooltip) into a pneumatic craft chest. Upon taking them out tooltip still shows contents, but after placing them down they are empty.

**Comment by DerpyFrood0421** [comment]
See here: https://github.com/BluSunrize/ImmersiveEngineering/issues/6088
