### ISSUE TITLE
[Bug]: No recipes for all of Ars Energistique

### ISSUE THREAD

**Issue by TheFlash787** [AllTheMods/ATM-10#911]
### Modpack Version

1.7

### What happened?

All recipes for Ars Energistique don't have any way to be crafted from JEI. I can't find any documentation from the mod developer or any other mentions of this issue.

![image](https://github.com/user-attachments/assets/5f3aa7a2-d4b3-41a5-860c-a6baa9811e3e)

**Comment by alekthefirst** [comment]
Fixed in i believe Ars Énergistique 2.0.3 beta, released with ATM10 1.18
