### ISSUE TITLE
[Crash]:  Opening AE2 guide by keybind crash the game, only specific for ae2:crystal_resonance_generator

### ISSUE THREAD

**Issue by StunAndBlock** [AllTheMods/ATM-10#914]
### Possible Fixes

Yes

### Modpack Version

1.7

### What happened?

 Opening AE2 guide by keybind crash the game, only specific for ae2:crystal_resonance_generator
 reason: "Tab" is null, error in rendering screen, seems guide book tab for  ae2:crystal_resonance_generator is corrupted or there is no one at all.

### Crash Log

https://gist.github.com/StunAndBlock/9edc6dfa116c230f8c5c7fca5de358da

### Latest.Log

https://gist.github.com/StunAndBlock/fcb0d8c4149613d9c1f825b542ec911c

**Comment by StunAndBlock** [comment]
P.S 
ae2:growth_accelerator also causes crash with same reason
"The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot read field "visible" because "tab" is null"

**Comment by alekthefirst** [comment]
Issue cannot be reproduced in ATM10 2.8 and has presumably been fixed

https://github.com/user-attachments/assets/71485e73-0d8f-4c48-a715-bc6c53a18018
