### ISSUE TITLE
[Crash]: Ars nouveau Drygmy

### ISSUE THREAD

**Issue by ShadowwDC** [AllTheMods/ATM-10#917]
### Possible Fixes

Yes

### Modpack Version

1.06/1.07

### What happened?

when summoning a second drygmy the chunk become corrupted, the client crash and cant log back in until he's teleported away from the base.

someone else ran into this issues after me and said that kill all entity did work.

no crash report have been created when the crash occurred

### Crash Log

https

**Comment by pr0saic** [comment]
https://github.com/baileyholl/Ars-Nouveau/issues/1454
