### ISSUE TITLE
[Bug]: Stella arcanum?

### ISSUE THREAD

**Issue by frsfdc** [AllTheMods/ATM-10#922]
### Possible Fixes

Yes

### Modpack Version

1.6

### What happened?

I've been playing on a server for a while,and I didn't find any in the overworld yet.I tried today to use a scrying ritual after finally finding one with the digital miner,yet i saw none for about 15 minutes.Does it work with the ritual?

**Comment by pr0saic** [comment]
Can confirm this works
![image](https://github.com/user-attachments/assets/67a8722c-6965-4137-a692-2da8744c3280)
Used manipulation essence too if that helps
