### ISSUE TITLE
[Bug]: latest update is crashing my game

### ISSUE THREAD

**Issue by whiteHat1997** [AllTheMods/ATM-10#928]
### Possible Fixes

Yes

### Modpack Version

1.8

### What happened?

when i installed the latest update my game started crashing as soon as i try to load into the world 
when i downgraded it works fine

**Comment by pr0saic** [comment]
Delete the Auroras mod config in your config folder

**Comment by whiteHat1997** [comment]
@pr0saic Worked , thank you for the quick response
