### ISSUE TITLE
[Crash]: Game crashes while loading a new world version

### ISSUE THREAD

**Issue by TheEmpireSro** [AllTheMods/ATM-10#931]
### Possible Fixes

Yes

### Modpack Version

1.8

### What happened?

I updated the pack, started a new world and my game closed.
Following crash appeared.
![Screenshot 2024-10-27 074048](https://github.com/user-attachments/assets/5d00dec1-13d1-4c3c-9773-6357b8cb71a2)

### Crash Log

<script src="https://gist.github.com/TheEmpireSro/72018506186c9f9a9bafc4603c218a35.js"></script>

**Comment by pr0saic** [comment]
Delete the Auroras mod config in your config folder: 
![image](https://github.com/user-attachments/assets/4b7acd15-13c6-4b3c-8aa9-2184ebf37879)

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/929

**Comment by TheEmpireSro** [comment]
Thanks! Sorry didnt see! I delete/close this.
