### ISSUE TITLE
[Crash]: Keep getting this when logging into my world

### ISSUE THREAD

**Issue by Hamude995** [AllTheMods/ATM-10#932]
### Possible Fixes

Yes

### Modpack Version

1.8

### What happened?

When I launch my world my game keep crashing and giving me the same reason every time: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsDouble()" because the return value of "com.google.gson.JsonObject.get(String)" is null

### Crash Log

https://gist.github.com/Hamude995/a5000efe6cca1f7d9ad91a3940861f3f

### Latest.Log

https://gist.github.com/Hamude995/91e88b7b3af8b72bbe0b63624bd4b306

**Comment by Hamude995** [comment]
Remove auroras config folder to fix

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/929
