### ISSUE TITLE
[Crash]: java.lang.NullPointerException when loading world after update to version 1.8

### ISSUE THREAD

**Issue by Epicycle23** [AllTheMods/ATM-10#935]
### Possible Fixes

Yes

### Modpack Version

1.8

### What happened?

Crash when loading world after upgrading from version 1.7 to 1.8

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsDouble()" because the return value of "com.google.gson.JsonObject.get(String)" is null

### Crash Log

https://gist.github.com/Epicycle23/18b2048635ce48374aeff484cb6084fb

### Latest.Log

https://gist.github.com/Epicycle23/7058a7702eb1362572a91da7643137f3

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/929
