### ISSUE TITLE
[Crash]: NPE after update from 1.7 to 1.8

### ISSUE THREAD

**Issue by DaLLr0g** [AllTheMods/ATM-10#936]
### Possible Fixes

Yes

### Modpack Version

1.8

### What happened?

I've updated the modpack to the latest 1.8, and after world loading, it instantly crashes with NullPointerException.

NOTE: I'm on mac OS 15.0.1, Apple Silicon

### Crash Log

https://gist.github.com/DaLLr0g/74e82b8eb1184cd47ca9891c233391b0

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/929

**Comment by DaLLr0g** [comment]
Looks like duplication of https://github.com/AllTheMods/ATM-10/issues/929
Will try workaround and keep it updated.

**Comment by DaLLr0g** [comment]
Helped :)
