### ISSUE TITLE
[Crash]: Garden cloche crash

### ISSUE THREAD

**Issue by Lounol72** [AllTheMods/ATM-10#941]
### Possible Fixes

Yes

### Modpack Version

10-1.8

### What happened?

I was doing immersive engineering and the game crashed  5seconds after I placed the garden cloche since then when I launch my world it crashes.

### Crash Log

https://gist.github.com/Lounol72/d78504857ad9cfcbe620e59b694a8c15

### Latest.Log

https://gist.github.com/Lounol72/83b32ac0e51f29d6a349fc5d9c505f00

**Comment by stardustdragon96** [comment]
same problem....
