### ISSUE TITLE
[Bug]: Actually Additions drill breaks like other tools at 0 charge

### ISSUE THREAD

**Issue by Tomtaley** [AllTheMods/ATM-10#944]
### Possible Fixes

Yes

### Modpack Version

1.7

### What happened?

When using the Actually Additions drill at 0 charge it breaks the item. Using Vein mine at low charge without power for all blocks will also cause the same outcome,

**Comment by Mrbysco** [comment]
That has been fixed in Actually Additions 1.3.9
