### ISSUE TITLE
[Question]: Night vision goggles make everything green

### ISSUE THREAD

**Issue by DaLLr0g** [AllTheMods/ATM-10#945]
### Possible Fixes

Yes

### Modpack Version

1.9

### What happened?

From 1.6 or 1.7 modpack version (on 1.9 as well) 'Night vision goggles' from 'Artifacts' turn everything in green. Is this supposed to work in this way? Kinda really ugly...
![image](https://github.com/user-attachments/assets/9533c49d-02d5-4e0a-9e40-900b58d7cb1b)
![image](https://github.com/user-attachments/assets/08f96ab4-de99-4607-8546-30e87e72272f)

**Comment by DaLLr0g** [comment]
just a side note about level of it
![image](https://github.com/user-attachments/assets/f849915e-3b1c-466d-8863-afcf979a8dd5)

**Comment by thisKid619** [comment]
yeah the update has them functioning more like real world night vision goggles

**Comment by DaLLr0g** [comment]
Honestly, then there’s no any sense of them =)
During mining you can't even distinguish ores

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/899
