### ISSUE TITLE
[Bug]: Observer Texture is a red

### ISSUE THREAD

**Issue by UryelJo** [AllTheMods/ATM-10#947]
### Possible Fixes

Yes

### Modpack Version

1.9

### What happened?

![2024-10-27_18 43 59](https://github.com/user-attachments/assets/2c175dd0-706b-4ff0-b32d-32a2c5636c63)

This

**Comment by TheBedrockMaster** [comment]
Dupe: https://github.com/AllTheMods/ATM-10/issues/812
