### ISSUE TITLE
[Bug]: JEI doesn't show Quantum Infusion recipie (@Advanced AE) 

### ISSUE THREAD

**Issue by Yamijiro** [AllTheMods/ATM-10#954]
### Possible Fixes

Yes

### Modpack Version

1.10

### What happened?

Checking the recipie on JEI doesn't work and checking usages for Quantum Infused Dust shows the recipie incorrectly.

Reaction Chamber doesn't auto export fluids.

**Comment by zeziba** [comment]
On the curseforge page in response to another person

[Curseforge page with comment](https://www.curseforge.com/minecraft/mc-mods/advancedae/comments)

> pedroksl
> [View user profile](https://www.curseforge.com/members/pedroksl)
> [Send message](https://legacy.curseforge.com/private-messages/send?recipient=pedroksl)
> 
> October 29, 2024
> 6761188
> 
> In reply to [MrLittleFox220](https://legacy.curseforge.com/members/mrlittlefox220):
>  The recipe is not missing. JEI does not have it. I only support REI/EMI. Packs that use the FTB JEI extras addon to add unofficial support to JEI will have to either manually add EMI or wait until they update. But to fix your issue right now, the recipe for quantum infusion is 5B of water and 1 Quantum Infused dust to make 1B of Quantum Infusion.

So the recipe would have to be manually added or the recommendations of the mod dev would have to be taken under consideration. 



Also the recipes are all wrong for the crystal assembler currently when you feed them into the AE2 recipes as each recipe requires only 1/2 (500mb vs 1000mb) of what it is putting in. It is doing the same thing mekanism used to do with the volume of liquid required,

**Comment by Yamijiro** [comment]
Honestly hope ATM10 can make EMI happen.

**Comment by tiwuno** [comment]
Same, Yamijiro. The crafting tree feature is such a massive QOL improvement that I've specifically started looking for modpacks that use EMI instead of/in addition to JEI.

**Comment by Yamijiro** [comment]
> Same, Yamijiro. The crafting tree feature is such a massive QOL improvement that I've specifically started looking for modpacks that use EMI instead of/in addition to JEI.

I agree. Not only that, but the recipie search history as well. If you go through and click the components of a craft once you can easily check them again after browsing all of them. Saving you many clicks and button presses in the process.

You can use EMI on your client even if it doesn't come with the modpack, but if it doesn't have full support it ends up missing recipies and such which also isn't that great.

**Comment by alekthefirst** [comment]
The reaction chamber recipes are bugged with JEI, this was fixed in 2.7 but the AAE version got rolled back in 2.8 to unfix it, because of an AE2 crash. The fix will be back in a future update.

**Comment by alekthefirst** [comment]
Resolved in ATM10 2.9
