### ISSUE TITLE
[Quests issues]: applied energistics 2 growth accelerator 

### ISSUE THREAD

**Issue by DudeDayne** [AllTheMods/ATM-10#963]
### Modpack Version

1.21.1

### Describe the issue

growth accelerator ap2 quest not working I have made multiple and dropped and picked them up

**Comment by TheBedrockMaster** [comment]
If you have a quest that isn't completing, you need to check if you completed all of it's requirements, you can check this by clicking on the quest, and clicking the small triangle/arrow on the top left of the quest popup. That will show all requirements.

If all the requirements are met, then the quest is probably actually stuck, which sometimes happens with FTB Quests:
To complete it, you need to be an OP (/op "username" from console) or have cheats enabled (if you didn't enable cheats in the world creation, open to LAN with cheats enabled).
With that, open the quests window.
Click the pencil icon on the bottom right, which enables editing mode.
Right click the quest in question.
Click Complete Instantly.

That will complete the quest, then disable the pencil button afterwards.

**"I want the reward from the quest though"**
In that case, in the quest popup, right click the reward, and click Reset Progress, that will let you claim the reward.
