### ISSUE TITLE
[Bug]: Silent gear automation missing

### ISSUE THREAD

**Issue by Krotu** [AllTheMods/ATM-10#964]
### Possible Fixes

Yes

### Modpack Version

1.11

### What happened?

In ATM9 Silent gear has a bunch of bunch of methods of automating processing, most of these seems to be missing at the moment. Examples are:

Starlight charger grader material requires dust made from silent gear materials, these currently require manual crushing using a stone anvil and a silent gear hammer whereas in ATM9 the various crushers could be used to automate this.

Salvager, Recrystallizer, Material Grader, Alloy Forge and Starlight Charger support push/pull from pipes (and pattern providers) in ATM9 but this interaction does not work in ATM10.

I hope the title makes sense, I wasn't sure what to call the pipe/pattern/block interaction.

**Comment by Krotu** [comment]
this is still missing some stuff, the ingots that are crafted rather than smelted from ore can still not be added to crushers, these are:
**Blaze Gold Ingot** (dust needed for Starmetal Dust/Starlight Charger Catalyst Tier 3 or can be used as Tier 1 on its own)
**Azure Electrum Ingot** (dust needed for Starmetal Dust/Starlight Charger Catalyst Tier 3)
Crimson Steel Ingot (no current use as dust so not important).

Also none of the pipe connections work still, the grader in particular could use this as grading to max sometimes takes hundreds of resources, does this need posting as a separate issue and is it a bug or a suggestion?

**Comment by pr0saic** [comment]
I've done those other dusts now, should be in the pack at some point. Did the grader used to work with pipes?

**Comment by Krotu** [comment]
![atm9vsatm10sg](https://github.com/user-attachments/assets/13492a7e-039f-440c-a6e6-949785b9d060)
everything except the gear workbench used to work (atm10 on the top, atm9 on the bottom)
They had no force eject options like mekanism type mods have, but you could pull/push to all of them before.
Its not just mekanism pipes either, if you place xnet connectors for example they are not recognised as a valid target either.

**Comment by pr0saic** [comment]
It doesn't look like the modpack is doing anything to change that so I've opened a bug report with Silent Gear for now: https://github.com/SilentChaos512/Silent-Gear/issues/735
