### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by MyHaven** [AllTheMods/ATM-10#969]
### Possible Fixes

No

### Modpack Version

1.6

### What happened?

I placed some garden cloches and when i added an ender gate to the top of them the game just crashed, and now i cant get into the game

### Crash Log

https://gist.github.com/MyHaven/e3421588e74fb6203c826d946f3f5879

### Latest.Log

https://gist.github.com/MyHaven/978f5071622d9656a0b8bfa9436bed6b

**Comment by TheBedrockMaster** [comment]
Update the pack.
