### ISSUE TITLE
[Crash]: Crash in the nether. 

### ISSUE THREAD

**Issue by NJM1564** [AllTheMods/ATM-10#97]
### Possible Fixes

Yes

### Modpack Version

10-0-12

### What happened?

Was flying in the nether near a ghast while wereing the dragon backpack and I believe that when the ghast fires it crashes the game. The backpack is supposed to protect against fire including the fireballs but that part might not have bin updated to the current version of MC.

### Crash Log

https://gist.github.com/NJM1564/817aa4f1c106a948e0d416f06a3bba3a

### Latest.Log

https://gist.github.com/NJM1564/42799f068bf8778e70ac5654b62d7a96

**Comment by Kevin-Marsh** [comment]
We don't have the traveller's backpack in the pack. Please go report this to the traveller's backpack devs.
