### ISSUE TITLE
[Bug]: Some Occultism advancements are not unlockable

### ISSUE THREAD

**Issue by schwetim** [AllTheMods/ATM-10#972]
### Possible Fixes

Yes

### Modpack Version

1.11

### What happened?

Some Occultism pentacles are not unlockable preventing further progress, like acquiring red chalk for summoning the Afrit. The requirements for the unlock are fullfilled (orange and grey chalk).
![2152151(1)](https://github.com/user-attachments/assets/e8dbcdc9-5714-475b-8e5c-b89dc1e31049)

**Comment by Pumpkin7266** [comment]
this seems to be a general problem with advancements on ATM10. i also had problems getting MI advancements. Something has been messing up in general with advancements. Tested Occultism standalone and didn't had problems

**Comment by Eqis-Edu** [comment]
Temporary solution:
https://github.com/Eqis-Edu/dict-without-adv-lock

Any modpack with advancements problems can use this

**Comment by Spulcr** [comment]
> Temporary solution: https://github.com/Eqis-Edu/dict-without-adv-lock
> 
> Any modpack with advancements problems can use this

I don’t fully understand how to use this. Could you elaborate?

**Comment by Spulcr** [comment]
> Temporary solution: https://github.com/Eqis-Edu/dict-without-adv-lock
> 
> Any modpack with advancements problems can use this

I’m not entirely sure how to use this. Could you provide more details?

**Comment by Eqis-Edu** [comment]
> I’m not entirely sure how to use this. Could you provide more details?

In the `<> Code` button download as zip, extract the `data` in your amt10 kubejs folder

In occultism 166 you dont need this, just click in the chalk sometimes in your inventory

**Comment by Spulcr** [comment]
> > I’m not entirely sure how to use this. Could you provide more details?
> 
> In the `<> Code` button download as zip, extract the `data` in your amt10 kubejs folder
> 
> In occultism 166 you dont need this, just click in the chalk sometimes in your inventory

Thanks, man. It worked!

**Comment by Yamijiro** [comment]
![2024-11-03_18 49 42](https://github.com/user-attachments/assets/a6fb3e88-f383-4548-a0a1-41b50c66193a)

For me it looks like this and clicking the chalk doesn't help sadly.
