### ISSUE TITLE
[Crash]: Server Crash when exchanging spell cross dimensional 

### ISSUE THREAD

**Issue by we1rq** [AllTheMods/ATM-10#976]
### Possible Fixes

Yes

### Modpack Version

Latest

### What happened?

I was kidnapping friends cat I used exchanged and /homed to the mining dimension then the server crashes 

used ars spell book
projectile 8 delays 1 exchange 
cast
/home 
server crash rolls back 

also can dupe items due to invintory rolling back but chests and barrels dont

### Crash Log

dont have access just konw how to recreate it

**Comment by asksladd** [comment]
The same thing happens to me while using a waystone or while flying fast

**Comment by alekthefirst** [comment]
Likely issue with Ars Noveau particles unloading, fixed in Ars Noveau 5.2.3 released with ATM10 1.17
