### ISSUE TITLE
[Bug]: Functional storage drawers not craftable

### ISSUE THREAD

**Issue by kollinkoko** [AllTheMods/ATM-10#98]
### Possible Fixes

Yes

### Modpack Version

0.12

### What happened?

When attempting to craft the 1x1 Oak Drawer or 1x1 Dark Oak Drawer, it instead makes Dark Oak Cupboard or Oak Cupboard's respectively. This is with a standard crafting table. There is no arrow to change the recipe.
![image](https://github.com/user-attachments/assets/8c867142-9323-4d6f-90d8-b7333b946478)

**Comment by aAndrew3030** [comment]
This is because Polymorph was removed from the pack (I am guessing a compatibility issue). If you not using handcrafted, I would disable it until they fix this, or you could try adding back Polymorph

**Comment by Arraval-rs** [comment]
Another possible "hack" to get around this: If you create any of the Chipped planks (tested with oak planks mosaic) using the carpenters table you can create the Functional Storage drawers no problem.

**Comment by Kevin-Marsh** [comment]
This will be patched in the next version.
