### ISSUE TITLE
[Bug]: Deepslate Dark Ore isn't accepted by the Integrated Dynamics Squeezers

### ISSUE THREAD

**Issue by indygwyn** [AllTheMods/ATM-10#987]
### Possible Fixes

Yes, probably just a config change

### Modpack Version

1.13

### What happened?

Went to make some Crushed Dark Gem Dust, saw that you could use Dark Ore in the ID Squeezers, then noticed that it's only Dark Ore not Deepslate Dark Ore

**Comment by pr0saic** [comment]
https://github.com/CyclopsMC/IntegratedDynamics/issues/1414

**Comment by pr0saic** [comment]
Fixed in latest Integrated Dynamics
