### ISSUE TITLE
[Crash]: Game crashing when trying to open

### ISSUE THREAD

**Issue by XavoxMaster** [AllTheMods/ATM-10#99]
### Possible Fixes

Yes

### Modpack Version

0.12

### What happened?

When I try to open the game it crashes, this is the first time I'm trying to open the modpack, I've already played the two previous versions of the modpack, All the Mods 8 and 9, and they worked fine.
I'll be attaching the console.log, it seems like it's an error in Java or something like that.

### Crash Log

It was not generated, first time opening the game

### Latest.Log

https://gist.github.com/XavoxMaster/d6c20d74a7ba030f78c47ae80d6b2bc0

**Comment by aAndrew3030** [comment]
What launcher are you using?

**Comment by XavoxMaster** [comment]
I am using the FTB APP downloaded from the official website, the version used is by Overwolf

Website link below
https://www.feed-the-beast.com/ftb-app

**Comment by Ciznia** [comment]
Have you tried unintaliing it  and reinstall it, i had a similar issue on another modpack where a little bug in the download make game crash again and again

**Comment by Gnomesk1llet** [comment]
[crash-2024-07-19_23.07.28-client.txt](https://github.com/user-attachments/files/16321251/crash-2024-07-19_23.07.28-client.txt)

I've been having this issue as well. I can get it to run on a fresh install, but if I close the game and try to reopen it, I get an exit code -1 Error: java.lang.IllegalStateException: Mod 'architectury' is not available! From the troubleshooting I've done on my end, it looks like mods that use omegaconfig to launch are what's causing the error, but I don't know enough about programming to have a solution beyond uninstalling those mods, or uninstalling the entire pack and reinstalling, neither of which are ideal.

I use the Curseforge app to run my mods, and the only alterations to the modpack I've made are to add RyoamicLights and Motschen's Better Leaves. I hope something in here helps!

**Comment by Ratsliart** [comment]
I am having this issue on FTB launcher as well. All other ATM packs launch fine. ATM 10 results in this error in the log:

**Comment by alekthefirst** [comment]
The Architectury crashes are different and belong in https://github.com/AllTheMods/ATM-10/issues/130
The module resolution issue seems to be resolved
