### ISSUE TITLE
[Crash]: Small Server Crash After Anyone Leaves

### ISSUE THREAD

**Issue by gunnarjessee** [AllTheMods/ATM-10#993]
### Possible Fixes

Yes

### Modpack Version

1.14

### What happened?

Pack: ATM10, Version: 1.14 (latest at the time)
Play type: Small 8g of Ram, mobile i5 intel CPU 2.5ghz gaming laptop server with nothing running but the server and an app called Parsec.

Anytime someone comes in the server for a minute or more the server will crash after they leave. Leaving a very generic minecraft/java Arraylist error to what appears to have to deal with either entities in chunks or chunkloading.

Tried removing a few mods and switching them out, but I could not even fathom the amount of mods that could modify either one of those.

This will happen for anyone that leaves the server, every time.

Thank you for your time!

### Crash Log

https://gist.github.com/gunnarjessee/9c0fed95d10dd16f34b74ecd5e7a7574

### Latest.Log

https://gist.github.com/gunnarjessee/2786b58175488a91418219cdbfb4ff70

**Comment by alekthefirst** [comment]
Solved in https://github.com/AllTheMods/ATM-10/issues/1251
Fixed in Ars Noveau 5.2.3 released with ATM10 1.17
