### ISSUE TITLE
[Bug]: Chipped Mason bench (or chisel) not working with Deepslate or Darkstone

### ISSUE THREAD

**Issue by Kaotac** [AllTheMods/ATM-10#995]
### Possible Fixes

Yes

### Modpack Version

1.11

### What happened?

Trying to use Deepslate and Darkstone on the @Chipped mason bench (or the hand held chisel) to get different blocks, but neither can be selected

**Comment by pr0saic** [comment]
Darkstone and cobbled deepslate have no chipped variants to be transformed into, only regular deepslate does
